### ISSUE TITLE
"Path must be a string. Received null" error when using with ember-decorators

### ISSUE THREAD

**Issue by lstrzebinczyk** [embroider-build/embroider#100]
Hello. I am very interested what embroider is bringing in to the table: )

I did a test run in my app, as explained in the readme, and found an issue. I was able to nail it down to the "ember-decorators" gem. The simplest reproduction case Is:

1. ember new embroider-test
2. update ember-source and ember-cli to 3.7.1 (Might be that only one of those is required)
3. install embroider as explained in the readme
4. `yarn add ember-decorators --dev`

starting the application produces this error:

```
killa@killa-MS-7A34:~/workspace/embroider-test$ ember s
Build Error (OneShot)

Path must be a string. Received null
        at RewritePackageJSON (embroider:core:rewrite-package-json)
-~- created here: -~-
    at new Plugin (/home/killa/workspace/embroider-test/node_modules/broccoli-plugin/index.js:7:31)
    at new RewritePackageJSON (/home/killa/workspace/embroider-test/node_modules/@embroider/compat/src/rewrite-package-json.js:11:9)
    at default_1.get v2Trees (/home/killa/workspace/embroider-test/node_modules/@embroider/compat/src/v1-addon.js:261:35)
    at default_1.<anonymous> (/home/killa/workspace/embroider-test/node_modules/typescript-memoize/dist/memoize-decorator.js:67:52)
    at default_1.get v2Tree [as v2Tree] (/home/killa/workspace/embroider-test/node_modules/@embroider/compat/src/v1-addon.js:246:52)
    at buildCompatAddon (/home/killa/workspace/embroider-test/node_modules/@embroider/compat/src/build-compat-addon.js:47:31)
    at Object.cachedBuildCompatAddon [as default] (/home/killa/workspace/embroider-test/node_modules/@embroider/compat/src/build-compat-addon.js:13:16)
    at CompatAddons.movedAddons.map.oldPkg (/home/killa/workspace/embroider-test/node_modules/@embroider/compat/src/compat-addons.js:33:105)
    at Array.map (<anonymous>)
    at new CompatAddons (/home/killa/workspace/embroider-test/node_modules/@embroider/compat/src/compat-addons.js:33:63)
-~- (end) -~-


Stack Trace and Error Report: /tmp/error.dump.b635ed319b165a635f044238ad1bb43a.log
```

And the stack trace in question is:
```
=================================================================================

ENV Summary:

  TIME: Mon Mar 25 2019 23:58:15 GMT+0100 (CET)
  TITLE: ember
  ARGV:
  - /usr/bin/node
  - /usr/bin/ember
  - s
  EXEC_PATH: /usr/bin/node
  TMPDIR: /tmp
  SHELL: /bin/bash
  PATH:
  - /home/killa/.cargo/bin
  - /home/killa/.cargo/bin
  - /home/killa/.rvm/gems/ruby-2.5.3/bin
  - /home/killa/.rvm/gems/ruby-2.5.3@global/bin
  - /home/killa/.rvm/rubies/ruby-2.5.3/bin
  - /home/killa/bin
  - /home/killa/.local/bin
  - /home/killa/.cargo/bin
  - /home/killa/.cargo/bin
  - /home/killa/bin
  - /home/killa/.local/bin
  - /usr/local/sbin
  - /usr/local/bin
  - /usr/sbin
  - /usr/bin
  - /sbin
  - /bin
  - /usr/games
  - /usr/local/games
  - /snap/bin
  - /home/killa/.rvm/bin
  - /home/killa/.rvm/bin
  - /home/killa/.rvm/bin
  PLATFORM: linux x64
  FREEMEM: 3618013184
  TOTALMEM: 16831975424
  UPTIME: 48908
  LOADAVG: 1.00341796875,1.1064453125,0.95361328125
  CPUS:
  - AMD Ryzen 7 1700X Eight-Core Processor - 2064
  - AMD Ryzen 7 1700X Eight-Core Processor - 1824
  - AMD Ryzen 7 1700X Eight-Core Processor - 1785
  - AMD Ryzen 7 1700X Eight-Core Processor - 3619
  - AMD Ryzen 7 1700X Eight-Core Processor - 2473
  - AMD Ryzen 7 1700X Eight-Core Processor - 2387
  - AMD Ryzen 7 1700X Eight-Core Processor - 1718
  - AMD Ryzen 7 1700X Eight-Core Processor - 1738
  - AMD Ryzen 7 1700X Eight-Core Processor - 3400
  - AMD Ryzen 7 1700X Eight-Core Processor - 2524
  - AMD Ryzen 7 1700X Eight-Core Processor - 3442
  - AMD Ryzen 7 1700X Eight-Core Processor - 2422
  - AMD Ryzen 7 1700X Eight-Core Processor - 2234
  - AMD Ryzen 7 1700X Eight-Core Processor - 2333
  - AMD Ryzen 7 1700X Eight-Core Processor - 2560
  - AMD Ryzen 7 1700X Eight-Core Processor - 1993
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.10.1-DEV
  - cldr: 32.0
  - http_parser: 2.8.0
  - icu: 60.1
  - modules: 57
  - napi: 3
  - nghttp2: 1.33.0
  - node: 8.15.1
  - openssl: 1.0.2r
  - tz: 2017c
  - unicode: 10.0
  - uv: 1.23.2
  - v8: 6.2.414.75
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: TypeError: Path must be a string. Received null
    at assertPath (path.js:28:11)
    at Object.dirname (path.js:1346:5)
    at get_or_create_1.getOrCreate (/home/killa/workspace/embroider-test/node_modules/@embroider/core/src/package-cache.js:20:31)
    at Object.getOrCreate (/home/killa/workspace/embroider-test/node_modules/@embroider/core/src/get-or-create.js:6:18)
    at MovablePackageCache.resolve (/home/killa/workspace/embroider-test/node_modules/@embroider/core/src/package-cache.js:19:32)
    at names.map.name (/home/killa/workspace/embroider-test/node_modules/@embroider/core/src/package.js:76:52)
    at Array.map (<anonymous>)
    at TweakedPackage.get dependencies (/home/killa/workspace/embroider-test/node_modules/@embroider/core/src/package.js:76:22)
    at TweakedPackage.<anonymous> (/home/killa/workspace/embroider-test/node_modules/typescript-memoize/dist/memoize-decorator.js:67:52)
    at DependencyAnalyzer.get externals [as externals] (/home/killa/workspace/embroider-test/node_modules/@embroider/compat/src/dependency-analyzer.js:26:34)
  - code: [undefined]
  - codeFrame: Path must be a string. Received null
        at RewritePackageJSON (embroider:core:rewrite-package-json)
-~- created here: -~-
    at new Plugin (/home/killa/workspace/embroider-test/node_modules/broccoli-plugin/index.js:7:31)
    at new RewritePackageJSON (/home/killa/workspace/embroider-test/node_modules/@embroider/compat/src/rewrite-package-json.js:11:9)
    at default_1.get v2Trees (/home/killa/workspace/embroider-test/node_modules/@embroider/compat/src/v1-addon.js:261:35)
    at default_1.<anonymous> (/home/killa/workspace/embroider-test/node_modules/typescript-memoize/dist/memoize-decorator.js:67:52)
    at default_1.get v2Tree [as v2Tree] (/home/killa/workspace/embroider-test/node_modules/@embroider/compat/src/v1-addon.js:246:52)
    at buildCompatAddon (/home/killa/workspace/embroider-test/node_modules/@embroider/compat/src/build-compat-addon.js:47:31)
    at Object.cachedBuildCompatAddon [as default] (/home/killa/workspace/embroider-test/node_modules/@embroider/compat/src/build-compat-addon.js:13:16)
    at CompatAddons.movedAddons.map.oldPkg (/home/killa/workspace/embroider-test/node_modules/@embroider/compat/src/compat-addons.js:33:105)
    at Array.map (<anonymous>)
    at new CompatAddons (/home/killa/workspace/embroider-test/node_modules/@embroider/compat/src/compat-addons.js:33:63)
-~- (end) -~-
  - errorMessage: Path must be a string. Received null
        at RewritePackageJSON (embroider:core:rewrite-package-json)
-~- created here: -~-
    at new Plugin (/home/killa/workspace/embroider-test/node_modules/broccoli-plugin/index.js:7:31)
    at new RewritePackageJSON (/home/killa/workspace/embroider-test/node_modules/@embroider/compat/src/rewrite-package-json.js:11:9)
    at default_1.get v2Trees (/home/killa/workspace/embroider-test/node_modules/@embroider/compat/src/v1-addon.js:261:35)
    at default_1.<anonymous> (/home/killa/workspace/embroider-test/node_modules/typescript-memoize/dist/memoize-decorator.js:67:52)
    at default_1.get v2Tree [as v2Tree] (/home/killa/workspace/embroider-test/node_modules/@embroider/compat/src/v1-addon.js:246:52)
    at buildCompatAddon (/home/killa/workspace/embroider-test/node_modules/@embroider/compat/src/build-compat-addon.js:47:31)
    at Object.cachedBuildCompatAddon [as default] (/home/killa/workspace/embroider-test/node_modules/@embroider/compat/src/build-compat-addon.js:13:16)
    at CompatAddons.movedAddons.map.oldPkg (/home/killa/workspace/embroider-test/node_modules/@embroider/compat/src/compat-addons.js:33:105)
    at Array.map (<anonymous>)
    at new CompatAddons (/home/killa/workspace/embroider-test/node_modules/@embroider/compat/src/compat-addons.js:33:63)
-~- (end) -~-
        at OneShot
-~- created here: -~-
    at new Plugin (/home/killa/workspace/embroider-test/node_modules/broccoli-plugin/index.js:7:31)
    at new OneShot (/home/killa/workspace/embroider-test/node_modules/@embroider/compat/src/one-shot.js:14:9)
    at Object.cachedBuildCompatAddon [as default] (/home/killa/workspace/embroider-test/node_modules/@embroider/compat/src/build-compat-addon.js:15:16)
    at CompatAddons.movedAddons.map.oldPkg (/home/killa/workspace/embroider-test/node_modules/@embroider/compat/src/compat-addons.js:33:105)
    at Array.map (<anonymous>)
    at new CompatAddons (/home/killa/workspace/embroider-test/node_modules/@embroider/compat/src/compat-addons.js:33:63)
    at Object.defaultPipeline [as compatBuild] (/home/killa/workspace/embroider-test/node_modules/@embroider/compat/src/default-pipeline.js:11:18)
    at module.exports (/home/killa/workspace/embroider-test/ember-cli-build.js:23:39)
    at Builder.readBuildFile (/home/killa/workspace/embroider-test/node_modules/ember-cli/lib/models/builder.js:52:14)
    at Builder.setupBroccoliBuilder (/home/killa/workspace/embroider-test/node_modules/ember-cli/lib/models/builder.js:66:22)
-~- (end) -~-
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
    - treeDir: [undefined]
  - message: Path must be a string. Received null
        at RewritePackageJSON (embroider:core:rewrite-package-json)
-~- created here: -~-
    at new Plugin (/home/killa/workspace/embroider-test/node_modules/broccoli-plugin/index.js:7:31)
    at new RewritePackageJSON (/home/killa/workspace/embroider-test/node_modules/@embroider/compat/src/rewrite-package-json.js:11:9)
    at default_1.get v2Trees (/home/killa/workspace/embroider-test/node_modules/@embroider/compat/src/v1-addon.js:261:35)
    at default_1.<anonymous> (/home/killa/workspace/embroider-test/node_modules/typescript-memoize/dist/memoize-decorator.js:67:52)
    at default_1.get v2Tree [as v2Tree] (/home/killa/workspace/embroider-test/node_modules/@embroider/compat/src/v1-addon.js:246:52)
    at buildCompatAddon (/home/killa/workspace/embroider-test/node_modules/@embroider/compat/src/build-compat-addon.js:47:31)
    at Object.cachedBuildCompatAddon [as default] (/home/killa/workspace/embroider-test/node_modules/@embroider/compat/src/build-compat-addon.js:13:16)
    at CompatAddons.movedAddons.map.oldPkg (/home/killa/workspace/embroider-test/node_modules/@embroider/compat/src/compat-addons.js:33:105)
    at Array.map (<anonymous>)
    at new CompatAddons (/home/killa/workspace/embroider-test/node_modules/@embroider/compat/src/compat-addons.js:33:63)
-~- (end) -~-
        at OneShot
-~- created here: -~-
    at new Plugin (/home/killa/workspace/embroider-test/node_modules/broccoli-plugin/index.js:7:31)
    at new OneShot (/home/killa/workspace/embroider-test/node_modules/@embroider/compat/src/one-shot.js:14:9)
    at Object.cachedBuildCompatAddon [as default] (/home/killa/workspace/embroider-test/node_modules/@embroider/compat/src/build-compat-addon.js:15:16)
    at CompatAddons.movedAddons.map.oldPkg (/home/killa/workspace/embroider-test/node_modules/@embroider/compat/src/compat-addons.js:33:105)
    at Array.map (<anonymous>)
    at new CompatAddons (/home/killa/workspace/embroider-test/node_modules/@embroider/compat/src/compat-addons.js:33:63)
    at Object.defaultPipeline [as compatBuild] (/home/killa/workspace/embroider-test/node_modules/@embroider/compat/src/default-pipeline.js:11:18)
    at module.exports (/home/killa/workspace/embroider-test/ember-cli-build.js:23:39)
    at Builder.readBuildFile (/home/killa/workspace/embroider-test/node_modules/ember-cli/lib/models/builder.js:52:14)
    at Builder.setupBroccoliBuilder (/home/killa/workspace/embroider-test/node_modules/ember-cli/lib/models/builder.js:66:22)
-~- (end) -~-
  - name: BuildError
  - nodeAnnotation: [undefined]
  - nodeName: OneShot
  - originalErrorMessage: Path must be a string. Received null
        at RewritePackageJSON (embroider:core:rewrite-package-json)
-~- created here: -~-
    at new Plugin (/home/killa/workspace/embroider-test/node_modules/broccoli-plugin/index.js:7:31)
    at new RewritePackageJSON (/home/killa/workspace/embroider-test/node_modules/@embroider/compat/src/rewrite-package-json.js:11:9)
    at default_1.get v2Trees (/home/killa/workspace/embroider-test/node_modules/@embroider/compat/src/v1-addon.js:261:35)
    at default_1.<anonymous> (/home/killa/workspace/embroider-test/node_modules/typescript-memoize/dist/memoize-decorator.js:67:52)
    at default_1.get v2Tree [as v2Tree] (/home/killa/workspace/embroider-test/node_modules/@embroider/compat/src/v1-addon.js:246:52)
    at buildCompatAddon (/home/killa/workspace/embroider-test/node_modules/@embroider/compat/src/build-compat-addon.js:47:31)
    at Object.cachedBuildCompatAddon [as default] (/home/killa/workspace/embroider-test/node_modules/@embroider/compat/src/build-compat-addon.js:13:16)
    at CompatAddons.movedAddons.map.oldPkg (/home/killa/workspace/embroider-test/node_modules/@embroider/compat/src/compat-addons.js:33:105)
    at Array.map (<anonymous>)
    at new CompatAddons (/home/killa/workspace/embroider-test/node_modules/@embroider/compat/src/compat-addons.js:33:63)
-~- (end) -~-
  - stack: TypeError: Path must be a string. Received null
    at assertPath (path.js:28:11)
    at Object.dirname (path.js:1346:5)
    at get_or_create_1.getOrCreate (/home/killa/workspace/embroider-test/node_modules/@embroider/core/src/package-cache.js:20:31)
    at Object.getOrCreate (/home/killa/workspace/embroider-test/node_modules/@embroider/core/src/get-or-create.js:6:18)
    at MovablePackageCache.resolve (/home/killa/workspace/embroider-test/node_modules/@embroider/core/src/package-cache.js:19:32)
    at names.map.name (/home/killa/workspace/embroider-test/node_modules/@embroider/core/src/package.js:76:52)
    at Array.map (<anonymous>)
    at TweakedPackage.get dependencies (/home/killa/workspace/embroider-test/node_modules/@embroider/core/src/package.js:76:22)
    at TweakedPackage.<anonymous> (/home/killa/workspace/embroider-test/node_modules/typescript-memoize/dist/memoize-decorator.js:67:52)
    at DependencyAnalyzer.get externals [as externals] (/home/killa/workspace/embroider-test/node_modules/@embroider/compat/src/dependency-analyzer.js:26:34)

=================================================================================
```
The package.json I ended up with is

```
{
  "name": "embroider-test",
  "version": "0.0.0",
  "private": true,
  "description": "Small description for embroider-test goes here",
  "repository": "",
  "license": "MIT",
  "author": "",
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "build": "ember build",
    "lint:hbs": "ember-template-lint .",
    "lint:js": "eslint .",
    "start": "ember serve",
    "test": "ember test"
  },
  "devDependencies": {
    "@ember/jquery": "^0.5.2",
    "@ember/optional-features": "^0.6.3",
    "@embroider/compat": "^0.1.0",
    "@embroider/core": "^0.1.0",
    "@embroider/webpack": "^0.1.0",
    "broccoli-asset-rev": "^2.7.0",
    "ember-ajax": "^3.1.0",
    "ember-cli": "~3.7.1",
    "ember-cli-app-version": "^3.2.0",
    "ember-cli-babel": "^6.16.0",
    "ember-cli-dependency-checker": "^3.0.0",
    "ember-cli-eslint": "^4.2.3",
    "ember-cli-htmlbars": "^3.0.0",
    "ember-cli-htmlbars-inline-precompile": "^1.0.3",
    "ember-cli-inject-live-reload": "^1.8.2",
    "ember-cli-sri": "^2.1.1",
    "ember-cli-template-lint": "^1.0.0-beta.1",
    "ember-cli-uglify": "^2.1.0",
    "ember-export-application-global": "^2.0.0",
    "ember-load-initializers": "^1.1.0",
    "ember-maybe-import-regenerator": "^0.1.6",
    "ember-qunit": "^3.4.1",
    "ember-resolver": "^5.0.1",
    "ember-source": "~3.7.1",
    "ember-welcome-page": "^3.2.0",
    "eslint-plugin-ember": "^5.2.0",
    "loader.js": "^4.7.0",
    "qunit-dom": "^0.8.0",

    "ember-decorators": "^5.1.4"

  },
  "engines": {
    "node": "6.* || 8.* || >= 10.*"
  }
}
```

I would love to help more to nail it down, but this is probably as far as I'm able to get. Please let me know if I can be of any more help.

**Comment by lstrzebinczyk** [comment]
I noticed multiple new versions and gave it a try again. Received new error:

```
unable to resolve package ember-data from /home/killa/workspace/SBweb/node_modules/ember-decorators
 ```

This one is, I think, unrelated to embroider itself, and requires me to move my codebase to native decorators syntax. I will close this issue and give it another try when I resolve my decorators issues.
