### ISSUE TITLE
Could not find module `luxon` imported from `(require)`

### ISSUE THREAD

**Issue by roomman** [embroider-build/embroider#1032]
I'm trying to import [Luxon](https://moment.github.io/luxon/#/install) into an Embroider enabled app, for use in a helper.

I've installed as a dependency and am importing with the following syntax:
```
import { DateTime } from 'luxon';
```
The stack trace is included below:
```
Error: Could not find module `luxon` imported from `(require)`
    at missingModule (/var/folders/cp/mp10cjhd1xdf8wg5gk7s9g500000gn/T/broccoli-8071SHJfck1TpX65/out-236-packager_runner_embroider_webpack/assets/node_modules/@embroider/synthesized-vendor/vendor/loader/loader.js:247:1)
    at findModule (/var/folders/cp/mp10cjhd1xdf8wg5gk7s9g500000gn/T/broccoli-8071SHJfck1TpX65/out-236-packager_runner_embroider_webpack/assets/node_modules/@embroider/synthesized-vendor/vendor/loader/loader.js:258:1)
    at requireModule (/var/folders/cp/mp10cjhd1xdf8wg5gk7s9g500000gn/T/broccoli-8071SHJfck1TpX65/out-236-packager_runner_embroider_webpack/assets/node_modules/@embroider/synthesized-vendor/vendor/loader/loader.js:24:1)
    at eval (webpack://solomon-website/../externals/luxon.js?:1:18)
    at Object.../externals/luxon.js (/var/folders/cp/mp10cjhd1xdf8wg5gk7s9g500000gn/T/broccoli-8071SHJfck1TpX65/out-236-packager_runner_embroider_webpack/assets/chunk.441aa393e8c8bc3b3244.js:115:1)
    at __webpack_require__ (/var/folders/cp/mp10cjhd1xdf8wg5gk7s9g500000gn/T/broccoli-8071SHJfck1TpX65/out-236-packager_runner_embroider_webpack/assets/chunk.384e50d9b673dc373f0c.js:31:42)
    at eval (webpack://solomon-website/./helpers/date-format.js?:7:74)
    at Module../helpers/date-format.js (/var/folders/cp/mp10cjhd1xdf8wg5gk7s9g500000gn/T/broccoli-8071SHJfck1TpX65/out-236-packager_runner_embroider_webpack/assets/chunk.441aa393e8c8bc3b3244.js:72:1)
    at __webpack_require__ (/var/folders/cp/mp10cjhd1xdf8wg5gk7s9g500000gn/T/broccoli-8071SHJfck1TpX65/out-236-packager_runner_embroider_webpack/assets/chunk.384e50d9b673dc373f0c.js:31:42)
    at eval (webpack://solomon-website/./templates/blog/index.hbs?:7:81)
    at Module../templates/blog/index.hbs (/var/folders/cp/mp10cjhd1xdf8wg5gk7s9g500000gn/T/broccoli-8071SHJfck1TpX65/out-236-packager_runner_embroider_webpack/assets/chunk.441aa393e8c8bc3b3244.js:29:1)
    at __webpack_require__ (/var/folders/cp/mp10cjhd1xdf8wg5gk7s9g500000gn/T/broccoli-8071SHJfck1TpX65/out-236-packager_runner_embroider_webpack/assets/chunk.384e50d9b673dc373f0c.js:31:42)
    at Module.eval [as callback] (webpack://solomon-website/./assets/_route_/blog.js?:9:10)
    at Module.exports (/var/folders/cp/mp10cjhd1xdf8wg5gk7s9g500000gn/T/broccoli-8071SHJfck1TpX65/out-236-packager_runner_embroider_webpack/assets/node_modules/@embroider/synthesized-vendor/vendor/loader/loader.js:106:1)
    at requireModule (/var/folders/cp/mp10cjhd1xdf8wg5gk7s9g500000gn/T/broccoli-8071SHJfck1TpX65/out-236-packager_runner_embroider_webpack/assets/node_modules/@embroider/synthesized-vendor/vendor/loader/loader.js:27:1)
    at ModuleRegistry.get (webpack://solomon-website/./node_modules/ember-resolver/resolvers/classic/index.js?:40:19)
    at Class._extractDefaultExport (webpack://solomon-website/./node_modules/ember-resolver/resolvers/classic/index.js?:473:39)
    at Class.resolveOther (webpack://solomon-website/./node_modules/ember-resolver/resolvers/classic/index.js?:133:30)
    at Class.resolveTemplate (webpack://solomon-website/./node_modules/ember-resolver/resolvers/classic/index.js?:274:25)
    at Class.resolve (webpack://solomon-website/./node_modules/ember-resolver/resolvers/classic/index.js?:190:41)
    at resolve (/var/folders/cp/mp10cjhd1xdf8wg5gk7s9g500000gn/T/broccoli-8071SHJfck1TpX65/out-236-packager_runner_embroider_webpack/assets/@ember/-internals/container/index.js:1106:1)
    at Registry.resolve (/var/folders/cp/mp10cjhd1xdf8wg5gk7s9g500000gn/T/broccoli-8071SHJfck1TpX65/out-236-packager_runner_embroider_webpack/assets/@ember/-internals/container/index.js:717:1)
    at Registry.resolve (/var/folders/cp/mp10cjhd1xdf8wg5gk7s9g500000gn/T/broccoli-8071SHJfck1TpX65/out-236-packager_runner_embroider_webpack/assets/@ember/-internals/container/index.js:720:1)
    at factoryFor (/var/folders/cp/mp10cjhd1xdf8wg5gk7s9g500000gn/T/broccoli-8071SHJfck1TpX65/out-236-packager_runner_embroider_webpack/assets/@ember/-internals/container/index.js:284:1)
    at instantiateFactory (/var/folders/cp/mp10cjhd1xdf8wg5gk7s9g500000gn/T/broccoli-8071SHJfck1TpX65/out-236-packager_runner_embroider_webpack/assets/@ember/-internals/container/index.js:337:1)
    at lookup (/var/folders/cp/mp10cjhd1xdf8wg5gk7s9g500000gn/T/broccoli-8071SHJfck1TpX65/out-236-packager_runner_embroider_webpack/assets/@ember/-internals/container/index.js:274:1)
    at Container.lookup (/var/folders/cp/mp10cjhd1xdf8wg5gk7s9g500000gn/T/broccoli-8071SHJfck1TpX65/out-236-packager_runner_embroider_webpack/assets/@ember/-internals/container/index.js:139:1)
    at Class.lookup (/var/folders/cp/mp10cjhd1xdf8wg5gk7s9g500000gn/T/broccoli-8071SHJfck1TpX65/out-236-packager_runner_embroider_webpack/assets/@ember/-internals/runtime/lib/mixins/container_proxy.js:81:1)
    at buildRenderOptions (/var/folders/cp/mp10cjhd1xdf8wg5gk7s9g500000gn/T/broccoli-8071SHJfck1TpX65/out-236-packager_runner_embroider_webpack/assets/@ember/-internals/routing/lib/system/route.js:1690:1)
    at BlogIndexRoute.[render] (/var/folders/cp/mp10cjhd1xdf8wg5gk7s9g500000gn/T/broccoli-8071SHJfck1TpX65/out-236-packager_runner_embroider_webpack/assets/@ember/-internals/routing/lib/system/route.js:1276:1)
    at BlogIndexRoute.renderTemplate (/var/folders/cp/mp10cjhd1xdf8wg5gk7s9g500000gn/T/broccoli-8071SHJfck1TpX65/out-236-packager_runner_embroider_webpack/assets/@ember/-internals/routing/lib/system/route.js:1312:1)
    at BlogIndexRoute.setup (/var/folders/cp/mp10cjhd1xdf8wg5gk7s9g500000gn/T/broccoli-8071SHJfck1TpX65/out-236-packager_runner_embroider_webpack/assets/@ember/-internals/routing/lib/system/route.js:836:1)
    at _routeEnteredOrUpdated (/var/folders/cp/mp10cjhd1xdf8wg5gk7s9g500000gn/T/broccoli-8071SHJfck1TpX65/out-236-packager_runner_embroider_webpack/assets/router_js.js:1777:1)
    at PrivateRouter.routeEnteredOrUpdated (/var/folders/cp/mp10cjhd1xdf8wg5gk7s9g500000gn/T/broccoli-8071SHJfck1TpX65/out-236-packager_runner_embroider_webpack/assets/router_js.js:1789:1)
    at PrivateRouter.setupContexts (/var/folders/cp/mp10cjhd1xdf8wg5gk7s9g500000gn/T/broccoli-8071SHJfck1TpX65/out-236-packager_runner_embroider_webpack/assets/router_js.js:1724:1)
    at PrivateRouter.finalizeTransition (/var/folders/cp/mp10cjhd1xdf8wg5gk7s9g500000gn/T/broccoli-8071SHJfck1TpX65/out-236-packager_runner_embroider_webpack/assets/router_js.js:1619:1)
    at /var/folders/cp/mp10cjhd1xdf8wg5gk7s9g500000gn/T/broccoli-8071SHJfck1TpX65/out-236-packager_runner_embroider_webpack/assets/router_js.js:1558:1
    at invokeCallback (/var/folders/cp/mp10cjhd1xdf8wg5gk7s9g500000gn/T/broccoli-8071SHJfck1TpX65/out-236-packager_runner_embroider_webpack/assets/rsvp.js:495:1)
    at publish (/var/folders/cp/mp10cjhd1xdf8wg5gk7s9g500000gn/T/broccoli-8071SHJfck1TpX65/out-236-packager_runner_embroider_webpack/assets/rsvp.js:478:1)
    at /var/folders/cp/mp10cjhd1xdf8wg5gk7s9g500000gn/T/broccoli-8071SHJfck1TpX65/out-236-packager_runner_embroider_webpack/assets/ember-testing/lib/ext/rsvp.js:19:1
    at invokeWithOnError (/var/folders/cp/mp10cjhd1xdf8wg5gk7s9g500000gn/T/broccoli-8071SHJfck1TpX65/out-236-packager_runner_embroider_webpack/assets/backburner.js:347:1)
    at Queue.flush (/var/folders/cp/mp10cjhd1xdf8wg5gk7s9g500000gn/T/broccoli-8071SHJfck1TpX65/out-236-packager_runner_embroider_webpack/assets/backburner.js:229:1)
    at DeferredActionQueues.flush (/var/folders/cp/mp10cjhd1xdf8wg5gk7s9g500000gn/T/broccoli-8071SHJfck1TpX65/out-236-packager_runner_embroider_webpack/assets/backburner.js:426:1)
    at Backburner._end (/var/folders/cp/mp10cjhd1xdf8wg5gk7s9g500000gn/T/broccoli-8071SHJfck1TpX65/out-236-packager_runner_embroider_webpack/assets/backburner.js:958:1)
    at Backburner._boundAutorunEnd (/var/folders/cp/mp10cjhd1xdf8wg5gk7s9g500000gn/T/broccoli-8071SHJfck1TpX65/out-236-packager_runner_embroider_webpack/assets/backburner.js:627:1)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
Is there a known workaround / fix for this?

**Comment by roomman** [comment]
Importing from `luxon/src/luxon` fixed this issue for me.
