### ISSUE TITLE
unable to resolve babel plugin @babel/plugin-proposal-private-methods from /tmp/embroider/41c7ff/tests/dummy

### ISSUE THREAD

**Issue by NullVoxPopuli** [embroider-build/embroider#1036]
In this Ci Run: https://github.com/NullVoxPopuli/ember-statechart-component/runs/4413261031?check_suite_focus=true#step:5:135
from this PR: https://github.com/NullVoxPopuli/ember-statechart-component/pull/149
which is trying to get around: https://github.com/babel/ember-cli-babel/issues/419

I've run in to this error: 
```
- message: unable to resolve babel plugin @babel/plugin-proposal-private-methods from /tmp/embroider/41c7ff/tests/dummy
        at WaitForTrees (@embroider/compat/app)
-~- created here: -~-
    at new Plugin (/home/runner/work/ember-statechart-component/ember-statechart-component/node_modules/@embroider/core/node_modules/broccoli-plugin/dist/index.js:47:36)
    at new WaitForTrees (/home/runner/work/ember-statechart-component/ember-statechart-component/node_modules/@embroider/core/src/wait-for-trees.js:30:9)
    at CompatApp.get tree (/home/runner/work/ember-statechart-component/ember-statechart-component/node_modules/@embroider/core/src/build-stage.js:26:16)
    at CompatApp.<anonymous> (/home/runner/work/ember-statechart-component/ember-statechart-component/node_modules/typescript-memoize/dist/memoize-decorator.js:132:52)
    ```
    
which, I don't quite understand, because this plugin should not be used?
my targets declare that I don't need private-method transformation. :thinking: 

I tried
```
❯ npx browserslist --update-db
Latest version:     1.0.30001284
Installed version:  1.0.30001284
caniuse-lite is up to date
caniuse-lite has been successfully updated

No target browser changes
```
but my browsers list is already up to date.

**Comment by NullVoxPopuli** [comment]
forcing the plugin to exist doesn't help either, which confuses me
: https://github.com/NullVoxPopuli/ember-statechart-component/pull/149/files#diff-efa7561fd196a5304c1c80012f1f6153c58faf5697ba3a59465ae7ce06b8e550R49-R62
```js
embroiderSafe({
  npm: {
    devDependencies: {
      '@babel/plugin-proposal-private-methods': '^7.0.0',
    },
  },
}),
```

**Comment by NullVoxPopuli** [comment]
Related issue: https://github.com/embroider-build/embroider/issues/979
