### ISSUE TITLE
`publicAssetURL` with `http` breaks FastBoot app start

### ISSUE THREAD

**Issue by harrywebdev** [embroider-build/embroider#1047]
The problem I've encountered is that when supplying `publicAssetURL` in the `ember-cli-build.js` and then running FastBoot server, the app does not start.

I've figured (maybe incorrectly) that the issue is that FastBoot cannot load chunks and vendor JS from a URL; I've tried with `http://localhost:4200/` and so script tag like this:

```
<fastboot-script src="/assets/chunk.cb00fe45238dfac55e20.js"></fastboot-script>
```

work fine, but with the `publicAssetURL` provided, the final tag looks like this:

```
<fastboot-script src="http://localhost:4200/assets/chunk.cb00fe45238dfac55e20.js"></fastboot-script>
```

and so the server does not load any chunks, nor the `vendor.js` file and so in my case dies on this error

```
/web/dist/ember-fetch/fetch-fastboot.js:2
define('fetch', ['exports'], function(exports) {
^

ReferenceError: define is not defined
    at /web/dist/ember-fetch/fetch-fastboot.js:2:1
    at Script.runInContext (vm.js:144:12)
    at Sandbox.runScript (/web/node_modules/fastboot/src/sandbox.js:57:12)
    at EmberApp.buildApp (/web/node_modules/fastboot/src/ember-app.js:158:15)
    at /web/node_modules/fastboot/src/ember-app.js:139:22
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at EmberApp.getNewApplicationInstance (/web/node_modules/fastboot/src/ember-app.js:209:17)
    at EmberApp._visit (/web/node_modules/fastboot/src/ember-app.js:240:9)
    at EmberApp.visit (/web/node_modules/fastboot/src/ember-app.js:325:7)
    at FastBoot.visit (/web/node_modules/fastboot/src/index.js:86:18)
    at /web/node_modules/fastboot-app-server/node_modules/fastboot-express-middleware/src/index.js:33:20
```

I'm running [FastBoot App Server](https://github.com/ember-fastboot/fastboot-app-server) of version 3.0.0.

I've came up with an idea to keep the paths absolute (as if no URL is provided) for FastBoot and only add that for the browser to use. The attached PR is currently a "hack" - I wouldn't go as far to call it a "fix". I don't know the internals so this might be completely off.

**Comment by ef4** [comment]
See https://github.com/embroider-build/embroider/pull/1046#issuecomment-991952676
