### ISSUE TITLE
Bug Report - Embroider chunk loading is causing Fastboot to throw an error

### ISSUE THREAD

**Issue by roomman** [embroider-build/embroider#1060]
### 🐞 Describe the Bug
Fastboot is throwing the following error when I hit the `blog` route in my Embroider enabled project, when code splitting is on:
```
ReferenceError: document is not defined
    at Function.__webpack_require__.l (/var/folders/cp/mp10cjhd1xdf8wg5gk7s9g500000gn/T/broccoli-41657P7FKRCvfTxWr/out-158-packager_runner_embroider_webpack/assets/chunk.7a34d1216b64cdf031d4.js:172:28)
    at Object.__webpack_require__.f.j (/var/folders/cp/mp10cjhd1xdf8wg5gk7s9g500000gn/T/broccoli-41657P7FKRCvfTxWr/out-158-packager_runner_embroider_webpack/assets/chunk.7a34d1216b64cdf031d4.js:269:37)
    at /var/folders/cp/mp10cjhd1xdf8wg5gk7s9g500000gn/T/broccoli-41657P7FKRCvfTxWr/out-158-packager_runner_embroider_webpack/assets/chunk.7a34d1216b64cdf031d4.js:134:40
    at Array.reduce (<anonymous>)
    at Function.__webpack_require__.e (/var/folders/cp/mp10cjhd1xdf8wg5gk7s9g500000gn/T/broccoli-41657P7FKRCvfTxWr/out-158-packager_runner_embroider_webpack/assets/chunk.7a34d1216b64cdf031d4.js:133:67)
    at Object.load (webpack://ember-visit-blog-bug/./assets/ember-visit-blog-bug.js?:67:60)
    at PrivateRouter.eval [as getRoute] (webpack://ember-visit-blog-bug/./node_modules/@embroider/router/index.js?:95:23)
    at UnresolvedRouteInfoByParam.fetchRoute (/var/folders/cp/mp10cjhd1xdf8wg5gk7s9g500000gn/T/broccoli-41657P7FKRCvfTxWr/out-158-packager_runner_embroider_webpack/assets/router_js.js:879:1)
    at UnresolvedRouteInfoByParam.get route [as route] (/var/folders/cp/mp10cjhd1xdf8wg5gk7s9g500000gn/T/broccoli-41657P7FKRCvfTxWr/out-158-packager_runner_embroider_webpack/assets/router_js.js:799:1)
    at URLTransitionIntent.applyToState (/var/folders/cp/mp10cjhd1xdf8wg5gk7s9g500000gn/T/broccoli-41657P7FKRCvfTxWr/out-158-packager_runner_embroider_webpack/assets/router_js.js:1411:1)
    at PrivateRouter.getTransitionByIntent (/var/folders/cp/mp10cjhd1xdf8wg5gk7s9g500000gn/T/broccoli-41657P7FKRCvfTxWr/out-158-packager_runner_embroider_webpack/assets/router_js.js:1558:1)
    at PrivateRouter.transitionByIntent (/var/folders/cp/mp10cjhd1xdf8wg5gk7s9g500000gn/T/broccoli-41657P7FKRCvfTxWr/out-158-packager_runner_embroider_webpack/assets/router_js.js:1513:1)
    at PrivateRouter.doTransition (/var/folders/cp/mp10cjhd1xdf8wg5gk7s9g500000gn/T/broccoli-41657P7FKRCvfTxWr/out-158-packager_runner_embroider_webpack/assets/router_js.js:1657:1)
    at PrivateRouter.handleURL (/var/folders/cp/mp10cjhd1xdf8wg5gk7s9g500000gn/T/broccoli-41657P7FKRCvfTxWr/out-158-packager_runner_embroider_webpack/assets/router_js.js:2117:1)
    at Router._doURLTransition (/var/folders/cp/mp10cjhd1xdf8wg5gk7s9g500000gn/T/broccoli-41657P7FKRCvfTxWr/out-158-packager_runner_embroider_webpack/assets/@ember/-internals/routing/lib/system/router.js:485:1)
    at Router.handleURL (/var/folders/cp/mp10cjhd1xdf8wg5gk7s9g500000gn/T/broccoli-41657P7FKRCvfTxWr/out-158-packager_runner_embroider_webpack/assets/@ember/-internals/routing/lib/system/router.js:479:1)
    at Class.visit (/var/folders/cp/mp10cjhd1xdf8wg5gk7s9g500000gn/T/broccoli-41657P7FKRCvfTxWr/out-158-packager_runner_embroider_webpack/assets/@ember/application/instance.js:250:1)
    at EmberApp._visit (/Users/simon/Sites/ember-visit-blog-bug/node_modules/fastboot/src/ember-app.js:265:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at EmberApp.visit (/Users/simon/Sites/ember-visit-blog-bug/node_modules/fastboot/src/ember-app.js:325:7)
    at FastBoot.visit (/Users/simon/Sites/ember-visit-blog-bug/node_modules/fastboot/src/index.js:86:18)
    at /Users/simon/Sites/ember-visit-blog-bug/node_modules/fastboot-express-middleware/src/index.js:33:20
```
Turning off code splitting fixes the issue.

With code splitting enabled, removing any component invocation from `blog.hbs` also fixes the issue. Could it be something to do with chunk sizing?

### 🔬 Minimal Reproduction
A reproduction [can be found here](https://github.com/roomman/ember-visit-blog-bug). The reproduction contains some "fluff", like tailwind classes and a helper that are only relevant to the bug because removing them, and thereby altering file sizes(?), fixes the bug.

### 😕 Actual Behavior
Run `ember serve` and hit `localhost:4200/blog` and Fastboot throws an error.

### 🤔 Expected Behavior
Run `ember serve` and hit `localhost:4200/blog` and the page renders.

### 🌍 Environment

- Ember: 3.28.8
- Node.js/npm: - 16.13.0 / 8.1.0
- OS: - macOS Big Sur 11.4
- Browser: - Safari 14.1.1 and Chrome 96.0.4664.93

**Comment by roomman** [comment]
Closing this as it appears to have been fixed by #1109. 🙏🏼
