### ISSUE TITLE
Expecting 'OPEN_SEXPR', 'ID', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', got 'INVALID'

### ISSUE THREAD

**Issue by angelayanpan** [embroider-build/embroider#1065]
hi, trying to add Embroider test scenarios to an addOn. and this is the error that I see when I try to run "yarn test" 

```
ERROR in ../../templates/components/projects-pills-typeahead.hbs
Module Error (from ../../../../../../../../../../Users/apan/Project/ember-cli-ts-typeahead/node_modules/thread-loader/dist/cjs.js):
Parse error on line 33:
...lt}}>            {{ember-cli-ts-typeahe
----------------------^
Expecting 'OPEN_SEXPR', 'ID', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', got 'INVALID'
 @ ./assets/dummy.js 4333:9-78

ERROR in ../../node_modules/@ember/test-helpers/-internal/debug-info.js 17:0-60
Module not found: Error: Can't resolve '@ember/test-waiters' in '$TMPDIR/embroider/dedea7/node_modules/@ember/test-helpers/-internal'
 @ ./assets/test.js 52:9-82

ERROR in ../../node_modules/@ember/test-helpers/settled.js 4:0-56
Module not found: Error: Can't resolve '@ember/test-waiters' in '$TMPDIR/embroider/dedea7/node_modules/@ember/test-helpers'
 @ ./assets/test.js 181:9-69

ERROR in ../../node_modules/@linkedin/ember-cli-pemberly-tracking/modifiers/render-performance.js 62:0-50
Module not found: Error: Can't resolve '@ember/test-waiters' in '$TMPDIR/embroider/dedea7/node_modules/@linkedin/ember-cli-pemberly-tracking/modifiers'
 @ ./assets/dummy.js 4219:9-108

ERROR in ../../node_modules/ember-a11y-testing/test-support/audit.js 5:0-53
Module not found: Error: Can't resolve '@ember/test-waiters' in '$TMPDIR/embroider/dedea7/node_modules/ember-a11y-testing/test-support'
 @ ./assets/test.js 232:9-79

ERROR in ./assets/dummy.js 4123:9-125
Module not found: Error: Can't resolve '../../../node_modules/@linkedin/ember-cli-pemberly-tracking/node_modules/@ember/test-waiters/build-waiter' in '$TMPDIR/embroider/dedea7/tests/dummy/assets'

ERROR in ./assets/dummy.js 4126:9-137
Module not found: Error: Can't resolve '../../../node_modules/@linkedin/ember-cli-pemberly-tracking/node_modules/@ember/test-waiters/ember-test-waiters/index' in '$TMPDIR/embroider/dedea7/tests/dummy/assets'

ERROR in ./assets/dummy.js 4129:9-118
Module not found: Error: Can't resolve '../../../node_modules/@linkedin/ember-cli-pemberly-tracking/node_modules/@ember/test-waiters/index' in '$TMPDIR/embroider/dedea7/tests/dummy/assets'

ERROR in ./assets/dummy.js 4132:9-118
Module not found: Error: Can't resolve '../../../node_modules/@linkedin/ember-cli-pemberly-tracking/node_modules/@ember/test-waiters/token' in '$TMPDIR/embroider/dedea7/tests/dummy/assets'

ERROR in ./assets/dummy.js 4135:9-124
Module not found: Error: Can't resolve '../../../node_modules/@linkedin/ember-cli-pemberly-tracking/node_modules/@ember/test-waiters/types/index' in '$TMPDIR/embroider/dedea7/tests/dummy/assets'

ERROR in ./assets/dummy.js 4138:9-129
Module not found: Error: Can't resolve '../../../node_modules/@linkedin/ember-cli-pemberly-tracking/node_modules/@ember/test-waiters/wait-for-promise' in '$TMPDIR/embroider/dedea7/tests/dummy/assets'

ERROR in ./assets/dummy.js 4141:9-121
Module not found: Error: Can't resolve '../../../node_modules/@linkedin/ember-cli-pemberly-tracking/node_modules/@ember/test-waiters/wait-for' in '$TMPDIR/embroider/dedea7/tests/dummy/assets'

ERROR in ./assets/dummy.js 4144:9-127
Module not found: Error: Can't resolve '../../../node_modules/@linkedin/ember-cli-pemberly-tracking/node_modules/@ember/test-waiters/waiter-manager' in '$TMPDIR/embroider/dedea7/tests/dummy/assets'

ERROR in ./assets/dummy.js 4360:9-74
Module not found: Error: Can't resolve '../../../node_modules/@ember/test-waiters/build-waiter' in '$TMPDIR/embroider/dedea7/tests/dummy/assets'

ERROR in ./assets/dummy.js 4363:9-86
Module not found: Error: Can't resolve '../../../node_modules/@ember/test-waiters/ember-test-waiters/index' in '$TMPDIR/embroider/dedea7/tests/dummy/assets'

ERROR in ./assets/dummy.js 4366:9-67
Module not found: Error: Can't resolve '../../../node_modules/@ember/test-waiters/index' in '$TMPDIR/embroider/dedea7/tests/dummy/assets'

ERROR in ./assets/dummy.js 4369:9-67
Module not found: Error: Can't resolve '../../../node_modules/@ember/test-waiters/token' in '$TMPDIR/embroider/dedea7/tests/dummy/assets'

ERROR in ./assets/dummy.js 4372:9-73
Module not found: Error: Can't resolve '../../../node_modules/@ember/test-waiters/types/index' in '$TMPDIR/embroider/dedea7/tests/dummy/assets'

ERROR in ./assets/dummy.js 4375:9-78
Module not found: Error: Can't resolve '../../../node_modules/@ember/test-waiters/wait-for-promise' in '$TMPDIR/embroider/dedea7/tests/dummy/assets'

ERROR in ./assets/dummy.js 4378:9-70
Module not found: Error: Can't resolve '../../../node_modules/@ember/test-waiters/wait-for' in '$TMPDIR/embroider/dedea7/tests/dummy/assets'

ERROR in ./assets/dummy.js 4381:9-76
Module not found: Error: Can't resolve '../../../node_modules/@ember/test-waiters/waiter-manager' in '$TMPDIR/embroider/dedea7/tests/dummy/assets'

ERROR in ./components/ts-typeahead.js 1:0-83
Module not found: Error: Can't resolve '@linkedin/ember-cli-ts-typeahead/components/ts-typeahead' in '$TMPDIR/embroider/dedea7/tests/dummy/components'
 @ ./assets/dummy.js 3043:9-49

22 errors have detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

webpack 5.65.0 compiled with 22 errors and 7 warnings in 14435 ms
cleaning up...
Build Error (PackagerRunner) in ../../templates/components/projects-pills-typeahead.hbs

Module Error (from ../../../../../../../../../../Users/apan/Project/ember-cli-ts-typeahead/node_modules/thread-loader/dist/cjs.js):
Parse error on line 33:
...lt}}>            {{ember-cli-ts-typeahe
----------------------^
Expecting 'OPEN_SEXPR', 'ID', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', got 'INVALID'


Stack Trace and Error Report: /var/folders/zx/zln4zlz96812ljx8xn1yg0c4001prb/T/error.dump.913e3b527a5878c4342cba332a4d17ec.log
Error: Command: ember exam --load-balance --parallel 16 --write-execution-file --ssl false exited with code 1
    at ChildProcess.<anonymous> (/Users/apan/Project/ember-cli-ts-typeahead/node_modules/@linkedin/ts-web-tools/src/utils/spawn.ts:23:13)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by ef4** [comment]
Can you share the contents of the `projects-pills-typeahead.hbs` template that is failing to parse?

**Comment by angelayanpan** [comment]
line 33 and to all the way end of the file:

```
<ArtdecoTypeahead as |ta|>
  <label class="t-16" for="project-name-typeahead-input">
    {{t "i18n_typeahead_label"}}
  </label>
  {{component
    "ember-cli-ts-typeahead@ts-pill-typeahead-input"
    artdecoTypeaheadRef=ta
    hideTypeaheadInput=hideTypeaheadInput
    onBlur=(action "onBlur")
    onDismiss=(action "onDismiss")
    onFocus=(action "onFocus")
    onInput=(action "onInput")
    onKeyDown=(action "onKeyDown")
    pills=pills
    placeholder=(t typeaheadPlaceholderKey)
    value=taValue
    inputId="project-name-typeahead-input"
  }}
  {{#unless isCreateProjectFlow}}
    <ta.typeahead-results-list
      @ariaLabel={{t "i18n_search_results_label"}}
      @className="projects-pills-typeahead__result-list"
      as |taList|
    >
      {{#if loadingResults}}
        {{component "ember-cli-ts-typeahead@typeahead/typeahead-loading"}}
      {{else if noResults}}
        {{component
          "ember-cli-ts-typeahead@typeahead/typeahead-no-results"
          showIcon=false
          headerTextAlign="left"
          heading=(t "i18n_no_projects_results")
        }}
      {{else if showResultsList}}
        {{#if showCreateButton}}
          <taList.typeahead-result
            @className="link"
            @idx={{results.length}}
            @onSelect={{action "onSelect" "CREATE" taValue}}
          >
            <span class="projects-pills-typeahead__result-create t-14" data-test-create-project-option>
              {{li-icon class="projects-pills-typeahead__plus-icon" type="plus-icon" size="small"}}
              {{#if taValue}}
                {{t "i18n_create_project_name" name=taValue}}
              {{else}}
                {{t "i18n_create_project"}}
              {{/if}}
            </span>
          </taList.typeahead-result>
        {{/if}}
        {{#if results.length}}
          <h4
            class={{concat
              "projects-pills-typeahead__optgroup"
              (if showCreateButton " show-create-button")
              " t-16 t-bold"
            }}
            data-test-options-heading
          >
            {{t (if taValue "i18n_matching_projects" "i18n_recent_projects")}}
          </h4>
        {{/if}}
        {{#each results as |result index|}}
          <taList.typeahead-result @idx={{index}} @onSelect={{action "onSelect" "UPDATE" result}}>
            {{ember-cli-ts-typeahead$typeahead/typeahead-project-result result=result}}
          </taList.typeahead-result>
        {{/each}}
      {{/if}}
    </ta.typeahead-results-list>
  {{/unless}}
</ArtdecoTypeahead>
```

**Comment by ef4** [comment]
Oh, and perhaps you have some custom AST transforms that are rewriting this template? If I recall correctly, LinkIn uses a `t` helper that has an AST transform.

**Comment by angelayanpan** [comment]
not sure what you mean?  is custom AST an issue with embroider?

**Comment by ef4** [comment]
If there are custom transforms, we might not see the syntax error in the template-as-authored, we'd need to see the template after it has passed through the custom transforms.

When you build this app, it prints somewhere in the output "building into..." and names a tempdir. Inside that tempdir is a reproduction of your node_modules, but rewritten into v2 format. Can you find this template in there and share a copy of what it looks like? It will probably be different from the one you pasted above.

**Comment by angelayanpan** [comment]
an update on this. I converted 2 to 3 {{component }} pattern to < /> and I think now I passed through this error. 

some other error surfaced. but no long seeing this.
