### ISSUE TITLE
using ember-element-helper in addons and building with embroider-optimized

### ISSUE THREAD

**Issue by angelayanpan** [embroider-build/embroider#1193]
ember-element-helper: 0.6.1

all embroider lib: 1.6

ember-cli: 3.26

Error from embroider: `Unsafe dynamic component: cannot statically analyze this expression in $TMPDIR/embroider/cec7f8/node_modules/@linkedin/ember-ts-presentational/components/blank-wrapper/index.hbs`

```
Build Error (PackagerRunner) in ../../node_modules/@linkedin/ember-ts-presentational/components/blank-wrapper/index.hbs

Module build failed (from ../../../../../content/data/multiproduct-post-commit-distributed-test/i001/workspace/ember-ts-vertical-link-menu_8274321a044b3b1b7c225e9efc8113eda17be0eb/node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 0)
$TMPDIR/embroider/cec7f8/node_modules/@linkedin/ember-ts-presentational/components/blank-wrapper/index.hbs/index.hbs: Unsafe dynamic component: cannot statically analyze this expression in $TMPDIR/embroider/cec7f8/node_modules/@linkedin/ember-ts-presentational/components/blank-wrapper/index.hbs
    at PoolWorker.fromErrorObj (/export/content/data/multiproduct-post-commit-distributed-test/i001/workspace/ember-ts-vertical-link-menu_8274321a044b3b1b7c225e9efc8113eda17be0eb/node_modules/thread-loader/dist/WorkerPool.js:346:12)
    at /export/content/data/multiproduct-post-commit-distributed-test/i001/workspace/ember-ts-vertical-link-menu_8274321a044b3b1b7c225e9efc8113eda17be0eb/node_modules/thread-loader/dist/WorkerPool.js:219:29
    at CompatResolver.dependenciesOf (/export/content/data/multiproduct-post-commit-distributed-test/i001/workspace/ember-ts-vertical-link-menu_8274321a044b3b1b7c225e9efc8113eda17be0eb/node_modules/@embroider/compat/src/resolver.js:252:33)
    at NodeTemplateCompiler.precompile (/export/content/data/multiproduct-post-commit-distributed-test/i001/workspace/ember-ts-vertical-link-menu_8274321a044b3b1b7c225e9efc8113eda17be0eb/node_modules/@embroider/core/src/template-compiler-common.js:61:42)
    at handleCalled (/export/content/data/multiproduct-post-commit-distributed-test/i001/workspace/ember-ts-vertical-link-menu_8274321a044b3b1b7c225e9efc8113eda17be0eb/node_modules/@embroider/core/src/babel-plugin-inline-hbs.js:75:39)
    at PluginPass.CallExpression (/export/content/data/multiproduct-post-commit-distributed-test/i001/workspace/ember-ts-vertical-link-menu_8274321a044b3b1b7c225e9efc8113eda17be0eb/node_modules/@embroider/core/src/babel-plugin-inline-hbs.js:44:29)
    at PluginPass.<anonymous> (/export/content/data/multiproduct-post-commit-distributed-test/i001/workspace/ember-ts-vertical-link-menu_8274321a044b3b1b7c225e9efc8113eda17be0eb/node_modules/@embroider/core/src/portable-babel-launcher.js:37:29)
    at newFn (/export/content/data/multiproduct-post-commit-distributed-test/i001/workspace/ember-ts-vertical-link-menu_8274321a044b3b1b7c225e9efc8113eda17be0eb/node_modules/@babel/traverse/lib/visitors.js:177:21)
    at NodePath._call (/export/content/data/multiproduct-post-commit-distributed-test/i001/workspace/ember-ts-vertical-link-menu_8274321a044b3b1b7c225e9efc8113eda17be0eb/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/export/content/data/multiproduct-post-commit-distributed-test/i001/workspace/ember-ts-vertical-link-menu_8274321a044b3b1b7c225e9efc8113eda17be0eb/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/export/content/data/multiproduct-post-commit-distributed-test/i001/workspace/ember-ts-vertical-link-menu_8274321a044b3b1b7c225e9efc8113eda17be0eb/node_modules/@babel/traverse/lib/path/context.js:100:31)
    at TraversalContext.visitQueue (/export/content/data/multiproduct-post-commit-distributed-test/i001/workspace/ember-ts-vertical-link-menu_8274321a044b3b1b7c225e9efc8113eda17be0eb/node_modules/@babel/traverse/lib/context.js:103:16)


Stack Trace and Error Report: /tmp/error.dump.8c3457ddc6f9dc135186763bf28e6634.log
Error: Command: ember exam --load-balance --parallel 16 --write-execution-file --ssl false exited with code 1
    at ChildProcess.<anonymous> (/export/content/data/multiproduct-post-commit-distributed-test/i001/workspace/ember-ts-vertical-link-menu_8274321a044b3b1b7c225e9efc8113eda17be0eb/node_modules/@linkedin/ts-web-tools/dist/spawn-d3d4ffec.js:15:116)
    at ChildProcess.emit (node:events:520:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Windvis** [comment]
@angelayanpan What does `blank-wrapper/index.hbs` template look like? The ember-element-helper should be Embroider optimized compatible (it runs the tests against it in CI).

**Comment by angelayanpan** [comment]
hi, it produces this error when: template looks like:

`{{#let (element this.tagName) as |Tag|}}{{/let}}`
or
`{{#let (element (or @tagName "span")) as |Tag|}}{{/let}}`
or
` {{#let (element "span") as |Tag|}} `<= still has that error 

this was discussed in last Thursday's office hour by the way.

**Comment by angelayanpan** [comment]
I believe the Tests against it in ember-element-helper is for `app only`,  that's what was mentioned by @rwjblue

**Comment by Windvis** [comment]
@angelayanpan Do you have any other ember-element-helper versions in your node_modules tree? Can you reproduce it in a new application / addon? What does `npm ls ember-element-helper` or `yarn why ember-element-helper` say?

Looking at the addon's code it seems that it used to transform `(element "span")` into `(component (-element "span"))` in < 0.5.0 releases which would hit [this code path](https://github.com/embroider-build/embroider/blob/9271aa877d70e4c1bf214fc4e34321ffeeb8d1ae/packages/compat/src/resolver.ts#L793-L803) in Embroider and output the error you are seeing.

The transform was also adjusted and has since been [removed](https://github.com/tildeio/ember-element-helper/pull/82) in the 0.6.1 release which makes me believe there is another version in play that might still bring in the old template transform (which isn't Embroider compatible) into your build.

**Comment by angelayanpan** [comment]
`apan@apan-mn1 ember-ts-vertical-link-menu % yarn why ember-element-helper
yarn why v1.22.4
[1/4] 🤔  Why do we have the module "ember-element-helper"...?
[2/4] 🚚  Initialising dependency graph...
warning Resolution field "@babel/parser@7.17.3" is incompatible with requested version "@babel/parser@^7.17.9"
warning Resolution field "@babel/parser@7.17.3" is incompatible with requested version "@babel/parser@^7.17.9"
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "ember-element-helper@0.6.1"
info Has been hoisted to "ember-element-helper"
info This module exists because it's specified in "dependencies".
info Disk size without dependencies: "380KB"
info Disk size with unique dependencies: "3.4MB"
info Disk size with transitive dependencies: "58.95MB"
info Number of shared dependencies: 190
=> Found "@linkedin/ember-ts-presentational#ember-element-helper@0.5.5"
info This module exists because "@linkedin#ember-ts-presentational" depends on it.
info Disk size without dependencies: "104KB"
info Disk size with unique dependencies: "3.13MB"
info Disk size with transitive dependencies: "58.68MB"
info Number of shared dependencies: 190
=> Found "@linkedin/hue-web-button#ember-element-helper@0.5.5"
info This module exists because "@linkedin#ember-ts-presentational#@linkedin#hue-web-button" depends on it.
info Disk size without dependencies: "104KB"
info Disk size with unique dependencies: "3.13MB"
info Disk size with transitive dependencies: "58.68MB"
info Number of shared dependencies: 190
=> Found "@linkedin/hue-web-tab#ember-element-helper@0.5.5"
info This module exists because "@linkedin#ember-ts-presentational#@linkedin#hue-web-tab" depends on it.
info Disk size without dependencies: "104KB"
info Disk size with unique dependencies: "3.13MB"
info Disk size with transitive dependencies: "58.68MB"
info Number of shared dependencies: 190
=> Found "@linkedin/hue-web-menu#ember-element-helper@0.5.5"
info This module exists because "@linkedin#ember-ts-presentational#@linkedin#hue-web-tab#@linkedin#hue-web-menu" depends on it.
info Disk size without dependencies: "104KB"
info Disk size with unique dependencies: "3.13MB"
info Disk size with transitive dependencies: "58.68MB"
info Number of shared dependencies: 190
✨  Done in 2.58s.`


I think you are right.  it seems like I have many many pre-0.6.1 versions.

**Comment by angelayanpan** [comment]
I added this:  `"ember-element-helper": "^0.6.1"` to resolutions, but I'm still getting an error from the file in `ember-ts-presentational`  :(

**Comment by angelayanpan** [comment]
also, can't reproduce this error if I just start a new addon from scratch

**Comment by angelayanpan** [comment]
https://github.com/tildeio/ember-element-helper/issues/84  <= maybe related?

**Comment by angelayanpan** [comment]
just wanted to give an update before closing this:

basically added resolution to 0.6.1 in all consumers first. and then that fan-ed out a bit.
but eventually I was able to bump ember-element-helper to 0.6.1
