### ISSUE TITLE
Using staticAppPaths results into RegEx error on Windows platform

### ISSUE THREAD

**Issue by davidvanelk** [embroider-build/embroider#1263]
Build of an ember app fails into a RegEx error when `staticAppPaths` is configured on a Windows machine. On a Linux machine everything works fine.
The project uses the following embroider version: ` "@embroider/compat": "~1.8.3"`

Console output when building on Windows:
```
file changed styleguide\template.hbs
Build Error (WaitForTrees)

Invalid regular expression: /^(?:utils|gql|models|locales)(?:$|\)/: Unterminated group
```

The configured `staticAppPaths` property from ember-cli-build.js:
```js
    staticAppPaths: ['utils', 'gql', 'models', 'locales'],
```

StackTrace from dumpfile:
```
ERROR Summary:

  - broccoliBuilderErrorStack: SyntaxError: Invalid regular expression: /^(?:utils|gql|models|locales)(?:$|\)/: Unterminated group
    at new RegExp (<anonymous>)
    at AppBuilder.get staticAppPathsPattern (<project-directory>\node_modules\@embroider\core\src\app.js:854:20)
    at AppBuilder.<anonymous> (<project-directory>\node_modules\typescript-memoize\dist\memoize-decorator.js:100:52)
    at AppBuilder.requiredOtherFiles (<project-directory>\node_modules\@embroider\core\src\app.js:862:28)
    at AppBuilder.appJSAsset (<project-directory>\node_modules\@embroider\core\src\app.js:879:38)
    at AppBuilder.topAppJSAsset (<project-directory>\node_modules\@embroider\core\src\app.js:845:21)
    at AppBuilder.insertEmberApp (<project-directory>\node_modules\@embroider\core\src\app.js:333:30)
    at AppBuilder.prepareAsset (<project-directory>\node_modules\@embroider\core\src\app.js:533:18)
    at AppBuilder.prepareAssets (<project-directory>\node_modules\@embroider\core\src\app.js:543:18)
    at AppBuilder.updateAssets (<project-directory>\node_modules\@embroider\core\src\app.js:610:27)
  - code: [undefined]
  - codeFrame: Invalid regular expression: /^(?:utils|gql|models|locales)(?:$|\)/: Unterminated group
  - errorMessage: Invalid regular expression: /^(?:utils|gql|models|locales)(?:$|\)/: Unterminated group
        at WaitForTrees (@embroider/compat/app)
-~- created here: -~-
    at new Plugin (<project-directory>\node_modules\@embroider\core\node_modules\broccoli-plugin\dist\index.js:47:36)
    at new WaitForTrees (<project-directory>\node_modules\@embroider\core\src\wait-for-trees.js:30:9)
    at CompatApp.get tree (<project-directory>\node_modules\@embroider\core\src\build-stage.js:25:16)
    at CompatApp.<anonymous> (<project-directory>\node_modules\typescript-memoize\dist\memoize-decorator.js:100:52)
    at new PackagerRunner (<project-directory>\node_modules\@embroider\core\src\to-broccoli-plugin.js:11:26)
    at Object.defaultPipeline (<project-directory>\node_modules\@embroider\compat\src\default-pipeline.js:49:12)
    at module.exports (<project-directory>\ember-cli-build.js:110:39)
    at Builder.readBuildFile (<project-directory>\node_modules\ember-cli\lib\models\builder.js:49:14)
    at Builder.setupBroccoliBuilder (<project-directory>\node_modules\ember-cli\lib\models\builder.js:63:22)
    at new Builder (<project-directory>\node_modules\ember-cli\lib\models\builder.js:29:10)
-~- (end) -~-
```

The dump notes that the built regex is not terminated properly. Maybe there is a difference between Unix and Windows platforms?

**Comment by Windvis** [comment]
I think this line is the problem: https://github.com/embroider-build/embroider/blob/031fd6ce264268d7e36a43c6c4c57417f25e3974/packages/core/src/app.ts#L1105

On Windows that `sep` variable [will be set to `\`](https://nodejs.org/api/path.html#pathsep) so it escapes the final `)` character which makes the regex invalid. I think we need to escape that `sep` variable before concatting it together.

The `/` character should also be escaped, but it seems the `new Regexp` call simply doesn't trigger an error (at least not on macOS).
