### ISSUE TITLE
Build Error when referencing styles from HTML in assets

### ISSUE THREAD

**Issue by bobisjan** [embroider-build/embroider#131]
Hello,

I'm testing Embroider in our application, and the build breaks on the missing stylesheets referenced from the `/public` folder.

`needed by assets/503.html: ENOENT: no such file or directory, stat '/private/var/folders/m3/2d92q9yx06j2q51zh2_w8js80000gn/T/embroider/585bc0/assets/styles/vendor.css'`

```html
<!-- /public/assets/503.html -->
<link rel="stylesheet" href="/assets/styles/vendor.css">
```

- `embroider 0.3.4`
- `ember-cli 3.9.0`

```
=================================================================================

ENV Summary:

  TIME: Sat Apr 13 2019 08:39:36 GMT+0200 (CEST)
  TITLE: ember
  ARGV:
  - /usr/local/bin/node
  - /Users/bobisjan/Developer/zonky-app/node_modules/.bin/ember
  - serve
  EXEC_PATH: /usr/local/bin/node
  TMPDIR: /var/folders/m3/2d92q9yx06j2q51zh2_w8js80000gn/T
  SHELL: /bin/bash
  PATH:
  - /var/folders/m3/2d92q9yx06j2q51zh2_w8js80000gn/T/yarn--1555137490450-0.32225072221560036
  - /Users/bobisjan/Developer/zonky-app/node_modules/.bin
  - /Users/bobisjan/.config/yarn/link/node_modules/.bin
  - /Users/bobisjan/Developer/zonky-app/node_modules/.bin
  - /Users/bobisjan/.config/yarn/link/node_modules/.bin
  - /usr/local/libexec/lib/node_modules/npm/bin/node-gyp-bin
  - /usr/local/lib/node_modules/npm/bin/node-gyp-bin
  - /usr/local/bin/node_modules/npm/bin/node-gyp-bin
  - /usr/local/opt/ruby/bin
  - /usr/local/bin
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  - /usr/local/MacGPG2/bin
  PLATFORM: darwin x64
  FREEMEM: 46301184
  TOTALMEM: 17179869184
  UPTIME: 1554166
  LOADAVG: 2.88427734375,2.53759765625,3.06787109375
  CPUS:
  - Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz - 2600
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.10.1-DEV
  - cldr: 32.0
  - http_parser: 2.8.0
  - icu: 60.1
  - modules: 57
  - napi: 3
  - nghttp2: 1.32.0
  - node: 8.11.3
  - openssl: 1.0.2o
  - tz: 2017c
  - unicode: 10.0
  - uv: 1.19.1
  - v8: 6.2.414.54
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: Error: needed by assets/503.html: ENOENT: no such file or directory, stat '/private/var/folders/m3/2d92q9yx06j2q51zh2_w8js80000gn/T/embroider/585bc0/assets/styles/vendor.css'
    at Object.fs.statSync (fs.js:948:11)
    at Object.statSync (/Users/bobisjan/Developer/zonky-app/node_modules/graceful-fs/polyfills.js:295:24)
    at Webpack.copyThrough (/Users/bobisjan/Developer/zonky-app/node_modules/@embroider/webpack/src/ember-webpack.js:370:39)
    at Webpack.writeStyle (/Users/bobisjan/Developer/zonky-app/node_modules/@embroider/webpack/src/ember-webpack.js:309:18)
    at provideErrorContext (/Users/bobisjan/Developer/zonky-app/node_modules/@embroider/webpack/src/ember-webpack.js:350:60)
    at Webpack.provideErrorContext (/Users/bobisjan/Developer/zonky-app/node_modules/@embroider/webpack/src/ember-webpack.js:315:30)
    at Webpack.writeFiles (/Users/bobisjan/Developer/zonky-app/node_modules/@embroider/webpack/src/ember-webpack.js:332:28)
    at Webpack.build (/Users/bobisjan/Developer/zonky-app/node_modules/@embroider/webpack/src/ember-webpack.js:147:24)
    at <anonymous>:null:null
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)

  - code: [undefined]
  - codeFrame: needed by assets/503.html: ENOENT: no such file or directory, stat '/private/var/folders/m3/2d92q9yx06j2q51zh2_w8js80000gn/T/embroider/585bc0/assets/styles/vendor.css'
  - errorMessage: needed by assets/503.html: ENOENT: no such file or directory, stat '/private/var/folders/m3/2d92q9yx06j2q51zh2_w8js80000gn/T/embroider/585bc0/assets/styles/vendor.css'
        at PackagerRunner (@embroider/webpack)
-~- created here: -~-
    at new Plugin (/Users/bobisjan/Developer/zonky-app/node_modules/broccoli-plugin/index.js:7:31)
    at new PackagerRunner (/Users/bobisjan/Developer/zonky-app/node_modules/@embroider/core/src/to-broccoli-plugin.js:11:13)
    at defaultPipeline (/Users/bobisjan/Developer/zonky-app/node_modules/@embroider/compat/src/default-pipeline.js:30:12)
    at module.exports (/Users/bobisjan/Developer/zonky-app/ember-cli-build.js:117:10)
    at Builder.readBuildFile (/Users/bobisjan/Developer/zonky-app/node_modules/ember-cli/lib/models/builder.js:52:14)
    at Builder.setupBroccoliBuilder (/Users/bobisjan/Developer/zonky-app/node_modules/ember-cli/lib/models/builder.js:66:22)
    at new Builder (/Users/bobisjan/Developer/zonky-app/node_modules/ember-cli/lib/models/builder.js:32:10)
    at ServeTask.run (/Users/bobisjan/Developer/zonky-app/node_modules/ember-cli/lib/tasks/serve.js:45:55)
    at Promise.resolve.then (/Users/bobisjan/Developer/zonky-app/node_modules/ember-cli/lib/models/command.js:243:46)
    at tryCatcher (/Users/bobisjan/Developer/zonky-app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:323:19)
    at invokeCallback (/Users/bobisjan/Developer/zonky-app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:495:31)
    at /Users/bobisjan/Developer/zonky-app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:559:14
    at flush (/Users/bobisjan/Developer/zonky-app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:2402:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

-~- (end) -~-
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
    - treeDir: [undefined]
  - message: needed by assets/503.html: ENOENT: no such file or directory, stat '/private/var/folders/m3/2d92q9yx06j2q51zh2_w8js80000gn/T/embroider/585bc0/assets/styles/vendor.css'
        at PackagerRunner (@embroider/webpack)
-~- created here: -~-
    at new Plugin (/Users/bobisjan/Developer/zonky-app/node_modules/broccoli-plugin/index.js:7:31)
    at new PackagerRunner (/Users/bobisjan/Developer/zonky-app/node_modules/@embroider/core/src/to-broccoli-plugin.js:11:13)
    at defaultPipeline (/Users/bobisjan/Developer/zonky-app/node_modules/@embroider/compat/src/default-pipeline.js:30:12)
    at module.exports (/Users/bobisjan/Developer/zonky-app/ember-cli-build.js:117:10)
    at Builder.readBuildFile (/Users/bobisjan/Developer/zonky-app/node_modules/ember-cli/lib/models/builder.js:52:14)
    at Builder.setupBroccoliBuilder (/Users/bobisjan/Developer/zonky-app/node_modules/ember-cli/lib/models/builder.js:66:22)
    at new Builder (/Users/bobisjan/Developer/zonky-app/node_modules/ember-cli/lib/models/builder.js:32:10)
    at ServeTask.run (/Users/bobisjan/Developer/zonky-app/node_modules/ember-cli/lib/tasks/serve.js:45:55)
    at Promise.resolve.then (/Users/bobisjan/Developer/zonky-app/node_modules/ember-cli/lib/models/command.js:243:46)
    at tryCatcher (/Users/bobisjan/Developer/zonky-app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:323:19)
    at invokeCallback (/Users/bobisjan/Developer/zonky-app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:495:31)
    at /Users/bobisjan/Developer/zonky-app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:559:14
    at flush (/Users/bobisjan/Developer/zonky-app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:2402:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

-~- (end) -~-
  - name: BuildError
  - nodeAnnotation: @embroider/webpack
  - nodeName: PackagerRunner
  - originalErrorMessage: needed by assets/503.html: ENOENT: no such file or directory, stat '/private/var/folders/m3/2d92q9yx06j2q51zh2_w8js80000gn/T/embroider/585bc0/assets/styles/vendor.css'
  - stack: Error: needed by assets/503.html: ENOENT: no such file or directory, stat '/private/var/folders/m3/2d92q9yx06j2q51zh2_w8js80000gn/T/embroider/585bc0/assets/styles/vendor.css'
    at Object.fs.statSync (fs.js:948:11)
    at Object.statSync (/Users/bobisjan/Developer/zonky-app/node_modules/graceful-fs/polyfills.js:295:24)
    at Webpack.copyThrough (/Users/bobisjan/Developer/zonky-app/node_modules/@embroider/webpack/src/ember-webpack.js:370:39)
    at Webpack.writeStyle (/Users/bobisjan/Developer/zonky-app/node_modules/@embroider/webpack/src/ember-webpack.js:309:18)
    at provideErrorContext (/Users/bobisjan/Developer/zonky-app/node_modules/@embroider/webpack/src/ember-webpack.js:350:60)
    at Webpack.provideErrorContext (/Users/bobisjan/Developer/zonky-app/node_modules/@embroider/webpack/src/ember-webpack.js:315:30)
    at Webpack.writeFiles (/Users/bobisjan/Developer/zonky-app/node_modules/@embroider/webpack/src/ember-webpack.js:332:28)
    at Webpack.build (/Users/bobisjan/Developer/zonky-app/node_modules/@embroider/webpack/src/ember-webpack.js:147:24)
    at <anonymous>:null:null
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)


=================================================================================

```

**Comment by ef4** [comment]
`/assets/styles/vendor.css` implies that you've customized something unusual about your build, because normally it would be `/assets/vendor.css`. 

But let's roll all this discussion into #133 because I can't identify multiple issues here, it may all be the same thing.
