### ISSUE TITLE
`staticComponents: true` results in certain webpack `require`s failing

### ISSUE THREAD

**Issue by kiosion** [embroider-build/embroider#1312]
After upgrading an app to use v2.0.2, components from the main app required by addons seem to be unable to be imported while `staticComponents` is enabled... turning this off results in everything (seemingly) working fine. I did try looking into this, but couldn't find much. It does seem to be limited to only addons that import components / utils from the main app...

Here's the full error:
```
logger.js:22 Error: Could not find module `app/components/custom-input` imported from `(require)`
    at missingModule (loader.js:247:1)
    at findModule (loader.js:258:1)
    at requireModule (loader.js:24:1)
    at eval (custom-input.js:1:18)
    at ../externals/app/components/custom-input.js (chunk.ee03b0cc0c2788612d82.js:30054:1)
    at __webpack_require__ (bootstrap:19:1)
    at eval (table-search.js:8:96)
    at ./lib/some-addon/components/data-table/table-search.js (chunk.ee03b0cc0c2788612d82.js:14911:1)
    at __webpack_require__ (bootstrap:19:1)
    at eval (table-search.js:5:117)
```

**Comment by bwbuchanan** [comment]
Is the addon using the component helper to import the app's component by-name?  e.g.:

```handlebars
<AddonComponent @subComponent="custom-input" />
```


When using `staticComponents`, you need to pass in component references instead, because in the above example, there is no way for embroider to know that it needs to include `custom-input` in the build.

Try this instead:

```handlebars
<AddonComponent @subComponent={{component "custom-input" }} />
```

Reference: https://github.com/embroider-build/embroider/blob/main/REPLACING-COMPONENT-HELPER.md

**Comment by bwbuchanan** [comment]
I think that the latest version of embroider fixed a bug that would previously result in any component that had been imported elsewhere in the app being available in the global scope. So, in previous versions, your addon could still find it, even through it shouldn't have been able to.

**Comment by kiosion** [comment]
That sounds like it could be the cause, I'll give that a shot later!
