### ISSUE TITLE
Recursively resolving v2 addons breaks the build

### ISSUE THREAD

**Issue by gossi** [embroider-build/embroider#1371]
Having a monorepo with more than one addon and these addons depend on each other will break the build.

The setup is described here: #1325
With a fix in #1327 

When this fix is applied, then the test-app cannot resolve the imports - it is resolving the wrong files/paths. I'm writing this from memory of a couple of weeks ago, needs investigation where exactly the wrong path is introduced (at first I want to have the problem documented).

This also happens under `pnpm` for me, which usually comes with the strictest rules around dependency resolving and _may_ be related to #1370 (?)

I was trying to figure out if there are tests for such situations, but need to learn first how tests for embroider work (can't confirm this for now). I would see it as a first step to have tests for such setups and make sure the build succeeds.

**Comment by gossi** [comment]
One way is to fix this for sure.

But there is an alternative solution, which is to make `ember-template-imports` available for v2 addons, based on the idea from @dfreeman: https://github.com/dfreeman/fccts-in-v2

The repo above works for gjs but needs a little love for gts.

**Comment by gossi** [comment]
My latest guess is, it has something to do with `webpack` and it may be related to `@embroider/webpack`.

Here is the reproduction: https://github.com/hokulea/hokulea/tree/1a30de49f2e4e381d5451646abd6b32bbbfb7f92

Start it:

```
pnpm i
pnpm build
cd ember/actions/test-app
ember s
```

which then brings this error message:

```
ERROR in ./helpers/dropdown-builder.js 1:0-79
Module not found: Error: Can't resolve '../../../foundation/package/helpers/dropdown-builder' in '$TMPDIR/embroider/5ad583/ember/actions/test-app/helpers'
resolve '../../../foundation/package/helpers/dropdown-builder' in '$TMPDIR/embroider/5ad583/ember/actions/test-app/helpers'
  using description file: $TMPDIR/embroider/5ad583/ember/actions/test-app/package.json (relative path: ./helpers)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: $TMPDIR/embroider/5ad583/ember/foundation/package/package.json (relative path: ./helpers/dropdown-builder)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        $TMPDIR/embroider/5ad583/ember/foundation/package/helpers/dropdown-builder doesn't exist
      .wasm
        Field 'browser' doesn't contain a valid alias configuration
        $TMPDIR/embroider/5ad583/ember/foundation/package/helpers/dropdown-builder.wasm doesn't exist
      .mjs
        Field 'browser' doesn't contain a valid alias configuration
        $TMPDIR/embroider/5ad583/ember/foundation/package/helpers/dropdown-builder.mjs doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        $TMPDIR/embroider/5ad583/ember/foundation/package/helpers/dropdown-builder.js doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        $TMPDIR/embroider/5ad583/ember/foundation/package/helpers/dropdown-builder.json doesn't exist
      .hbs
        Field 'browser' doesn't contain a valid alias configuration
        $TMPDIR/embroider/5ad583/ember/foundation/package/helpers/dropdown-builder.hbs doesn't exist
      .hbs.js
        Field 'browser' doesn't contain a valid alias configuration
        $TMPDIR/embroider/5ad583/ember/foundation/package/helpers/dropdown-builder.hbs.js doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        $TMPDIR/embroider/5ad583/ember/foundation/package/helpers/dropdown-builder.ts doesn't exist
      as directory
        $TMPDIR/embroider/5ad583/ember/foundation/package/helpers/dropdown-builder doesn't exist
 @ ./assets/@hokulea/ember-actions-test-app.js 59:13-57

webpack 5.75.0 compiled with 1 error in 3772 ms
Build Error (PackagerRunner) in helpers/dropdown-builder.js

Module not found: Error: Can't resolve '../../../foundation/package/helpers/dropdown-builder' in '$TMPDIR/embroider/5ad583/ember/actions/test-app/helpers/dropdown-builder.js'


Stack Trace and Error Report: /var/folders/5s/d0fql03n6mj78fw8b5mk0x3m0000gn/T/error.dump.94817f8c01f960994888538894cabe76.log
```

here are the contents from `$TMPDIR/embroider/5ad583/ember/actions/test-app/helpers/dropdown-builder.js`:

```js
export { default } from "@hokulea/ember-foundation/helpers/dropdown-builder"
```

This is the file generated with embroider when building the addon, which then is generated in `dist/__app__/helpers/dropdown-builder.js`.

Now it becomes interesting, because the error message is different than to what the file contents showing. From here on I _assume_ what's happening:

I think, the import path is resolved to its physical location. From how it _looks_, only the `@hokulea/ember-founation` is resolved to its physical folder: `../../../foundation/` (relative to the js file) and then the module path is appended to that location, which results in: `../../../foundation/package/helpers/dropdown-builder`, which of course can't be resolved.

Well, still very much suggestive. The stack trace (see below) hints at webpack, but the error message is "originated" in, see this excerpt:

```
errorMessage: helpers/dropdown-builder.js: Module not found: Error: Can't resolve '../../../foundation/package/helpers/dropdown-builder' in '$TMPDIR/embroider/5ad583/ember/actions/test-app/helpers/dropdown-builder.js'
        at PackagerRunner (@embroider/webpack)
```


Stack trace:

```
ERROR Summary:

  - broccoliBuilderErrorStack: ModuleNotFoundError: Module not found: Error: Can't resolve '../../../foundation/package/helpers/dropdown-builder' in '$TMPDIR/embroider/5ad583/ember/actions/test-app/helpers/dropdown-builder.js'
    at /Users/thomas/code/hokulea/hokulea/node_modules/.pnpm/webpack@5.75.0/node_modules/webpack/lib/Compilation.js:2016:28
    at /Users/thomas/code/hokulea/hokulea/node_modules/.pnpm/webpack@5.75.0/node_modules/webpack/lib/NormalModuleFactory.js:798:13
    at eval (eval at create (/Users/thomas/code/hokulea/hokulea/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /Users/thomas/code/hokulea/hokulea/node_modules/.pnpm/webpack@5.75.0/node_modules/webpack/lib/NormalModuleFactory.js:270:22
    at eval (eval at create (/Users/thomas/code/hokulea/hokulea/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /Users/thomas/code/hokulea/hokulea/node_modules/.pnpm/webpack@5.75.0/node_modules/webpack/lib/NormalModuleFactory.js:434:22
    at /Users/thomas/code/hokulea/hokulea/node_modules/.pnpm/webpack@5.75.0/node_modules/webpack/lib/NormalModuleFactory.js:116:11
    at /Users/thomas/code/hokulea/hokulea/node_modules/.pnpm/webpack@5.75.0/node_modules/webpack/lib/NormalModuleFactory.js:670:25
    at /Users/thomas/code/hokulea/hokulea/node_modules/.pnpm/webpack@5.75.0/node_modules/webpack/lib/NormalModuleFactory.js:855:8
    at /Users/thomas/code/hokulea/hokulea/node_modules/.pnpm/webpack@5.75.0/node_modules/webpack/lib/NormalModuleFactory.js:975:5
  - code: [undefined]
  - codeFrame: Module not found: Error: Can't resolve '../../../foundation/package/helpers/dropdown-builder' in '$TMPDIR/embroider/5ad583/ember/actions/test-app/helpers/dropdown-builder.js'
  - errorMessage: helpers/dropdown-builder.js: Module not found: Error: Can't resolve '../../../foundation/package/helpers/dropdown-builder' in '$TMPDIR/embroider/5ad583/ember/actions/test-app/helpers/dropdown-builder.js'
        at PackagerRunner (@embroider/webpack)
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: helpers/dropdown-builder.js
    - line: [null]
    - treeDir: [undefined]
  - message: helpers/dropdown-builder.js: Module not found: Error: Can't resolve '../../../foundation/package/helpers/dropdown-builder' in '$TMPDIR/embroider/5ad583/ember/actions/test-app/helpers/dropdown-builder.js'
        at PackagerRunner (@embroider/webpack)
  - name: Error
  - nodeAnnotation: @embroider/webpack
  - nodeName: PackagerRunner
  - originalErrorMessage: Module not found: Error: Can't resolve '../../../foundation/package/helpers/dropdown-builder' in '$TMPDIR/embroider/5ad583/ember/actions/test-app/helpers/dropdown-builder.js'
  - stack: ModuleNotFoundError: Module not found: Error: Can't resolve '../../../foundation/package/helpers/dropdown-builder' in '$TMPDIR/embroider/5ad583/ember/actions/test-app/helpers/dropdown-builder.js'
    at /Users/thomas/code/hokulea/hokulea/node_modules/.pnpm/webpack@5.75.0/node_modules/webpack/lib/Compilation.js:2016:28
    at /Users/thomas/code/hokulea/hokulea/node_modules/.pnpm/webpack@5.75.0/node_modules/webpack/lib/NormalModuleFactory.js:798:13
    at eval (eval at create (/Users/thomas/code/hokulea/hokulea/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /Users/thomas/code/hokulea/hokulea/node_modules/.pnpm/webpack@5.75.0/node_modules/webpack/lib/NormalModuleFactory.js:270:22
    at eval (eval at create (/Users/thomas/code/hokulea/hokulea/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /Users/thomas/code/hokulea/hokulea/node_modules/.pnpm/webpack@5.75.0/node_modules/webpack/lib/NormalModuleFactory.js:434:22
    at /Users/thomas/code/hokulea/hokulea/node_modules/.pnpm/webpack@5.75.0/node_modules/webpack/lib/NormalModuleFactory.js:116:11
    at /Users/thomas/code/hokulea/hokulea/node_modules/.pnpm/webpack@5.75.0/node_modules/webpack/lib/NormalModuleFactory.js:670:25
    at /Users/thomas/code/hokulea/hokulea/node_modules/.pnpm/webpack@5.75.0/node_modules/webpack/lib/NormalModuleFactory.js:855:8
    at /Users/thomas/code/hokulea/hokulea/node_modules/.pnpm/webpack@5.75.0/node_modules/webpack/lib/NormalModuleFactory.js:975:5
```

**Comment by gossi** [comment]
As paired with @NullVoxPopuli we tried embroider unstable release, which resolved this issue 👍 

Good job everyone 🙌
