### ISSUE TITLE
Build error following update to 3.0.0

### ISSUE THREAD

**Issue by roomman** [embroider-build/embroider#1434]
I just updated to 3.0.0 and when I save a change to a component I get this build error message:
```
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Compiler'
    --- property 'root' closes the circle
    at JSON.stringify (<anonymous>)
    at stringify (/Users/simon/Sites/solomon-next-reporting-ui/node_modules/jsonfile/utils.js:3:20)
    at outputJsonSync (/Users/simon/Sites/solomon-next-reporting-ui/node_modules/@embroider/core/node_modules/fs-extra/lib/json/output-json-sync.js:7:15)
    at AppBuilder.addResolverConfig (/Users/simon/Sites/solomon-next-reporting-ui/node_modules/@embroider/core/src/app.js:764:39)
    at AppBuilder.build (/Users/simon/Sites/solomon-next-reporting-ui/node_modules/@embroider/core/src/app.js:708:14)
    at async WaitForTrees.buildHook (/Users/simon/Sites/solomon-next-reporting-ui/node_modules/@embroider/core/src/build-stage.js:33:13)
```
I have the following installed in my package.json:
```
"@embroider/compat": "^3.0.0",
"@embroider/core": "^3.0.0",
"@embroider/router": "^2.1.0",
"@embroider/webpack": "^3.0.0",
```

**Comment by NullVoxPopuli** [comment]
Do you have a reproduction repo?

**Comment by roomman** [comment]
@NullVoxPopuli slap-bang in the middle of a deadline but will put one together ASAP.

**Comment by NullVoxPopuli** [comment]
Thank you!! ♥️🎉

**Comment by roomman** [comment]
This issue duplicates #1441 so I am closing.
