### ISSUE TITLE
Imported css is duplicated during ember serve development build with fastboot

### ISSUE THREAD

**Issue by truuman** [embroider-build/embroider#1456]
Hi!

Using embroider with fastboot in a fresh project results in the `<link rel="stylesheet">` tags that are injected in the built `dist/index.html` file to be duplicated when importing css with `import` statements.

Reproduction steps:

1. `ember new css-repro --embroider` ~ embroider@2.1.1
2. `cd css-repro`
3. `ember install ember-cli-fastboot`
4. Create `random.css` in `./app`
5. Add `import './random.css'` in `./app/app.js`
6. Run `ember serve`
7. Open `./app/random.css` and save it a couple of times
8. Check `./dist/index.html`, there will be multiple duplicate `<link>`s for stylesheets

Repro repo: https://github.com/truumahn/embroider-css-inject-repro/tree/main ~ embroider@unstable

The issue occurs both with `embroider@2.1.1` and `embroider@3.0.x`

This only happens during `ember serve`.

I suppose the issue is somewhere around the MiniCssExtract webpack plugin, `css-loader` or maybe the `ember-auto-import` configuraton.

Also, manually removing the duplicate links and then triggering a rebuild results in all the previously duplicated links to be added again, so the links to inject is stored somewhere during the build and instead of replacing them they are readded each time.

**Comment by truumahn** [comment]
I'm not sure how how you got to that error message, I just cloned the repo, ran `npm install` then `ember serve`.

I did get an entirely different error though which wasn't there at the time I posted this issue:

```
Error: Unable to require module 'crypto' in Fastboot because its package 'crypto' was not explicitly allowed in 'fastbootDependencies' in your package.json.
    at Object.require (/home/tibor/Work/jeti/embroider-css-inject-repro/node_modules/fastboot/src/fastboot-schema.js:199:11)
    at eval (webpack://css-repro/./node_modules/@ember-data/store/-private.js?:200:39)
    at Object../node_modules/@ember-data/store/-private.js (/tmp/broccoli-368306CQD03Mfx4AkB/out-763-packager_runner_embroider_webpack/assets/chunk.be651e2d30becea7598f.js:348:1)
    at __webpack_require__ (/tmp/broccoli-368306CQD03Mfx4AkB/out-763-packager_runner_embroider_webpack/assets/chunk.fe0c8ba2ffe5c37e3955.js:31:41)
    at eval (webpack://css-repro/./node_modules/@ember-data/store/index.js?:12:66)
    at Object../node_modules/@ember-data/store/index.js (/tmp/broccoli-368306CQD03Mfx4AkB/out-763-packager_runner_embroider_webpack/assets/chunk.be651e2d30becea7598f.js:359:1)
    at __webpack_require__ (/tmp/broccoli-368306CQD03Mfx4AkB/out-763-packager_runner_embroider_webpack/assets/chunk.fe0c8ba2ffe5c37e3955.js:31:41)
    at eval (webpack://css-repro/./node_modules/@ember-data/debug/setup.js?:6:75)
    at Object../node_modules/@ember-data/debug/setup.js (/tmp/broccoli-368306CQD03Mfx4AkB/out-763-packager_runner_embroider_webpack/assets/chunk.be651e2d30becea7598f.js:183:1)
    at __webpack_require__ (/tmp/broccoli-368306CQD03Mfx4AkB/out-763-packager_runner_embroider_webpack/assets/chunk.fe0c8ba2ffe5c37e3955.js:31:41)
 ```
However this could be fixed by using the solution provided here: https://github.com/emberjs/data/issues/6690#issuecomment-1444356627, practically just adding `crypto` to `fastbootDependencies` in `package.json`.

The node version I'm using is 16.

**Comment by truumahn** [comment]
@mansona have you had a chance to look at this since then?

**Comment by jknight12882** [comment]
Somewhat related, but we are getting duplicated css and js lines in our `index.html` when using `ember build --environment=development --output-path ../some/path --watch`. Only happens on changes, works fine on the initial build

**Comment by jknight12882** [comment]
Yup, confirmed, using 3.4.0 of embroider core. I'll wait for the dot release

**Comment by mansona** [comment]
@jknight12882 patch release is out 👍
