### ISSUE TITLE
Windows 7 - Build fails just after enabling embroider on an existing app

### ISSUE THREAD

**Issue by HerveSeger** [embroider-build/embroider#146]
Hi.

I have a working application using `ember v3.4.8` and I have followed the instructions in the `readme` to try `embroider`.
So I have updated the file `ember-cli-build.js` and run `ember build`.

It fails with:
```
Build Error (OneShot)

[BABEL] unknown: ._parallelBabel is not a valid Plugin property
        at ImportParser (embroider:core:import-parser)
-~- created here: -~-
    at new Plugin (c:\development\projects\git\insurance-online-ui\node_modules\broccoli-plugin\index.js:7:31)
    at new ImportParser (c:\development\projects\git\insurance-online-ui\node_modules\@embroider\compat\src\import-parser.js:36:9)
    at V1Addon.parseImports (c:\development\projects\git\insurance-online-ui\node_modules\@embroider\compat\src\v1-addon.js:187:16)
    at V1Addon.buildAddonTestSupport (c:\development\projects\git\insurance-online-ui\node_modules\@embroider\compat\src\v1-addon.js:481:42)
    at V1Addon.build (c:\development\projects\git\insurance-online-ui\node_modules\@embroider\compat\src\v1-addon.js:617:14)
    at V1Addon.<anonymous> (c:\development\projects\git\insurance-online-ui\node_modules\typescript-memoize\dist\memoize-decorator.js:67:52)
    at V1Addon.get v2Trees (c:\development\projects\git\insurance-online-ui\node_modules\@embroider\compat\src\v1-addon.js:335:45)
    at V1Addon.<anonymous> (c:\development\projects\git\insurance-online-ui\node_modules\typescript-memoize\dist\memoize-decorator.js:67:52)
    at V1Addon.get v2Tree [as v2Tree] (c:\development\projects\git\insurance-online-ui\node_modules\@embroider\compat\src\v1-addon.js:326:52)
    at oldPackages.map.pkg (c:\development\projects\git\insurance-online-ui\node_modules\@embroider\compat\src\build-compat-addon.js:42:48)
-~- (end) -~-


Stack Trace and Error Report: c:\DEVELO~1\tmp/error.dump.fe5e29e0269d89f4157130e26526ae3f.log
```

The stack trace:
```
ERROR Summary:

  - broccoliBuilderErrorStack: Error: [BABEL] unknown: ._parallelBabel is not a valid Plugin property
    at Object.keys.forEach.key (c:\development\projects\git\insurance-online-ui\node_modules\@babel\core\lib\config\validation\plugins.js:52:56)
    at Array.forEach (<anonymous>)
    at validatePluginObject (c:\development\projects\git\insurance-online-ui\node_modules\@babel\core\lib\config\validation\plugins.js:50:20)
    at instantiatePlugin (c:\development\projects\git\insurance-online-ui\node_modules\@babel\core\lib\config\full.js:209:55)
    at cachedFunction (c:\development\projects\git\insurance-online-ui\node_modules\@babel\core\lib\config\caching.js:33:19)
    at loadPluginDescriptor (c:\development\projects\git\insurance-online-ui\node_modules\@babel\core\lib\config\full.js:200:10)
    at config.plugins.reduce (c:\development\projects\git\insurance-online-ui\node_modules\@babel\core\lib\config\full.js:69:20)
    at Array.reduce (<anonymous>)
    at recurseDescriptors (c:\development\projects\git\insurance-online-ui\node_modules\@babel\core\lib\config\full.js:67:38)
    at loadFullConfig (c:\development\projects\git\insurance-online-ui\node_modules\@babel\core\lib\config\full.js:108:6)
  - code: [undefined]
  - codeFrame: [BABEL] unknown: ._parallelBabel is not a valid Plugin property
        at ImportParser (embroider:core:import-parser)
-~- created here: -~-
    at new Plugin (c:\development\projects\git\insurance-online-ui\node_modules\broccoli-plugin\index.js:7:31)
    at new ImportParser (c:\development\projects\git\insurance-online-ui\node_modules\@embroider\compat\src\import-parser.js:36:9)
    at V1Addon.parseImports (c:\development\projects\git\insurance-online-ui\node_modules\@embroider\compat\src\v1-addon.js:187:16)
    at V1Addon.buildAddonTestSupport (c:\development\projects\git\insurance-online-ui\node_modules\@embroider\compat\src\v1-addon.js:481:42)
    at V1Addon.build (c:\development\projects\git\insurance-online-ui\node_modules\@embroider\compat\src\v1-addon.js:617:14)
    at V1Addon.<anonymous> (c:\development\projects\git\insurance-online-ui\node_modules\typescript-memoize\dist\memoize-decorator.js:67:52)
    at V1Addon.get v2Trees (c:\development\projects\git\insurance-online-ui\node_modules\@embroider\compat\src\v1-addon.js:335:45)
    at V1Addon.<anonymous> (c:\development\projects\git\insurance-online-ui\node_modules\typescript-memoize\dist\memoize-decorator.js:67:52)
    at V1Addon.get v2Tree [as v2Tree] (c:\development\projects\git\insurance-online-ui\node_modules\@embroider\compat\src\v1-addon.js:326:52)
    at oldPackages.map.pkg (c:\development\projects\git\insurance-online-ui\node_modules\@embroider\compat\src\build-compat-addon.js:42:48)
-~- (end) -~-
  - errorMessage: [BABEL] unknown: ._parallelBabel is not a valid Plugin property
        at ImportParser (embroider:core:import-parser)
-~- created here: -~-
    at new Plugin (c:\development\projects\git\insurance-online-ui\node_modules\broccoli-plugin\index.js:7:31)
    at new ImportParser (c:\development\projects\git\insurance-online-ui\node_modules\@embroider\compat\src\import-parser.js:36:9)
    at V1Addon.parseImports (c:\development\projects\git\insurance-online-ui\node_modules\@embroider\compat\src\v1-addon.js:187:16)
    at V1Addon.buildAddonTestSupport (c:\development\projects\git\insurance-online-ui\node_modules\@embroider\compat\src\v1-addon.js:481:42)
    at V1Addon.build (c:\development\projects\git\insurance-online-ui\node_modules\@embroider\compat\src\v1-addon.js:617:14)
    at V1Addon.<anonymous> (c:\development\projects\git\insurance-online-ui\node_modules\typescript-memoize\dist\memoize-decorator.js:67:52)
    at V1Addon.get v2Trees (c:\development\projects\git\insurance-online-ui\node_modules\@embroider\compat\src\v1-addon.js:335:45)
    at V1Addon.<anonymous> (c:\development\projects\git\insurance-online-ui\node_modules\typescript-memoize\dist\memoize-decorator.js:67:52)
    at V1Addon.get v2Tree [as v2Tree] (c:\development\projects\git\insurance-online-ui\node_modules\@embroider\compat\src\v1-addon.js:326:52)
    at oldPackages.map.pkg (c:\development\projects\git\insurance-online-ui\node_modules\@embroider\compat\src\build-compat-addon.js:42:48)
-~- (end) -~-
        at OneShot
-~- created here: -~-
    at new Plugin (c:\development\projects\git\insurance-online-ui\node_modules\broccoli-plugin\index.js:7:31)
    at new OneShot (c:\development\projects\git\insurance-online-ui\node_modules\@embroider\compat\src\one-shot.js:14:9)
    at Object.cachedBuildCompatAddon [as default] (c:\development\projects\git\insurance-online-ui\node_modules\@embroider\compat\src\build-compat-addon.js:15:16)
    at CompatAddons.movedAddons.map.oldPkg (c:\development\projects\git\insurance-online-ui\node_modules\@embroider\compat\src\compat-addons.js:39:105)
    at Array.map (<anonymous>)
    at new CompatAddons (c:\development\projects\git\insurance-online-ui\node_modules\@embroider\compat\src\compat-addons.js:39:63)
    at Object.defaultPipeline [as compatBuild] (c:\development\projects\git\insurance-online-ui\node_modules\@embroider\compat\src\default-pipeline.js:17:18)
    at module.exports (c:\development\projects\git\insurance-online-ui\ember-cli-build.js:97:38)
    at Builder.readBuildFile (c:\development\projects\git\insurance-online-ui\node_modules\ember-cli\lib\models\builder.js:52:14)
    at Builder.setupBroccoliBuilder (c:\development\projects\git\insurance-online-ui\node_modules\ember-cli\lib\models\builder.js:66:22)
-~- (end) -~-
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
    - treeDir: [undefined]
  - message: [BABEL] unknown: ._parallelBabel is not a valid Plugin property
        at ImportParser (embroider:core:import-parser)
-~- created here: -~-
    at new Plugin (c:\development\projects\git\insurance-online-ui\node_modules\broccoli-plugin\index.js:7:31)
    at new ImportParser (c:\development\projects\git\insurance-online-ui\node_modules\@embroider\compat\src\import-parser.js:36:9)
    at V1Addon.parseImports (c:\development\projects\git\insurance-online-ui\node_modules\@embroider\compat\src\v1-addon.js:187:16)
    at V1Addon.buildAddonTestSupport (c:\development\projects\git\insurance-online-ui\node_modules\@embroider\compat\src\v1-addon.js:481:42)
    at V1Addon.build (c:\development\projects\git\insurance-online-ui\node_modules\@embroider\compat\src\v1-addon.js:617:14)
    at V1Addon.<anonymous> (c:\development\projects\git\insurance-online-ui\node_modules\typescript-memoize\dist\memoize-decorator.js:67:52)
    at V1Addon.get v2Trees (c:\development\projects\git\insurance-online-ui\node_modules\@embroider\compat\src\v1-addon.js:335:45)
    at V1Addon.<anonymous> (c:\development\projects\git\insurance-online-ui\node_modules\typescript-memoize\dist\memoize-decorator.js:67:52)
    at V1Addon.get v2Tree [as v2Tree] (c:\development\projects\git\insurance-online-ui\node_modules\@embroider\compat\src\v1-addon.js:326:52)
    at oldPackages.map.pkg (c:\development\projects\git\insurance-online-ui\node_modules\@embroider\compat\src\build-compat-addon.js:42:48)
-~- (end) -~-
        at OneShot
-~- created here: -~-
    at new Plugin (c:\development\projects\git\insurance-online-ui\node_modules\broccoli-plugin\index.js:7:31)
    at new OneShot (c:\development\projects\git\insurance-online-ui\node_modules\@embroider\compat\src\one-shot.js:14:9)
    at Object.cachedBuildCompatAddon [as default] (c:\development\projects\git\insurance-online-ui\node_modules\@embroider\compat\src\build-compat-addon.js:15:16)
    at CompatAddons.movedAddons.map.oldPkg (c:\development\projects\git\insurance-online-ui\node_modules\@embroider\compat\src\compat-addons.js:39:105)
    at Array.map (<anonymous>)
    at new CompatAddons (c:\development\projects\git\insurance-online-ui\node_modules\@embroider\compat\src\compat-addons.js:39:63)
    at Object.defaultPipeline [as compatBuild] (c:\development\projects\git\insurance-online-ui\node_modules\@embroider\compat\src\default-pipeline.js:17:18)
    at module.exports (c:\development\projects\git\insurance-online-ui\ember-cli-build.js:97:38)
    at Builder.readBuildFile (c:\development\projects\git\insurance-online-ui\node_modules\ember-cli\lib\models\builder.js:52:14)
    at Builder.setupBroccoliBuilder (c:\development\projects\git\insurance-online-ui\node_modules\ember-cli\lib\models\builder.js:66:22)
-~- (end) -~-
  - name: BuildError
  - nodeAnnotation: [undefined]
  - nodeName: OneShot
  - originalErrorMessage: [BABEL] unknown: ._parallelBabel is not a valid Plugin property
        at ImportParser (embroider:core:import-parser)
-~- created here: -~-
    at new Plugin (c:\development\projects\git\insurance-online-ui\node_modules\broccoli-plugin\index.js:7:31)
    at new ImportParser (c:\development\projects\git\insurance-online-ui\node_modules\@embroider\compat\src\import-parser.js:36:9)
    at V1Addon.parseImports (c:\development\projects\git\insurance-online-ui\node_modules\@embroider\compat\src\v1-addon.js:187:16)
    at V1Addon.buildAddonTestSupport (c:\development\projects\git\insurance-online-ui\node_modules\@embroider\compat\src\v1-addon.js:481:42)
    at V1Addon.build (c:\development\projects\git\insurance-online-ui\node_modules\@embroider\compat\src\v1-addon.js:617:14)
    at V1Addon.<anonymous> (c:\development\projects\git\insurance-online-ui\node_modules\typescript-memoize\dist\memoize-decorator.js:67:52)
    at V1Addon.get v2Trees (c:\development\projects\git\insurance-online-ui\node_modules\@embroider\compat\src\v1-addon.js:335:45)
    at V1Addon.<anonymous> (c:\development\projects\git\insurance-online-ui\node_modules\typescript-memoize\dist\memoize-decorator.js:67:52)
    at V1Addon.get v2Tree [as v2Tree] (c:\development\projects\git\insurance-online-ui\node_modules\@embroider\compat\src\v1-addon.js:326:52)
    at oldPackages.map.pkg (c:\development\projects\git\insurance-online-ui\node_modules\@embroider\compat\src\build-compat-addon.js:42:48)
-~- (end) -~-
  - stack: Error: [BABEL] unknown: ._parallelBabel is not a valid Plugin property
    at Object.keys.forEach.key (c:\development\projects\git\insurance-online-ui\node_modules\@babel\core\lib\config\validation\plugins.js:52:56)
    at Array.forEach (<anonymous>)
    at validatePluginObject (c:\development\projects\git\insurance-online-ui\node_modules\@babel\core\lib\config\validation\plugins.js:50:20)
    at instantiatePlugin (c:\development\projects\git\insurance-online-ui\node_modules\@babel\core\lib\config\full.js:209:55)
    at cachedFunction (c:\development\projects\git\insurance-online-ui\node_modules\@babel\core\lib\config\caching.js:33:19)
    at loadPluginDescriptor (c:\development\projects\git\insurance-online-ui\node_modules\@babel\core\lib\config\full.js:200:10)
    at config.plugins.reduce (c:\development\projects\git\insurance-online-ui\node_modules\@babel\core\lib\config\full.js:69:20)
    at Array.reduce (<anonymous>)
    at recurseDescriptors (c:\development\projects\git\insurance-online-ui\node_modules\@babel\core\lib\config\full.js:67:38)
    at loadFullConfig (c:\development\projects\git\insurance-online-ui\node_modules\@babel\core\lib\config\full.js:108:6)

=================================================================================
```

I was just testing so there is no rush here. I will switch back to good ol' Broccoli and that's it.

**Comment by btecu** [comment]
I got the same error on an existing project on Windows.

**Comment by ChristopherConnock** [comment]
Same error on an existing Ember CLI 3.9.0 project on windows:

```
[BABEL] unknown: ._parallelBabel is not a valid Plugin property
        at ImportParser (embroider:core:import-parser)
```

**Comment by ChristopherConnock** [comment]
Similar error on brand new Ember CLI 3.90 project on windows 10:

```
Plugin 0 specified in "base" provided an invalid property of "_parallelBabel"
        at ImportParser (embroider:core:import-parser)
```

**Comment by acorncom** [comment]
For folks hitting this problem, could you make a reproduction app that throws the same error butbis publicly accessible? It generally make this type of bug easier to track down ...

**Comment by HerveSeger** [comment]
Thanks for the info. I will give it another try.
Stay tuned.

**Comment by ChristopherConnock** [comment]
0.3.5 does produce a different error:
```
Build Error (WaitForTrees)

C:\Users\511\AppData\Local\Temp\embroider\4251f7\C:\Users\511\Documents\GitHub\embroider-test\node_modules\@ember contains invalid WIN32 path characters.
```

**Comment by HerveSeger** [comment]
I just tried and I get the same error as @ChristopherConnock.
`C:\Temp\embroider\508a9c\c:\projects\git\insurance-online-ui\node_modules\@ember contains invalid WIN32 path characters.`

The stack trace is identical to what is displayed above.

**Comment by lifeart** [comment]
![image](https://user-images.githubusercontent.com/1360552/59631059-8fa65f80-914f-11e9-8baa-45f7bb863215.png)

**Comment by lifeart** [comment]
`app.root`, `dep.root` has doubled paths, like `C:\Users\lifeart\AppData\Local\Temp\embroider\f5179b\C:\Users\lifeart\Documents\repos\js-framework-benchmark\frameworks\keyed\ember\node_modules\@ember\optional-features`

**Comment by lifeart** [comment]
able to fix this in https://github.com/embroider-build/embroider/pull/228

have new windows issue:

![image](https://user-images.githubusercontent.com/1360552/59634019-781ea500-9156-11e9-8cd9-300a3c841c5d.png)

```
ERROR Summary:

  - broccoliBuilderErrorStack: Error: could not find app styles in index.html
    at definitelyReplace (C:\Users\lifeart\Documents\repos\js-framework-benchmark\frameworks\keyed\ember\node_modules\@embroider\compat\src\compat-app.js:233:15)
    at Object.prepare (C:\Users\lifeart\Documents\repos\js-framework-benchmark\frameworks\keyed\ember\node_modules\@embroider\compat\src\compat-app.js:118:33)
    at new PreparedEmberHTML (C:\Users\lifeart\Documents\repos\js-framework-benchmark\frameworks\keyed\ember\node_modules\@embroider\core\src\ember-html.js:30:26)
    at new ParsedEmberAsset (C:\Users\lifeart\Documents\repos\js-framework-benchmark\frameworks\keyed\ember\node_modules\@embroider\core\src\app.js:43:21)
    at AppBuilder.prepareAsset (C:\Users\lifeart\Documents\repos\js-framework-benchmark\frameworks\keyed\ember\node_modules\@embroider\core\src\app.js:294:26)
    at AppBuilder.prepareAssets (C:\Users\lifeart\Documents\repos\js-framework-benchmark\frameworks\keyed\ember\node_modules\@embroider\core\src\app.js:306:18)
    at AppBuilder.updateAssets (C:\Users\lifeart\Documents\repos\js-framework-benchmark\frameworks\keyed\ember\node_modules\@embroider\core\src\app.js:374:27)
    at AppBuilder.build (C:\Users\lifeart\Documents\repos\js-framework-benchmark\frameworks\keyed\ember\node_modules\@embroider\core\src\app.js:428:38)
    at WaitForTrees.wait_for_trees_1.default [as buildHook] (C:\Users\lifeart\Documents\repos\js-framework-benchmark\frameworks\keyed\ember\node_modules\@embroider\core\src\build-stage.js:37:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  - code: [undefined]
  - codeFrame: could not find app styles in index.html
  - errorMessage: could not find app styles in index.html
        at WaitForTrees (@embroider/compat/app)
-~- created here: -~-
    at new Plugin (C:\Users\lifeart\Documents\repos\js-framework-benchmark\frameworks\keyed\ember\node_modules\broccoli-plugin\index.js:7:31)
    at new WaitForTrees (C:\Users\lifeart\Documents\repos\js-framework-benchmark\frameworks\keyed\ember\node_modules\@embroider\core\src\wait-for-trees.js:30:9)
    at CompatApp.get tree (C:\Users\lifeart\Documents\repos\js-framework-benchmark\frameworks\keyed\ember\node_modules\@embroider\core\src\build-stage.js:26:16)
    at CompatApp.<anonymous> (C:\Users\lifeart\Documents\repos\js-framework-benchmark\frameworks\keyed\ember\node_modules\typescript-memoize\dist\memoize-decorator.js:67:52)
    at new PackagerRunner (C:\Users\lifeart\Documents\repos\js-framework-benchmark\frameworks\keyed\ember\node_modules\@embroider\core\src\to-broccoli-plugin.js:11:26)
    at Object.defaultPipeline [as compatBuild] (C:\Users\lifeart\Documents\repos\js-framework-benchmark\frameworks\keyed\ember\node_modules\@embroider\compat\src\default-pipeline.js:30:12)
    at module.exports (C:\Users\lifeart\Documents\repos\js-framework-benchmark\frameworks\keyed\ember\ember-cli-build.js:25:39)
    at Builder.readBuildFile (C:\Users\lifeart\Documents\repos\js-framework-benchmark\frameworks\keyed\ember\node_modules\ember-cli\lib\models\builder.js:52:14)
    at Builder.setupBroccoliBuilder (C:\Users\lifeart\Documents\repos\js-framework-benchmark\frameworks\keyed\ember\node_modules\ember-cli\lib\models\builder.js:66:22)
    at new Builder (C:\Users\lifeart\Documents\repos\js-framework-benchmark\frameworks\keyed\ember\node_modules\ember-cli\lib\models\builder.js:32:10)
-~- (end) -~-
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
    - treeDir: [undefined]
  - message: could not find app styles in index.html
        at WaitForTrees (@embroider/compat/app)
-~- created here: -~-
    at new Plugin (C:\Users\lifeart\Documents\repos\js-framework-benchmark\frameworks\keyed\ember\node_modules\broccoli-plugin\index.js:7:31)
    at new WaitForTrees (C:\Users\lifeart\Documents\repos\js-framework-benchmark\frameworks\keyed\ember\node_modules\@embroider\core\src\wait-for-trees.js:30:9)
    at CompatApp.get tree (C:\Users\lifeart\Documents\repos\js-framework-benchmark\frameworks\keyed\ember\node_modules\@embroider\core\src\build-stage.js:26:16)
    at CompatApp.<anonymous> (C:\Users\lifeart\Documents\repos\js-framework-benchmark\frameworks\keyed\ember\node_modules\typescript-memoize\dist\memoize-decorator.js:67:52)
    at new PackagerRunner (C:\Users\lifeart\Documents\repos\js-framework-benchmark\frameworks\keyed\ember\node_modules\@embroider\core\src\to-broccoli-plugin.js:11:26)
    at Object.defaultPipeline [as compatBuild] (C:\Users\lifeart\Documents\repos\js-framework-benchmark\frameworks\keyed\ember\node_modules\@embroider\compat\src\default-pipeline.js:30:12)
    at module.exports (C:\Users\lifeart\Documents\repos\js-framework-benchmark\frameworks\keyed\ember\ember-cli-build.js:25:39)
    at Builder.readBuildFile (C:\Users\lifeart\Documents\repos\js-framework-benchmark\frameworks\keyed\ember\node_modules\ember-cli\lib\models\builder.js:52:14)
    at Builder.setupBroccoliBuilder (C:\Users\lifeart\Documents\repos\js-framework-benchmark\frameworks\keyed\ember\node_modules\ember-cli\lib\models\builder.js:66:22)
    at new Builder (C:\Users\lifeart\Documents\repos\js-framework-benchmark\frameworks\keyed\ember\node_modules\ember-cli\lib\models\builder.js:32:10)
-~- (end) -~-
  - name: BuildError
  - nodeAnnotation: @embroider/compat/app
  - nodeName: WaitForTrees
  - originalErrorMessage: could not find app styles in index.html
  - stack: Error: could not find app styles in index.html
    at definitelyReplace (C:\Users\lifeart\Documents\repos\js-framework-benchmark\frameworks\keyed\ember\node_modules\@embroider\compat\src\compat-app.js:233:15)
    at Object.prepare (C:\Users\lifeart\Documents\repos\js-framework-benchmark\frameworks\keyed\ember\node_modules\@embroider\compat\src\compat-app.js:118:33)
    at new PreparedEmberHTML (C:\Users\lifeart\Documents\repos\js-framework-benchmark\frameworks\keyed\ember\node_modules\@embroider\core\src\ember-html.js:30:26)
    at new ParsedEmberAsset (C:\Users\lifeart\Documents\repos\js-framework-benchmark\frameworks\keyed\ember\node_modules\@embroider\core\src\app.js:43:21)
    at AppBuilder.prepareAsset (C:\Users\lifeart\Documents\repos\js-framework-benchmark\frameworks\keyed\ember\node_modules\@embroider\core\src\app.js:294:26)
    at AppBuilder.prepareAssets (C:\Users\lifeart\Documents\repos\js-framework-benchmark\frameworks\keyed\ember\node_modules\@embroider\core\src\app.js:306:18)
    at AppBuilder.updateAssets (C:\Users\lifeart\Documents\repos\js-framework-benchmark\frameworks\keyed\ember\node_modules\@embroider\core\src\app.js:374:27)
    at AppBuilder.build (C:\Users\lifeart\Documents\repos\js-framework-benchmark\frameworks\keyed\ember\node_modules\@embroider\core\src\app.js:428:38)
    at WaitForTrees.wait_for_trees_1.default [as buildHook] (C:\Users\lifeart\Documents\repos\js-framework-benchmark\frameworks\keyed\ember\node_modules\@embroider\core\src\build-stage.js:37:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)

=================================================================================

```

**Comment by lifeart** [comment]
hm, I have no app and vendor styles in my app `index.html`, it may be an issue.

**Comment by lifeart** [comment]
next issue: 
![image](https://user-images.githubusercontent.com/1360552/59634541-ba94b180-9157-11e9-98a4-b6a5a63b95ae.png)

**Comment by lifeart** [comment]
Looks like all this issues solved

**Comment by lifeart** [comment]
@HerveSeger, @btecu, @ChristopherConnock could you please, retest it againist https://github.com/embroider-build/embroider/pull/228 ? (don't forget to compile soures)

**Comment by HerveSeger** [comment]
I just tested with version `0.4.3` that has been released a few hours ago.

There is some good progress, it is cool.
Nevertheless, it fails in the `cleanup` step:
```
λ yarn build
yarn run v1.16.0
$ ember build
Environment: development
/ BuildingBuilding into C:\Temp\embroider\8900e1
cleaning up...
Build Error (WaitForTrees)

Cannot find module './bower_components/bootstrap-sass/assets/javascripts/bootstrap/tab.js' from 'C:\Temp\embroider\8900e1\node_modules\@embroider\synthesized-vendor'


Stack Trace and Error Report: C:\Temp/error.dump.061f0fc75dfcae457762950f6a5941f4.log
```

It comes from one of our addon that embeds corporate components where we import a bunch of javascript files:
``` javascript
// addon/index.js
_importPlugins(app) {
		if (app) {
			app.import(`${app.bowerDirectory}/bootstrap-sass/assets/javascripts/bootstrap/tab.js`);
			app.import(`${app.bowerDirectory}/bootstrap-sass/assets/javascripts/bootstrap/dropdown.js`);
			app.import(`${app.bowerDirectory}/bootstrap-sass/assets/javascripts/bootstrap/transition.js`);
			app.import(`${app.bowerDirectory}/bootstrap-sass/assets/javascripts/bootstrap/alert.js`);
			app.import(`${app.bowerDirectory}/bootstrap-sass/assets/javascripts/bootstrap/modal.js`);
			app.import(`${app.bowerDirectory}/parsleyjs/dist/parsley.min.js`);
		}
	},
```

The stack trace is:
```
ERROR Summary:

  - broccoliBuilderErrorStack: Error: Cannot find module './bower_components/bootstrap-sass/assets/javascripts/bootstrap/tab.js' from 'C:\Temp\embroider\8900e1\node_modules\@embroider\synthesized-vendor'
    at Function.module.exports [as sync] (c:\projects\git\embroider-app\node_modules\resolve\lib\sync.js:58:15)
    at AppBuilder.impliedAddonAssets (c:\projects\git\embroider-app\node_modules\@embroider\core\src\app.js:182:51)
    at AppBuilder.impliedAssets (c:\projects\git\embroider-app\node_modules\@embroider\core\src\app.js:157:27)
    at AppBuilder.insertEmberApp (c:\projects\git\embroider-app\node_modules\@embroider\core\src\app.js:244:36)
    at AppBuilder.prepareAsset (c:\projects\git\embroider-app\node_modules\@embroider\core\src\app.js:296:18)
    at AppBuilder.prepareAssets (c:\projects\git\embroider-app\node_modules\@embroider\core\src\app.js:306:18)
    at AppBuilder.updateAssets (c:\projects\git\embroider-app\node_modules\@embroider\core\src\app.js:374:27)
    at AppBuilder.build (c:\projects\git\embroider-app\node_modules\@embroider\core\src\app.js:428:38)
    at WaitForTrees.wait_for_trees_1.default [as buildHook] (c:\projects\git\embroider-app\node_modules\@embroider\core\src\build-stage.js:37:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  - code: [undefined]
  - codeFrame: Cannot find module './bower_components/bootstrap-sass/assets/javascripts/bootstrap/tab.js' from 'C:\Temp\embroider\8900e1\node_modules\@embroider\synthesized-vendor'
  - errorMessage: Cannot find module './bower_components/bootstrap-sass/assets/javascripts/bootstrap/tab.js' from 'C:\Temp\embroider\8900e1\node_modules\@embroider\synthesized-vendor'
        at WaitForTrees (@embroider/compat/app)
-~- created here: -~-
    at new Plugin (c:\projects\git\embroider-app\node_modules\broccoli-plugin\index.js:7:31)
    at new WaitForTrees (c:\projects\git\embroider-app\node_modules\@embroider\core\src\wait-for-trees.js:30:9)
    at CompatApp.get tree (c:\projects\git\embroider-app\node_modules\@embroider\core\src\build-stage.js:26:16)
    at CompatApp.<anonymous> (c:\projects\git\embroider-app\node_modules\typescript-memoize\dist\memoize-decorator.js:67:52)
    at new PackagerRunner (c:\projects\git\embroider-app\node_modules\@embroider\core\src\to-broccoli-plugin.js:10:26)
    at Object.defaultPipeline [as compatBuild] (c:\projects\git\embroider-app\node_modules\@embroider\compat\src\default-pipeline.js:30:12)
    at module.exports (c:\projects\git\embroider-app\ember-cli-build.js:84:38)
    at Builder.readBuildFile (c:\projects\git\embroider-app\node_modules\ember-cli\lib\models\builder.js:51:14)
    at Builder.setupBroccoliBuilder (c:\projects\git\embroider-app\node_modules\ember-cli\lib\models\builder.js:65:22)
    at new Builder (c:\projects\git\embroider-app\node_modules\ember-cli\lib\models\builder.js:31:10)
-~- (end) -~-
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
    - treeDir: [undefined]
  - message: Cannot find module './bower_components/bootstrap-sass/assets/javascripts/bootstrap/tab.js' from 'C:\Temp\embroider\8900e1\node_modules\@embroider\synthesized-vendor'
        at WaitForTrees (@embroider/compat/app)
-~- created here: -~-
    at new Plugin (c:\projects\git\embroider-app\node_modules\broccoli-plugin\index.js:7:31)
    at new WaitForTrees (c:\projects\git\embroider-app\node_modules\@embroider\core\src\wait-for-trees.js:30:9)
    at CompatApp.get tree (c:\projects\git\embroider-app\node_modules\@embroider\core\src\build-stage.js:26:16)
    at CompatApp.<anonymous> (c:\projects\git\embroider-app\node_modules\typescript-memoize\dist\memoize-decorator.js:67:52)
    at new PackagerRunner (c:\projects\git\embroider-app\node_modules\@embroider\core\src\to-broccoli-plugin.js:10:26)
    at Object.defaultPipeline [as compatBuild] (c:\projects\git\embroider-app\node_modules\@embroider\compat\src\default-pipeline.js:30:12)
    at module.exports (c:\projects\git\embroider-app\ember-cli-build.js:84:38)
    at Builder.readBuildFile (c:\projects\git\embroider-app\node_modules\ember-cli\lib\models\builder.js:51:14)
    at Builder.setupBroccoliBuilder (c:\projects\git\embroider-app\node_modules\ember-cli\lib\models\builder.js:65:22)
    at new Builder (c:\projects\git\embroider-app\node_modules\ember-cli\lib\models\builder.js:31:10)
-~- (end) -~-
  - name: BuildError
  - nodeAnnotation: @embroider/compat/app
  - nodeName: WaitForTrees
  - originalErrorMessage: Cannot find module './bower_components/bootstrap-sass/assets/javascripts/bootstrap/tab.js' from 'C:\Temp\embroider\8900e1\node_modules\@embroider\synthesized-vendor'
  - stack: Error: Cannot find module './bower_components/bootstrap-sass/assets/javascripts/bootstrap/tab.js' from 'C:\Temp\embroider\8900e1\node_modules\@embroider\synthesized-vendor'
    at Function.module.exports [as sync] (c:\projects\git\embroider-app\node_modules\resolve\lib\sync.js:58:15)
    at AppBuilder.impliedAddonAssets (c:\projects\git\embroider-app\node_modules\@embroider\core\src\app.js:182:51)
    at AppBuilder.impliedAssets (c:\projects\git\embroider-app\node_modules\@embroider\core\src\app.js:157:27)
    at AppBuilder.insertEmberApp (c:\projects\git\embroider-app\node_modules\@embroider\core\src\app.js:244:36)
    at AppBuilder.prepareAsset (c:\projects\git\embroider-app\node_modules\@embroider\core\src\app.js:296:18)
    at AppBuilder.prepareAssets (c:\projects\git\embroider-app\node_modules\@embroider\core\src\app.js:306:18)
    at AppBuilder.updateAssets (c:\projects\git\embroider-app\node_modules\@embroider\core\src\app.js:374:27)
    at AppBuilder.build (c:\projects\git\embroider-app\node_modules\@embroider\core\src\app.js:428:38)
    at WaitForTrees.wait_for_trees_1.default [as buildHook] (c:\projects\git\embroider-app\node_modules\@embroider\core\src\build-stage.js:37:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)

=================================================================================
```

I hope this helps.

**Comment by lifeart** [comment]
@HerveSeger what do you think about idea to create new issue, due to addon error, to skip cleared stuff and focus on exact problem. (best if it has reproduction repo or kinda)

**Comment by HerveSeger** [comment]
Sure. 
I will leave this issue open to give other contributors the chance to provide their input.

**Comment by ef4** [comment]
I don't think we support bower at all.

I'm not opposed if somebody wants to implement that, but it's not high on my priority list. Bower itself keeps telling people to stop using it.

I think the implementation would go in the code that generates the `@embroider/synthesized-vendor` package.

**Comment by stefanpenner** [comment]
@ef4 my vote would be not to support `bower`. Bower doesn't even support bower anymore... It may just be a liability for us to support it.

**Comment by HerveSeger** [comment]
I agree with the decision of not supporting bower.

On our side, we wanted to get rid of it anyway so it will just force us to take a look at this.

**Comment by void-mAlex** [comment]
original issue seems to have been resolved so closing this
