### ISSUE TITLE
Unable to find @glimmer/syntax

### ISSUE THREAD

**Issue by meirish** [embroider-build/embroider#147]
Hello! Excited for this in the future - I wanted to see if it would work on our app, but it looks like not yet. I ran into this:
Error in ember-cli output:
```
Build Error (OneShot)

templates/components/basic-dropdown.hbs: unable to find @glimmer/syntax methods in /Users/meirish/go/src/github.com/hashicorp/vault/ui/node_modules/ember-source/dist/ember-template-compiler.js
        in /var/folders/n0/1cj2fwvj7hggltr7zqn8g9v40000gp/T/broccoli-458054dtb3uvdOdIF/out-01-funnel
        at embroider-template-compile-stage1
```

And the full thing from the log file:

```
ERROR Summary:

  - broccoliBuilderErrorStack: Error: unable to find @glimmer/syntax methods in /Users/meirish/go/src/github.com/hashicorp/vault/ui/node_modules/ember-source/dist/ember-template-compiler.js
    at loadGlimmerSyntax (/Users/meirish/go/src/github.com/hashicorp/vault/ui/node_modules/@embroider/core/src/template-compiler.js:63:11)
    at TemplateCompiler.setup (/Users/meirish/go/src/github.com/hashicorp/vault/ui/node_modules/@embroider/core/src/template-compiler.js:134:22)
    at TemplateCompiler.<anonymous> (/Users/meirish/go/src/github.com/hashicorp/vault/ui/node_modules/typescript-memoize/dist/memoize-decorator.js:67:52)
    at TemplateCompiler.get cacheKey [as cacheKey] (/Users/meirish/go/src/github.com/hashicorp/vault/ui/node_modules/@embroider/core/src/template-compiler.js:131:21)
    at TemplateCompileTree.cacheKeyProcessString (/Users/meirish/go/src/github.com/hashicorp/vault/ui/node_modules/@embroider/core/src/template-compiler.js:262:55)
    at Object.processString (/Users/meirish/go/src/github.com/hashicorp/vault/ui/node_modules/@embroider/core/node_modules/broccoli-persistent-filter/lib/strategies/persistent.js:30:19)
    at Processor.processString (/Users/meirish/go/src/github.com/hashicorp/vault/ui/node_modules/@embroider/core/node_modules/broccoli-persistent-filter/lib/processor.js:19:27)
    at resolve (/Users/meirish/go/src/github.com/hashicorp/vault/ui/node_modules/@embroider/core/node_modules/broccoli-persistent-filter/index.js:353:16)
    at initializePromise (/Users/meirish/go/src/github.com/hashicorp/vault/ui/node_modules/@embroider/core/node_modules/rsvp/dist/rsvp.js:520:5)
    at new Promise (/Users/meirish/go/src/github.com/hashicorp/vault/ui/node_modules/@embroider/core/node_modules/rsvp/dist/rsvp.js:995:33)
  - codeFrame: templates/components/basic-dropdown.hbs: unable to find @glimmer/syntax methods in /Users/meirish/go/src/github.com/hashicorp/vault/ui/node_modules/ember-source/dist/ember-template-compiler.js
        in /var/folders/n0/1cj2fwvj7hggltr7zqn8g9v40000gp/T/broccoli-458054dtb3uvdOdIF/out-01-funnel
        at embroider-template-compile-stage1
  - errorMessage: templates/components/basic-dropdown.hbs: unable to find @glimmer/syntax methods in /Users/meirish/go/src/github.com/hashicorp/vault/ui/node_modules/ember-source/dist/ember-template-compiler.js
        in /var/folders/n0/1cj2fwvj7hggltr7zqn8g9v40000gp/T/broccoli-458054dtb3uvdOdIF/out-01-funnel
        at embroider-template-compile-stage1
        at OneShot
-~- created here: -~-
    at new Plugin (/Users/meirish/go/src/github.com/hashicorp/vault/ui/node_modules/broccoli-plugin/index.js:7:31)
    at new OneShot (/Users/meirish/go/src/github.com/hashicorp/vault/ui/node_modules/@embroider/compat/src/one-shot.js:14:9)
    at Object.cachedBuildCompatAddon [as default] (/Users/meirish/go/src/github.com/hashicorp/vault/ui/node_modules/@embroider/compat/src/build-compat-addon.js:15:16)
    at CompatAddons.movedAddons.map.oldPkg (/Users/meirish/go/src/github.com/hashicorp/vault/ui/node_modules/@embroider/compat/src/compat-addons.js:39:105)
    at Array.map (<anonymous>)
    at new CompatAddons (/Users/meirish/go/src/github.com/hashicorp/vault/ui/node_modules/@embroider/compat/src/compat-addons.js:39:63)
    at Object.defaultPipeline [as compatBuild] (/Users/meirish/go/src/github.com/hashicorp/vault/ui/node_modules/@embroider/compat/src/default-pipeline.js:17:18)
    at module.exports (/Users/meirish/go/src/github.com/hashicorp/vault/ui/ember-cli-build.js:74:39)
    at Builder.readBuildFile (/Users/meirish/go/src/github.com/hashicorp/vault/ui/node_modules/ember-cli/lib/models/builder.js:52:14)
    at Builder.setupBroccoliBuilder (/Users/meirish/go/src/github.com/hashicorp/vault/ui/node_modules/ember-cli/lib/models/builder.js:66:22)
-~- (end) -~-
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
    - treeDir: [undefined]
  - message: templates/components/basic-dropdown.hbs: unable to find @glimmer/syntax methods in /Users/meirish/go/src/github.com/hashicorp/vault/ui/node_modules/ember-source/dist/ember-template-compiler.js
        in /var/folders/n0/1cj2fwvj7hggltr7zqn8g9v40000gp/T/broccoli-458054dtb3uvdOdIF/out-01-funnel
        at embroider-template-compile-stage1
        at OneShot
-~- created here: -~-
    at new Plugin (/Users/meirish/go/src/github.com/hashicorp/vault/ui/node_modules/broccoli-plugin/index.js:7:31)
    at new OneShot (/Users/meirish/go/src/github.com/hashicorp/vault/ui/node_modules/@embroider/compat/src/one-shot.js:14:9)
    at Object.cachedBuildCompatAddon [as default] (/Users/meirish/go/src/github.com/hashicorp/vault/ui/node_modules/@embroider/compat/src/build-compat-addon.js:15:16)
    at CompatAddons.movedAddons.map.oldPkg (/Users/meirish/go/src/github.com/hashicorp/vault/ui/node_modules/@embroider/compat/src/compat-addons.js:39:105)
    at Array.map (<anonymous>)
    at new CompatAddons (/Users/meirish/go/src/github.com/hashicorp/vault/ui/node_modules/@embroider/compat/src/compat-addons.js:39:63)
    at Object.defaultPipeline [as compatBuild] (/Users/meirish/go/src/github.com/hashicorp/vault/ui/node_modules/@embroider/compat/src/default-pipeline.js:17:18)
    at module.exports (/Users/meirish/go/src/github.com/hashicorp/vault/ui/ember-cli-build.js:74:39)
    at Builder.readBuildFile (/Users/meirish/go/src/github.com/hashicorp/vault/ui/node_modules/ember-cli/lib/models/builder.js:52:14)
    at Builder.setupBroccoliBuilder (/Users/meirish/go/src/github.com/hashicorp/vault/ui/node_modules/ember-cli/lib/models/builder.js:66:22)
-~- (end) -~-
  - name: BuildError
  - nodeAnnotation: [undefined]
  - nodeName: OneShot
  - originalErrorMessage: templates/components/basic-dropdown.hbs: unable to find @glimmer/syntax methods in /Users/meirish/go/src/github.com/hashicorp/vault/ui/node_modules/ember-source/dist/ember-template-compiler.js
        in /var/folders/n0/1cj2fwvj7hggltr7zqn8g9v40000gp/T/broccoli-458054dtb3uvdOdIF/out-01-funnel
        at embroider-template-compile-stage1
  - stack: Error: unable to find @glimmer/syntax methods in /Users/meirish/go/src/github.com/hashicorp/vault/ui/node_modules/ember-source/dist/ember-template-compiler.js
    at loadGlimmerSyntax (/Users/meirish/go/src/github.com/hashicorp/vault/ui/node_modules/@embroider/core/src/template-compiler.js:63:11)
    at TemplateCompiler.setup (/Users/meirish/go/src/github.com/hashicorp/vault/ui/node_modules/@embroider/core/src/template-compiler.js:134:22)
    at TemplateCompiler.<anonymous> (/Users/meirish/go/src/github.com/hashicorp/vault/ui/node_modules/typescript-memoize/dist/memoize-decorator.js:67:52)
    at TemplateCompiler.get cacheKey [as cacheKey] (/Users/meirish/go/src/github.com/hashicorp/vault/ui/node_modules/@embroider/core/src/template-compiler.js:131:21)
    at TemplateCompileTree.cacheKeyProcessString (/Users/meirish/go/src/github.com/hashicorp/vault/ui/node_modules/@embroider/core/src/template-compiler.js:262:55)
    at Object.processString (/Users/meirish/go/src/github.com/hashicorp/vault/ui/node_modules/@embroider/core/node_modules/broccoli-persistent-filter/lib/strategies/persistent.js:30:19)
    at Processor.processString (/Users/meirish/go/src/github.com/hashicorp/vault/ui/node_modules/@embroider/core/node_modules/broccoli-persistent-filter/lib/processor.js:19:27)
    at resolve (/Users/meirish/go/src/github.com/hashicorp/vault/ui/node_modules/@embroider/core/node_modules/broccoli-persistent-filter/index.js:353:16)
    at initializePromise (/Users/meirish/go/src/github.com/hashicorp/vault/ui/node_modules/@embroider/core/node_modules/rsvp/dist/rsvp.js:520:5)
    at new Promise (/Users/meirish/go/src/github.com/hashicorp/vault/ui/node_modules/@embroider/core/node_modules/rsvp/dist/rsvp.js:995:33)

=================================================================================
```

Is there a minimum version of Ember required? (We're on 3.4.x currently), also here's the `ember-cli-build.js` file in case that helps: https://github.com/hashicorp/vault/blob/e25a8a1c7480305e749b7518b8e4eef6b9df9eb8/ui/ember-cli-build.js

**Comment by ef4** [comment]
You're correct, it looks like we didn't suport Ember 3.4. But I think that is fixed by https://github.com/embroider-build/embroider/pull/201

Mostly Embroider doesn't depend very tightly on Ember itself, so we should be fairly broadly compatible with ember-source versions. The one place we dig into internals is when loading and extending the template compiler.

**Comment by meirish** [comment]
Thanks! I’ll try it again after we update.
