### ISSUE TITLE
Build Error: could not find app javascript in index.html

### ISSUE THREAD

**Issue by kevinansfield** [embroider-build/embroider#148]
In Ghost we have a requirement to publish both development and production html/js/css files in a single package so we have a setup that generates files with different names and custom `{{content-for}}` hooks for inserting the right `<script>` and `<link>` tags.

- [in-repo-addon with custom {{content-for}} hook](https://github.com/TryGhost/Ghost-Admin/blob/master/lib/asset-delivery/index.js#L11-L27)
- [usage in index.html](https://github.com/TryGhost/Ghost-Admin/blob/master/app/index.html#L50)

Following the setup instructions in the readme, for a development build I see the following error:

```
>> Build Error (WaitForTrees)
>> could not find app javascript in index.html
>> Stack Trace and Error Report: /var/folders/30/3l01y1ld18l598kxr5srm7kr0000gn/T/error.dump.4359fa193c0e4e77c12dd665e1725452.log
```

<details>
<summary>Stack Trace and Error Report</summary>

```
=================================================================================

ENV Summary:

  TIME: Fri Apr 26 2019 08:54:16 GMT+0200 (Central European Summer Time)
  TITLE: ember
  ARGV:
  - /Users/kevinansfield/.nvm/versions/node/v10.15.1/bin/node
  - /Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/.bin/ember
  - serve
  - --live-reload-base-url=/ghost/
  - --live-reload-port=4201
  EXEC_PATH: /Users/kevinansfield/.nvm/versions/node/v10.15.1/bin/node
  TMPDIR: /var/folders/30/3l01y1ld18l598kxr5srm7kr0000gn/T
  SHELL: /usr/local/bin/zsh
  PATH:
  - /Users/kevinansfield/.nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin
  - /Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/.bin
  - /Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/.bin
  - /Users/kevinansfield/code/ghost/Ghost/core/node_modules/.bin
  - /Users/kevinansfield/code/ghost/Ghost/node_modules/.bin
  - /Users/kevinansfield/code/ghost/node_modules/.bin
  - /Users/kevinansfield/code/node_modules/.bin
  - /Users/kevinansfield/node_modules/.bin
  - /Users/node_modules/.bin
  - /node_modules/.bin
  - /Users/kevinansfield/.nvm/versions/node/v10.15.1/bin
  - /Users/kevinansfield/.rvm/gems/ruby-2.3.3/bin
  - /Users/kevinansfield/.rvm/gems/ruby-2.3.3@global/bin
  - /Users/kevinansfield/.rvm/rubies/ruby-2.3.3/bin
  - /Users/kevinansfield/.yarn/bin
  - /Users/kevinansfield/.nvm/versions/node/v10.15.1/bin
  - /usr/local/opt/php@7.1/sbin
  - /usr/local/opt/php@7.1/bin
  - /usr/local/heroku/bin
  - /Applications/Postgres.app/Contents/Versions/latest/bin
  - /usr/local/bin
  - /usr/local/sbin
  - /usr/local/share/npm/bin
  - /usr/local/bin
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  - /usr/local/MacGPG2/bin
  - /Users/kevinansfield/.rvm/bin
  - /Users/kevinansfield/.composer/vendor/bin
  PLATFORM: darwin x64
  FREEMEM: 27926528
  TOTALMEM: 17179869184
  UPTIME: 1118791
  LOADAVG: 5.68408203125,5.861328125,9.69091796875
  CPUS:
  - Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz - 2900
  - Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz - 2900
  - Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz - 2900
  - Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz - 2900
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.15.0
  - cldr: 33.1
  - http_parser: 2.8.0
  - icu: 62.1
  - modules: 64
  - napi: 3
  - nghttp2: 1.34.0
  - node: 10.15.1
  - openssl: 1.1.0j
  - tz: 2018e
  - unicode: 11.0
  - uv: 1.23.2
  - v8: 6.8.275.32-node.12
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: Error: could not find app javascript in index.html
    at definitelyReplace (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/@embroider/compat/src/compat-app.js:238:15)
    at Object.prepare (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/@embroider/compat/src/compat-app.js:119:37)
    at new PreparedEmberHTML (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/@embroider/core/src/ember-html.js:30:26)
    at new ParsedEmberAsset (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/@embroider/core/src/app.js:40:21)
    at AppBuilder.prepareAsset (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/@embroider/core/src/app.js:267:26)
    at AppBuilder.prepareAssets (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/@embroider/core/src/app.js:279:18)
    at AppBuilder.updateAssets (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/@embroider/core/src/app.js:347:27)
    at AppBuilder.build (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/@embroider/core/src/app.js:401:38)
    at WaitForTrees.wait_for_trees_1.default [as buildHook] (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/@embroider/core/src/build-stage.js:37:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  - code: [undefined]
  - codeFrame: could not find app javascript in index.html
  - errorMessage: could not find app javascript in index.html
        at WaitForTrees (@embroider/compat/app)
-~- created here: -~-
    at new Plugin (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/broccoli-plugin/index.js:7:31)
    at new WaitForTrees (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/@embroider/core/src/wait-for-trees.js:30:9)
    at CompatApp.get tree (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/@embroider/core/src/build-stage.js:26:16)
    at CompatApp.<anonymous> (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/typescript-memoize/dist/memoize-decorator.js:67:52)
    at new PackagerRunner (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/@embroider/core/src/to-broccoli-plugin.js:11:26)
    at Object.defaultPipeline [as compatBuild] (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/@embroider/compat/src/default-pipeline.js:30:12)
    at module.exports (/Users/kevinansfield/code/ghost/Ghost/core/client/ember-cli-build.js:241:41)
    at Builder.readBuildFile (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/ember-cli/lib/models/builder.js:52:14)
    at Builder.setupBroccoliBuilder (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/ember-cli/lib/models/builder.js:66:22)
    at new Builder (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/ember-cli/lib/models/builder.js:32:10)
-~- (end) -~-
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
    - treeDir: [undefined]
  - message: could not find app javascript in index.html
        at WaitForTrees (@embroider/compat/app)
-~- created here: -~-
    at new Plugin (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/broccoli-plugin/index.js:7:31)
    at new WaitForTrees (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/@embroider/core/src/wait-for-trees.js:30:9)
    at CompatApp.get tree (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/@embroider/core/src/build-stage.js:26:16)
    at CompatApp.<anonymous> (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/typescript-memoize/dist/memoize-decorator.js:67:52)
    at new PackagerRunner (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/@embroider/core/src/to-broccoli-plugin.js:11:26)
    at Object.defaultPipeline [as compatBuild] (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/@embroider/compat/src/default-pipeline.js:30:12)
    at module.exports (/Users/kevinansfield/code/ghost/Ghost/core/client/ember-cli-build.js:241:41)
    at Builder.readBuildFile (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/ember-cli/lib/models/builder.js:52:14)
    at Builder.setupBroccoliBuilder (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/ember-cli/lib/models/builder.js:66:22)
    at new Builder (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/ember-cli/lib/models/builder.js:32:10)
-~- (end) -~-
  - name: BuildError
  - nodeAnnotation: @embroider/compat/app
  - nodeName: WaitForTrees
  - originalErrorMessage: could not find app javascript in index.html
  - stack: Error: could not find app javascript in index.html
    at definitelyReplace (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/@embroider/compat/src/compat-app.js:238:15)
    at Object.prepare (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/@embroider/compat/src/compat-app.js:119:37)
    at new PreparedEmberHTML (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/@embroider/core/src/ember-html.js:30:26)
    at new ParsedEmberAsset (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/@embroider/core/src/app.js:40:21)
    at AppBuilder.prepareAsset (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/@embroider/core/src/app.js:267:26)
    at AppBuilder.prepareAssets (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/@embroider/core/src/app.js:279:18)
    at AppBuilder.updateAssets (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/@embroider/core/src/app.js:347:27)
    at AppBuilder.build (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/@embroider/core/src/app.js:401:38)
    at WaitForTrees.wait_for_trees_1.default [as buildHook] (/Users/kevinansfield/code/ghost/Ghost/core/client/node_modules/@embroider/core/src/build-stage.js:37:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)

=================================================================================
```

</details>

Is there some additional config needed in order to tell Embroider where to find the JS files?

**Comment by ef4** [comment]
This kind of customization is at odds with our ability to do lazy loading & code splitting. It locks in a pattern where there are always exactly two bundles (vendor.js and ghost.js). Whereas we want the set of bundles to be optimized dynamically. We want to put an abstraction barrier between the application author and the knowledge of which things go into which `dist/assets/*.js` file.

So I don't expect to ever make Embroider compatible with the existing implementation you're using. Instead, we'll need to find a different strategy for solving your problem. 

One thing that would work is setting up the build pipeline so that when you're ready to publish you're really building the app twice, with different settings, and combining the outputs.

**Comment by lifeart** [comment]
@kevinansfield may be fixed by https://github.com/embroider-build/embroider/pull/252

**Comment by kevinansfield** [comment]
Unfortunately I'm hitting a different error using latest release so I'm not sure if it's fixed. I get the same error when linking latest master which has https://github.com/embroider-build/embroider/pull/252 in it.

```
>> Build Error (OneShot)
>> [BroccoliMergeTrees] error while merging the following:
>>   1.  [ObserveTree: @embroider/compat/observe-tree]
>>   2.  [ObserveTree: @embroider/compat/observe-tree]
>>   3.  [ObserveTree: @embroider/compat/observe-tree]
>>   4.  [Funnel]
>>   5.  [RewritePackageJSON: embroider:core:rewrite-package-json]
>> Merge error: file app.css exists in /var/folders/30/3l01y1ld18l598kxr5srm7kr0000gn/T/broccoli-53952DJYhHakv1FBT/out-26-observe_tree_embroider_compat_observe_tree and /var/folders/30/3l01y1ld18l598kxr5srm7kr0000gn/T/broccoli-53952DJYhHakv1FBT/out-30-observe_tree_embroider_compat_observe_tree
>> Pass option { overwrite: true } to mergeTrees in order to have the latter file win.
>>         at BroccoliMergeTrees
>> -~- created here: -~-
>>     at BroccoliMergeTrees.Plugin (/Users/kevinansfield/code/ghost/embroider/node_modules/broccoli-plugin/index.js:7:31)
>>     at new BroccoliMergeTrees (/Users/kevinansfield/code/ghost/embroider/node_modules/broccoli-merge-trees/index.js:16:10)
>>     at Object.BroccoliMergeTrees [as default] (/Users/kevinansfield/code/ghost/embroider/node_modules/broccoli-merge-trees/index.js:10:53)
>>     at V1Addon.get v2Tree [as v2Tree] (/Users/kevinansfield/code/ghost/embroider/packages/compat/src/v1-addon.js:310:46)
>>     at oldPackages.map.pkg (/Users/kevinansfield/code/ghost/embroider/packages/compat/src/build-compat-addon.js:42:48)
>>     at Array.map (<anonymous>)
>>     at buildCompatAddon (/Users/kevinansfield/code/ghost/embroider/packages/compat/src/build-compat-addon.js:42:33)
>>     at Object.cachedBuildCompatAddon [as default] (/Users/kevinansfield/code/ghost/embroider/packages/compat/src/build-compat-addon.js:13:16)
>>     at CompatAddons.movedAddons.map.oldPkg (/Users/kevinansfield/code/ghost/embroider/packages/compat/src/compat-addons.js:39:105)
>>     at Array.map (<anonymous>)
>> -~- (end) -~-
>> Stack Trace and Error Report: /var/folders/30/3l01y1ld18l598kxr5srm7kr0000gn/T/error.dump.158b156cff479ce1df63c72f6cc887c6.log
```

**Comment by kevinansfield** [comment]
Found the resolution for that `app.css` error in https://github.com/embroider-build/embroider/issues/169. 

@lifeart unfortunately on latest master with the https://github.com/embroider-build/embroider/pull/252 fix I still get the original error:

```
>> Build Error (WaitForTrees)
>> could not find app javascript in index.html
```

**Comment by lifeart** [comment]
@kevinansfield did you `yarn clean; yarn compile` fresh master?

**Comment by kevinansfield** [comment]
@lifeart this was a `git clone; yarn install; yarn compile` then linking of `@embroider/{core,compat,webpack}` into my project. I've tried a `yarn clean; yarn compile` just in case but still the same error

**Comment by imkathir** [comment]
I've encountered one issue similar to this issue. Production build of my app is not building. It's failing with the following error log `could not find app javascript in index.html`.

**Comment by imkathir** [comment]
Replcaing `rootURL: '/myAppName/'` fixed the issue for me.

**Comment by raido** [comment]
I’ve hit missing trailing slash issue with rootURL as well.
