### ISSUE TITLE
Embroider clobbers local `this.options` in ember-inline-svg

### ISSUE THREAD

**Issue by patocallaghan** [embroider-build/embroider#152]
If if try to use embroider on an app that uses ember-inline-svg I get the following error: `this.options is not a function`.

It appears when using embroider the local `this.options` function is clobbered by an object hash

![image](https://user-images.githubusercontent.com/685034/56994397-db4c7c00-6b96-11e9-9d7d-70c48aa510a6.png)

Whereas without embroider it has the correct `this.options` function

![image](https://user-images.githubusercontent.com/685034/56994329-ab04dd80-6b96-11e9-9c13-ebc3bb85815e.png)

The relevant `this.options` code in ember-inline-svg is here https://github.com/minutebase/ember-inline-svg/blob/ca91b01daf73b7c714b83053b5e0057dee1a2ffd/index.js#L20-L32

I've also created a sample app which replicates the problem [here](https://github.com/patocallaghan/embroider-test-app/tree/f97fa30b7167e960f0f901c740f29e408db50739)

**Error log:**
```
=================================================================================

ENV Summary:

  TIME: Tue Apr 30 2019 22:14:51 GMT+0100 (Irish Standard Time)
  TITLE: ember
  ARGV:
  - /Users/pat/.nvm/versions/node/v10.15.0/bin/node
  - /Users/pat/hacking/embroider-test-app/node_modules/.bin/ember
  - build
  EXEC_PATH: /Users/pat/.nvm/versions/node/v10.15.0/bin/node
  TMPDIR: /var/folders/mk/5t937px5627_y_j551f8gbkm0000gn/T
  SHELL: /bin/zsh
  PATH:
  - /var/folders/mk/5t937px5627_y_j551f8gbkm0000gn/T/yarn--1556658883945-0.39350346415838433
  - /Users/pat/hacking/embroider-test-app/node_modules/.bin
  - /Users/pat/.config/yarn/link/node_modules/.bin
  - /Users/pat/hacking/embroider-test-app/node_modules/.bin
  - /Users/pat/.config/yarn/link/node_modules/.bin
  - /Users/pat/.nvm/versions/node/v10.15.0/libexec/lib/node_modules/npm/bin/node-gyp-bin
  - /Users/pat/.nvm/versions/node/v10.15.0/lib/node_modules/npm/bin/node-gyp-bin
  - /Users/pat/.nvm/versions/node/v10.15.0/bin/node_modules/npm/bin/node-gyp-bin
  - /Users/pat/.nvm/versions/node/v10.15.0/bin
  - /Users/pat/.yarn/bin
  - /Users/pat/.config/yarn/global/node_modules/.bin
  - /Users/pat/.rbenv/shims
  - /Users/pat/.pilot/bin
  - /usr/local/bin
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  - /Users/pat/.nvm/versions/node/v10.15.0/bin
  - /Users/pat/.yarn/bin
  - /Users/pat/.config/yarn/global/node_modules/.bin
  - /Users/pat/.rbenv/shims
  - /Users/pat/.pilot/bin
  PLATFORM: darwin x64
  FREEMEM: 607375360
  TOTALMEM: 17179869184
  UPTIME: 1112030
  LOADAVG: 3.42236328125,3.203125,3.62109375
  CPUS:
  - Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz - 2700
  - Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz - 2700
  - Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz - 2700
  - Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz - 2700
  - Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz - 2700
  - Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz - 2700
  - Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz - 2700
  - Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz - 2700
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.15.0
  - cldr: 33.1
  - http_parser: 2.8.0
  - icu: 62.1
  - modules: 64
  - napi: 3
  - ndb: 1.0.42
  - nghttp2: 1.34.0
  - node: 10.15.0
  - openssl: 1.1.0j
  - tz: 2018e
  - unicode: 11.0
  - uv: 1.23.2
  - v8: 6.8.275.32-node.45
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - code: [undefined]
  - codeFrame: [undefined]
  - errorMessage: this.options is not a function
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: this.options is not a function
  - name: TypeError
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: TypeError: this.options is not a function
    at Class.svgPaths (/Users/pat/hacking/embroider-test-app/node_modules/ember-inline-svg/index.js:31:17)
    at Class.treeForApp (/Users/pat/hacking/embroider-test-app/node_modules/ember-inline-svg/index.js:44:30)
    at Class._treeFor (/Users/pat/hacking/embroider-test-app/node_modules/ember-cli/lib/models/addon.js:684:33)
    at throughTreeCache (/Users/pat/hacking/embroider-test-app/node_modules/@embroider/compat/src/v1-addon.js:375:43)
    at V1Addon.throughTreeCache (/Users/pat/hacking/embroider-test-app/node_modules/@embroider/compat/src/v1-addon.js:359:20)
    at V1Addon.invokeOriginalTreeFor (/Users/pat/hacking/embroider-test-app/node_modules/@embroider/compat/src/v1-addon.js:366:21)
    at V1Addon.buildTreeForApp (/Users/pat/hacking/embroider-test-app/node_modules/@embroider/compat/src/v1-addon.js:520:33)
    at V1Addon.build (/Users/pat/hacking/embroider-test-app/node_modules/@embroider/compat/src/v1-addon.js:619:14)
    at V1Addon.<anonymous> (/Users/pat/hacking/embroider-test-app/node_modules/typescript-memoize/dist/memoize-decorator.js:67:52)
    at V1Addon.get v2Trees (/Users/pat/hacking/embroider-test-app/node_modules/@embroider/compat/src/v1-addon.js:335:45)

=================================================================================
```

**Comment by patocallaghan** [comment]
I should mention if I rename ember-inline-svg's `this.options` to something else, like `this.svgOptions`, it builds fine. I raised this issue as I'm not sure how prevalent having your own `this.options` is in the addon community.

**Comment by patocallaghan** [comment]
Closing as my fix in https://github.com/embroider-build/embroider/pull/153 was merged
