### ISSUE TITLE
The presence of a `.ts` file breaks Javascript builds

### ISSUE THREAD

**Issue by bendemboski** [embroider-build/embroider#1557]
## Repro
1. `npx ember-cli new embroider-ts`
2. `cd embroider-ts`
3. `yarn add --dev @embroider/core @embroider/compat @embroider/webpack webpack`
4. Update `ember-cli-build.js` according to the [setup instructions](https://github.com/embroider-build/embroider#how-to-try-it)
5. Create a file named `app/foo.ts` that contains `type Foo = unknown;`
6. `ember test`

## Result
```
Build Error (PackagerRunner) in foo.ts

Module build failed (from ../../thread-loader/dist/cjs.js):
Thread Loader (Worker 1)
/private/tmp/embroider-rs/node_modules/.embroider/rewritten-app/foo.ts/foo.ts: Missing semicolon. (1:4)

> 1 | type Foo = unknown;
    |     ^

    at instantiate (/private/tmp/embroider-rs/node_modules/@babel/parser/lib/index.js:63:32)
    at constructor (/private/tmp/embroider-rs/node_modules/@babel/parser/lib/index.js:358:12)
    at Parser.raise (/private/tmp/embroider-rs/node_modules/@babel/parser/lib/index.js:3255:19)
    at Parser.semicolon (/private/tmp/embroider-rs/node_modules/@babel/parser/lib/index.js:3622:10)
    at Parser.parseExpressionStatement (/private/tmp/embroider-rs/node_modules/@babel/parser/lib/index.js:13154:10)
    at Parser.parseStatementContent (/private/tmp/embroider-rs/node_modules/@babel/parser/lib/index.js:12737:19)
    at Parser.parseStatementLike (/private/tmp/embroider-rs/node_modules/@babel/parser/lib/index.js:12584:17)
    at Parser.parseModuleItem (/private/tmp/embroider-rs/node_modules/@babel/parser/lib/index.js:12561:17)
    at Parser.parseBlockOrModuleBlockBody (/private/tmp/embroider-rs/node_modules/@babel/parser/lib/index.js:13185:36)
    at Parser.parseBlockBody (/private/tmp/embroider-rs/node_modules/@babel/parser/lib/index.js:13178:10)
    at Parser.parseProgram (/private/tmp/embroider-rs/node_modules/@babel/parser/lib/index.js:12460:10)
    at Parser.parseTopLevel (/private/tmp/embroider-rs/node_modules/@babel/parser/lib/index.js:12450:25)
    at Parser.parse (/private/tmp/embroider-rs/node_modules/@babel/parser/lib/index.js:14345:10)
    at parse (/private/tmp/embroider-rs/node_modules/@babel/parser/lib/index.js:14386:38)
    at parser (/private/tmp/embroider-rs/node_modules/@babel/core/lib/parser/index.js:41:34)
    at parser.next (<anonymous>)
    at normalizeFile (/private/tmp/embroider-rs/node_modules/@babel/core/lib/transformation/normalize-file.js:64:38)
    at normalizeFile.next (<anonymous>)
    at run (/private/tmp/embroider-rs/node_modules/@babel/core/lib/transformation/index.js:21:50)
    at run.next (<anonymous>)
    at transform (/private/tmp/embroider-rs/node_modules/@babel/core/lib/transform.js:22:41)
    at transform.next (<anonymous>)
    at step (/private/tmp/embroider-rs/node_modules/gensync/index.js:261:32)
    at /private/tmp/embroider-rs/node_modules/gensync/index.js:273:13
    at async.call.result.err.err (/private/tmp/embroider-rs/node_modules/gensync/index.js:223:11)
    at /private/tmp/embroider-rs/node_modules/gensync/index.js:189:28
    at /private/tmp/embroider-rs/node_modules/@babel/core/lib/gensync-utils/async.js:68:7
    at /private/tmp/embroider-rs/node_modules/gensync/index.js:113:33
    at step (/private/tmp/embroider-rs/node_modules/gensync/index.js:287:14)
    at /private/tmp/embroider-rs/node_modules/gensync/index.js:273:13
    at async.call.result.err.err (/private/tmp/embroider-rs/node_modules/gensync/index.js:223:11)


Stack Trace and Error Report: /var/folders/l8/bkj9cn6x6jq0dh6lm8fyx7q40000gn/T/error.dump.174c792fd5b6130045a16308799a6564.log
```

## Discussion
This happens if the `.ts` file is in `app` or `tests`, and it also happens in V1 addons. It looks like `embroider` is trying to include the file in the build, but ends up passing it to babel to transpile as if it were a `.js` file? I would think that in this case, since there's no typescript tooling/config, `.ts` files would just be ignored.

This came up in [ember-concurrency](https://github.com/machty/ember-concurrency/actions/runs/5631982439/job/15259493501?pr=537) because even though its source isn't typescript and it doesn't do any typescript building, it has [a types test](https://github.com/machty/ember-concurrency/blob/00d06faac0e92eb470994ddfae74f21ee278b1ac/tests/types/ember-concurrency-test.ts) that triggers this. We can work around it by moving the test to a `types-tests` folder outside of `tests`, but this seems like an issue with `embroider` that should be addressed since just the presence of a `.ts` file shouldn't break builds like this.

**Comment by NullVoxPopuli** [comment]
I confirmed this with pnpm -- thanks for the reproduction!

The work-around, however is to add `enableTypeScriptTransform: true` to `ember-cli-build.js`, but I think we should _always_ have TS support, since it's so common, and costs us nothing to have support it if people aren't using TS.

```js
'use strict';

const EmberApp = require('ember-cli/lib/broccoli/ember-app');

module.exports = function (defaults) {
  const app = new EmberApp(defaults, {
    // Add options here
    'ember-cli-babel': {
      enableTypeScriptTransform: true,
    },
  });

  const { Webpack } = require('@embroider/webpack');
  return require('@embroider/compat').compatBuild(app, Webpack);
};
```
