### ISSUE TITLE
@embroider/macros/runtime.js: @babel/template placeholder "SAMPLE_FEATURE_FLAG": Expected string substitutionError: @babel/template placeholder "SAMPLE_FEATURE_FLAG": Expected string substitution

### ISSUE THREAD

**Issue by spicalous** [embroider-build/embroider#1573]
Apologies in advance, not sure if this is the correct place to raise this issue

I upgraded ember-data from 4.0.2 to 4.8.8 and my ember build is throwing this error

```
ERROR Summary:

  - broccoliBuilderErrorStack: Error: /home/.../@embroider/macros/runtime.js: @babel/template placeholder "SAMPLE_FEATURE_FLAG": Expected string substitutionError: @babel/template placeholder "SAMPLE_FEATURE_FLAG": Expected string substitution
    at applyReplacement (/home/.../node_modules/@babel/template/lib/populate.js:74:13)
    at /home/.../node_modules/@babel/template/lib/populate.js:44:7
    at Array.forEach (<anonymous>)
    at populatePlaceholders (/home/.../node_modules/@babel/template/lib/populate.js:42:43)
    at /home/.../node_modules/@babel/template/lib/string.js:20:51
    at /home/.../node_modules/@babel/template/lib/builder.js:75:14
    at Object.buildLiterals (/home/.../node_modules/ember-cli-mirage/node_modules/@embroider/macros/src/babel/evaluate-json.js:377:73)
    at Object.inlineRuntimeConfig (/home/.../node_modules/ember-cli-mirage/node_modules/@embroider/macros/src/babel/get-config.js:107:55)
    at PluginPass.enter (/home/.../node_modules/ember-cli-mirage/node_modules/@embroider/macros/src/babel/macros-babel-plugin.js:77:38)
```

I'm not 100% sure where to go from here, any help or request for more debug info or nudge in the right direction would be appreciated!

**Comment by lifeart** [comment]
Related message in `e-data` issue: https://github.com/emberjs/data/issues/8411#issuecomment-1445982701

**Comment by void-mAlex** [comment]
> Related message in `e-data` issue: [emberjs/data#8411 (comment)](https://github.com/emberjs/data/issues/8411#issuecomment-1445982701) Related issue in `mirage`: [miragejs/ember-cli-mirage#2461](https://github.com/miragejs/ember-cli-mirage/issues/2461)

last comment in the mirage ticket says using latest alpha fixed it, which is also what I was suggesting/asking about

**Comment by spicalous** [comment]
@void-mAlex @lifeart Thanks for your help!
