### ISSUE TITLE
Embroider not working with Ember CLI Addon Docs

### ISSUE THREAD

**Issue by patocallaghan** [embroider-build/embroider#164]
I tried Embroider out on an addon that uses `ember-cli-addon-docs` to generate a site. I get the following error:

```
You specified a `"srcDir": app/styles` which does not exist and did not specify `"allowEmpty": true`.
```

It's worth noting that the `tests/dummy` app has a styles directory out of the box but the top-level `app` directory doesn't.

To reproduce:
1. Create a brand new addon, `npx ember-cli addon embroider-addon`
2. Add the Embroider libraries and config
3. `yarn add ember-cli-addon-docs`
4. `yarn build`

Here's a sample repo which can show the issue
 
Repo: https://github.com/patocallaghan/embroider-addon
Diff: https://github.com/patocallaghan/embroider-addon/compare/02554d38f85c7969ff12b5c9070b7779e5701594...master

Version info:
```
ember-cli: 3.9.0
node: 10.15.0
os: darwin x64
```

Here's the full error log.

```
=================================================================================

ENV Summary:

  TIME: Fri May 10 2019 08:05:44 GMT+0100 (Irish Standard Time)
  TITLE: ember
  ARGV:
  - /Users/pat/.nvm/versions/node/v10.15.0/bin/node
  - /Users/pat/hacking/embroider-addon/node_modules/.bin/ember
  - build
  EXEC_PATH: /Users/pat/.nvm/versions/node/v10.15.0/bin/node
  TMPDIR: /var/folders/mk/5t937px5627_y_j551f8gbkm0000gn/T
  SHELL: /bin/zsh
  PATH:
  - /var/folders/mk/5t937px5627_y_j551f8gbkm0000gn/T/yarn--1557471935960-0.42826558526890457
  - /Users/pat/hacking/embroider-addon/node_modules/.bin
  - /Users/pat/.config/yarn/link/node_modules/.bin
  - /Users/pat/hacking/embroider-addon/node_modules/.bin
  - /Users/pat/.config/yarn/link/node_modules/.bin
  - /Users/pat/.nvm/versions/node/v10.15.0/libexec/lib/node_modules/npm/bin/node-gyp-bin
  - /Users/pat/.nvm/versions/node/v10.15.0/lib/node_modules/npm/bin/node-gyp-bin
  - /Users/pat/.nvm/versions/node/v10.15.0/bin/node_modules/npm/bin/node-gyp-bin
  - /Users/pat/.nvm/versions/node/v10.15.0/bin
  - /Users/pat/.yarn/bin
  - /Users/pat/.config/yarn/global/node_modules/.bin
  - /Users/pat/.rbenv/shims
  - /Users/pat/.pilot/bin
  - /Library/Frameworks/Python.framework/Versions/3.7/bin
  - /usr/local/bin
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  PLATFORM: darwin x64
  FREEMEM: 149737472
  TOTALMEM: 17179869184
  UPTIME: 1405465
  LOADAVG: 2.66259765625,3.39501953125,5.8603515625
  CPUS:
  - Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz - 2700
  - Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz - 2700
  - Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz - 2700
  - Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz - 2700
  - Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz - 2700
  - Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz - 2700
  - Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz - 2700
  - Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz - 2700
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.15.0
  - cldr: 33.1
  - http_parser: 2.8.0
  - icu: 62.1
  - modules: 64
  - napi: 3
  - nghttp2: 1.34.0
  - node: 10.15.0
  - openssl: 1.1.0j
  - tz: 2018e
  - unicode: 11.0
  - uv: 1.23.2
  - v8: 6.8.275.32-node.45
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: Error: You specified a `"srcDir": app/styles` which does not exist and did not specify `"allowEmpty": true`.
    at Funnel.build (/Users/pat/hacking/embroider-addon/node_modules/broccoli-funnel/index.js:252:15)
    at resolve (/Users/pat/hacking/embroider-addon/node_modules/broccoli/lib/wrappers/transform-node.js:29:35)
    at new Promise (<anonymous>:null:null)
    at TransformNodeWrapper.build (/Users/pat/hacking/embroider-addon/node_modules/broccoli/lib/wrappers/transform-node.js:21:12)
    at Promise.resolve.then.then.then (/Users/pat/hacking/embroider-addon/node_modules/broccoli/lib/builder.js:116:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)

  - code: [undefined]
  - codeFrame: You specified a `"srcDir": app/styles` which does not exist and did not specify `"allowEmpty": true`.
        at Funnel
-~- created here: -~-
    at Funnel.Plugin (/Users/pat/hacking/embroider-addon/node_modules/broccoli-plugin/index.js:7:31)
    at new Funnel (/Users/pat/hacking/embroider-addon/node_modules/broccoli-funnel/index.js:57:10)
    at V1Addon.buildTreeForStyles (/Users/pat/hacking/embroider-addon/node_modules/@embroider/compat/src/v1-addon.js:432:24)
    at V1Addon.build (/Users/pat/hacking/embroider-addon/node_modules/@embroider/compat/src/v1-addon.js:593:14)
    at V1Addon.<anonymous> (/Users/pat/hacking/embroider-addon/node_modules/typescript-memoize/dist/memoize-decorator.js:67:52)
    at V1Addon.get v2Trees (/Users/pat/hacking/embroider-addon/node_modules/@embroider/compat/src/v1-addon.js:307:30)
    at V1Addon.<anonymous> (/Users/pat/hacking/embroider-addon/node_modules/typescript-memoize/dist/memoize-decorator.js:67:52)
    at V1Addon.get v2Tree [as v2Tree] (/Users/pat/hacking/embroider-addon/node_modules/@embroider/compat/src/v1-addon.js:298:52)
    at oldPackages.map.pkg (/Users/pat/hacking/embroider-addon/node_modules/@embroider/compat/src/build-compat-addon.js:42:48)
    at Array.map (<anonymous>:null:null)
    at buildCompatAddon (/Users/pat/hacking/embroider-addon/node_modules/@embroider/compat/src/build-compat-addon.js:42:33)
    at Object.cachedBuildCompatAddon [as default] (/Users/pat/hacking/embroider-addon/node_modules/@embroider/compat/src/build-compat-addon.js:13:16)
    at CompatAddons.movedAddons.map.oldPkg (/Users/pat/hacking/embroider-addon/node_modules/@embroider/compat/src/compat-addons.js:39:105)
    at Array.map (<anonymous>:null:null)
    at new CompatAddons (/Users/pat/hacking/embroider-addon/node_modules/@embroider/compat/src/compat-addons.js:39:63)
    at Object.defaultPipeline [as compatBuild] (/Users/pat/hacking/embroider-addon/node_modules/@embroider/compat/src/default-pipeline.js:17:18)
    at module.exports (/Users/pat/hacking/embroider-addon/ember-cli-build.js:18:39)
    at Builder.readBuildFile (/Users/pat/hacking/embroider-addon/node_modules/ember-cli/lib/models/builder.js:52:14)
    at Builder.setupBroccoliBuilder (/Users/pat/hacking/embroider-addon/node_modules/ember-cli/lib/models/builder.js:66:22)
    at new Builder (/Users/pat/hacking/embroider-addon/node_modules/ember-cli/lib/models/builder.js:32:10)
    at BuildTask.run (/Users/pat/hacking/embroider-addon/node_modules/ember-cli/lib/tasks/build.js:15:19)
    at Promise.resolve.then (/Users/pat/hacking/embroider-addon/node_modules/ember-cli/lib/models/command.js:243:46)
    at tryCatcher (/Users/pat/hacking/embroider-addon/node_modules/rsvp/dist/rsvp.js:323:19)
    at invokeCallback (/Users/pat/hacking/embroider-addon/node_modules/rsvp/dist/rsvp.js:495:31)
    at /Users/pat/hacking/embroider-addon/node_modules/rsvp/dist/rsvp.js:559:14
    at flush (/Users/pat/hacking/embroider-addon/node_modules/rsvp/dist/rsvp.js:2402:5)
    at process._tickCallback (internal/process/next_tick.js:61:11)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

-~- (end) -~-
  - errorMessage: You specified a `"srcDir": app/styles` which does not exist and did not specify `"allowEmpty": true`.
        at Funnel
-~- created here: -~-
    at Funnel.Plugin (/Users/pat/hacking/embroider-addon/node_modules/broccoli-plugin/index.js:7:31)
    at new Funnel (/Users/pat/hacking/embroider-addon/node_modules/broccoli-funnel/index.js:57:10)
    at V1Addon.buildTreeForStyles (/Users/pat/hacking/embroider-addon/node_modules/@embroider/compat/src/v1-addon.js:432:24)
    at V1Addon.build (/Users/pat/hacking/embroider-addon/node_modules/@embroider/compat/src/v1-addon.js:593:14)
    at V1Addon.<anonymous> (/Users/pat/hacking/embroider-addon/node_modules/typescript-memoize/dist/memoize-decorator.js:67:52)
    at V1Addon.get v2Trees (/Users/pat/hacking/embroider-addon/node_modules/@embroider/compat/src/v1-addon.js:307:30)
    at V1Addon.<anonymous> (/Users/pat/hacking/embroider-addon/node_modules/typescript-memoize/dist/memoize-decorator.js:67:52)
    at V1Addon.get v2Tree [as v2Tree] (/Users/pat/hacking/embroider-addon/node_modules/@embroider/compat/src/v1-addon.js:298:52)
    at oldPackages.map.pkg (/Users/pat/hacking/embroider-addon/node_modules/@embroider/compat/src/build-compat-addon.js:42:48)
    at Array.map (<anonymous>:null:null)
    at buildCompatAddon (/Users/pat/hacking/embroider-addon/node_modules/@embroider/compat/src/build-compat-addon.js:42:33)
    at Object.cachedBuildCompatAddon [as default] (/Users/pat/hacking/embroider-addon/node_modules/@embroider/compat/src/build-compat-addon.js:13:16)
    at CompatAddons.movedAddons.map.oldPkg (/Users/pat/hacking/embroider-addon/node_modules/@embroider/compat/src/compat-addons.js:39:105)
    at Array.map (<anonymous>:null:null)
    at new CompatAddons (/Users/pat/hacking/embroider-addon/node_modules/@embroider/compat/src/compat-addons.js:39:63)
    at Object.defaultPipeline [as compatBuild] (/Users/pat/hacking/embroider-addon/node_modules/@embroider/compat/src/default-pipeline.js:17:18)
    at module.exports (/Users/pat/hacking/embroider-addon/ember-cli-build.js:18:39)
    at Builder.readBuildFile (/Users/pat/hacking/embroider-addon/node_modules/ember-cli/lib/models/builder.js:52:14)
    at Builder.setupBroccoliBuilder (/Users/pat/hacking/embroider-addon/node_modules/ember-cli/lib/models/builder.js:66:22)
    at new Builder (/Users/pat/hacking/embroider-addon/node_modules/ember-cli/lib/models/builder.js:32:10)
    at BuildTask.run (/Users/pat/hacking/embroider-addon/node_modules/ember-cli/lib/tasks/build.js:15:19)
    at Promise.resolve.then (/Users/pat/hacking/embroider-addon/node_modules/ember-cli/lib/models/command.js:243:46)
    at tryCatcher (/Users/pat/hacking/embroider-addon/node_modules/rsvp/dist/rsvp.js:323:19)
    at invokeCallback (/Users/pat/hacking/embroider-addon/node_modules/rsvp/dist/rsvp.js:495:31)
    at /Users/pat/hacking/embroider-addon/node_modules/rsvp/dist/rsvp.js:559:14
    at flush (/Users/pat/hacking/embroider-addon/node_modules/rsvp/dist/rsvp.js:2402:5)
    at process._tickCallback (internal/process/next_tick.js:61:11)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

-~- (end) -~-
        at OneShot
-~- created here: -~-
    at new Plugin (/Users/pat/hacking/embroider-addon/node_modules/broccoli-plugin/index.js:7:31)
    at new OneShot (/Users/pat/hacking/embroider-addon/node_modules/@embroider/compat/src/one-shot.js:14:9)
    at Object.cachedBuildCompatAddon [as default] (/Users/pat/hacking/embroider-addon/node_modules/@embroider/compat/src/build-compat-addon.js:15:16)
    at CompatAddons.movedAddons.map.oldPkg (/Users/pat/hacking/embroider-addon/node_modules/@embroider/compat/src/compat-addons.js:39:105)
    at Array.map (<anonymous>:null:null)
    at new CompatAddons (/Users/pat/hacking/embroider-addon/node_modules/@embroider/compat/src/compat-addons.js:39:63)
    at Object.defaultPipeline [as compatBuild] (/Users/pat/hacking/embroider-addon/node_modules/@embroider/compat/src/default-pipeline.js:17:18)
    at module.exports (/Users/pat/hacking/embroider-addon/ember-cli-build.js:18:39)
    at Builder.readBuildFile (/Users/pat/hacking/embroider-addon/node_modules/ember-cli/lib/models/builder.js:52:14)
    at Builder.setupBroccoliBuilder (/Users/pat/hacking/embroider-addon/node_modules/ember-cli/lib/models/builder.js:66:22)
    at new Builder (/Users/pat/hacking/embroider-addon/node_modules/ember-cli/lib/models/builder.js:32:10)
    at BuildTask.run (/Users/pat/hacking/embroider-addon/node_modules/ember-cli/lib/tasks/build.js:15:19)
    at Promise.resolve.then (/Users/pat/hacking/embroider-addon/node_modules/ember-cli/lib/models/command.js:243:46)
    at tryCatcher (/Users/pat/hacking/embroider-addon/node_modules/rsvp/dist/rsvp.js:323:19)
    at invokeCallback (/Users/pat/hacking/embroider-addon/node_modules/rsvp/dist/rsvp.js:495:31)
    at /Users/pat/hacking/embroider-addon/node_modules/rsvp/dist/rsvp.js:559:14
    at flush (/Users/pat/hacking/embroider-addon/node_modules/rsvp/dist/rsvp.js:2402:5)
    at process._tickCallback (internal/process/next_tick.js:61:11)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

-~- (end) -~-
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
    - treeDir: [undefined]
  - message: You specified a `"srcDir": app/styles` which does not exist and did not specify `"allowEmpty": true`.
        at Funnel
-~- created here: -~-
    at Funnel.Plugin (/Users/pat/hacking/embroider-addon/node_modules/broccoli-plugin/index.js:7:31)
    at new Funnel (/Users/pat/hacking/embroider-addon/node_modules/broccoli-funnel/index.js:57:10)
    at V1Addon.buildTreeForStyles (/Users/pat/hacking/embroider-addon/node_modules/@embroider/compat/src/v1-addon.js:432:24)
    at V1Addon.build (/Users/pat/hacking/embroider-addon/node_modules/@embroider/compat/src/v1-addon.js:593:14)
    at V1Addon.<anonymous> (/Users/pat/hacking/embroider-addon/node_modules/typescript-memoize/dist/memoize-decorator.js:67:52)
    at V1Addon.get v2Trees (/Users/pat/hacking/embroider-addon/node_modules/@embroider/compat/src/v1-addon.js:307:30)
    at V1Addon.<anonymous> (/Users/pat/hacking/embroider-addon/node_modules/typescript-memoize/dist/memoize-decorator.js:67:52)
    at V1Addon.get v2Tree [as v2Tree] (/Users/pat/hacking/embroider-addon/node_modules/@embroider/compat/src/v1-addon.js:298:52)
    at oldPackages.map.pkg (/Users/pat/hacking/embroider-addon/node_modules/@embroider/compat/src/build-compat-addon.js:42:48)
    at Array.map (<anonymous>:null:null)
    at buildCompatAddon (/Users/pat/hacking/embroider-addon/node_modules/@embroider/compat/src/build-compat-addon.js:42:33)
    at Object.cachedBuildCompatAddon [as default] (/Users/pat/hacking/embroider-addon/node_modules/@embroider/compat/src/build-compat-addon.js:13:16)
    at CompatAddons.movedAddons.map.oldPkg (/Users/pat/hacking/embroider-addon/node_modules/@embroider/compat/src/compat-addons.js:39:105)
    at Array.map (<anonymous>:null:null)
    at new CompatAddons (/Users/pat/hacking/embroider-addon/node_modules/@embroider/compat/src/compat-addons.js:39:63)
    at Object.defaultPipeline [as compatBuild] (/Users/pat/hacking/embroider-addon/node_modules/@embroider/compat/src/default-pipeline.js:17:18)
    at module.exports (/Users/pat/hacking/embroider-addon/ember-cli-build.js:18:39)
    at Builder.readBuildFile (/Users/pat/hacking/embroider-addon/node_modules/ember-cli/lib/models/builder.js:52:14)
    at Builder.setupBroccoliBuilder (/Users/pat/hacking/embroider-addon/node_modules/ember-cli/lib/models/builder.js:66:22)
    at new Builder (/Users/pat/hacking/embroider-addon/node_modules/ember-cli/lib/models/builder.js:32:10)
    at BuildTask.run (/Users/pat/hacking/embroider-addon/node_modules/ember-cli/lib/tasks/build.js:15:19)
    at Promise.resolve.then (/Users/pat/hacking/embroider-addon/node_modules/ember-cli/lib/models/command.js:243:46)
    at tryCatcher (/Users/pat/hacking/embroider-addon/node_modules/rsvp/dist/rsvp.js:323:19)
    at invokeCallback (/Users/pat/hacking/embroider-addon/node_modules/rsvp/dist/rsvp.js:495:31)
    at /Users/pat/hacking/embroider-addon/node_modules/rsvp/dist/rsvp.js:559:14
    at flush (/Users/pat/hacking/embroider-addon/node_modules/rsvp/dist/rsvp.js:2402:5)
    at process._tickCallback (internal/process/next_tick.js:61:11)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

-~- (end) -~-
        at OneShot
-~- created here: -~-
    at new Plugin (/Users/pat/hacking/embroider-addon/node_modules/broccoli-plugin/index.js:7:31)
    at new OneShot (/Users/pat/hacking/embroider-addon/node_modules/@embroider/compat/src/one-shot.js:14:9)
    at Object.cachedBuildCompatAddon [as default] (/Users/pat/hacking/embroider-addon/node_modules/@embroider/compat/src/build-compat-addon.js:15:16)
    at CompatAddons.movedAddons.map.oldPkg (/Users/pat/hacking/embroider-addon/node_modules/@embroider/compat/src/compat-addons.js:39:105)
    at Array.map (<anonymous>:null:null)
    at new CompatAddons (/Users/pat/hacking/embroider-addon/node_modules/@embroider/compat/src/compat-addons.js:39:63)
    at Object.defaultPipeline [as compatBuild] (/Users/pat/hacking/embroider-addon/node_modules/@embroider/compat/src/default-pipeline.js:17:18)
    at module.exports (/Users/pat/hacking/embroider-addon/ember-cli-build.js:18:39)
    at Builder.readBuildFile (/Users/pat/hacking/embroider-addon/node_modules/ember-cli/lib/models/builder.js:52:14)
    at Builder.setupBroccoliBuilder (/Users/pat/hacking/embroider-addon/node_modules/ember-cli/lib/models/builder.js:66:22)
    at new Builder (/Users/pat/hacking/embroider-addon/node_modules/ember-cli/lib/models/builder.js:32:10)
    at BuildTask.run (/Users/pat/hacking/embroider-addon/node_modules/ember-cli/lib/tasks/build.js:15:19)
    at Promise.resolve.then (/Users/pat/hacking/embroider-addon/node_modules/ember-cli/lib/models/command.js:243:46)
    at tryCatcher (/Users/pat/hacking/embroider-addon/node_modules/rsvp/dist/rsvp.js:323:19)
    at invokeCallback (/Users/pat/hacking/embroider-addon/node_modules/rsvp/dist/rsvp.js:495:31)
    at /Users/pat/hacking/embroider-addon/node_modules/rsvp/dist/rsvp.js:559:14
    at flush (/Users/pat/hacking/embroider-addon/node_modules/rsvp/dist/rsvp.js:2402:5)
    at process._tickCallback (internal/process/next_tick.js:61:11)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

-~- (end) -~-
  - name: BuildError
  - nodeAnnotation: [undefined]
  - nodeName: OneShot
  - originalErrorMessage: You specified a `"srcDir": app/styles` which does not exist and did not specify `"allowEmpty": true`.
        at Funnel
-~- created here: -~-
    at Funnel.Plugin (/Users/pat/hacking/embroider-addon/node_modules/broccoli-plugin/index.js:7:31)
    at new Funnel (/Users/pat/hacking/embroider-addon/node_modules/broccoli-funnel/index.js:57:10)
    at V1Addon.buildTreeForStyles (/Users/pat/hacking/embroider-addon/node_modules/@embroider/compat/src/v1-addon.js:432:24)
    at V1Addon.build (/Users/pat/hacking/embroider-addon/node_modules/@embroider/compat/src/v1-addon.js:593:14)
    at V1Addon.<anonymous> (/Users/pat/hacking/embroider-addon/node_modules/typescript-memoize/dist/memoize-decorator.js:67:52)
    at V1Addon.get v2Trees (/Users/pat/hacking/embroider-addon/node_modules/@embroider/compat/src/v1-addon.js:307:30)
    at V1Addon.<anonymous> (/Users/pat/hacking/embroider-addon/node_modules/typescript-memoize/dist/memoize-decorator.js:67:52)
    at V1Addon.get v2Tree [as v2Tree] (/Users/pat/hacking/embroider-addon/node_modules/@embroider/compat/src/v1-addon.js:298:52)
    at oldPackages.map.pkg (/Users/pat/hacking/embroider-addon/node_modules/@embroider/compat/src/build-compat-addon.js:42:48)
    at Array.map (<anonymous>:null:null)
    at buildCompatAddon (/Users/pat/hacking/embroider-addon/node_modules/@embroider/compat/src/build-compat-addon.js:42:33)
    at Object.cachedBuildCompatAddon [as default] (/Users/pat/hacking/embroider-addon/node_modules/@embroider/compat/src/build-compat-addon.js:13:16)
    at CompatAddons.movedAddons.map.oldPkg (/Users/pat/hacking/embroider-addon/node_modules/@embroider/compat/src/compat-addons.js:39:105)
    at Array.map (<anonymous>:null:null)
    at new CompatAddons (/Users/pat/hacking/embroider-addon/node_modules/@embroider/compat/src/compat-addons.js:39:63)
    at Object.defaultPipeline [as compatBuild] (/Users/pat/hacking/embroider-addon/node_modules/@embroider/compat/src/default-pipeline.js:17:18)
    at module.exports (/Users/pat/hacking/embroider-addon/ember-cli-build.js:18:39)
    at Builder.readBuildFile (/Users/pat/hacking/embroider-addon/node_modules/ember-cli/lib/models/builder.js:52:14)
    at Builder.setupBroccoliBuilder (/Users/pat/hacking/embroider-addon/node_modules/ember-cli/lib/models/builder.js:66:22)
    at new Builder (/Users/pat/hacking/embroider-addon/node_modules/ember-cli/lib/models/builder.js:32:10)
    at BuildTask.run (/Users/pat/hacking/embroider-addon/node_modules/ember-cli/lib/tasks/build.js:15:19)
    at Promise.resolve.then (/Users/pat/hacking/embroider-addon/node_modules/ember-cli/lib/models/command.js:243:46)
    at tryCatcher (/Users/pat/hacking/embroider-addon/node_modules/rsvp/dist/rsvp.js:323:19)
    at invokeCallback (/Users/pat/hacking/embroider-addon/node_modules/rsvp/dist/rsvp.js:495:31)
    at /Users/pat/hacking/embroider-addon/node_modules/rsvp/dist/rsvp.js:559:14
    at flush (/Users/pat/hacking/embroider-addon/node_modules/rsvp/dist/rsvp.js:2402:5)
    at process._tickCallback (internal/process/next_tick.js:61:11)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

-~- (end) -~-
  - stack: Error: You specified a `"srcDir": app/styles` which does not exist and did not specify `"allowEmpty": true`.
    at Funnel.build (/Users/pat/hacking/embroider-addon/node_modules/broccoli-funnel/index.js:252:15)
    at resolve (/Users/pat/hacking/embroider-addon/node_modules/broccoli/lib/wrappers/transform-node.js:29:35)
    at new Promise (<anonymous>:null:null)
    at TransformNodeWrapper.build (/Users/pat/hacking/embroider-addon/node_modules/broccoli/lib/wrappers/transform-node.js:21:12)
    at Promise.resolve.then.then.then (/Users/pat/hacking/embroider-addon/node_modules/broccoli/lib/builder.js:116:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)


=================================================================================

```

**Comment by sdhull** [comment]
I get this same error in my app when trying out embroider in my app... I assume _some_ addon is to blame but no idea which one it is or how to find out which one it is.

**Comment by mistahenry** [comment]
I am also encountering the same error in my setup. 

```
ember-cli: 3.8.1
node: 8.15.0
os: darwin x64
```

When I investigate the offending line in `buildTreeForStyles` in my own project,

```
tree = this.invokeOriginalTreeFor('styles');
if (tree) {
    console.log(this.name);
    tree = new Funnel(tree, {
      srcDir: 'app/styles',
      destDir: '_app_styles_',
    });
}
```

the following addons are entering this code block. 

```
ember-cli-bootstrap-4
ember-paper
```

I want to look a little further into those addons when I have a little more time but thought I'd pass on the info here.

**Comment by sdhull** [comment]
@mistahenry that's helpful. We have bootstrap but not paper in our app

**Comment by sdhull** [comment]
I'm not sure if it would be embroider or broccoli, but it seems like it would be useful to emit the addon name when raising the error.

Another thought is: maybe it would be cool to be able to circumvent this exception by defaulting `allowEmpty` to true? Unsure whether or not that's feasible

**Comment by efx** [comment]
@sdhull @mistahenry could you open separate issues with minimal reproduction examples? 
@patocallaghan I am seeing that error following those steps but step 3 needs to be `yarn add -D ember-cli-addon-docs` otherwise embroider exits early since it validates where the dependency was added in your package.json.

**Comment by btecu** [comment]
I'm also running into this and it appears to be caused by `ember-bootstrap`.

**Comment by Mike-Neto** [comment]
I was able to repro it using only `ember-cli-bulma`

Repro script from an empty ubuntu container:
```
docker run -it ubuntu

# inside docker container or any debian machine
cd && apt update
# setup apt packages
apt install curl --assume-yes # 1MB download

# setup node
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
nvm install --lts

# setup ember dummy app
npm i -g npm
npm i -g ember-cli
ember -v && ember new dummy && cd dummy && ember build

# Update to use embroider
npm i --save-dev @embroider/core @embroider/compat @embroider/webpack
sed -i '/return app.toTree();/c\  const { Webpack } = require("@embroider/webpack");\n  return require("@embroider/compat").compatBuild(app, Webpack);' ./ember-cli-build.js
cat ember-cli-build.js && ember build

# Install a new addon & make it break
npm i --save-dev bulma ember-bulma-css && ember build # build should break now.
```

**Comment by btecu** [comment]
Has anyone figured out a solution to this issue? I'd like to get `embroider` on a few projects but all of them are using `ember-bootstrap` and I'm getting:
```You specified a `"srcDir": app/styles` which does not exist and did not specify `"allowEmpty": true`.```

cc @ef4 @stefanpenner

**Comment by simonihmig** [comment]
I played with this, trying to fix at least the ember-bootstrap related issue. My findings:
* First of all here is a reproduction repo of the failing build for ember-bootstrap: https://github.com/simonihmig/e-b-embroider. 
* as @mistahenry pointed out, the build fails at the created `Funnel` in `buildTreeForStyles()`. More specifically it fails because of this line: https://github.com/embroider-build/embroider/blob/7621fa256065e07a836aceb031857d398983eabc/packages/compat/src/v1-addon.ts#L492
* what puzzled me is that the comment above ( `the user's tree returns their own styles with no "app/styles" wrapping`) actually seems to contradict the following code AFAICT, as the `srcDir` option assumes this path *is* part of the source tree ( [`A string representing the portion of the input node to start the funneling from`](https://github.com/broccolijs/broccoli-funnel#options))
* removing that line makes the build error go away, and all the addon provided styles (scss files) are available, and the Sass imports for this work just fine! 
* so as removing that line *seems*  to fix the issue, I created this PR: #340. But please double check this is really correct!

Maybe others here could try to confirm this works for them too? As embroider is a monorepo, and also needs a compile step, it's probably easiest to just find the file in `node_modules/@embroider/compat/src/v1-addon.js` and patch it in-place.

**Comment by simonihmig** [comment]
Ok, seems I have to revoke some of this, as the "fix" solves the problem for ember-bootstrap, but creates a new one for ember-paper (which the failing test in my PR is based on). The difference between those addons apparently is that I don't properly call the super method here: https://github.com/kaliber5/ember-bootstrap/blob/master/index.js#L185-L191, while ember-paper does: https://github.com/miguelcobain/ember-paper/blob/master/index.js#L536. And that one is wrapping the tree in the expected `app/styles` folder: https://github.com/ember-cli/ember-cli/blob/master/lib/models/addon.js#L964-L967

And indeed I could confirm that adding that super call fixes the problem, without any changes in embroider!

*However* as this somehow worked in the legacy build system, and other addons in the wild didn't care to call super as well (even @ef4's own `ember-sass-bootstrap`: https://github.com/ef4/ember-sass-bootstrap/blob/master/index.js#L12 😉), I think we should try to support both cases here! My understanding would be to always return a styles tree from `buildTreeForStyles()` that has no `app/styles` wrapper, either because it didn't have one in the first place coming from the addon (current ember-bootstrap), or we strip it *if* it has one (ember-paper). Is that right? If so, I could try to come up with an updated PR...

**Comment by simonihmig** [comment]
2nd attempt: https://github.com/embroider-build/embroider/pull/341
