### ISSUE TITLE
`Module not found: Error: bug: embroider resolver's meta is not propagating`

### ISSUE THREAD

**Issue by gossi** [embroider-build/embroider#1752]
I'm running into this error:

```
Module not found: Error: bug: embroider resolver's meta is not propagating
```

The main idea was to use `webpack.resolve.alias` to point to code that I moved somewhere else.

Repro: 

- Branch: https://github.com/gossi/unidancing/tree/re-architecture
- Commit: https://github.com/gossi/unidancing/tree/d28a643e21289054699ca8f8f25f38fa4c30c2fb

After checkout:

```
pnpm install
cd web/
pnpm test:prebuild
pnpm start
```

POI in the code:

- The main folder is `web/app/domain/` where I moved my code into
- The webpack config found in `web/ember-cli-build.js` for the alias
- The ts config: `web/tsconfig.ts` with its `paths` which made it possible at first at least in the editor

I traced it here: https://github.com/embroider-build/embroider/blob/289f83d80d133da3de2b342e63f937986248c07d/packages/core/src/module-resolver.ts#L1058-L1065

And with a bit more debug, I figured it was coming from this file: `web/app/domain/supporting/tina/index.ts`, which when renamed into `index.gts` it worked.

Which is weird, because on `node_modules/.embroider/rewritten-app` I can see, the `gts` files are already correctly transpiled to `.ts` (using `template()` from `@ember/template-compiler`).

**Comment by gossi** [comment]
Oh, renaming `ts` files that re-export `gts` files to `gts`, aka `index.ts` -> `index.gts`. Then I run into very unreliable errors:

Opening the browser at `localhost:4200`, this is what I see:

```
Error: Could not find module `@unidancing/home` imported from `(require)`
    at missingModule (/var/folders/95/bfjp2z0x5l57lzbp6c047rxw0000gn/T/broccoli-53051GagfUkX2RGFf/out-591-packager_runner_embroider_webpack/rewritten-packages/@embroider/synthesized-vendor/vendor/loader/loader.js:247:1)
    at findModule (/var/folders/95/bfjp2z0x5l57lzbp6c047rxw0000gn/T/broccoli-53051GagfUkX2RGFf/out-591-packager_runner_embroider_webpack/rewritten-packages/@embroider/synthesized-vendor/vendor/loader/loader.js:258:1)
    at require (/var/folders/95/bfjp2z0x5l57lzbp6c047rxw0000gn/T/broccoli-53051GagfUkX2RGFf/out-591-packager_runner_embroider_webpack/rewritten-packages/@embroider/synthesized-vendor/vendor/loader/loader.js:24:1)
    at Object.../../../../node_modules/.pnpm/@embroider+babel-loader-9@3.1.1_@embroider+core@3.4.3_supports-color@8.1.1_webpack@5.89.0/node_modules/@embroider/babel-loader-9/index.js?{"variant":{"name":"dev","runtime":"all","optimizeForProduction":false},"appBabelConfigPath":"/Users/thomas/code/gossi/unidancing/web/node_modules/.embroider/rewritten-app/_babel_config_.js","cacheDirectory":"/private/var/folders/95/bfjp2z0x5l57lzbp6c047rxw0000gn/T/embroider/webpack-babel-loader"}!../../../../node_modules/.pnpm/@embroider+webpack@3.2.1_@embroider+core@3.4.3_webpack@5.89.0/node_modules/@embroider/webpack/src/virtual-loader.js?f=%2F%40embroider%2Fext-cjs%2F%40unidancing%2Fhome&a=%2FUsers%2Fthomas%2Fcode%2Fgossi%2Funidancing%2Fweb! (/var/folders/95/bfjp2z0x5l57lzbp6c047rxw0000gn/T/broccoli-53051GagfUkX2RGFf/out-591-packager_runner_embroider_webpack/assets/@embroider/ext-cjs/@unidancing/home:2:18)
    at __webpack_require__ (/var/folders/95/bfjp2z0x5l57lzbp6c047rxw0000gn/T/broccoli-53051GagfUkX2RGFf/out-591-packager_runner_embroider_webpack/assets/webpack:/@unidancing/app/webpack/bootstrap:19:1)
    at Module../routes/index.ts (/var/folders/95/bfjp2z0x5l57lzbp6c047rxw0000gn/T/broccoli-53051GagfUkX2RGFf/out-591-packager_runner_embroider_webpack/assets/chunk.196c7bb30a2f0fba6530.js:23791:74)
    at require (/var/folders/95/bfjp2z0x5l57lzbp6c047rxw0000gn/T/broccoli-53051GagfUkX2RGFf/out-591-packager_runner_embroider_webpack/assets/webpack:/@unidancing/app/webpack/bootstrap:19:1)
    at Module.callback (/var/folders/95/bfjp2z0x5l57lzbp6c047rxw0000gn/T/broccoli-53051GagfUkX2RGFf/out-591-packager_runner_embroider_webpack/assets/webpack:/@unidancing/app/assets/@unidancing/app.js:147:47)
    at Module.exports (/var/folders/95/bfjp2z0x5l57lzbp6c047rxw0000gn/T/broccoli-53051GagfUkX2RGFf/out-591-packager_runner_embroider_webpack/rewritten-packages/@embroider/synthesized-vendor/vendor/loader/loader.js:106:1)
    at require (/var/folders/95/bfjp2z0x5l57lzbp6c047rxw0000gn/T/broccoli-53051GagfUkX2RGFf/out-591-packager_runner_embroider_webpack/rewritten-packages/@embroider/synthesized-vendor/vendor/loader/loader.js:27:1)
    at ModuleRegistry.get (/var/folders/95/bfjp2z0x5l57lzbp6c047rxw0000gn/T/broccoli-53051GagfUkX2RGFf/out-591-packager_runner_embroider_webpack/assets/webpack:/@unidancing/rewritten-packages/ember-resolver.c9bce00a/node_modules/ember-resolver/index.js:25:12)
    at Resolver._extractDefaultExport (/var/folders/95/bfjp2z0x5l57lzbp6c047rxw0000gn/T/broccoli-53051GagfUkX2RGFf/out-591-packager_runner_embroider_webpack/assets/webpack:/@unidancing/rewritten-packages/ember-resolver.c9bce00a/node_modules/ember-resolver/index.js:534:39)
    at Resolver.resolveOther (/var/folders/95/bfjp2z0x5l57lzbp6c047rxw0000gn/T/broccoli-53051GagfUkX2RGFf/out-591-packager_runner_embroider_webpack/assets/webpack:/@unidancing/rewritten-packages/ember-resolver.c9bce00a/node_modules/ember-resolver/index.js:163:32)
    at Resolver.resolve (/var/folders/95/bfjp2z0x5l57lzbp6c047rxw0000gn/T/broccoli-53051GagfUkX2RGFf/out-591-packager_runner_embroider_webpack/assets/webpack:/@unidancing/rewritten-packages/ember-resolver.c9bce00a/node_modules/ember-resolver/index.js:199:23)
    at resolve (/var/folders/95/bfjp2z0x5l57lzbp6c047rxw0000gn/T/broccoli-53051GagfUkX2RGFf/out-591-packager_runner_embroider_webpack/assets/@ember/-internals/container/index.js:726:1)
    at Registry.resolve (/var/folders/95/bfjp2z0x5l57lzbp6c047rxw0000gn/T/broccoli-53051GagfUkX2RGFf/out-591-packager_runner_embroider_webpack/assets/@ember/-internals/container/index.js:507:1)
    at Registry.resolve (/var/folders/95/bfjp2z0x5l57lzbp6c047rxw0000gn/T/broccoli-53051GagfUkX2RGFf/out-591-packager_runner_embroider_webpack/assets/@ember/-internals/container/index.js:509:1)
    at factoryFor (/var/folders/95/bfjp2z0x5l57lzbp6c047rxw0000gn/T/broccoli-53051GagfUkX2RGFf/out-591-packager_runner_embroider_webpack/assets/@ember/-internals/container/index.js:231:1)
    at instantiateFactory (/var/folders/95/bfjp2z0x5l57lzbp6c047rxw0000gn/T/broccoli-53051GagfUkX2RGFf/out-591-packager_runner_embroider_webpack/assets/@ember/-internals/container/index.js:270:1)
    at lookup (/var/folders/95/bfjp2z0x5l57lzbp6c047rxw0000gn/T/broccoli-53051GagfUkX2RGFf/out-591-packager_runner_embroider_webpack/assets/@ember/-internals/container/index.js:224:1)
    at Container.lookup (/var/folders/95/bfjp2z0x5l57lzbp6c047rxw0000gn/T/broccoli-53051GagfUkX2RGFf/out-591-packager_runner_embroider_webpack/assets/@ember/-internals/container/index.js:122:1)
    at ApplicationInstance.lookup (/var/folders/95/bfjp2z0x5l57lzbp6c047rxw0000gn/T/broccoli-53051GagfUkX2RGFf/out-591-packager_runner_embroider_webpack/assets/@ember/-internals/runtime/lib/mixins/container_proxy.js:19:1)
    at PrivateRouter.original (/var/folders/95/bfjp2z0x5l57lzbp6c047rxw0000gn/T/broccoli-53051GagfUkX2RGFf/out-591-packager_runner_embroider_webpack/assets/@ember/routing/router.js:183:1)
    at PrivateRouter.getRoute (/var/folders/95/bfjp2z0x5l57lzbp6c047rxw0000gn/T/broccoli-53051GagfUkX2RGFf/out-591-packager_runner_embroider_webpack/assets/webpack:/@unidancing/src/index.ts:80:18)
    at UnresolvedRouteInfoByParam.fetchRoute (/var/folders/95/bfjp2z0x5l57lzbp6c047rxw0000gn/T/broccoli-53051GagfUkX2RGFf/out-591-packager_runner_embroider_webpack/assets/router_js.js:714:1)
    at UnresolvedRouteInfoByParam.get route [as route] (/var/folders/95/bfjp2z0x5l57lzbp6c047rxw0000gn/T/broccoli-53051GagfUkX2RGFf/out-591-packager_runner_embroider_webpack/assets/router_js.js:648:1)
    at URLTransitionIntent.applyToState (/var/folders/95/bfjp2z0x5l57lzbp6c047rxw0000gn/T/broccoli-53051GagfUkX2RGFf/out-591-packager_runner_embroider_webpack/assets/router_js.js:1151:1)
    at PrivateRouter.getTransitionByIntent (/var/folders/95/bfjp2z0x5l57lzbp6c047rxw0000gn/T/broccoli-53051GagfUkX2RGFf/out-591-packager_runner_embroider_webpack/assets/router_js.js:1276:1)
    at PrivateRouter.transitionByIntent (/var/folders/95/bfjp2z0x5l57lzbp6c047rxw0000gn/T/broccoli-53051GagfUkX2RGFf/out-591-packager_runner_embroider_webpack/assets/router_js.js:1239:1)
    at PrivateRouter.doTransition (/var/folders/95/bfjp2z0x5l57lzbp6c047rxw0000gn/T/broccoli-53051GagfUkX2RGFf/out-591-packager_runner_embroider_webpack/assets/router_js.js:1357:1)
    at PrivateRouter.handleURL (/var/folders/95/bfjp2z0x5l57lzbp6c047rxw0000gn/T/broccoli-53051GagfUkX2RGFf/out-591-packager_runner_embroider_webpack/assets/router_js.js:1748:1)
    at Router._doURLTransition (/var/folders/95/bfjp2z0x5l57lzbp6c047rxw0000gn/T/broccoli-53051GagfUkX2RGFf/out-591-packager_runner_embroider_webpack/assets/@ember/routing/router.js:471:1)
    at Router.handleURL (/var/folders/95/bfjp2z0x5l57lzbp6c047rxw0000gn/T/broccoli-53051GagfUkX2RGFf/out-591-packager_runner_embroider_webpack/assets/@ember/routing/router.js:467:1)
    at ApplicationInstance.visit (/var/folders/95/bfjp2z0x5l57lzbp6c047rxw0000gn/T/broccoli-53051GagfUkX2RGFf/out-591-packager_runner_embroider_webpack/assets/@ember/application/instance.js:215:1)
    at EmberApp._visit (/Users/thomas/code/gossi/unidancing/node_modules/.pnpm/fastboot@4.1.2/node_modules/fastboot/src/ember-app.js:269:20)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at EmberApp.visit (/Users/thomas/code/gossi/unidancing/node_modules/.pnpm/fastboot@4.1.2/node_modules/fastboot/src/ember-app.js:329:7)
    at FastBoot.visit (/Users/thomas/code/gossi/unidancing/node_modules/.pnpm/fastboot@4.1.2/node_modules/fastboot/src/index.js:86:18)
    at /Users/thomas/code/gossi/unidancing/node_modules/.pnpm/fastboot-express-middleware@4.1.2/node_modules/fastboot-express-middleware/src/index.js:33:20
```

Once I hit refresh in the browser, this is what I see from then onwards:

```
TypeError: Cannot read properties of undefined (reading 'HomeRoute')
    at Module.default (/var/folders/95/bfjp2z0x5l57lzbp6c047rxw0000gn/T/broccoli-53051GagfUkX2RGFf/out-591-packager_runner_embroider_webpack/assets/chunk.196c7bb30a2f0fba6530.js:23789:108)
    at Resolver._extractDefaultExport (/var/folders/95/bfjp2z0x5l57lzbp6c047rxw0000gn/T/broccoli-53051GagfUkX2RGFf/out-591-packager_runner_embroider_webpack/assets/webpack:/@unidancing/rewritten-packages/ember-resolver.c9bce00a/node_modules/ember-resolver/index.js:541:25)
    at Resolver.resolveOther (/var/folders/95/bfjp2z0x5l57lzbp6c047rxw0000gn/T/broccoli-53051GagfUkX2RGFf/out-591-packager_runner_embroider_webpack/assets/webpack:/@unidancing/rewritten-packages/ember-resolver.c9bce00a/node_modules/ember-resolver/index.js:163:32)
    at Resolver.resolve (/var/folders/95/bfjp2z0x5l57lzbp6c047rxw0000gn/T/broccoli-53051GagfUkX2RGFf/out-591-packager_runner_embroider_webpack/assets/webpack:/@unidancing/rewritten-packages/ember-resolver.c9bce00a/node_modules/ember-resolver/index.js:199:23)
    at resolve (/var/folders/95/bfjp2z0x5l57lzbp6c047rxw0000gn/T/broccoli-53051GagfUkX2RGFf/out-591-packager_runner_embroider_webpack/assets/@ember/-internals/container/index.js:726:1)
    at Registry.resolve (/var/folders/95/bfjp2z0x5l57lzbp6c047rxw0000gn/T/broccoli-53051GagfUkX2RGFf/out-591-packager_runner_embroider_webpack/assets/@ember/-internals/container/index.js:507:1)
    at Registry.resolve (/var/folders/95/bfjp2z0x5l57lzbp6c047rxw0000gn/T/broccoli-53051GagfUkX2RGFf/out-591-packager_runner_embroider_webpack/assets/@ember/-internals/container/index.js:509:1)
    at factoryFor (/var/folders/95/bfjp2z0x5l57lzbp6c047rxw0000gn/T/broccoli-53051GagfUkX2RGFf/out-591-packager_runner_embroider_webpack/assets/@ember/-internals/container/index.js:231:1)
    at instantiateFactory (/var/folders/95/bfjp2z0x5l57lzbp6c047rxw0000gn/T/broccoli-53051GagfUkX2RGFf/out-591-packager_runner_embroider_webpack/assets/@ember/-internals/container/index.js:270:1)
    at lookup (/var/folders/95/bfjp2z0x5l57lzbp6c047rxw0000gn/T/broccoli-53051GagfUkX2RGFf/out-591-packager_runner_embroider_webpack/assets/@ember/-internals/container/index.js:224:1)
    at Container.lookup (/var/folders/95/bfjp2z0x5l57lzbp6c047rxw0000gn/T/broccoli-53051GagfUkX2RGFf/out-591-packager_runner_embroider_webpack/assets/@ember/-internals/container/index.js:122:1)
    at ApplicationInstance.lookup (/var/folders/95/bfjp2z0x5l57lzbp6c047rxw0000gn/T/broccoli-53051GagfUkX2RGFf/out-591-packager_runner_embroider_webpack/assets/@ember/-internals/runtime/lib/mixins/container_proxy.js:19:1)
    at PrivateRouter.original (/var/folders/95/bfjp2z0x5l57lzbp6c047rxw0000gn/T/broccoli-53051GagfUkX2RGFf/out-591-packager_runner_embroider_webpack/assets/@ember/routing/router.js:183:1)
    at PrivateRouter.getRoute (/var/folders/95/bfjp2z0x5l57lzbp6c047rxw0000gn/T/broccoli-53051GagfUkX2RGFf/out-591-packager_runner_embroider_webpack/assets/webpack:/@unidancing/src/index.ts:80:18)
    at UnresolvedRouteInfoByParam.fetchRoute (/var/folders/95/bfjp2z0x5l57lzbp6c047rxw0000gn/T/broccoli-53051GagfUkX2RGFf/out-591-packager_runner_embroider_webpack/assets/router_js.js:714:1)
    at UnresolvedRouteInfoByParam.get route [as route] (/var/folders/95/bfjp2z0x5l57lzbp6c047rxw0000gn/T/broccoli-53051GagfUkX2RGFf/out-591-packager_runner_embroider_webpack/assets/router_js.js:648:1)
    at URLTransitionIntent.applyToState (/var/folders/95/bfjp2z0x5l57lzbp6c047rxw0000gn/T/broccoli-53051GagfUkX2RGFf/out-591-packager_runner_embroider_webpack/assets/router_js.js:1151:1)
    at PrivateRouter.getTransitionByIntent (/var/folders/95/bfjp2z0x5l57lzbp6c047rxw0000gn/T/broccoli-53051GagfUkX2RGFf/out-591-packager_runner_embroider_webpack/assets/router_js.js:1276:1)
    at PrivateRouter.transitionByIntent (/var/folders/95/bfjp2z0x5l57lzbp6c047rxw0000gn/T/broccoli-53051GagfUkX2RGFf/out-591-packager_runner_embroider_webpack/assets/router_js.js:1239:1)
    at PrivateRouter.doTransition (/var/folders/95/bfjp2z0x5l57lzbp6c047rxw0000gn/T/broccoli-53051GagfUkX2RGFf/out-591-packager_runner_embroider_webpack/assets/router_js.js:1357:1)
    at PrivateRouter.handleURL (/var/folders/95/bfjp2z0x5l57lzbp6c047rxw0000gn/T/broccoli-53051GagfUkX2RGFf/out-591-packager_runner_embroider_webpack/assets/router_js.js:1748:1)
    at Router._doURLTransition (/var/folders/95/bfjp2z0x5l57lzbp6c047rxw0000gn/T/broccoli-53051GagfUkX2RGFf/out-591-packager_runner_embroider_webpack/assets/@ember/routing/router.js:471:1)
    at Router.handleURL (/var/folders/95/bfjp2z0x5l57lzbp6c047rxw0000gn/T/broccoli-53051GagfUkX2RGFf/out-591-packager_runner_embroider_webpack/assets/@ember/routing/router.js:467:1)
    at ApplicationInstance.visit (/var/folders/95/bfjp2z0x5l57lzbp6c047rxw0000gn/T/broccoli-53051GagfUkX2RGFf/out-591-packager_runner_embroider_webpack/assets/@ember/application/instance.js:215:1)
    at EmberApp._visit (/Users/thomas/code/gossi/unidancing/node_modules/.pnpm/fastboot@4.1.2/node_modules/fastboot/src/ember-app.js:269:20)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at EmberApp.visit (/Users/thomas/code/gossi/unidancing/node_modules/.pnpm/fastboot@4.1.2/node_modules/fastboot/src/ember-app.js:329:7)
    at FastBoot.visit (/Users/thomas/code/gossi/unidancing/node_modules/.pnpm/fastboot@4.1.2/node_modules/fastboot/src/index.js:86:18)
    at /Users/thomas/code/gossi/unidancing/node_modules/.pnpm/fastboot-express-middleware@4.1.2/node_modules/fastboot-express-middleware/src/index.js:33:20
```

So, the first error is only visible "once"/after the first run. Hmm 🤔
