### ISSUE TITLE
Libraries cannot import virtrual files generated from unplugin

### ISSUE THREAD

**Issue by NullVoxPopuli** [embroider-build/embroider#1814]
It's possible I'll solve this myself and close the issue, as I think I already know what the problem is.

Getting this error:
```
Module not found: Error: @universal-ember/kolay-ui is trying to import from virtual:kolay but that is not one of its explicit dependencies
```

<details<summary>error coming from embroider</summary>
```
 104   │   - broccoliBuilderErrorStack: ModuleNotFoundError: Module not found: Error: @universal-ember/kolay-ui is trying to import from virtual:kolay but that is not one of its explicit dependencies
 105   │     at <.pnpm>/webpack@5.90.3/node_modules/webpack/lib/Compilation.js:2029:28
 106   │     at <.pnpm>/webpack@5.90.3/node_modules/webpack/lib/NormalModuleFactory.js:895:13
 107   │     at eval (eval at create (<.pnpm>/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
 108   │     at <.pnpm>/webpack@5.90.3/node_modules/webpack/lib/NormalModuleFactory.js:332:22
 109   │     at eval (eval at create (<.pnpm>/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
 110   │     at <.pnpm>/@embroider+webpack@3.2.2-unstable.12a42ca_@embroider+core@3.4.4-unstable.12a42ca_webpack@5.90.3/node_modules/@embroider/webpack/src/we
       │ bpack-resolver-plugin.js:58:27

```

</details>

from this code:
```js
    let { loadApiDocs } = await import('virtual:kolay/api-docs');
```
_which_ is within `@universal-ember/kolay-ui`'s code, and there is no package named `virtual:kolay`

This is my unplugin, 
```js
import { stripIndent } from 'common-tags';
import { createUnplugin } from 'unplugin';

import { generateTypeDocJSON } from './typedoc.js';

const SECRET_INTERNAL_IMPORT = `virtual:kolay/api-docs`;
const MORE_INTERNAL = `\0${SECRET_INTERNAL_IMPORT}`;

export const apiDocs = createUnplugin(
  (options) => {
    const name = 'kolay::api-docs';

    function getDest(pkgName) {
      return `${options.dest ?? 'docs'}/${pkgName}.json`;
    }

    return {
      name,
      async buildEnd() {
        await Promise.all(
          options.packages.map(async (pkgName) => {
            let data = await generateTypeDocJSON({ packageName: pkgName });

            if (data) {
              let dest = getDest(pkgName);

              this.emitFile({
                type: 'asset',
                fileName: dest,
                source: JSON.stringify(data),
              });
            }
          })
        );
      },
      resolveId(source) {
        if (source === SECRET_INTERNAL_IMPORT) {
          return {
            id: MORE_INTERNAL,
          };
        }

        return;
      },
      loadInclude(id) {
        if (!id.startsWith('\0')) return false;

        return id === MORE_INTERNAL;
      },
      load(id) {
        if (id !== MORE_INTERNAL) return;

        let content = stripIndent`
          export const packageNames = [
            ${options.packages.map((raw) => `'${raw}',`).join('\n  ')}
          ];

          export const loadApiDocs = {
            ${options.packages
              .map((name) => {
                return `'${name}': () => fetch('${getDest(name)}'),`;
              })
              .join('\n  ')}
          };
        `;

        return content;
      },
    };
  }
);
```

Which is modeled after this working plugin here: https://github.com/yjl9903/unplugin-info
demo'd here: https://github.com/NullVoxPopuli/embroider-with-webpack-build-plugins-demo :tada:

But I just realized that the working demo probably works because _it's the app_ that's importing the virtual module, not the library!!!

**Comment by NullVoxPopuli** [comment]
hm, after moving my import to the app, this was unexpected, a runtime error :thinking:

```
 Error while processing route: page.index Could not find module `virtual:kolay/api-docs` imported from `(require)` missingModule@http://localhost:4200/assets/vendor.js:254:11
findModule@http://localhost:4200/assets/vendor.js:265:20
```

**Comment by mansona** [comment]
this will likely be fixed by https://github.com/embroider-build/embroider/pull/1794 (I think 🤔 )

**Comment by NullVoxPopuli** [comment]
Finally figured out my delta, and why my even smaller repro was succeeding where my slightly less small repro (a repro for a bigger project) was failing:

_I was using unstable embroider_.

I did the bad thing and reported an issue while using unstable embroider :see_no_evil: oops.

Disregard! my code works under the stable release!
