### ISSUE TITLE
Embroider + Fastboot: Build not invoking `app-boot` in contentFor hook. Causing Fastboot app to fail

### ISSUE THREAD

**Issue by dnalagatla** [embroider-build/embroider#183]
Embroider document indicates contentFor hook for `app-boot` type is deprecated. Ember-cli-fastboot relies on that type to insert Fastboot app-factory module and during runtime, the fastboot relies on this module. 

https://github.com/ember-fastboot/ember-cli-fastboot/blob/master/index.js#L109

As this module is not present Fastboot throws following error upon loading the app:
```
Error: Could not find module `~fastboot/app-factory` imported from `(require)`
    at missingModule (/Users/dnalagat/DEVELOPMENT/test-pemberly-bpr/test-ember/my-embroider-test/dist/assets/node_modules/@embroider/synthesized-vendor/vendor/loader/loader.js:247:1)
    at findModule (/Users/dnalagat/DEVELOPMENT/test-pemberly-bpr/test-ember/my-embroider-test/dist/assets/node_modules/@embroider/synthesized-vendor/vendor/loader/loader.js:258:1)
    at Object.requireModule (/Users/dnalagat/DEVELOPMENT/test-pemberly-bpr/test-ember/my-embroider-test/dist/assets/node_modules/@embroider/synthesized-vendor/vendor/loader/loader.js:24:1)
    at Object.<anonymous> (/Users/dnalagat/DEVELOPMENT/test-pemberly-bpr/test-ember/my-embroider-test/node_modules/fastboot/src/ember-app.js:179:18)
    at VMSandbox.run (/Users/dnalagat/DEVELOPMENT/test-pemberly-bpr/test-ember/my-embroider-test/node_modules/fastboot/src/vm-sandbox.js:18:15)
    at EmberApp.createEmberApp (/Users/dnalagat/DEVELOPMENT/test-pemberly-bpr/test-ember/my-embroider-test/node_modules/fastboot/src/ember-app.js:178:30)
    at EmberApp.retrieveSandboxedApp (/Users/dnalagat/DEVELOPMENT/test-pemberly-bpr/test-ember/my-embroider-test/node_modules/fastboot/src/ember-app.js:203:17)
    at new EmberApp (/Users/dnalagat/DEVELOPMENT/test-pemberly-bpr/test-ember/my-embroider-test/node_modules/fastboot/src/ember-app.js:59:21)
    at FastBoot._buildEmberApp (/Users/dnalagat/DEVELOPMENT/test-pemberly-bpr/test-ember/my-embroider-test/node_modules/fastboot/src/index.js:114:17)
    at new FastBoot (/Users/dnalagat/DEVELOPMENT/test-pemberly-bpr/test-ember/my-embroider-test/node_modules/fastboot/src/index.js:52:10)
    at app.use (/Users/dnalagat/DEVELOPMENT/test-pemberly-bpr/test-ember/my-embroider-test/node_modules/ember-cli-fastboot/index.js:320:29)
    at Layer.handle [as handle_request] (/Users/dnalagat/DEVELOPMENT/test-pemberly-bpr/test-ember/my-embroider-test/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/dnalagat/DEVELOPMENT/test-pemberly-bpr/test-ember/my-embroider-test/node_modules/express/lib/router/index.js:317:13)
    at /Users/dnalagat/DEVELOPMENT/test-pemberly-bpr/test-ember/my-embroider-test/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/dnalagat/DEVELOPMENT/test-pemberly-bpr/test-ember/my-embroider-test/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/dnalagat/DEVELOPMENT/test-pemberly-bpr/test-ember/my-embroider-test/node_modules/express/lib/router/index.js:275:10)
    at err (/Users/dnalagat/DEVELOPMENT/test-pemberly-bpr/test-ember/my-embroider-test/node_modules/ember-cli/lib/tasks/server/middleware/broccoli-watcher/index.js:54:11)
    at watcher.then (/Users/dnalagat/DEVELOPMENT/test-pemberly-bpr/test-ember/my-embroider-test/node_modules/broccoli-middleware/lib/watcher-middleware.js:35:7)
    at tryCatcher (/Users/dnalagat/DEVELOPMENT/test-pemberly-bpr/test-ember/my-embroider-test/node_modules/ember-cli/node_modules/rsvp/dist/lib/rsvp/-internal.js:39:19)
    at invokeCallback (/Users/dnalagat/DEVELOPMENT/test-pemberly-bpr/test-ember/my-embroider-test/node_modules/ember-cli/node_modules/rsvp/dist/lib/rsvp/-internal.js:211:31)
    at /Users/dnalagat/DEVELOPMENT/test-pemberly-bpr/test-ember/my-embroider-test/node_modules/ember-cli/node_modules/rsvp/dist/lib/rsvp/then.js:26:14
    at flush (/Users/dnalagat/DEVELOPMENT/test-pemberly-bpr/test-ember/my-embroider-test/node_modules/ember-cli/node_modules/rsvp/dist/lib/rsvp/asap.js:80:5)
    at process.internalTickCallback (internal/process/next_tick.js:70:11)
```

cc: @stefanpenner @ef4  @rwjblue

**Comment by dnalagatla** [comment]
Fixed as part of this PR - https://github.com/ember-fastboot/ember-cli-fastboot/pull/702

**Comment by dnalagatla** [comment]
The changes were reverted. After discussing with @stefanpenner worked in introducing a runtime flag to disable auto-boot in only while loading in FastBoot environment.

**Comment by void-mAlex** [comment]
closing as pr with fix has been merged
