### ISSUE TITLE
embroider @ v3 is not compatible with explicit babel config w/ ember-cli-babel

### ISSUE THREAD

**Issue by NullVoxPopuli** [embroider-build/embroider#1929]
Following the instructions from ember-cli-babel here: https://github.com/emberjs/ember-cli-babel?tab=readme-ov-file#babel-config-usage
and demonstrated in this repro: https://github.com/NullVoxPopuli/embroider-3-repro-cant-use-babel-config-from-ember-cli-babel/commit/b289ad46fd6713f854c6bda9536d986525eefc8b

We get this collection of errors: 
<details><summary>the errors</summary>

```
ERROR in ./assets/embroider-custom-babel.js 6:25-111
Module not found: Error: unable to resolve package node_modules from 🏠/Development$TMPDIR/embroider-custom-babel

ERROR in ./assets/embroider-custom-babel.js
Module not found: Error: Can't resolve '@embroider/macros' in '🏠/Development$TMPDIR/embroider-custom-babel/node_modules/.embroider/rewritten-app/assets'

ERROR in ./assets/test.js 8:25-116
Module not found: Error: unable to resolve package node_modules from 🏠/Development$TMPDIR/embroider-custom-babel

ERROR in ./assets/test.js
Module not found: Error: Can't resolve '@embroider/macros' in '🏠/Development$TMPDIR/embroider-custom-babel/node_modules/.embroider/rewritten-app/assets'

ERROR in ../rewritten-packages/@ember-data/graph.efc40fee/node_modules/@ember-data/graph/-private.js
Module not found: Error: Can't resolve '@embroider/macros' in '🏠/Development$TMPDIR/embroider-custom-babel/node_modules/.embroider/rewritten-packages/@ember-data/graph.efc40fee/node_modules/@ember-data/graph'
 @ ../rewritten-packages/@ember-data/json-api.49ec57bc/node_modules/@ember-data/json-api/index.js
 @ ../rewritten-packages/ember-data.004ccfeb/node_modules/ember-data/store.js
 @ ../rewritten-packages/ember-data.004ccfeb/node_modules/ember-data/_app_/services/store.js
 @ ./assets/embroider-custom-babel.js 32:34-85

ERROR in ../rewritten-packages/@ember-data/json-api.49ec57bc/node_modules/@ember-data/json-api/index.js
Module not found: Error: Can't resolve '@embroider/macros' in '🏠/Development$TMPDIR/embroider-custom-babel/node_modules/.embroider/rewritten-packages/@ember-data/json-api.49ec57bc/node_modules/@ember-data/json-api'
 @ ../rewritten-packages/ember-data.004ccfeb/node_modules/ember-data/store.js
 @ ../rewritten-packages/ember-data.004ccfeb/node_modules/ember-data/_app_/services/store.js
 @ ./assets/embroider-custom-babel.js 32:34-85

ERROR in ../rewritten-packages/@ember-data/legacy-compat.80e834ee/node_modules/@ember-data/legacy-compat/index.js
Module not found: Error: Can't resolve '@embroider/macros' in '🏠/Development$TMPDIR/embroider-custom-babel/node_modules/.embroider/rewritten-packages/@ember-data/legacy-compat.80e834ee/node_modules/@ember-data/legacy-compat'
 @ ../rewritten-packages/ember-data.004ccfeb/node_modules/ember-data/store.js
 @ ../rewritten-packages/ember-data.004ccfeb/node_modules/ember-data/_app_/services/store.js
 @ ./assets/embroider-custom-babel.js 32:34-85

ERROR in ../rewritten-packages/@ember-data/request.0e86a7f4/node_modules/@ember-data/request/fetch.js
Module not found: Error: Can't resolve '@embroider/macros' in '🏠/Development$TMPDIR/embroider-custom-babel/node_modules/.embroider/rewritten-packages/@ember-data/request.0e86a7f4/node_modules/@ember-data/request'
 @ ../rewritten-packages/ember-data.004ccfeb/node_modules/ember-data/store.js
 @ ../rewritten-packages/ember-data.004ccfeb/node_modules/ember-data/_app_/services/store.js
 @ ./assets/embroider-custom-babel.js 32:34-85

ERROR in ../rewritten-packages/@ember-data/request.0e86a7f4/node_modules/@ember-data/request/index.js
Module not found: Error: Can't resolve '@embroider/macros' in '🏠/Development$TMPDIR/embroider-custom-babel/node_modules/.embroider/rewritten-packages/@ember-data/request.0e86a7f4/node_modules/@ember-data/request'
 @ ../rewritten-packages/ember-data.004ccfeb/node_modules/ember-data/store.js
 @ ../rewritten-packages/ember-data.004ccfeb/node_modules/ember-data/_app_/services/store.js
 @ ./assets/embroider-custom-babel.js 32:34-85

ERROR in ../../.pnpm/ember-page-title@8.2.3_ember-source@5.8.0/node_modules/ember-page-title/dist/helpers/page-title.js
Module not found: Error: ember-page-title is trying to import from node_modules but that is not one of its explicit dependencies
 @ ../../.pnpm/ember-page-title@8.2.3_ember-source@5.8.0/node_modules/ember-page-title/dist/_app_/helpers/page-title.js
 @ ./templates/application.hbs
 @ ./assets/embroider-custom-babel.js 50:34-93

ERROR in ../../.pnpm/ember-page-title@8.2.3_ember-source@5.8.0/node_modules/ember-page-title/dist/services/page-title.js
Module not found: Error: ember-page-title is trying to import from node_modules but that is not one of its explicit dependencies
 @ ../../.pnpm/ember-page-title@8.2.3_ember-source@5.8.0/node_modules/ember-page-title/dist/_app_/services/page-title.js
 @ ./assets/embroider-custom-babel.js 17:34-90

ERROR in ../../.pnpm/ember-qunit@8.0.2_@ember+test-helpers@3.3.0_ember-source@5.8.0_qunit@2.20.1/node_modules/ember-qunit/dist/index.js 37:27-188
Module not found: Error: ember-qunit is trying to import from node_modules but that is not one of its explicit dependencies
 @ ./tests/test-helper.js
 @ ./assets/test.js 13:34-88

ERROR in ../../.pnpm/ember-qunit@8.0.2_@ember+test-helpers@3.3.0_ember-source@5.8.0_qunit@2.20.1/node_modules/ember-qunit/dist/index.js
Module not found: Error: ember-qunit is trying to import from node_modules but that is not one of its explicit dependencies
 @ ./tests/test-helper.js
 @ ./assets/test.js 13:34-88

ERROR in ../../.pnpm/ember-qunit@8.0.2_@ember+test-helpers@3.3.0_ember-source@5.8.0_qunit@2.20.1/node_modules/ember-qunit/dist/index.js
Module not found: Error: ember-qunit is trying to import from node_modules but that is not one of its explicit dependencies
 @ ./tests/test-helper.js
 @ ./assets/test.js 13:34-88

ERROR in ../../.pnpm/ember-qunit@8.0.2_@ember+test-helpers@3.3.0_ember-source@5.8.0_qunit@2.20.1/node_modules/ember-qunit/dist/index.js
Module not found: Error: ember-qunit is trying to import from node_modules but that is not one of its explicit dependencies
 @ ./tests/test-helper.js
 @ ./assets/test.js 13:34-88

ERROR in ../../.pnpm/ember-qunit@8.0.2_@ember+test-helpers@3.3.0_ember-source@5.8.0_qunit@2.20.1/node_modules/ember-qunit/dist/index.js
Module not found: Error: ember-qunit is trying to import from node_modules but that is not one of its explicit dependencies
 @ ./tests/test-helper.js
 @ ./assets/test.js 13:34-88

ERROR in ../../.pnpm/ember-qunit@8.0.2_@ember+test-helpers@3.3.0_ember-source@5.8.0_qunit@2.20.1/node_modules/ember-qunit/dist/index.js
Module not found: Error: ember-qunit is trying to import from node_modules but that is not one of its explicit dependencies
 @ ./tests/test-helper.js
 @ ./assets/test.js 13:34-88

ERROR in ../../.pnpm/ember-welcome-page@7.0.2/node_modules/ember-welcome-page/dist/components/welcome-page.js
Module not found: Error: ember-welcome-page is trying to import from node_modules but that is not one of its explicit dependencies
 @ ../../.pnpm/ember-welcome-page@7.0.2/node_modules/ember-welcome-page/dist/_app_/components/welcome-page.js
 @ ./templates/application.hbs
 @ ./assets/embroider-custom-babel.js 50:34-93

7 errors have detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

webpack 5.91.0 compiled with 18 errors and 1 warning in 2431 ms
Build Error (PackagerRunner) in assets/embroider-custom-babel.js

Module not found: Error: unable to resolve package node_modules from 🏠/Development$TMPDIR/embroider-custom-babel


Stack Trace and Error Report: /tmp/error.dump.1bfbe2d3c9029e1fc90e7d82c4e96f32.log

```

</details>

<details><summary>the error dump</summary>

```
=================================================================================

ENV Summary:

  TIME: Mon May 20 2024 11:14:31 GMT-0400 (Eastern Daylight Time)
  TITLE: ember
  ARGV:
  - 🏠/.volta/tools/image/node/20.12.1/bin/node
  - <repo>/node_modules/ember-cli/bin/ember
  - serve
  EXEC_PATH: 🏠/.volta/tools/image/node/20.12.1/bin/node
  TMPDIR: /tmp
  SHELL: /bin/bash
  PATH:
  - <repo>/node_modules/.bin
  - 🏠/.volta/tools/image/pnpm/8.15.6/dist/node-gyp-bin
  - 🏠/.volta/tools/image/pnpm/8.15.6/bin
  - 🏠/.volta/tools/image/yarn/1.22.19/bin
  - 🏠/.volta/tools/image/node/20.12.1/bin
  - 🏠/.bun/bin
  - 🏠/.local/bin
  - 🏠/.bun/bin
  - 🏠/.deno/bin
  - 🏠/.volta/bin
  - /tmp/frum_117812_1716217981878/bin
  - 🏠/.cargo/bin
  - 🏠/Applications
  - 🏠/apps/phantomjs/bin
  - 🏠/scripts/system-utils
  - 🏠/scripts/node
  - 🏠/scripts/git
  - 🏠/scripts/rails
  - 🏠/scripts
  - 🏠/.cargo/bin
  - 🏠/.volta/bin
  - 🏠/.local/bin
  - /usr/local/sbin
  - /usr/local/bin
  - /usr/sbin
  - /usr/bin
  - /sbin
  - /bin
  - /usr/games
  - /usr/local/games
  - /snap/bin
  - /snap/bin
  PLATFORM: linux x64
  FREEMEM: 32531570688
  TOTALMEM: 66550112256
  UPTIME: 9738.93
  LOADAVG: 3.24,2.68,2.77
  CPUS:
  - AMD Ryzen 9 7900X 12-Core Processor - 4577
  - AMD Ryzen 9 7900X 12-Core Processor - 4021
  - AMD Ryzen 9 7900X 12-Core Processor - 4744
  - AMD Ryzen 9 7900X 12-Core Processor - 4767
  - AMD Ryzen 9 7900X 12-Core Processor - 400
  - AMD Ryzen 9 7900X 12-Core Processor - 400
  - AMD Ryzen 9 7900X 12-Core Processor - 4986
  - AMD Ryzen 9 7900X 12-Core Processor - 4708
  - AMD Ryzen 9 7900X 12-Core Processor - 5023
  - AMD Ryzen 9 7900X 12-Core Processor - 4772
  - AMD Ryzen 9 7900X 12-Core Processor - 4980
  - AMD Ryzen 9 7900X 12-Core Processor - 4800
  - AMD Ryzen 9 7900X 12-Core Processor - 400
  - AMD Ryzen 9 7900X 12-Core Processor - 4949
  - AMD Ryzen 9 7900X 12-Core Processor - 4738
  - AMD Ryzen 9 7900X 12-Core Processor - 4747
  - AMD Ryzen 9 7900X 12-Core Processor - 4528
  - AMD Ryzen 9 7900X 12-Core Processor - 4606
  - AMD Ryzen 9 7900X 12-Core Processor - 4726
  - AMD Ryzen 9 7900X 12-Core Processor - 4766
  - AMD Ryzen 9 7900X 12-Core Processor - 3710
  - AMD Ryzen 9 7900X 12-Core Processor - 4853
  - AMD Ryzen 9 7900X 12-Core Processor - 4983
  - AMD Ryzen 9 7900X 12-Core Processor - 4269
  ENDIANNESS: LE
  VERSIONS:
  - acorn: 8.11.3
  - ada: 2.7.6
  - ares: 1.27.0
  - base64: 0.5.2
  - brotli: 1.1.0
  - cjs_module_lexer: 1.2.2
  - cldr: 44.1
  - icu: 74.2
  - llhttp: 8.1.2
  - modules: 115
  - napi: 9
  - nghttp2: 1.60.0
  - nghttp3: 0.7.0
  - ngtcp2: 0.8.1
  - node: 20.12.1
  - openssl: 3.0.13+quic
  - simdutf: 4.0.8
  - tz: 2024a
  - undici: 5.28.4
  - unicode: 15.1
  - uv: 1.46.0
  - uvwasi: 0.0.20
  - v8: 11.3.244.8-node.19
  - zlib: 1.3.0.1-motley-40e35a7

ERROR Summary:

  - broccoliBuilderErrorStack: ModuleNotFoundError: Module not found: Error: unable to resolve package node_modules from 🏠/Development$TMPDIR/embroider-custom-babel
    at <.pnpm>/webpack@5.91.0/node_modules/webpack/lib/Compilation.js:2094:28
    at <.pnpm>/webpack@5.91.0/node_modules/webpack/lib/NormalModuleFactory.js:895:13
    at eval (eval at create (<.pnpm>/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at <.pnpm>/webpack@5.91.0/node_modules/webpack/lib/NormalModuleFactory.js:332:22
    at eval (eval at create (<.pnpm>/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at <.pnpm>/@embroider+webpack@3.2.3_@embroider+core@3.4.9_webpack@5.91.0/node_modules/@embroider/webpack/src/webpack-resolver-plugin.js:58:27
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at process.processImmediate (node:internal/timers:449:9)
  - code: [undefined]
  - codeFrame: Module not found: Error: unable to resolve package node_modules from 🏠/Development$TMPDIR/embroider-custom-babel
  - errorMessage: assets/embroider-custom-babel.js: Module not found: Error: unable to resolve package node_modules from 🏠/Development$TMPDIR/embroider-custom-babel
        at PackagerRunner (@embroider/webpack)
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: assets/embroider-custom-babel.js
    - line: [null]
    - treeDir: [undefined]
  - message: assets/embroider-custom-babel.js: Module not found: Error: unable to resolve package node_modules from 🏠/Development$TMPDIR/embroider-custom-babel
        at PackagerRunner (@embroider/webpack)
  - name: Error
  - nodeAnnotation: @embroider/webpack
  - nodeName: PackagerRunner
  - originalErrorMessage: Module not found: Error: unable to resolve package node_modules from 🏠/Development$TMPDIR/embroider-custom-babel
  - stack: ModuleNotFoundError: Module not found: Error: unable to resolve package node_modules from 🏠/Development$TMPDIR/embroider-custom-babel
    at <.pnpm>/webpack@5.91.0/node_modules/webpack/lib/Compilation.js:2094:28
    at <.pnpm>/webpack@5.91.0/node_modules/webpack/lib/NormalModuleFactory.js:895:13
    at eval (eval at create (<.pnpm>/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at <.pnpm>/webpack@5.91.0/node_modules/webpack/lib/NormalModuleFactory.js:332:22
    at eval (eval at create (<.pnpm>/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at <.pnpm>/@embroider+webpack@3.2.3_@embroider+core@3.4.9_webpack@5.91.0/node_modules/@embroider/webpack/src/webpack-resolver-plugin.js:58:27
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at process.processImmediate (node:internal/timers:449:9)

=================================================================================

```

</details>

**Comment by NullVoxPopuli** [comment]
yeah, just want to document for SEO reasons and such.

**Comment by NullVoxPopuli** [comment]
This also doesn't work (again just documenting, while I try to figure out how to add a transform to an existing app):

```js
module.exports = async function (defaults) {
  const app = new EmberApp(defaults, {
    babel: {
      plugins: [
        require.resolve('ember-scoped-css/babel-plugin'),
      ]
    }
  });

  // ...
```

**Comment by NullVoxPopuli** [comment]
For others, even for embroider @ v3, the only way to add babel plugins is via v1 addon (or in-repo addon)

(this has been known for a while, just closing the loop, so folks have something actionable to do if they come across this issue)
