### ISSUE TITLE
[BUG] ember-cli:watcher do not work

### ISSUE THREAD

**Issue by AmilKey** [embroider-build/embroider#1989]
I got this error when start with ` DEBUG=ember-cli:watcher ember s` after this error ember-cli not trigger a build, after changes any files no trigger build

```
 ember-cli:watcher initialize { verbose: true, poll: false, watchman: true, node: false } +13ms
  ember-cli:watcher didChange { directory: '/var/folders/s3/8kf6f5ps02n7wsybzd_7vgpm0000gn/T/broccoli-5417l2gTbvvuZbl7/out-923-packager_runner_embroider_webpack', graph: TransformNodeWrapper { buildState: { selfTime: 9094.611461999999, totalTime: 36490.001207000016 }, _revision: 1, nodeInfo: { instantiationStack: [Getter], nodeType: 'transform', inputNodes: [Array], setup: [Function: bound _setup], getCallbackObject: [Function: bound getCallbackObject], name: 'PackagerRunner', annotation: '@embroider/webpack', persistentOutput: true, needsCache: false, volatile: false, trackInputChanges: false, fsFacade: false }, originalNode: PackagerRunner { _instantiationError: Error at new Plugin (/Users/xxxx/projects/test/node_modules/@embroider/core/node_modules/broccoli-plugin/dist/index.js:47:36) at new PackagerRunner (/Users/xxxx/projects/test/node_modules/@embroider/core/src/to-broccoli-plugin.js:11:13) at Object.defaultPipeline (/Users/xxxx/projects/test/node_modules/@embroider/compat/src/default-pipeline.js:38:12) at module.exports (/Users/xxxx/projects/test/ember-cli-build.js:15:39) at Builder.readBuildFile (/Users/xxxx/projects/test/node_modules/ember-cli/lib/models/builder.js:48:20) at async Builder.setupBroccoliBuilder (/Users/xxxx/projects/test/node_modules/ember-cli/lib/models/builder.js:68:17) at async Builder.ensureBroccoliBuilder (/Users/xxxx/projects/test/node_modules/ember-cli/lib/models/builder.js:56:7) at async Watcher.constructBroccoliWatcher (/Users/xxxx/projects/test/node_modules/ember-cli/lib/models/watcher.js:59:5) at async Watcher.setupBroccoliWatcher (/Users/xxxx/projects/test/node_modules/ember-cli/lib/models/watcher.js:43:37) at async Watcher.build (/Users/xxxx/projects/test/node_modules/ember-cli/lib/models/watcher.js:31:5), _name: 'PackagerRunner', _annotation: '@embroider/webpack', _baseConstructorCalled: true, _inputNodes: [Array], _persistentOutput: true, _needsCache: false, _volatile: false, _trackInputChanges: false, __broccoliFeatures__: [Object], stage: [Object], variants: [Array], options: [Object], cachePath: undefined, packager: [Webpack] }, node: PackagerRunner { _instantiationError: Error at new Plugin (/Users/xxxx/projects/test/node_modules/@embroider/core/node_modules/broccoli-plugin/dist/index.js:47:36) at new PackagerRunner (/Users/xxxx/projects/test/node_modules/@embroider/core/src/to-broccoli-plugin.js:11:13) at Object.defaultPipeline (/Users/xxxx/projects/test/node_modules/@embroider/compat/src/default-pipeline.js:38:12) at module.exports (/Users/xxxx/projects/test/ember-cli-build.js:15:39) at Builder.readBuildFile (/Users/xxxx/projects/test/node_modules/ember-cli/lib/models/builder.js:48:20) at async Builder.setupBroccoliBuilder (/Users/xxxx/projects/test/node_modules/ember-cli/lib/models/builder.js:68:17) at async Builder.ensureBroccoliBuilder (/Users/xxxx/projects/test/node_modules/ember-cli/lib/models/builder.js:56:7) at async Watcher.constructBroccoliWatcher (/Users/xxxx/projects/test/node_modules/ember-cli/lib/models/watcher.js:59:5) at async Watcher.setupBroccoliWatcher (/Users/xxxx/projects/test/node_modules/ember-cli/lib/models/watcher.js:43:37) at async Watcher.build (/Users/xxxx/projects/test/node_modules/ember-cli/lib/models/watcher.js:31:5), _name: 'PackagerRunner', _annotation: '@embroider/webpack', _baseConstructorCalled: true, _inputNodes: [Array], _persistentOutput: true, _needsCache: false, _volatile: false, _trackInputChanges: false, __broccoliFeatures__: [Object], stage: [Object], variants: [Array], options: [Object], cachePath: undefined, packager: [Webpack] }, label: 'PackagerRunner (@embroider/webpack)', inputNodeWrappers: [ [TransformNodeWrapper] ], id: 923, inputPaths: [ '/var/folders/s3/8kf6f5ps02n7wsybzd_7vgpm0000gn/T/broccoli-5417l2gTbvvuZbl7/out-922-wait_for_trees_embroider_compat_app' ], outputPath: '/var/folders/s3/8kf6f5ps02n7wsybzd_7vgpm0000gn/T/broccoli-5417l2gTbvvuZbl7/out-923-packager_runner_embroider_webpack', callbackObject: PackagerRunner { _instantiationError: Error at new Plugin (/Users/xxxx/projects/test/node_modules/@embroider/core/node_modules/broccoli-plugin/dist/index.js:47:36) at new PackagerRunner (/Users/xxxx/projects/test/node_modules/@embroider/core/src/to-broccoli-plugin.js:11:13) at Object.defaultPipeline (/Users/xxxx/projects/test/node_modules/@embroider/compat/src/default-pipeline.js:38:12) at module.exports (/Users/xxxx/projects/test/ember-cli-build.js:15:39) at Builder.readBuildFile (/Users/xxxx/projects/test/node_modules/ember-cli/lib/models/builder.js:48:20) at async Builder.setupBroccoliBuilder (/Users/xxxx/projects/test/node_modules/ember-cli/lib/models/builder.js:68:17) at async Builder.ensureBroccoliBuilder (/Users/xxxx/projects/test/node_modules/ember-cli/lib/models/builder.js:56:7) at async Watcher.constructBroccoliWatcher (/Users/xxxx/projects/test/node_modules/ember-cli/lib/models/watcher.js:59:5) at async Watcher.setupBroccoliWatcher (/Users/xxxx/projects/test/node_modules/ember-cli/lib/models/watcher.js:43:37) at async Watcher.build (/Users/xxxx/projects/test/node_modules/ember-cli/lib/models/watcher.js:31:5), _name: 'PackagerRunner', _annotation: '@embroider/webpack', _baseConstructorCalled: true, _inputNodes: [Array], _persistentOutput: true, _needsCache: false, _volatile: false, _trackInputChanges: false, __broccoliFeatures__: [Object], stage: [Object], variants: [Array], options: [Object], cachePath: undefined, packager: [Webpack] }, inputRevisions: WeakMap { <items unknown> }, __heimdall_cookie__: Cookie { _node: [HeimdallNode], _restoreNode: [HeimdallNode], _heimdall: [Heimdall], _stopped: true }, __heimdall__: HeimdallNode { _heimdall: [Heimdall], _id: 1937, id: [Object], stats: [Object], _children: [Array], parent: [HeimdallNode] } }, filePath: undefined } +19s```
  
  package.json
  ```
    "devDependencies": {
    "@babel/core": "^7.24.4",
    "@babel/eslint-parser": "^7.24.1",
    "@babel/plugin-proposal-decorators": "^7.24.1",
    "@ember/optional-features": "^2.1.0",
    "@ember/string": "^3.1.1",
    "@ember/test-helpers": "^3.3.0",
    "@embroider/compat": "^3.5.3",
    "@embroider/core": "^3.4.12",
    "@embroider/webpack": "^4.0.3",
    "@glimmer/component": "^1.1.2",
    "@glimmer/tracking": "^1.1.2",
    "@tailwindcss/forms": "^0.5.7",
    "autoprefixer": "^10.0.2",
    "broccoli-asset-rev": "^3.0.0",
    "concurrently": "^8.2.2",
    "ember-auto-import": "^2.7.2",
    "ember-basic-dropdown": "^8.1.0",
    "ember-cli": "~5.9.0",
    "ember-cli-app-version": "^6.0.1",
    "ember-cli-babel": "^8.2.0",
    "ember-cli-clean-css": "^3.0.0",
    "ember-cli-dependency-checker": "^3.3.2",
    "ember-cli-htmlbars": "^6.3.0",
    "ember-cli-inject-live-reload": "^2.1.0",
    "ember-cli-notifications": "^9.0.0",
    "ember-cli-sri": "^2.1.1",
    "ember-cli-terser": "^4.0.2",
    "ember-cloud-firestore-adapter": "^4.0.0",
    "ember-concurrency": "^4.0.2",
    "ember-data": "~5.3.3",
    "ember-fetch": "^8.1.2",
    "ember-load-initializers": "^2.1.2",
    "ember-modifier": "^4.1.0",
    "ember-page-title": "^8.2.3",
    "ember-power-select": "^8.2.0",
    "ember-promise-helpers": "^2.0.0",
    "ember-qunit": "^8.0.2",
    "ember-resolver": "^11.0.1",
    "ember-simple-auth": "^6.0.0",
    "ember-source": "~5.8.0",
    "ember-template-lint": "^5.13.0",
    "ember-truth-helpers": "^4.0.3",
    "eslint": "^8.57.0",
    "eslint-config-prettier": "^9.1.0",
    "eslint-plugin-ember": "^11.12.0",
    "eslint-plugin-n": "^16.6.2",
    "eslint-plugin-prettier": "^5.1.3",
    "eslint-plugin-qunit": "^8.1.1",
    "loader.js": "^4.7.0",
    "postcss": "^8.0.0",
    "postcss-loader": "^7.0.0",
    "prettier": "^3.2.5",
    "qunit": "^2.20.1",
    "qunit-dom": "^2.0.0",
    "stylelint": "^15.11.0",
    "stylelint-config-standard": "^34.0.0",
    "stylelint-prettier": "^4.1.0",
    "tailwindcss": "^3.4.4",
    "tracked-built-ins": "^3.3.0",
    "webpack": "^5.92.0"
  },
  ```
  node -v
v18.20.3
 npm -v
10.7.0
  yarn -v
1.22.19

macOS 13.6.7

**Comment by mansona** [comment]
it's very hard to see the error since it's rendered all in one big line, are you able to fix the output? or are you able to produce a reproduction that shows this error?

**Comment by mansona** [comment]
also for the record setting `DEBUG=ember-cli:watcher` is just a way to show extra debug output, it should not affect any functionality

**Comment by AmilKey** [comment]
> it's very hard to see the error since it's rendered all in one big line, are you able to fix the output? or are you able to produce a reproduction that shows this error?

sorry for misunderstanding, the cause of this error was not this command `DEBUG=ember-cli:watcher`, using this command I just got this log

```
ember-cli:watcher initialize { 
    verbose: true, 
    poll: false, 
    watchman: true, 
    node: false 
} +13ms

ember-cli:watcher didChange { 
    directory: '/var/folders/s3/8kf6f5ps02n7wsybzd_7vgpm0000gn/T/broccoli-5417l2gTbvvuZbl7/out-923-packager_runner_embroider_webpack', 
    graph: TransformNodeWrapper { 
        buildState: { 
            selfTime: 9094.611461999999, 
            totalTime: 36490.001207000016 
        }, 
        _revision: 1, 
        nodeInfo: { 
            instantiationStack: [Getter], 
            nodeType: 'transform', 
            inputNodes: [Array], 
            setup: [Function: bound _setup], 
            getCallbackObject: [Function: bound getCallbackObject], 
            name: 'PackagerRunner', 
            annotation: '@embroider/webpack', 
            persistentOutput: true, 
            needsCache: false, 
            volatile: false, 
            trackInputChanges: false, 
            fsFacade: false 
        }, 
        originalNode: PackagerRunner { 
            _instantiationError: Error 
                at new Plugin (/Users/xxxx/projects/test/node_modules/@embroider/core/node_modules/broccoli-plugin/dist/index.js:47:36)
                at new PackagerRunner (/Users/xxxx/projects/test/node_modules/@embroider/core/src/to-broccoli-plugin.js:11:13)
                at Object.defaultPipeline (/Users/xxxx/projects/test/node_modules/@embroider/compat/src/default-pipeline.js:38:12)
                at module.exports (/Users/xxxx/projects/test/ember-cli-build.js:15:39)
                at Builder.readBuildFile (/Users/xxxx/projects/test/node_modules/ember-cli/lib/models/builder.js:48:20)
                at async Builder.setupBroccoliBuilder (/Users/xxxx/projects/test/node_modules/ember-cli/lib/models/builder.js:68:17)
                at async Builder.ensureBroccoliBuilder (/Users/xxxx/projects/test/node_modules/ember-cli/lib/models/builder.js:56:7)
                at async Watcher.constructBroccoliWatcher (/Users/xxxx/projects/test/node_modules/ember-cli/lib/models/watcher.js:59:5)
                at async Watcher.setupBroccoliWatcher (/Users/xxxx/projects/test/node_modules/ember-cli/lib/models/watcher.js:43:37)
                at async Watcher.build (/Users/xxxx/projects/test/node_modules/ember-cli/lib/models/watcher.js:31:5),
            _name: 'PackagerRunner',
            _annotation: '@embroider/webpack',
            _baseConstructorCalled: true,
            _inputNodes: [Array],
            _persistentOutput: true,
            _needsCache: false,
            _volatile: false,
            _trackInputChanges: false,
            __broccoliFeatures__: [Object],
            stage: [Object],
            variants: [Array],
            options: [Object],
            cachePath: undefined,
            packager: [Webpack] 
        },
        node: PackagerRunner { 
            _instantiationError: Error 
                at new Plugin (/Users/xxxx/projects/test/node_modules/@embroider/core/node_modules/broccoli-plugin/dist/index.js:47:36)
                at new PackagerRunner (/Users/xxxx/projects/test/node_modules/@embroider/core/src/to-broccoli-plugin.js:11:13)
                at Object.defaultPipeline (/Users/xxxx/projects/test/node_modules/@embroider/compat/src/default-pipeline.js:38:12)
                at module.exports (/Users/xxxx/projects/test/ember-cli-build.js:15:39)
                at Builder.readBuildFile (/Users/xxxx/projects/test/node_modules/ember-cli/lib/models/builder.js:48:20)
                at async Builder.setupBroccoliBuilder (/Users/xxxx/projects/test/node_modules/ember-cli/lib/models/builder.js:68:17)
                at async Builder.ensureBroccoliBuilder (/Users/xxxx/projects/test/node_modules/ember-cli/lib/models/builder.js:56:7)
                at async Watcher.constructBroccoliWatcher (/Users/xxxx/projects/test/node_modules/ember-cli/lib/models/watcher.js:59:5)
                at async Watcher.setupBroccoliWatcher (/Users/xxxx/projects/test/node_modules/ember-cli/lib/models/watcher.js:43:37)
                at async Watcher.build (/Users/xxxx/projects/test/node_modules/ember-cli/lib/models/watcher.js:31:5),
            _name: 'PackagerRunner',
            _annotation: '@embroider/webpack',
            _baseConstructorCalled: true,
            _inputNodes: [Array],
            _persistentOutput: true,
            _needsCache: false,
            _volatile: false,
            _trackInputChanges: false,
            __broccoliFeatures__: [Object],
            stage: [Object],
            variants: [Array],
            options: [Object],
            cachePath: undefined,
            packager: [Webpack] 
        },
        label: 'PackagerRunner (@embroider/webpack)',
        inputNodeWrappers: [ [TransformNodeWrapper] ],
        id: 923,
        inputPaths: [ '/var/folders/s3/8kf6f5ps02n7wsybzd_7vgpm0000gn/T/broccoli-5417l2gTbvvuZbl7/out-922-wait_for_trees_embroider_compat_app' ],
        outputPath: '/var/folders/s3/8kf6f5ps02n7wsybzd_7vgpm0000gn/T/broccoli-5417l2gTbvvuZbl7/out-923-packager_runner_embroider_webpack',
        callbackObject: PackagerRunner { 
            _instantiationError: Error 
                at new Plugin (/Users/xxxx/projects/test/node_modules/@embroider/core/node_modules/broccoli-plugin/dist/index.js:47:36)
                at new PackagerRunner (/Users/xxxx/projects/test/node_modules/@embroider/core/src/to-broccoli-plugin.js:11:13)
                at Object.defaultPipeline (/Users/xxxx/projects/test/node_modules/@embroider/compat/src/default-pipeline.js:38:12)
                at module.exports (/Users/xxxx/projects/test/ember-cli-build.js:15:39)
                at Builder.readBuildFile (/Users/xxxx/projects/test/node_modules/ember-cli/lib/models/builder.js:48:20)
                at async Builder.setupBroccoliBuilder (/Users/xxxx/projects/test/node_modules/ember-cli/lib/models/builder.js:68:17)
                at async Builder.ensureBroccoliBuilder (/Users/xxxx/projects/test/node_modules/ember-cli/lib/models/builder.js:56:7)
                at async Watcher.constructBroccoliWatcher (/Users/xxxx/projects/test/node_modules/ember-cli/lib/models/watcher.js:59:5)
                at async Watcher.setupBroccoliWatcher (/Users/xxxx/projects/test/node_modules/ember-cli/lib/models/watcher.js:43:37)
                at async Watcher.build (/Users/xxxx/projects/test/node_modules/ember-cli/lib/models/watcher.js:31:5),
            _name: 'PackagerRunner',
            _annotation: '@embroider/webpack',
            _baseConstructorCalled: true,
            _inputNodes: [Array],
            _persistentOutput: true,
            _needsCache: false,
            _volatile: false,
            _trackInputChanges: false,
            __broccoliFeatures__: [Object],
            stage: [Object],
            variants: [Array],
            options: [Object],
            cachePath: undefined,
            packager: [Webpack] 
        },
        inputRevisions: WeakMap { <items unknown> },
        __heimdall_cookie__: Cookie { 
            _node: [HeimdallNode], 
            _restoreNode: [HeimdallNode], 
            _heimdall: [Heimdall], 
            _stopped: true 
        },
        __heimdall__: HeimdallNode { 
            _heimdall: [Heimdall], 
            _id: 1937, 
            id: [Object], 
            stats: [Object], 
            _children: [Array], 
            parent: [HeimdallNode] 
        } 
    }, 
    filePath: undefined 
} +19s

```

**Comment by vihai** [comment]
I confirm I have this issue with a fresh ember 6.4 app codemodded for embroider 4.1

**Comment by NullVoxPopuli** [comment]
with embroider 4/vite, we aren't suppossed to use `ember s` -- just running `vite` or `vite dev` will get you what you want.
