### ISSUE TITLE
Can't resolve a file

### ISSUE THREAD

**Issue by lstrzebinczyk** [embroider-build/embroider#255]
Hello

I'm trying to get emberoider to compile my application, but I am receiving this error:

```
Module not found: Error: Can't resolve '../lib/shorten-team-name' in '/tmp/embroider/b5758f/helpers'
```
The full stack trace:

```
=================================================================================

ENV Summary:

  TIME: Tue Jun 25 2019 16:55:43 GMT+0200 (CEST)
  TITLE: ember
  ARGV:
  - /usr/bin/node
  - /usr/bin/ember
  - s
  EXEC_PATH: /usr/bin/node
  TMPDIR: /tmp
  SHELL: /bin/bash
  PATH:
  - /home/killa/.cargo/bin
  - /home/killa/.cargo/bin
  - /home/killa/.rvm/gems/ruby-2.5.3/bin
  - /home/killa/.rvm/gems/ruby-2.5.3@global/bin
  - /home/killa/.rvm/rubies/ruby-2.5.3/bin
  - /home/killa/bin
  - /home/killa/.local/bin
  - /home/killa/.cargo/bin
  - /home/killa/.cargo/bin
  - /home/killa/bin
  - /home/killa/.local/bin
  - /usr/local/sbin
  - /usr/local/bin
  - /usr/sbin
  - /usr/bin
  - /sbin
  - /bin
  - /usr/games
  - /usr/local/games
  - /snap/bin
  - /home/killa/.rvm/bin
  - /home/killa/.rvm/bin
  - /home/killa/.rvm/bin
  PLATFORM: linux x64
  FREEMEM: 2379505664
  TOTALMEM: 16831954944
  UPTIME: 27789
  LOADAVG: 2.66455078125,0.79443359375,0.51708984375
  CPUS:
  - AMD Ryzen 7 1700X Eight-Core Processor - 2116
  - AMD Ryzen 7 1700X Eight-Core Processor - 1843
  - AMD Ryzen 7 1700X Eight-Core Processor - 1823
  - AMD Ryzen 7 1700X Eight-Core Processor - 2517
  - AMD Ryzen 7 1700X Eight-Core Processor - 2055
  - AMD Ryzen 7 1700X Eight-Core Processor - 2203
  - AMD Ryzen 7 1700X Eight-Core Processor - 3134
  - AMD Ryzen 7 1700X Eight-Core Processor - 2264
  - AMD Ryzen 7 1700X Eight-Core Processor - 2355
  - AMD Ryzen 7 1700X Eight-Core Processor - 2568
  - AMD Ryzen 7 1700X Eight-Core Processor - 3591
  - AMD Ryzen 7 1700X Eight-Core Processor - 3428
  - AMD Ryzen 7 1700X Eight-Core Processor - 3204
  - AMD Ryzen 7 1700X Eight-Core Processor - 2796
  - AMD Ryzen 7 1700X Eight-Core Processor - 3527
  - AMD Ryzen 7 1700X Eight-Core Processor - 3533
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.10.1-DEV
  - cldr: 32.0
  - http_parser: 2.8.0
  - icu: 60.1
  - modules: 57
  - napi: 4
  - nghttp2: 1.33.0
  - node: 8.16.0
  - openssl: 1.0.2r
  - tz: 2017c
  - unicode: 10.0
  - uv: 1.23.2
  - v8: 6.2.414.77
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: ModuleNotFoundError: Module not found: Error: Can't resolve '../lib/shorten-team-name' in '/tmp/embroider/b5758f/helpers'
    at factory.create (/home/killa/workspace/SBweb/node_modules/webpack/lib/Compilation.js:821:10)
    at factory (/home/killa/workspace/SBweb/node_modules/webpack/lib/NormalModuleFactory.js:397:22)
    at resolver (/home/killa/workspace/SBweb/node_modules/webpack/lib/NormalModuleFactory.js:130:21)
    at asyncLib.parallel (/home/killa/workspace/SBweb/node_modules/webpack/lib/NormalModuleFactory.js:224:22)
    at /home/killa/workspace/SBweb/node_modules/neo-async/async.js:2825:7
    at /home/killa/workspace/SBweb/node_modules/neo-async/async.js:6886:13
    at normalResolver.resolve (/home/killa/workspace/SBweb/node_modules/webpack/lib/NormalModuleFactory.js:214:25)
    at doResolve (/home/killa/workspace/SBweb/node_modules/enhanced-resolve/lib/Resolver.js:184:12)
    at hook.callAsync (/home/killa/workspace/SBweb/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/home/killa/workspace/SBweb/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
  - code: [undefined]
  - codeFrame: Module not found: Error: Can't resolve '../lib/shorten-team-name' in '/tmp/embroider/b5758f/helpers'
  - errorMessage: Module not found: Error: Can't resolve '../lib/shorten-team-name' in '/tmp/embroider/b5758f/helpers'
        at PackagerRunner (@embroider/webpack)
-~- created here: -~-
    at new Plugin (/home/killa/workspace/SBweb/node_modules/broccoli-plugin/index.js:7:31)
    at new PackagerRunner (/home/killa/workspace/SBweb/node_modules/@embroider/core/src/to-broccoli-plugin.js:10:13)
    at Object.defaultPipeline [as compatBuild] (/home/killa/workspace/SBweb/node_modules/@embroider/compat/src/default-pipeline.js:30:12)
    at module.exports (/home/killa/workspace/SBweb/ember-cli-build.js:34:39)
    at Builder.readBuildFile (/home/killa/workspace/SBweb/node_modules/ember-cli/lib/models/builder.js:51:14)
    at Builder.setupBroccoliBuilder (/home/killa/workspace/SBweb/node_modules/ember-cli/lib/models/builder.js:65:22)
    at new Builder (/home/killa/workspace/SBweb/node_modules/ember-cli/lib/models/builder.js:31:10)
    at ServeTask.run (/home/killa/workspace/SBweb/node_modules/ember-cli/lib/tasks/serve.js:49:7)
    at Promise.resolve.then (/home/killa/workspace/SBweb/node_modules/ember-cli/lib/models/command.js:239:24)
    at tryCatcher (/home/killa/workspace/SBweb/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:323:19)
-~- (end) -~-
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
    - treeDir: [undefined]
  - message: Module not found: Error: Can't resolve '../lib/shorten-team-name' in '/tmp/embroider/b5758f/helpers'
        at PackagerRunner (@embroider/webpack)
-~- created here: -~-
    at new Plugin (/home/killa/workspace/SBweb/node_modules/broccoli-plugin/index.js:7:31)
    at new PackagerRunner (/home/killa/workspace/SBweb/node_modules/@embroider/core/src/to-broccoli-plugin.js:10:13)
    at Object.defaultPipeline [as compatBuild] (/home/killa/workspace/SBweb/node_modules/@embroider/compat/src/default-pipeline.js:30:12)
    at module.exports (/home/killa/workspace/SBweb/ember-cli-build.js:34:39)
    at Builder.readBuildFile (/home/killa/workspace/SBweb/node_modules/ember-cli/lib/models/builder.js:51:14)
    at Builder.setupBroccoliBuilder (/home/killa/workspace/SBweb/node_modules/ember-cli/lib/models/builder.js:65:22)
    at new Builder (/home/killa/workspace/SBweb/node_modules/ember-cli/lib/models/builder.js:31:10)
    at ServeTask.run (/home/killa/workspace/SBweb/node_modules/ember-cli/lib/tasks/serve.js:49:7)
    at Promise.resolve.then (/home/killa/workspace/SBweb/node_modules/ember-cli/lib/models/command.js:239:24)
    at tryCatcher (/home/killa/workspace/SBweb/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:323:19)
-~- (end) -~-
  - name: BuildError
  - nodeAnnotation: @embroider/webpack
  - nodeName: PackagerRunner
  - originalErrorMessage: Module not found: Error: Can't resolve '../lib/shorten-team-name' in '/tmp/embroider/b5758f/helpers'
  - stack: ModuleNotFoundError: Module not found: Error: Can't resolve '../lib/shorten-team-name' in '/tmp/embroider/b5758f/helpers'
    at factory.create (/home/killa/workspace/SBweb/node_modules/webpack/lib/Compilation.js:821:10)
    at factory (/home/killa/workspace/SBweb/node_modules/webpack/lib/NormalModuleFactory.js:397:22)
    at resolver (/home/killa/workspace/SBweb/node_modules/webpack/lib/NormalModuleFactory.js:130:21)
    at asyncLib.parallel (/home/killa/workspace/SBweb/node_modules/webpack/lib/NormalModuleFactory.js:224:22)
    at /home/killa/workspace/SBweb/node_modules/neo-async/async.js:2825:7
    at /home/killa/workspace/SBweb/node_modules/neo-async/async.js:6886:13
    at normalResolver.resolve (/home/killa/workspace/SBweb/node_modules/webpack/lib/NormalModuleFactory.js:214:25)
    at doResolve (/home/killa/workspace/SBweb/node_modules/enhanced-resolve/lib/Resolver.js:184:12)
    at hook.callAsync (/home/killa/workspace/SBweb/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/home/killa/workspace/SBweb/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)

=================================================================================
```

I indeed have a `/lib/shorten-team-name.ts` file which just exports a function, I only in my code import it as

```
import shortenTeamName from "web/lib/shorten-team-name";
```
One of the imports is indeed inside a helper (as in, file in /helpers) file.

Which generates no issues in non-embroider build. 
'/tmp/embroider/b5758f/helpers' seems to be a directory of all of the helpers used in my application, including ones from addons. `/tmp/embroider/b5758f/` itself seems to be all files of my app joined into a single application, and all the import/export paths seem to be correct to me.

Might this be an error on embroider side? What else can I do to help boil this down?

**Comment by balinterdi** [comment]
> I indeed have a /lib/shorten-team-name.ts file which just exports a function, I only in my code import it as

Is it possible that the problem is that the .ts file is not compiled to .js before it's being imported?

Also, although not a real solution, did you try to replace the relative import (`../lib/shorten-team-name`) with an absolute one?

**Comment by lstrzebinczyk** [comment]
Hey, sorry I missed your response. Currently my builds are failing due to https://github.com/embroider-build/embroider/issues/274. 

I don't know much compilers, I guess any error is possible. I will try the suggested solition as #274 is solved

**Comment by balinterdi** [comment]
Ah, I see. Sorry, I can't give you the needed guidance myself (at least not yet).

**Comment by lstrzebinczyk** [comment]
Embroider 0.7 is throwing a different error now for my build, I'm closing this issue since it's probably no longer relevant.
