### ISSUE TITLE
Cannot find module './vendor/ember-cli/vendor-prefix.js'

### ISSUE THREAD

**Issue by kandhavivekraj** [embroider-build/embroider#257]
Build Error (WaitForTrees)

Cannot find module './vendor/ember-cli/vendor-prefix.js' from '/private/var/folders/hm/k9p_y4pn0td7j85vktlx3fjm2k96sb/T/embroider/542bcb/node_modules/@embroider/synthesized-vendor'

**ERROR Summary:**

  - broccoliBuilderErrorStack: Error: Cannot find module './vendor/ember-cli/vendor-prefix.js' from '/private/var/folders/hm/k9p_y4pn0td7j85vktlx3fjm2k96sb/T/embroider/542bcb/node_modules/@embroider/synthesized-vendor'

   at Function.module.exports [as sync] (/.../embroider/node_modules/resolve/lib/sync.js:58:15)
   at AppBuilder.impliedAddonAssets (/.../embroider/packages/core/src/app.js:182:51)
   at AppBuilder.impliedAssets (/.../embroider/packages/core/src/app.js:157:27)
   at AppBuilder.insertEmberApp (/.../embroider/packages/core/src/app.js:246:36)
   at AppBuilder.prepareAsset (/.../embroider/packages/core/src/app.js:298:18)
   at AppBuilder.prepareAssets (/.../embroider/packages/core/src/app.js:308:18)
   at AppBuilder.updateAssets (/.../embroider/packages/core/src/app.js:376:27)
   at AppBuilder.build (/.../embroider/packages/core/src/app.js:430:38)
   at WaitForTrees.wait_for_trees_1.default [as buildHook] (/.../embroider/packages/core/src/build-stage.js:37:31)
   at process._tickCallback (internal/process/next_tick.js:68:7)

 - code: [undefined]
 - codeFrame: Cannot find module './vendor/ember-cli/vendor-prefix.js' from '/private/var/folders/hm/k9p_y4pn0td7j85vktlx3fjm2k96sb/T/embroider/542bcb/node_modules/@embroider/synthesized-vendor'
  - errorMessage: Build Canceled: Broccoli Builder ran into an error with `WaitForTrees` plugin. 💥

**Comment by ef4** [comment]
Thanks for testing. What ember-cli version?

**Comment by kandhavivekraj** [comment]
-> ember -v
ember-cli: 3.4.4
node: 10.15.3
os: darwin x64

**Comment by ef4** [comment]
Hmm, I can't reproduce just by trying to downgrade a basic app to ember-cli 3.4.4. 

My guess is that the presence of some addon is changing the timing of [this](https://github.com/ember-cli/ember-cli/blob/b9f4213106b95ba6be3e0ea6bfa5a3ef9f5e72cf/lib/broccoli/default-packager.js#L1301) code so that it runs earlier than usual. There is probably a real embroider bug here but I'll need your help coming up with a reproduction.

One idea is to make a new empty ember ember app (using ember-cli 3.4.4), then copy into it your package.json to get the same set of addons. Hopefully that will give the same build error and be shareable.

**Comment by ef4** [comment]
Did you figure out what was happening?

**Comment by kandhavivekraj** [comment]
One of our plugins was calling `app.toTree()` that led to this. Sorry for the trouble.
