### ISSUE TITLE
Error while using Embroider with @classic decorator

### ISSUE THREAD

**Issue by gokatz** [embroider-build/embroider#317]
Thanks to all the contributors for the work on Embroider.

Recently I started to look into utilizing the embroider build and faced the following issue when using it with `@classic` decorator from [ember-classic-decorator](https://github.com/pzuraq/ember-classic-decorator). 

```
Build Error (PackagerRunner)

Module not found: Error: Can't resolve 'ember-classic-decorator' in '/private/var/folders/kp/fvcf7t_94cq0rfrfszk0ctzm_svdjr/T/embroider/c4c287/components'
```

Ember Source: 3.12
Reproduction: https://github.com/gokatz/embroider-build

<details>
  <summary>Stack Trace and Error Report: (Click to expand)</summary>
  
```
=================================================================================

ENV Summary:

  TIME: Mon Aug 26 2019 23:15:19 GMT+0530 (India Standard Time)
  TITLE: ember
  ARGV:
  - /Users/gokul/.volta/tools/image/node/10.16.3/6.9.0/bin/node
  - /Users/gokul/.config/yarn/global/node_modules/.bin/ember
  - s
  EXEC_PATH: /Users/gokul/.volta/tools/image/node/10.16.3/6.9.0/bin/node
  TMPDIR: /var/folders/kp/fvcf7t_94cq0rfrfszk0ctzm_svdjr/T
  SHELL: /bin/bash
  PATH:
  - /Users/gokul/.volta/tools/image/node/10.16.3/6.9.0/bin
  - /Users/gokul/.volta/tools/image/yarn/1.17.3/bin
  - /opt/local/bin
  - /opt/local/sbin
  - /Users/gokul/.notion/bin
  - /Users/gokul/.yarn/bin
  - /Users/gokul/.config/yarn/global/node_modules/.bin
  - /Users/gokul/.nvm/versions/node/v10.9.0/bin
  - /Users/gokul/Home/web/setup/
  - /Users/gokul/Home/web/setup//kdiff3.app/Contents/MacOS
  - /Users/gokul/Home/web/setup//apache-ant-1.8.1/bin
  - /Users/gokul/Home/web/setup//gradle-2.12/bin
  - /usr/local/bin
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  - /usr/local/go/bin
  - /opt/X11/bin
  - /Users/gokul/Home/web/setup//mysql/bin
  - /usr/local/mysql/bin/
  - /Users/gokul/.rvm/bin
  - /Users/gokul/Library/Android/sdk/tools
  - /Users/gokul/Library/Android/sdk/platform-tools
  PLATFORM: darwin x64
  FREEMEM: 156184576
  TOTALMEM: 17179869184
  UPTIME: 49023
  LOADAVG: 2.9990234375,2.6298828125,2.66357421875
  CPUS:
  - Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz - 2500
  - Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz - 2500
  - Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz - 2500
  - Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz - 2500
  - Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz - 2500
  - Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz - 2500
  - Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz - 2500
  - Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz - 2500
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.15.0
  - brotli: 1.0.7
  - cldr: 35.1
  - http_parser: 2.8.0
  - icu: 64.2
  - modules: 64
  - napi: 4
  - nghttp2: 1.39.2
  - node: 10.16.3
  - openssl: 1.1.1c
  - tz: 2019a
  - unicode: 12.1
  - uv: 1.28.0
  - v8: 6.8.275.32-node.54
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: ModuleNotFoundError: Module not found: Error: Can't resolve 'ember-classic-decorator' in '/private/var/folders/kp/fvcf7t_94cq0rfrfszk0ctzm_svdjr/T/embroider/c4c287/components'
    at factory.create (/Users/gokul/Home/my-app/node_modules/webpack/lib/Compilation.js:821:10)
    at factory (/Users/gokul/Home/my-app/node_modules/webpack/lib/NormalModuleFactory.js:397:22)
    at resolver (/Users/gokul/Home/my-app/node_modules/webpack/lib/NormalModuleFactory.js:130:21)
    at asyncLib.parallel (/Users/gokul/Home/my-app/node_modules/webpack/lib/NormalModuleFactory.js:224:22)
    at /Users/gokul/Home/my-app/node_modules/neo-async/async.js:2825:7
    at /Users/gokul/Home/my-app/node_modules/neo-async/async.js:6886:13
    at normalResolver.resolve (/Users/gokul/Home/my-app/node_modules/webpack/lib/NormalModuleFactory.js:214:25)
    at doResolve (/Users/gokul/Home/my-app/node_modules/enhanced-resolve/lib/Resolver.js:184:12)
    at hook.callAsync (/Users/gokul/Home/my-app/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (<anonymous>:15:1)
    at resolver.doResolve (/Users/gokul/Home/my-app/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5)
    at hook.callAsync (/Users/gokul/Home/my-app/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (<anonymous>:15:1)
    at hook.callAsync (/Users/gokul/Home/my-app/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (<anonymous>:12:1)
    at resolver.doResolve (/Users/gokul/Home/my-app/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
    at hook.callAsync (/Users/gokul/Home/my-app/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn4 (<anonymous>:48:1)
    at resolver.doResolve (/Users/gokul/Home/my-app/node_modules/enhanced-resolve/lib/ModuleKindPlugin.js:23:37)
    at hook.callAsync (/Users/gokul/Home/my-app/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (<anonymous>:15:1)
    at hook.callAsync (/Users/gokul/Home/my-app/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (<anonymous>:15:1)
    at args (/Users/gokul/Home/my-app/node_modules/enhanced-resolve/lib/forEachBail.js:30:14)
    at hook.callAsync (/Users/gokul/Home/my-app/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (<anonymous>:15:1)
    at resolver.doResolve (/Users/gokul/Home/my-app/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5)
    at hook.callAsync (/Users/gokul/Home/my-app/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (<anonymous>:15:1)
    at hook.callAsync (/Users/gokul/Home/my-app/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (<anonymous>:12:1)
    at resolver.doResolve (/Users/gokul/Home/my-app/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
    at hook.callAsync (/Users/gokul/Home/my-app/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn5 (<anonymous>:60:1)
    at hook.callAsync (/Users/gokul/Home/my-app/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (<anonymous>:12:1)
    at resolver.doResolve (/Users/gokul/Home/my-app/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
    at hook.callAsync (/Users/gokul/Home/my-app/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn1 (<anonymous>:24:1)
    at hook.callAsync (/Users/gokul/Home/my-app/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (<anonymous>:15:1)
    at hook.callAsync (/Users/gokul/Home/my-app/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn3 (<anonymous>:42:1)
    at hook.callAsync (/Users/gokul/Home/my-app/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (<anonymous>:12:1)
    at resolver.doResolve (/Users/gokul/Home/my-app/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
    at hook.callAsync (/Users/gokul/Home/my-app/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn2 (<anonymous>:33:1)
    at hook.callAsync (/Users/gokul/Home/my-app/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn2 (<anonymous>:33:1)
    at fs.stat (/Users/gokul/Home/my-app/node_modules/enhanced-resolve/lib/FileExistsPlugin.js:22:13)
    at process.nextTick (/Users/gokul/Home/my-app/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:73:15)
    at process._tickCallback (internal/process/next_tick.js:61:11)

  - code: [undefined]
  - codeFrame: Module not found: Error: Can't resolve 'ember-classic-decorator' in '/private/var/folders/kp/fvcf7t_94cq0rfrfszk0ctzm_svdjr/T/embroider/c4c287/components'
  - errorMessage: Module not found: Error: Can't resolve 'ember-classic-decorator' in '/private/var/folders/kp/fvcf7t_94cq0rfrfszk0ctzm_svdjr/T/embroider/c4c287/components'
        at PackagerRunner (@embroider/webpack)
-~- created here: -~-
    at new Plugin (/Users/gokul/Home/my-app/node_modules/broccoli-plugin/index.js:7:31)
    at new PackagerRunner (/Users/gokul/Home/my-app/node_modules/@embroider/core/src/to-broccoli-plugin.js:10:13)
    at Object.defaultPipeline [as compatBuild] (/Users/gokul/Home/my-app/node_modules/@embroider/compat/src/default-pipeline.js:35:12)
    at module.exports (/Users/gokul/Home/my-app/ember-cli-build.js:121:39)
    at Builder.readBuildFile (/Users/gokul/Home/my-app/node_modules/ember-cli/lib/models/builder.js:51:14)
    at Builder.setupBroccoliBuilder (/Users/gokul/Home/my-app/node_modules/ember-cli/lib/models/builder.js:65:22)
    at new Builder (/Users/gokul/Home/my-app/node_modules/ember-cli/lib/models/builder.js:31:10)
    at ServeTask.run (/Users/gokul/Home/my-app/node_modules/ember-cli/lib/tasks/serve.js:49:7)
    at Promise.resolve.then (/Users/gokul/Home/my-app/node_modules/ember-cli/lib/models/command.js:239:24)
    at tryCatcher (/Users/gokul/Home/my-app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:323:19)
    at invokeCallback (/Users/gokul/Home/my-app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:495:31)
    at /Users/gokul/Home/my-app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:559:14
    at flush (/Users/gokul/Home/my-app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:2402:5)
    at process._tickCallback (internal/process/next_tick.js:61:11)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

-~- (end) -~-
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
    - treeDir: [undefined]
  - message: Module not found: Error: Can't resolve 'ember-classic-decorator' in '/private/var/folders/kp/fvcf7t_94cq0rfrfszk0ctzm_svdjr/T/embroider/c4c287/components'
        at PackagerRunner (@embroider/webpack)
-~- created here: -~-
    at new Plugin (/Users/gokul/Home/my-app/node_modules/broccoli-plugin/index.js:7:31)
    at new PackagerRunner (/Users/gokul/Home/my-app/node_modules/@embroider/core/src/to-broccoli-plugin.js:10:13)
    at Object.defaultPipeline [as compatBuild] (/Users/gokul/Home/my-app/node_modules/@embroider/compat/src/default-pipeline.js:35:12)
    at module.exports (/Users/gokul/Home/my-app/ember-cli-build.js:121:39)
    at Builder.readBuildFile (/Users/gokul/Home/my-app/node_modules/ember-cli/lib/models/builder.js:51:14)
    at Builder.setupBroccoliBuilder (/Users/gokul/Home/my-app/node_modules/ember-cli/lib/models/builder.js:65:22)
    at new Builder (/Users/gokul/Home/my-app/node_modules/ember-cli/lib/models/builder.js:31:10)
    at ServeTask.run (/Users/gokul/Home/my-app/node_modules/ember-cli/lib/tasks/serve.js:49:7)
    at Promise.resolve.then (/Users/gokul/Home/my-app/node_modules/ember-cli/lib/models/command.js:239:24)
    at tryCatcher (/Users/gokul/Home/my-app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:323:19)
    at invokeCallback (/Users/gokul/Home/my-app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:495:31)
    at /Users/gokul/Home/my-app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:559:14
    at flush (/Users/gokul/Home/my-app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:2402:5)
    at process._tickCallback (internal/process/next_tick.js:61:11)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

-~- (end) -~-
  - name: BuildError
  - nodeAnnotation: @embroider/webpack
  - nodeName: PackagerRunner
  - originalErrorMessage: Module not found: Error: Can't resolve 'ember-classic-decorator' in '/private/var/folders/kp/fvcf7t_94cq0rfrfszk0ctzm_svdjr/T/embroider/c4c287/components'
  - stack: ModuleNotFoundError: Module not found: Error: Can't resolve 'ember-classic-decorator' in '/private/var/folders/kp/fvcf7t_94cq0rfrfszk0ctzm_svdjr/T/embroider/c4c287/components'
    at factory.create (/Users/gokul/Home/my-app/node_modules/webpack/lib/Compilation.js:821:10)
    at factory (/Users/gokul/Home/my-app/node_modules/webpack/lib/NormalModuleFactory.js:397:22)
    at resolver (/Users/gokul/Home/my-app/node_modules/webpack/lib/NormalModuleFactory.js:130:21)
    at asyncLib.parallel (/Users/gokul/Home/my-app/node_modules/webpack/lib/NormalModuleFactory.js:224:22)
    at /Users/gokul/Home/my-app/node_modules/neo-async/async.js:2825:7
    at /Users/gokul/Home/my-app/node_modules/neo-async/async.js:6886:13
    at normalResolver.resolve (/Users/gokul/Home/my-app/node_modules/webpack/lib/NormalModuleFactory.js:214:25)
    at doResolve (/Users/gokul/Home/my-app/node_modules/enhanced-resolve/lib/Resolver.js:184:12)
    at hook.callAsync (/Users/gokul/Home/my-app/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (<anonymous>:15:1)
    at resolver.doResolve (/Users/gokul/Home/my-app/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5)
    at hook.callAsync (/Users/gokul/Home/my-app/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (<anonymous>:15:1)
    at hook.callAsync (/Users/gokul/Home/my-app/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (<anonymous>:12:1)
    at resolver.doResolve (/Users/gokul/Home/my-app/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
    at hook.callAsync (/Users/gokul/Home/my-app/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn4 (<anonymous>:48:1)
    at resolver.doResolve (/Users/gokul/Home/my-app/node_modules/enhanced-resolve/lib/ModuleKindPlugin.js:23:37)
    at hook.callAsync (/Users/gokul/Home/my-app/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (<anonymous>:15:1)
    at hook.callAsync (/Users/gokul/Home/my-app/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (<anonymous>:15:1)
    at args (/Users/gokul/Home/my-app/node_modules/enhanced-resolve/lib/forEachBail.js:30:14)
    at hook.callAsync (/Users/gokul/Home/my-app/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (<anonymous>:15:1)
    at resolver.doResolve (/Users/gokul/Home/my-app/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5)
    at hook.callAsync (/Users/gokul/Home/my-app/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (<anonymous>:15:1)
    at hook.callAsync (/Users/gokul/Home/my-app/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (<anonymous>:12:1)
    at resolver.doResolve (/Users/gokul/Home/my-app/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
    at hook.callAsync (/Users/gokul/Home/my-app/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn5 (<anonymous>:60:1)
    at hook.callAsync (/Users/gokul/Home/my-app/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (<anonymous>:12:1)
    at resolver.doResolve (/Users/gokul/Home/my-app/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
    at hook.callAsync (/Users/gokul/Home/my-app/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn1 (<anonymous>:24:1)
    at hook.callAsync (/Users/gokul/Home/my-app/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (<anonymous>:15:1)
    at hook.callAsync (/Users/gokul/Home/my-app/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn3 (<anonymous>:42:1)
    at hook.callAsync (/Users/gokul/Home/my-app/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (<anonymous>:12:1)
    at resolver.doResolve (/Users/gokul/Home/my-app/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
    at hook.callAsync (/Users/gokul/Home/my-app/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn2 (<anonymous>:33:1)
    at hook.callAsync (/Users/gokul/Home/my-app/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn2 (<anonymous>:33:1)
    at fs.stat (/Users/gokul/Home/my-app/node_modules/enhanced-resolve/lib/FileExistsPlugin.js:22:13)
    at process.nextTick (/Users/gokul/Home/my-app/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:73:15)
    at process._tickCallback (internal/process/next_tick.js:61:11)


=================================================================================
```
</details>

Any help would be great.

cc: @pzuraq

**Comment by stefanpenner** [comment]
@gokatz I'm noticing this as well.

**Comment by pzuraq** [comment]
This is probably due to the fact that `ember-classic-decorator` doesn't actually expose exports, it's all done via `vendor` since we want to remove it from production builds.

This could probably be fixed for Embroider, but the larger issue is that the `@classic` decorator and import are supposed to be fully removed from production builds. Can Embroider remove arbitrary code/run arbitrary babel transforms like that?

**Comment by stefanpenner** [comment]
I've put together a failing PR that demonstrates this issue (and hopefully get's us regression testing once merged): https://github.com/embroider-build/embroider/pull/323

**Comment by gokatz** [comment]
Thanks for looking into this @stefanpenner and happy birthday 🎂

**Comment by stefanpenner** [comment]
@gokatz thank you kindly :)

**Comment by stefanpenner** [comment]
I believe this is working "As expected" in embroider, and rather the solution may need to be in ember-classic-decorators.

Some ideas on how to fix 

* Future approach, would be likely to use embroider's macro system to conditionally introduce this dependency.
* Follow the approach of `@ember/object` and friends, and simply convert the module import to a global, and include that global via vendor.
* An alternative, and one I think we should avoid using, would be to use a backdoor embroider has which supports an unfortunate (and not to be advertised feature of ember-cli)...

**Comment by stefanpenner** [comment]
chatting with @pzuraq, he's down with 2. so I'll take a stab at that this afternoon.

**Comment by stefanpenner** [comment]
I sketched out a solution, and will likely have time late tomorrow or this weekend to make it actually work: https://github.com/pzuraq/ember-classic-decorator/pull/11

**Comment by drouhard** [comment]
Can this issue be closed now? The fix in ember-classic-decorator referenced above was merged.

**Comment by ef4** [comment]
Yes, though we also have a separate unrelated issue with ember-classic-decorator. https://github.com/emberjs/ember-classic-decorator/issues/37
