### ISSUE TITLE
Error in addon / Funnel: Expected Broccoli node, got null for inputNodes[0]

### ISSUE THREAD

**Issue by lifeart** [embroider-build/embroider#34]
```
ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - code: [undefined]
  - codeFrame: [undefined]
  - errorMessage: Funnel: Expected Broccoli node, got null for inputNodes[0]
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: Funnel: Expected Broccoli node, got null for inputNodes[0]
  - name: TypeError
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: TypeError: Funnel: Expected Broccoli node, got null for inputNodes[0]
    at Funnel.Plugin (C:\Users\lifeart\Documents\repos\ts-test\node_modules\broccoli-plugin\index.js:23:13)
    at new Funnel (C:\Users\lifeart\Documents\repos\ts-test\node_modules\broccoli-funnel\index.js:57:10)
    at V1App.combinedVendor (C:\Users\lifeart\Documents\repos\ts-test\node_modules\@embroider\compat\src\v1-app.js:269:13)
    at V1App.synthesizeVendorPackage (C:\Users\lifeart\Documents\repos\ts-test\node_modules\@embroider\compat\src\v1-app.js:299:67)
    at CompatAddons.getVendorPackage (C:\Users\lifeart\Documents\repos\ts-test\node_modules\@embroider\compat\src\compat-addons.js:77:22)
    at new CompatAddons (C:\Users\lifeart\Documents\repos\ts-test\node_modules\@embroider\compat\src\compat-addons.js:34:32)
    at Object.defaultPipeline [as compatBuild] (C:\Users\lifeart\Documents\repos\ts-test\node_modules\@embroider\compat\src\default-pipeline.js:11:18)
    at module.exports (C:\Users\lifeart\Documents\repos\ts-test\ember-cli-build.js:17:38)
    at Builder.readBuildFile (C:\Users\lifeart\Documents\repos\ts-test\node_modules\ember-cli\lib\models\builder.js:52:14)
    at Builder.setupBroccoliBuilder (C:\Users\lifeart\Documents\repos\ts-test\node_modules\ember-cli\lib\models\builder.js:66:22)
```

**Comment by ef4** [comment]
Thanks for testing and reporting.

Does your app customize the vendor tree in ember-cli-build.js? Do you have the default `vendor` directory that all ember apps start with?

If you can debug further, try to put a breakpoint here

```
    at V1App.combinedVendor (C:\Users\lifeart\Documents\repos\ts-test\node_modules\@embroider\compat\src\v1-app.js:269:13)
```
and see which call to `new Funnel` is getting an undefined tree, and see if you can figure out why.

**Comment by lifeart** [comment]
```ts
private combinedVendor(addonTrees: Tree[]): Tree {
    return mergeTrees(
      [
        ...addonTrees.map(tree => new Funnel(tree, {
          allowEmpty: true,
          srcDir: 'vendor',
          destDir: 'vendor',
        })),
        new Funnel(this.vendorTree, {
          destDir: 'vendor'
        })
      ],
      { overwrite: true }
    );
  }
```

```
this.vendorTree === null
``` in new Funnel(this.vendorTree,

**Comment by lifeart** [comment]
reproduction repo - https://github.com/lifeart/reproduction-emberdoider-ts-addon
`yarn; ember s` -> Error

**Comment by NullVoxPopuli** [comment]
this occasionally still happens even with embroider/* 3.2

<details><summary>info</summary>

```
=================================================================================

ENV Summary:

  TIME: Sun Jul 23 2023 19:00:26 GMT-0400 (Eastern Daylight Time)
  TITLE: ember
  ARGV:
  - 🏠/.volta/tools/image/node/18.17.0/bin/node
  - <repo>/node_modules/.pnpm/ember-cli@5.1.0/node_modules/ember-cli/bin/ember
  - s
  EXEC_PATH: 🏠/.volta/tools/image/node/18.17.0/bin/node
  TMPDIR: /tmp
  SHELL: /bin/bash
  PATH:
  - ./node_modules/.bin
  - 🏠/.volta/tools/image/pnpm/8.6.9/bin
  - 🏠/.volta/tools/image/yarn/1.22.19/bin
  - 🏠/.volta/tools/image/node/18.17.0/bin
  - 🏠/.local/bin
  - 🏠/.volta/bin
  - 🏠/Applications
  - 🏠/apps/phantomjs/bin
  - 🏠/scripts/system-utils
  - 🏠/scripts/git
  - 🏠/scripts/rails
  - 🏠/scripts
  - 🏠/.local/bin
  - 🏠/.volta/bin
  - 🏠/Applications
  - 🏠/apps/phantomjs/bin
  - 🏠/scripts/system-utils
  - 🏠/scripts/git
  - 🏠/scripts/rails
  - 🏠/scripts
  - /usr/local/sbin
  - /usr/local/bin
  - /usr/sbin
  - /usr/bin
  - /sbin
  - /bin
  - /usr/games
  - /usr/local/games
  - /snap/bin
  - /snap/bin
  - 🏠/.fzf/bin
  PLATFORM: linux x64
  FREEMEM: 37828837376
  TOTALMEM: 67211022336
  UPTIME: 180392.58
  LOADAVG: 1.1,1.07,1.03
  CPUS:
  - 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz - 2395
  - 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz - 4184
  - 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz - 1045
  - 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz - 2400
  - 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz - 2400
  - 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz - 2400
  - 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz - 3974
  - 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz - 632
  ENDIANNESS: LE
  VERSIONS:
  - acorn: 8.8.2
  - ada: 2.5.0
  - ares: 1.19.1
  - brotli: 1.0.9
  - cldr: 43.0
  - icu: 73.1
  - llhttp: 6.0.11
  - modules: 108
  - napi: 9
  - nghttp2: 1.52.0
  - nghttp3: 0.7.0
  - ngtcp2: 0.8.1
  - node: 18.17.0
  - openssl: 3.0.9+quic
  - simdutf: 3.2.12
  - tz: 2023c
  - undici: 5.22.1
  - unicode: 15.0
  - uv: 1.44.2
  - uvwasi: 0.0.18
  - v8: 10.2.154.26-node.26
  - zlib: 1.2.13.1-motley

ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - code: [undefined]
  - codeFrame: [undefined]
  - errorMessage: Funnel (tests/index.html): Expected Broccoli node, got null for inputNodes[0]
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: Funnel (tests/index.html): Expected Broccoli node, got null for inputNodes[0]
  - name: TypeError
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: TypeError: Funnel (tests/index.html): Expected Broccoli node, got null for inputNodes[0]
    at new Plugin (<repo>/node_modules/.pnpm/broccoli-plugin@4.0.7/node_modules/broccoli-plugin/dist/index.js:63:23)
    at new Funnel (<repo>/node_modules/.pnpm/broccoli-funnel@3.0.8/node_modules/broccoli-funnel/index.js:55:5)
    at funnel (<repo>/node_modules/.pnpm/broccoli-funnel@3.0.8/node_modules/broccoli-funnel/index.js:508:10)
    at get testIndexTree [as testIndexTree] (<repo>/node_modules/.pnpm/@embroider+compat@3.2.0_@embroider+core@3.2.0/node_modules/@embroider/compat/src/compat-app.js:164:51)
    at get htmlTree [as htmlTree] (<repo>/node_modules/.pnpm/@embroider+compat@3.2.0_@embroider+core@3.2.0/node_modules/@embroider/compat/src/compat-app.js:142:78)
    at CompatApp.inTrees (<repo>/node_modules/.pnpm/@embroider+compat@3.2.0_@embroider+core@3.2.0/node_modules/@embroider/compat/src/compat-app.js:646:28)
    at tree (<repo>/node_modules/.pnpm/@embroider+compat@3.2.0_@embroider+core@3.2.0/node_modules/@embroider/compat/src/compat-app.js:675:32)
    at get tree [as tree] (<repo>/node_modules/.pnpm/@embroider+compat@3.2.0_@embroider+core@3.2.0/node_modules/@embroider/compat/src/compat-app.js:694:24)
    at new PackagerRunner (<repo>/node_modules/.pnpm/@embroider+core@3.2.0/node_modules/@embroider/core/src/to-broccoli-plugin.js:11:26)
    at Object.defaultPipeline (<repo>/node_modules/.pnpm/@embroider+compat@3.2.0_@embroider+core@3.2.0/node_modules/@embroider/compat/src/default-pipeline.js:38:12)

=================================================================================
```

</summary>

This time, I ran in to it while trying to run `ember s` on one of ember-data's test-apps.

I'm checking what could be the issue.
Repro is here: https://github.com/emberjs/data/compare/main...NullVoxPopuli:chore/fix-perf-test-app?expand=1

**Comment by NullVoxPopuli** [comment]
just as the error hinted at, in this particular case, the tests directory was missing.

tests/index.html is required,
as is tests/test-helper.js/ts

So, I suppose the issue here is maybe one of two things:
- we need to either provide a better error about what the user can do (add tests directory / files if they are missing)
- or not error if these files don't exist.

Though, I imagine that eventual vite-usage would mean that the `/tests` stuff would be lazily checked, which would solve the problem regardless -- and it'd be easier to provide a better error for that situation ( as in, we can rely on vite to handle and report the error )
