### ISSUE TITLE
Seems to break with latest ember-cli-typescript

### ISSUE THREAD

**Issue by makepanic** [embroider-build/embroider#352]
I'm in the progress of trying embroider with our app.

Seems like something is breaking in regards to the latest TS version (via ember-cli-typescript):

```
unable to resolve babel plugin @babel/plugin-proposal-optional-chaining from

- broccoliBuilderErrorStack: Error: unable to resolve babel plugin @babel/plugin-proposal-optional-chaining from /tmp/embroider/13b7f6/project
    at PortableBabelConfig.resolveBabelPlugin (/path/to/project/node_modules/@embroider/core/src/portable-babel-config.js:74:27)
    at PortableBabelConfig.makePortable (/path/to/project/node_modules/@embroider/core/src/portable-babel-config.js:22:29)
    at /path/to/project/node_modules/@embroider/core/src/portable-plugin-config.js:64:55
```

The only usage of the babel plugin from our yarn.lock:

```
ember-cli-typescript@^3.1.1:
  version "3.1.1"
  resolved "https://registry.yarnpkg.com/ember-cli-typescript/-/ember-cli-typescript-3.1.1.tgz#a5a12ebf915e43ded7bf6bb460ecea4b67b0d95b"
  integrity sha512-HCjM5EZ29Yh94Jy/M2+MVkS9LdtOoGYtYLIcZ4F7umJaRJM67ku/xCyN/2r+uTeYTNdpJN9+HWx30a6yyAbfRA==
  dependencies:
    "@babel/plugin-proposal-nullish-coalescing-operator" "^7.4.4"
    "@babel/plugin-proposal-optional-chaining" "^7.6.0"
    "@babel/plugin-transform-typescript" "~7.7.0"
```

e-c-ts is adding the babel plugins like this:

https://github.com/typed-ember/ember-cli-typescript/blob/39e3b7f2f9cec078b69e732db15da4471af392c4/ts/addon.ts#L84

So maybe the issue is in `ember-cli-babel-plugin-helpers` adding the plugin in a way that embroider isn't supporting: https://github.com/dfreeman/ember-cli-babel-plugin-helpers/blob/master/src/index.ts#L77

**Comment by NullVoxPopuli** [comment]
I got this error:
```
Build Error (WaitForTrees)

unable to resolve babel plugin @babel/plugin-transform-typescript from /tmp/embroider/25570d


Stack Trace and Error Report: /tmp/error.dump.d8754024c9f8aad3ded80e808f409b6f.log
```
```
  - broccoliBuilderErrorStack: Error: unable to resolve babel plugin @babel/plugin-transform-typescript from /tmp/embroider/25570d
    at PortableBabelConfig.resolveBabelPlugin (/home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/packages/frontend/node_modules/@embroider/core/src/portable-babel-config.js:74:27)
    at PortableBabelConfig.makePortable (/home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/packages/frontend/node_modules/@embroider/core/src/portable-babel-config.js:22:29)
    at value.map (/home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/packages/frontend/node_modules/@embroider/core/src/portable-plugin-config.js:64:55)
    at Array.map (<anonymous>:null:null)
    at PortableBabelConfig.makePortable (/home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/packages/frontend/node_modules/@embroider/core/src/portable-plugin-config.js:64:26)
    at PortableBabelConfig.makePortable (/home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/packages/frontend/node_modules/@embroider/core/src/portable-babel-config.js:35:22)
    at mapValues_1.default (/home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/packages/frontend/node_modules/@embroider/core/src/portable-plugin-config.js:74:84)
    at /home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/packages/frontend/node_modules/lodash/mapValues.js:38:34
    at /home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/packages/frontend/node_modules/lodash/_createBaseFor.js:17:11
    at baseForOwn (/home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/packages/frontend/node_modules/lodash/_baseForOwn.js:13:20)
    at Object.mapValues [as default] (/home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/packages/frontend/node_modules/lodash/mapValues.js:37:3)
    at PortableBabelConfig.makePortable (/home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/packages/frontend/node_modules/@embroider/core/src/portable-plugin-config.js:74:47)
    at PortableBabelConfig.makePortable (/home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/packages/frontend/node_modules/@embroider/core/src/portable-babel-config.js:35:22)
    at PortableBabelConfig.ensurePortable (/home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/packages/frontend/node_modules/@embroider/core/src/portable-plugin-config.js:40:40)
    at PortableBabelConfig.get [as isParallelSafe] (/home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/packages/frontend/node_modules/@embroider/core/src/portable-plugin-config.js:34:29)
    at AppBuilder.addBabelConfig (/home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/packages/frontend/node_modules/@embroider/core/src/app.js:505:26)
    at AppBuilder.build (/home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/packages/frontend/node_modules/@embroider/core/src/app.js:443:14)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by makepanic** [comment]
will check again after https://github.com/typed-ember/ember-cli-typescript/pull/946 is ready. Seems like that's the issue.

**Comment by makepanic** [comment]
Checked this again with the fix that landed in ember-cli-typescript https://github.com/typed-ember/ember-cli-typescript/commit/c9314993aff1bcfa5ffe10578ddbbb80bc89a0bf and it works.

**Comment by pranavliag** [comment]
Hii.. Superb addon 👍 
@makepanic I am getting same error ...
using latest version of embroider(0.9.0) and ember-cli-typescript.

in `ember-cli-build.js`
```
 const { Webpack } = require('@embroider/webpack');
 return require('@embroider/compat').compatBuild(app, Webpack);
```

**Comment by makepanic** [comment]
The fix in ember-cli-typescript wasn't released yet. You can resolve the package to https://github.com/typed-ember/ember-cli-typescript/commit/c9314993aff1bcfa5ffe10578ddbbb80bc89a0bf if you want use the fix in your app

**Comment by jamescdavis** [comment]
[ember-cli-typescript@3.1.2](https://github.com/typed-ember/ember-cli-typescript/releases/tag/v3.1.2) has been released and includes this fix.

**Comment by NullVoxPopuli** [comment]
looks like my error has moved on to a different issue!
```
This problem is likely caused by another plugin injecting
"QUnit" without registering it in the scope tracker. If you are the author
 of that plugin, please use "scope.registerDeclaration(declarationPath)".
(node:6890) UnhandledPromiseRejectionWarning: ModuleBuildError: Module build failed (from /home/lprestonsegoiii/Development/NullVoxPopuli/emberclear/packages/frontend/node_modules/@embroider/webpack/src/webpack-hbs-loader.js):
Error: Missing component Chat::ChatHistory::NewMessages in /tmp/embroider/25570d/pods/components/pod/chat/chat-history/template.hbs
```
(it seems to not support template-co-location)
