### ISSUE TITLE
Can't resolve 'qunit-dom'

### ISSUE THREAD

**Issue by makepanic** [embroider-build/embroider#356]
I'm in the progress of trying embroider with our app.

```
Build Error (PackagerRunner)

Module not found: Error: Can't resolve 'qunit-dom' in '/tmp/embroider/13b7f6/app/tests'
```

It seems like there's an issue when importing `qunit-dom` in our `test-helper.js`. 
I've also tried to change it to `test-helper.ts` but that doesn't seem to change anything.

```
=================================================================================

ENV Summary:

  TIME: Thu Nov 14 2019 08:18:49 GMT+0100 (Central European Standard Time)
  TITLE: ember
  ARGV:
  - /usr/bin/node
  - /path/to/app/app/node_modules/.bin/ember
  - serve
  EXEC_PATH: /usr/bin/node
  TMPDIR: /tmp
  SHELL: /usr/bin/zsh
  PLATFORM: linux x64
  FREEMEM: 2138923008
  TOTALMEM: 20857180160
  UPTIME: 2394
  LOADAVG: 3.55126953125,3.62744140625,3.53662109375
  CPUS:
  - Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz - 951
  - Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz - 998
  - Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz - 835
  - Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz - 1230
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.15.0
  - brotli: 1.0.7
  - cldr: 35.1
  - http_parser: 2.8.0
  - icu: 64.2
  - llhttp: 1.1.4
  - modules: 72
  - napi: 5
  - nghttp2: 1.39.2
  - node: 12.13.0
  - openssl: 1.1.1d
  - tz: 2019a
  - unicode: 12.1
  - uv: 1.33.1
  - v8: 7.7.299.13-node.12
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: ModuleNotFoundError: Module not found: Error: Can't resolve 'qunit-dom' in '/tmp/embroider/13b7f6/app/tests'
    at /path/to/app/node_modules/webpack/lib/Compilation.js:821:10
    at /path/to/app/node_modules/webpack/lib/NormalModuleFactory.js:397:22
    at /path/to/app/node_modules/webpack/lib/NormalModuleFactory.js:130:21
    at /path/to/app/node_modules/webpack/lib/NormalModuleFactory.js:224:22
    at /path/to/app/node_modules/webpack/node_modules/neo-async/async.js:2825:7
    at /path/to/app/node_modules/webpack/node_modules/neo-async/async.js:6886:13
    at /path/to/app/node_modules/webpack/lib/NormalModuleFactory.js:214:25
    at /path/to/app/node_modules/enhanced-resolve/lib/Resolver.js:184:12
    at /path/to/app/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/path/to/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
  - code: [undefined]
  - codeFrame: Module not found: Error: Can't resolve 'qunit-dom' in '/tmp/embroider/13b7f6/app/tests'
  - errorMessage: Module not found: Error: Can't resolve 'qunit-dom' in '/tmp/embroider/13b7f6/app/tests'
        at PackagerRunner (@embroider/webpack)
-~- created here: -~-
    at new Plugin (/path/to/app/node_modules/@embroider/core/node_modules/broccoli-plugin/dist/index.js:42:31)
    at new PackagerRunner (/path/to/app/node_modules/@embroider/core/src/to-broccoli-plugin.js:10:13)
    at Object.defaultPipeline [as compatBuild] (/path/to/app/node_modules/@embroider/compat/src/default-pipeline.js:35:12)
    at module.exports (/path/to/app/app/ember-cli-build.js:121:19)
    at Builder.readBuildFile (/path/to/app/node_modules/ember-cli/lib/models/builder.js:52:14)
    at Builder.setupBroccoliBuilder (/path/to/app/node_modules/ember-cli/lib/models/builder.js:66:22)
    at new Builder (/path/to/app/node_modules/ember-cli/lib/models/builder.js:32:10)
    at ServeTask.run (/path/to/app/node_modules/ember-cli/lib/tasks/serve.js:49:7)
    at /path/to/app/node_modules/ember-cli/lib/models/command.js:239:24
    at tryCatcher (/path/to/app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:326:21)
-~- (end) -~-
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
    - treeDir: [undefined]
  - message: Module not found: Error: Can't resolve 'qunit-dom' in '/tmp/embroider/13b7f6/app/tests'
        at PackagerRunner (@embroider/webpack)
-~- created here: -~-
    at new Plugin (/path/to/app/node_modules/@embroider/core/node_modules/broccoli-plugin/dist/index.js:42:31)
    at new PackagerRunner (/path/to/app/node_modules/@embroider/core/src/to-broccoli-plugin.js:10:13)
    at Object.defaultPipeline [as compatBuild] (/path/to/app/node_modules/@embroider/compat/src/default-pipeline.js:35:12)
    at module.exports (/path/to/app/app/ember-cli-build.js:121:19)
    at Builder.readBuildFile (/path/to/app/node_modules/ember-cli/lib/models/builder.js:52:14)
    at Builder.setupBroccoliBuilder (/path/to/app/node_modules/ember-cli/lib/models/builder.js:66:22)
    at new Builder (/path/to/app/node_modules/ember-cli/lib/models/builder.js:32:10)
    at ServeTask.run (/path/to/app/node_modules/ember-cli/lib/tasks/serve.js:49:7)
    at /path/to/app/node_modules/ember-cli/lib/models/command.js:239:24
    at tryCatcher (/path/to/app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:326:21)
-~- (end) -~-
  - name: BuildError
  - nodeAnnotation: @embroider/webpack
  - nodeName: PackagerRunner
  - originalErrorMessage: Module not found: Error: Can't resolve 'qunit-dom' in '/tmp/embroider/13b7f6/app/tests'
  - stack: ModuleNotFoundError: Module not found: Error: Can't resolve 'qunit-dom' in '/tmp/embroider/13b7f6/app/tests'
    at /path/to/app/node_modules/webpack/lib/Compilation.js:821:10
    at /path/to/app/node_modules/webpack/lib/NormalModuleFactory.js:397:22
    at /path/to/app/node_modules/webpack/lib/NormalModuleFactory.js:130:21
    at /path/to/app/node_modules/webpack/lib/NormalModuleFactory.js:224:22
    at /path/to/app/node_modules/webpack/node_modules/neo-async/async.js:2825:7
    at /path/to/app/node_modules/webpack/node_modules/neo-async/async.js:6886:13
    at /path/to/app/node_modules/webpack/lib/NormalModuleFactory.js:214:25
    at /path/to/app/node_modules/enhanced-resolve/lib/Resolver.js:184:12
    at /path/to/app/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/path/to/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)

=================================================================================
```

Our package.json has `qunit-dom` in the `devDependencies`. I've also tried to move it into dependencies but that didn't change things.

I guess this is somewhat related to qunit-dom being an ember-addon which we probably can't really import in another module.
If I change the qunit-dom package.json to `"main": "dist/qunit-dom.js"` it's throwing an error because qunit tries to extend [`QUnit` without importing it](https://github.com/simplabs/qunit-dom/blob/master/lib/qunit-dom.ts#L11):

```
QUnit is not defined
```

It seems to build if I remove the `qunit-dom` import.

**Comment by ef4** [comment]
I fixed this upstream via https://github.com/simplabs/qunit-dom/pull/542

The import is purely for the convenience of the typescript compiler, it doesn't actually cause any code to be included.  As a workaround until that PR lands, you can probably get the types included a different way, like using  a [triple-slash directive](https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html) pointing at the `qunit-dom/dist/qunit-dom.d.ts`.
