### ISSUE TITLE
precompile is not a function

### ISSUE THREAD

**Issue by josemarluedke** [embroider-build/embroider#37]
After #19 was fixed, I now get the following error: 

```
ERROR in ./tests/integration/components/my-awesome-component-test.js
Module build failed (from /Users/josemarluedke/code/tmp/my-embroider-test/node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 0)
/private/tmp/embroider-workspace/tests/integration/components/my-awesome-component-test.js: precompile is not a function

    at compileTemplate (/Users/josemarluedke/code/tmp/my-embroider-test/node_modules/babel-plugin-htmlbars-inline-precompile/index.js:11:61)
    at PluginPass.TaggedTemplateExpression (/Users/josemarluedke/code/tmp/my-embroider-test/node_modules/babel-plugin-htmlbars-inline-precompile/index.js:53:38)
    at newFn (/Users/josemarluedke/code/tmp/my-embroider-test/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/Users/josemarluedke/code/tmp/my-embroider-test/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/josemarluedke/code/tmp/my-embroider-test/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/josemarluedke/code/tmp/my-embroider-test/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/Users/josemarluedke/code/tmp/my-embroider-test/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/Users/josemarluedke/code/tmp/my-embroider-test/node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (/Users/josemarluedke/code/tmp/my-embroider-test/node_modules/babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (/Users/josemarluedke/code/tmp/my-embroider-test/node_modules/babel-traverse/lib/index.js:114:17)
 @ ./assets/test.js 187:0-71
Build Error (PackagerRunner)

webpack returned errors to @embroider/webpack
```

A reproduction can be found [here](https://github.com/josemarluedke/my-embroider-test) at SHA `12253f7`.

Let me know if this report doesn't help.

**Comment by ef4** [comment]
Thanks for sharing a working reproduction. It looks like we are failing to notice that part of the babel plugin config is non-serializable.

**Comment by sabinbajracharya** [comment]
Running a new Ember project (with **@ember/octane-app-blueprint**) results in the following error.
But **runs ok** without using the blueprint.
```
ENV Summary:

  TIME: Thu Oct 17 2019 16:50:54 GMT+0545 (Nepal Time)
  TITLE: ember
  ARGV:
  - /Users/sabin/.nvm/versions/node/v10.16.3/bin/node
  - /Users/sabin/.nvm/versions/node/v10.16.3/bin/ember
  - serve
  EXEC_PATH: /Users/sabin/.nvm/versions/node/v10.16.3/bin/node
  TMPDIR: /var/folders/8j/c5v7_7155n99ytqr75sf1kgh0000gn/T
  SHELL: /bin/bash
  PATH:
  - /Users/sabin/.nvm/versions/node/v10.16.3/bin
  - /Users/sabin/.cargo/bin
  - /usr/local/bin
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  - /Users/sabin/Library/Android/sdk/platform-tools/
  - /Users/sabin/Programs/flutter/bin/
  - /Users/sabin/Programs/flutter/bin/cache/dart-sdk/bin/
  - /Users/sabin/.pub-cache/bin
  - /Users/sabin/Library/Python/2.7/bin
  - /Users/sabin/Library/Android/sdk/build-tools/28.0.3
  PLATFORM: darwin x64
  FREEMEM: 144805888
  TOTALMEM: 17179869184
  UPTIME: 17929
  LOADAVG: 1.79296875,1.82373046875,1.89404296875
  CPUS:
  - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz - 2800
  - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz - 2800
  - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz - 2800
  - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz - 2800
  - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz - 2800
  - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz - 2800
  - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz - 2800
  - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz - 2800
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.15.0
  - brotli: 1.0.7
  - cldr: 35.1
  - http_parser: 2.8.0
  - icu: 64.2
  - modules: 64
  - napi: 4
  - nghttp2: 1.39.2
  - node: 10.16.3
  - openssl: 1.1.1c
  - tz: 2019a
  - unicode: 12.1
  - uv: 1.28.0
  - v8: 6.8.275.32-node.54
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: ModuleBuildError: Module build failed (from /Users/sabin/Documents/startup/ember-quickstart/node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 7)
precompile is not a function

    at compileTemplate (/Users/sabin/Documents/startup/ember-quickstart/node_modules/babel-plugin-htmlbars-inline-precompile/index.js:91:28)
    at PluginPass.TaggedTemplateExpression (/Users/sabin/Documents/startup/ember-quickstart/node_modules/babel-plugin-htmlbars-inline-precompile/index.js:174:26)
    at newFn (/Users/sabin/Documents/startup/ember-quickstart/node_modules/@babel/traverse/lib/visitors.js:195:21)
    at NodePath._call (/Users/sabin/Documents/startup/ember-quickstart/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/Users/sabin/Documents/startup/ember-quickstart/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/Users/sabin/Documents/startup/ember-quickstart/node_modules/@babel/traverse/lib/path/context.js:88:12)
    at TraversalContext.visitQueue (/Users/sabin/Documents/startup/ember-quickstart/node_modules/@babel/traverse/lib/context.js:120:16)
    at TraversalContext.visitSingle (/Users/sabin/Documents/startup/ember-quickstart/node_modules/@babel/traverse/lib/context.js:92:19)
    at TraversalContext.visit (/Users/sabin/Documents/startup/ember-quickstart/node_modules/@babel/traverse/lib/context.js:148:19)
    at Function.traverse.node (/Users/sabin/Documents/startup/ember-quickstart/node_modules/@babel/traverse/lib/index.js:96:17)
    at runLoaders (/Users/sabin/Documents/startup/ember-quickstart/node_modules/webpack/lib/NormalModule.js:301:20)
    at /Users/sabin/Documents/startup/ember-quickstart/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/sabin/Documents/startup/ember-quickstart/node_modules/loader-runner/lib/LoaderRunner.js:182:20
    at context.callback (/Users/sabin/Documents/startup/ember-quickstart/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.callback (/Users/sabin/Documents/startup/ember-quickstart/node_modules/thread-loader/dist/index.js:51:7)
    at /Users/sabin/Documents/startup/ember-quickstart/node_modules/async/internal/queue.js:101:31
    at /Users/sabin/Documents/startup/ember-quickstart/node_modules/async/internal/onlyOnce.js:12:16
    at callback (/Users/sabin/Documents/startup/ember-quickstart/node_modules/thread-loader/dist/WorkerPool.js:161:21)
    at /Users/sabin/Documents/startup/ember-quickstart/node_modules/thread-loader/dist/WorkerPool.js:187:17
    at /Users/sabin/Documents/startup/ember-quickstart/node_modules/async/internal/map.js:32:9
  - code: [undefined]
  - codeFrame: Module build failed (from /Users/sabin/Documents/startup/ember-quickstart/node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 7)
precompile is not a function

    at compileTemplate (/Users/sabin/Documents/startup/ember-quickstart/node_modules/babel-plugin-htmlbars-inline-precompile/index.js:91:28)
    at PluginPass.TaggedTemplateExpression (/Users/sabin/Documents/startup/ember-quickstart/node_modules/babel-plugin-htmlbars-inline-precompile/index.js:174:26)
    at newFn (/Users/sabin/Documents/startup/ember-quickstart/node_modules/@babel/traverse/lib/visitors.js:195:21)
    at NodePath._call (/Users/sabin/Documents/startup/ember-quickstart/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/Users/sabin/Documents/startup/ember-quickstart/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/Users/sabin/Documents/startup/ember-quickstart/node_modules/@babel/traverse/lib/path/context.js:88:12)
    at TraversalContext.visitQueue (/Users/sabin/Documents/startup/ember-quickstart/node_modules/@babel/traverse/lib/context.js:120:16)
    at TraversalContext.visitSingle (/Users/sabin/Documents/startup/ember-quickstart/node_modules/@babel/traverse/lib/context.js:92:19)
    at TraversalContext.visit (/Users/sabin/Documents/startup/ember-quickstart/node_modules/@babel/traverse/lib/context.js:148:19)
    at Function.traverse.node (/Users/sabin/Documents/startup/ember-quickstart/node_modules/@babel/traverse/lib/index.js:96:17)
  - errorMessage: Module build failed (from /Users/sabin/Documents/startup/ember-quickstart/node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 7)
precompile is not a function

    at compileTemplate (/Users/sabin/Documents/startup/ember-quickstart/node_modules/babel-plugin-htmlbars-inline-precompile/index.js:91:28)
    at PluginPass.TaggedTemplateExpression (/Users/sabin/Documents/startup/ember-quickstart/node_modules/babel-plugin-htmlbars-inline-precompile/index.js:174:26)
    at newFn (/Users/sabin/Documents/startup/ember-quickstart/node_modules/@babel/traverse/lib/visitors.js:195:21)
    at NodePath._call (/Users/sabin/Documents/startup/ember-quickstart/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/Users/sabin/Documents/startup/ember-quickstart/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/Users/sabin/Documents/startup/ember-quickstart/node_modules/@babel/traverse/lib/path/context.js:88:12)
    at TraversalContext.visitQueue (/Users/sabin/Documents/startup/ember-quickstart/node_modules/@babel/traverse/lib/context.js:120:16)
    at TraversalContext.visitSingle (/Users/sabin/Documents/startup/ember-quickstart/node_modules/@babel/traverse/lib/context.js:92:19)
    at TraversalContext.visit (/Users/sabin/Documents/startup/ember-quickstart/node_modules/@babel/traverse/lib/context.js:148:19)
    at Function.traverse.node (/Users/sabin/Documents/startup/ember-quickstart/node_modules/@babel/traverse/lib/index.js:96:17)
        at PackagerRunner (@embroider/webpack)
-~- created here: -~-
    at new Plugin (/Users/sabin/Documents/startup/ember-quickstart/node_modules/@embroider/core/node_modules/broccoli-plugin/dist/index.js:42:31)
    at new PackagerRunner (/Users/sabin/Documents/startup/ember-quickstart/node_modules/@embroider/core/src/to-broccoli-plugin.js:10:13)
    at Object.defaultPipeline [as compatBuild] (/Users/sabin/Documents/startup/ember-quickstart/node_modules/@embroider/compat/src/default-pipeline.js:35:12)
    at module.exports (/Users/sabin/Documents/startup/ember-quickstart/ember-cli-build.js:25:39)
    at Builder.readBuildFile (/Users/sabin/Documents/startup/ember-quickstart/node_modules/ember-cli/lib/models/builder.js:52:14)
    at Builder.setupBroccoliBuilder (/Users/sabin/Documents/startup/ember-quickstart/node_modules/ember-cli/lib/models/builder.js:66:22)
    at new Builder (/Users/sabin/Documents/startup/ember-quickstart/node_modules/ember-cli/lib/models/builder.js:32:10)
    at ServeTask.run (/Users/sabin/Documents/startup/ember-quickstart/node_modules/ember-cli/lib/tasks/serve.js:49:7)
    at Promise.resolve.then (/Users/sabin/Documents/startup/ember-quickstart/node_modules/ember-cli/lib/models/command.js:239:24)
    at tryCatcher (/Users/sabin/Documents/startup/ember-quickstart/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:326:21)
-~- (end) -~-
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
    - treeDir: [undefined]
  - message: Module build failed (from /Users/sabin/Documents/startup/ember-quickstart/node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 7)
precompile is not a function

    at compileTemplate (/Users/sabin/Documents/startup/ember-quickstart/node_modules/babel-plugin-htmlbars-inline-precompile/index.js:91:28)
    at PluginPass.TaggedTemplateExpression (/Users/sabin/Documents/startup/ember-quickstart/node_modules/babel-plugin-htmlbars-inline-precompile/index.js:174:26)
    at newFn (/Users/sabin/Documents/startup/ember-quickstart/node_modules/@babel/traverse/lib/visitors.js:195:21)
    at NodePath._call (/Users/sabin/Documents/startup/ember-quickstart/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/Users/sabin/Documents/startup/ember-quickstart/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/Users/sabin/Documents/startup/ember-quickstart/node_modules/@babel/traverse/lib/path/context.js:88:12)
    at TraversalContext.visitQueue (/Users/sabin/Documents/startup/ember-quickstart/node_modules/@babel/traverse/lib/context.js:120:16)
    at TraversalContext.visitSingle (/Users/sabin/Documents/startup/ember-quickstart/node_modules/@babel/traverse/lib/context.js:92:19)
    at TraversalContext.visit (/Users/sabin/Documents/startup/ember-quickstart/node_modules/@babel/traverse/lib/context.js:148:19)
    at Function.traverse.node (/Users/sabin/Documents/startup/ember-quickstart/node_modules/@babel/traverse/lib/index.js:96:17)
        at PackagerRunner (@embroider/webpack)
-~- created here: -~-
    at new Plugin (/Users/sabin/Documents/startup/ember-quickstart/node_modules/@embroider/core/node_modules/broccoli-plugin/dist/index.js:42:31)
    at new PackagerRunner (/Users/sabin/Documents/startup/ember-quickstart/node_modules/@embroider/core/src/to-broccoli-plugin.js:10:13)
    at Object.defaultPipeline [as compatBuild] (/Users/sabin/Documents/startup/ember-quickstart/node_modules/@embroider/compat/src/default-pipeline.js:35:12)
    at module.exports (/Users/sabin/Documents/startup/ember-quickstart/ember-cli-build.js:25:39)
    at Builder.readBuildFile (/Users/sabin/Documents/startup/ember-quickstart/node_modules/ember-cli/lib/models/builder.js:52:14)
    at Builder.setupBroccoliBuilder (/Users/sabin/Documents/startup/ember-quickstart/node_modules/ember-cli/lib/models/builder.js:66:22)
    at new Builder (/Users/sabin/Documents/startup/ember-quickstart/node_modules/ember-cli/lib/models/builder.js:32:10)
    at ServeTask.run (/Users/sabin/Documents/startup/ember-quickstart/node_modules/ember-cli/lib/tasks/serve.js:49:7)
    at Promise.resolve.then (/Users/sabin/Documents/startup/ember-quickstart/node_modules/ember-cli/lib/models/command.js:239:24)
    at tryCatcher (/Users/sabin/Documents/startup/ember-quickstart/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:326:21)
-~- (end) -~-
  - name: BuildError
  - nodeAnnotation: @embroider/webpack
  - nodeName: PackagerRunner
  - originalErrorMessage: Module build failed (from /Users/sabin/Documents/startup/ember-quickstart/node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 7)
precompile is not a function

    at compileTemplate (/Users/sabin/Documents/startup/ember-quickstart/node_modules/babel-plugin-htmlbars-inline-precompile/index.js:91:28)
    at PluginPass.TaggedTemplateExpression (/Users/sabin/Documents/startup/ember-quickstart/node_modules/babel-plugin-htmlbars-inline-precompile/index.js:174:26)
    at newFn (/Users/sabin/Documents/startup/ember-quickstart/node_modules/@babel/traverse/lib/visitors.js:195:21)
    at NodePath._call (/Users/sabin/Documents/startup/ember-quickstart/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/Users/sabin/Documents/startup/ember-quickstart/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/Users/sabin/Documents/startup/ember-quickstart/node_modules/@babel/traverse/lib/path/context.js:88:12)
    at TraversalContext.visitQueue (/Users/sabin/Documents/startup/ember-quickstart/node_modules/@babel/traverse/lib/context.js:120:16)
    at TraversalContext.visitSingle (/Users/sabin/Documents/startup/ember-quickstart/node_modules/@babel/traverse/lib/context.js:92:19)
    at TraversalContext.visit (/Users/sabin/Documents/startup/ember-quickstart/node_modules/@babel/traverse/lib/context.js:148:19)
    at Function.traverse.node (/Users/sabin/Documents/startup/ember-quickstart/node_modules/@babel/traverse/lib/index.js:96:17)
  - stack: ModuleBuildError: Module build failed (from /Users/sabin/Documents/startup/ember-quickstart/node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 7)
precompile is not a function

    at compileTemplate (/Users/sabin/Documents/startup/ember-quickstart/node_modules/babel-plugin-htmlbars-inline-precompile/index.js:91:28)
    at PluginPass.TaggedTemplateExpression (/Users/sabin/Documents/startup/ember-quickstart/node_modules/babel-plugin-htmlbars-inline-precompile/index.js:174:26)
    at newFn (/Users/sabin/Documents/startup/ember-quickstart/node_modules/@babel/traverse/lib/visitors.js:195:21)
    at NodePath._call (/Users/sabin/Documents/startup/ember-quickstart/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/Users/sabin/Documents/startup/ember-quickstart/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/Users/sabin/Documents/startup/ember-quickstart/node_modules/@babel/traverse/lib/path/context.js:88:12)
    at TraversalContext.visitQueue (/Users/sabin/Documents/startup/ember-quickstart/node_modules/@babel/traverse/lib/context.js:120:16)
    at TraversalContext.visitSingle (/Users/sabin/Documents/startup/ember-quickstart/node_modules/@babel/traverse/lib/context.js:92:19)
    at TraversalContext.visit (/Users/sabin/Documents/startup/ember-quickstart/node_modules/@babel/traverse/lib/context.js:148:19)
    at Function.traverse.node (/Users/sabin/Documents/startup/ember-quickstart/node_modules/@babel/traverse/lib/index.js:96:17)
    at runLoaders (/Users/sabin/Documents/startup/ember-quickstart/node_modules/webpack/lib/NormalModule.js:301:20)
    at /Users/sabin/Documents/startup/ember-quickstart/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/sabin/Documents/startup/ember-quickstart/node_modules/loader-runner/lib/LoaderRunner.js:182:20
    at context.callback (/Users/sabin/Documents/startup/ember-quickstart/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.callback (/Users/sabin/Documents/startup/ember-quickstart/node_modules/thread-loader/dist/index.js:51:7)
    at /Users/sabin/Documents/startup/ember-quickstart/node_modules/async/internal/queue.js:101:31
    at /Users/sabin/Documents/startup/ember-quickstart/node_modules/async/internal/onlyOnce.js:12:16
    at callback (/Users/sabin/Documents/startup/ember-quickstart/node_modules/thread-loader/dist/WorkerPool.js:161:21)
    at /Users/sabin/Documents/startup/ember-quickstart/node_modules/thread-loader/dist/WorkerPool.js:187:17
    at /Users/sabin/Documents/startup/ember-quickstart/node_modules/async/internal/map.js:32:9

```
