### ISSUE TITLE
this.app.testIndex is not a function

### ISSUE THREAD

**Issue by Turbo87** [embroider-build/embroider#385]
We're seeing the following error when trying to build our app with Embroider:

```
TypeError: this.app.testIndex is not a function
    at V1App.get htmlTree [as htmlTree] (/builds/qonto/qonto-js/node_modules/@embroider/compat/src/v1-app.js:139:77)
    at setup (/builds/qonto/qonto-js/node_modules/@embroider/compat/src/compat-app.js:31:31)
    at new CompatApp (/builds/qonto/qonto-js/node_modules/@embroider/compat/src/compat-app.js:268:40)
    at Object.defaultPipeline [as compatBuild] (/builds/qonto/qonto-js/node_modules/@embroider/compat/src/default-pipeline.js:30:24)
    at module.exports (/builds/qonto/qonto-js/ember-cli-build.js:119:41)
    at Builder.readBuildFile (/builds/qonto/qonto-js/node_modules/ember-cli/lib/models/builder.js:52:14)
    at Builder.setupBroccoliBuilder (/builds/qonto/qonto-js/node_modules/ember-cli/lib/models/builder.js:66:22)
    at new Builder (/builds/qonto/qonto-js/node_modules/ember-cli/lib/models/builder.js:32:10)
    at BuildTask.run (/builds/qonto/qonto-js/node_modules/ember-cli/lib/tasks/build.js:15:19)
    at Promise.resolve.then (/builds/qonto/qonto-js/node_modules/ember-cli/lib/models/command.js:239:24)
    at tryCatcher (/builds/qonto/qonto-js/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:326:21)
    at invokeCallback (/builds/qonto/qonto-js/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:498:33)
    at /builds/qonto/qonto-js/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:562:16
    at flush (/builds/qonto/qonto-js/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:2441:7)
    at process._tickCallback (internal/process/next_tick.js:61:11)
    at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

Ember 3.16, Ember CLI 3.16 and Ember Data 3.16. With Ember CLI 3.15 we were seeing other errors, so I'm assuming something in Ember CLI 3.16 caused this to break. 🤔

**Comment by ef4** [comment]
Thanks for reporting, I think you are correct, this is easy to reproduce and should be straightforward.

**Comment by ef4** [comment]
https://github.com/ember-cli/ember-cli/commit/07f849c011395648f73d3aa1ccc6233600971937

**Comment by knownasilya** [comment]
Ran into this too.

**Comment by knownasilya** [comment]
Seems to have fixed for me. Now a new one lol: ` Error: Can't resolve 'dns' in '/Users/ilya/sandbox/drawknife/node_modules/fetch/lib'
    at /Users/ilya/sandbox/drawknife/node_modules/webpack/lib/Compilation.js:821:10
    at /Users/ilya/sandbox/drawknife/node_modules/webpack/lib/NormalModuleFactory.js:`
