### ISSUE TITLE
Error in compat mode in addon: Cannot read property 'pkg' of undefined

### ISSUE THREAD

**Issue by knownasilya** [embroider-build/embroider#518]
```
- broccoliBuilderErrorStack: [undefined]
  - code: [undefined]
  - codeFrame: [undefined]
  - errorMessage: Cannot read property 'pkg' of undefined
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: Cannot read property 'pkg' of undefined
  - name: TypeError
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: TypeError: Cannot read property 'pkg' of undefined
    at Function.create (/home/travis/build/knownasilya/pagination-pager/node_modules/@embroider/compat/src/v1-app.js:40:25)
    at new V1InstanceCache (/home/travis/build/knownasilya/pagination-pager/node_modules/@embroider/compat/src/v1-instance-cache.js:24:37)
    at core_1.getOrCreate (/home/travis/build/knownasilya/pagination-pager/node_modules/@embroider/compat/src/v1-instance-cache.js:33:72)
    at Object.getOrCreate (/home/travis/build/knownasilya/pagination-pager/node_modules/@embroider/compat/node_modules/@embroider/core/src/get-or-create.js:6:18)
    at Function.forApp (/home/travis/build/knownasilya/pagination-pager/node_modules/@embroider/compat/src/v1-instance-cache.js:33:31)
    at new CompatAddons (/home/travis/build/knownasilya/pagination-pager/node_modules/@embroider/compat/src/compat-addons.js:26:51)
    at Object.defaultPipeline [as compatBuild] (/home/travis/build/knownasilya/pagination-pager/node_modules/@embroider/compat/src/default-pipeline.js:17:18)
    at module.exports (/home/travis/build/knownasilya/pagination-pager/ember-cli-build.js:33:8)
    at Builder.readBuildFile (/home/travis/build/knownasilya/pagination-pager/node_modules/ember-cli/lib/models/builder.js:49:14)
    at Builder.setupBroccoliBuilder (/home/travis/build/knownasilya/pagination-pager/node_modules/ember-cli/lib/models/builder.js:63:22)
```
Test: https://travis-ci.org/github/knownasilya/pagination-pager/jobs/726560505

Code: https://github.com/knownasilya/pagination-pager

**Comment by Gothamoo7** [comment]
Hi @knownasilya, may I know how do you fixed this?

**Comment by rwjblue** [comment]
Hmm, this was reported a while back. @knownasilya do you know if this is still an issue?

**Comment by knownasilya** [comment]
I never resolved it. Will try to update to latest embroider and see if that helps.

**Comment by knownasilya** [comment]
So updating to latest Embroider setup via ember-cli-update, and then bumping it to 0.41.0 solved it for me.
https://github.com/knownasilya/pagination-pager/pull/55

**Comment by sandstrom** [comment]
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue. Since it's quite old I just wanted to ask if this is still relevant? If it isn't, maybe we can close this issue?

By closing some old issues we reduce the list of open issues to a more manageable set.

**Comment by knownasilya** [comment]
Can probably close.
