### ISSUE TITLE
Error in compat mode in addon: core_1.applyVariantToBabelConfig is not a function

### ISSUE THREAD

**Issue by knownasilya** [embroider-build/embroider#519]
```
- broccoliBuilderErrorStack: TypeError: core_1.applyVariantToBabelConfig is not a function
    at babelLoaderOptions (/home/travis/build/knownasilya/ember-toggle/node_modules/@embroider/webpack/src/ember-webpack.js:419:44)
    at Webpack.configureWebpack (/home/travis/build/knownasilya/ember-toggle/node_modules/@embroider/webpack/src/ember-webpack.js:119:33)
    at config.variants.map.variant (/home/travis/build/knownasilya/ember-toggle/node_modules/@embroider/webpack/src/ember-webpack.js:162:84)
    at Array.map (<anonymous>)
    at Webpack.getWebpack (/home/travis/build/knownasilya/ember-toggle/node_modules/@embroider/webpack/src/ember-webpack.js:162:40)
    at Webpack.build (/home/travis/build/knownasilya/ember-toggle/node_modules/@embroider/webpack/src/ember-webpack.js:61:32)
    at PackagerRunner.build (/home/travis/build/knownasilya/ember-toggle/node_modules/@embroider/compat/node_modules/@embroider/core/src/to-broccoli-plugin.js:29:34)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  - code: [undefined]
  - codeFrame: core_1.applyVariantToBabelConfig is not a function
  - errorMessage: core_1.applyVariantToBabelConfig is not a function
        at PackagerRunner (@embroider/webpack)
-~- created here: -~-
    at new Plugin (/home/travis/build/knownasilya/ember-toggle/node_modules/@embroider/compat/node_modules/@embroider/core/node_modules/broccoli-plugin/dist/index.js:45:31)
    at new PackagerRunner (/home/travis/build/knownasilya/ember-toggle/node_modules/@embroider/compat/node_modules/@embroider/core/src/to-broccoli-plugin.js:10:13)
    at Object.defaultPipeline [as compatBuild] (/home/travis/build/knownasilya/ember-toggle/node_modules/@embroider/compat/src/default-pipeline.js:36:12)
    at module.exports (/home/travis/build/knownasilya/ember-toggle/ember-cli-build.js:20:8)
    at Builder.readBuildFile (/home/travis/build/knownasilya/ember-toggle/node_modules/ember-cli/lib/models/builder.js:49:14)
    at Builder.setupBroccoliBuilder (/home/travis/build/knownasilya/ember-toggle/node_modules/ember-cli/lib/models/builder.js:63:22)
    at new Builder (/home/travis/build/knownasilya/ember-toggle/node_modules/ember-cli/lib/models/builder.js:29:10)
    at BuildTask.run (/home/travis/build/knownasilya/ember-toggle/node_modules/ember-cli/lib/tasks/build.js:13:19)
    at Promise.resolve.then (/home/travis/build/knownasilya/ember-toggle/node_modules/ember-cli/lib/models/command.js:238:24)
    at process._tickCallback (internal/process/next_tick.js:68:7)
-~- (end) -~-
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
    - treeDir: [undefined]
  - message: core_1.applyVariantToBabelConfig is not a function
        at PackagerRunner (@embroider/webpack)
-~- created here: -~-
    at new Plugin (/home/travis/build/knownasilya/ember-toggle/node_modules/@embroider/compat/node_modules/@embroider/core/node_modules/broccoli-plugin/dist/index.js:45:31)
    at new PackagerRunner (/home/travis/build/knownasilya/ember-toggle/node_modules/@embroider/compat/node_modules/@embroider/core/src/to-broccoli-plugin.js:10:13)
    at Object.defaultPipeline [as compatBuild] (/home/travis/build/knownasilya/ember-toggle/node_modules/@embroider/compat/src/default-pipeline.js:36:12)
    at module.exports (/home/travis/build/knownasilya/ember-toggle/ember-cli-build.js:20:8)
    at Builder.readBuildFile (/home/travis/build/knownasilya/ember-toggle/node_modules/ember-cli/lib/models/builder.js:49:14)
    at Builder.setupBroccoliBuilder (/home/travis/build/knownasilya/ember-toggle/node_modules/ember-cli/lib/models/builder.js:63:22)
    at new Builder (/home/travis/build/knownasilya/ember-toggle/node_modules/ember-cli/lib/models/builder.js:29:10)
    at BuildTask.run (/home/travis/build/knownasilya/ember-toggle/node_modules/ember-cli/lib/tasks/build.js:13:19)
    at Promise.resolve.then (/home/travis/build/knownasilya/ember-toggle/node_modules/ember-cli/lib/models/command.js:238:24)
    at process._tickCallback (internal/process/next_tick.js:68:7)
-~- (end) -~-
  - name: Error
  - nodeAnnotation: @embroider/webpack
  - nodeName: PackagerRunner
  - originalErrorMessage: core_1.applyVariantToBabelConfig is not a function
  - stack: TypeError: core_1.applyVariantToBabelConfig is not a function
    at babelLoaderOptions (/home/travis/build/knownasilya/ember-toggle/node_modules/@embroider/webpack/src/ember-webpack.js:419:44)
    at Webpack.configureWebpack (/home/travis/build/knownasilya/ember-toggle/node_modules/@embroider/webpack/src/ember-webpack.js:119:33)
    at config.variants.map.variant (/home/travis/build/knownasilya/ember-toggle/node_modules/@embroider/webpack/src/ember-webpack.js:162:84)
    at Array.map (<anonymous>)
    at Webpack.getWebpack (/home/travis/build/knownasilya/ember-toggle/node_modules/@embroider/webpack/src/ember-webpack.js:162:40)
    at Webpack.build (/home/travis/build/knownasilya/ember-toggle/node_modules/@embroider/webpack/src/ember-webpack.js:61:32)
    at PackagerRunner.build (/home/travis/build/knownasilya/ember-toggle/node_modules/@embroider/compat/node_modules/@embroider/core/src/to-broccoli-plugin.js:29:34)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Test https://travis-ci.org/github/knownasilya/ember-toggle/jobs/726613122
Code https://github.com/knownasilya/ember-toggle

**Comment by chrismllr** [comment]
Seeing this one as well. Using configurations outlined in the medium article from ember-times this wk:
https://medium.com/@kiwiupover/embroider-preparation-14d59edafc0b

**Comment by raido** [comment]
I've hit this with `ember-page-title` as well - https://github.com/adopted-ember-addons/ember-page-title/issues/173

**Comment by knownasilya** [comment]
Seems mostly related to ember-auto-import using older embroider deps (https://github.com/embroider-build/embroider/issues/520#issuecomment-693498749), and in ember-page-title I don't think we use it so auto-import can be removed there.

**Comment by raido** [comment]
Needs additional verification with ember-toggle which is NPM + package-lock.json based as well but it seems switching to Yarn makes Embroider happy 😮 - https://github.com/adopted-ember-addons/ember-page-title/pull/180#issuecomment-698507257

**Comment by knownasilya** [comment]
Update: ember-toggle passed embroider tests after removing ember-auto-import (did not switch to yarn).

**Comment by raido** [comment]
Hmm, `ember-page-title` has `ember-cli-fastboot-testing` which includes older version of `ember-auto-import` - maybe with NPM it gets hoisted differently compared to Yarn and that's the reason for failure. 🤔

**Comment by raido** [comment]
Confirmed, if I remove both `ember-auto-import` and `ember-cli-fastboot-testing` from `ember-page-title` - build will pass with NPM just fine. 

While with Yarn it "just works".
