### ISSUE TITLE
Cannot find addon.scss for addon that works otherwise

### ISSUE THREAD

**Issue by knownasilya** [embroider-build/embroider#57]
I get an error when running `ember serve` in an app that has an addon that exports sass styles.
The addon has `addon/styles/addon.scss` (which is empty). The actual styles are in the `app` folder.

In `/Users/ilya/workspace/build/tmp/sass_compiler-input_base_path-14F44Vcb.tmp` there is a single `_app_styles_` folder and that has all files from `someaddon/app/styles/`.

```
File not found: /addon.scss
in any of the following include paths:
  /Users/ilya/workspace/build/tmp/sass_compiler-input_base_path-14F44Vcb.tmp
        at OneShot
-~- created here: -~-
    at new Plugin (/Users/ilya/workspace/build/node_modules/broccoli-plugin/index.js:7:31)
    at new OneShot (/Users/ilya/workspace/build/node_modules/@embroider/compat/src/one-shot.js:14:9)
    at Object.cachedBuildCompatAddon [as default] (/Users/ilya/workspace/build/node_modules/@embroider/compat/src/build-compat-addon.js:15:16)
    at CompatAddons.movedAddons.map.oldPkg (/Users/ilya/workspace/build/node_modules/@embroider/compat/src/compat-addons.js:33:105)
    at Array.map (<anonymous>:null:null)
    at new CompatAddons (/Users/ilya/workspace/build/node_modules/@embroider/compat/src/compat-addons.js:33:63)
    at Object.defaultPipeline [as compatBuild] (/Users/ilya/workspace/build/node_modules/@embroider/compat/src/default-pipeline.js:11:18)
    at module.exports (/Users/ilya/workspace/build/ember-cli-build.js:50:39)
    at Builder.readBuildFile (/Users/ilya/workspace/build/node_modules/ember-cli/lib/models/builder.js:52:14)
    at Builder.setupBroccoliBuilder (/Users/ilya/workspace/build/node_modules/ember-cli/lib/models/builder.js:66:22)
    at new Builder (/Users/ilya/workspace/build/node_modules/ember-cli/lib/models/builder.js:32:10)
    at ServeTask.run (/Users/ilya/workspace/build/node_modules/ember-cli/lib/tasks/serve.js:45:55)
    at Promise.resolve.then (/Users/ilya/workspace/build/node_modules/ember-cli/lib/models/command.js:243:46)
    at tryCatcher (/Users/ilya/workspace/build/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:323:19)
    at invokeCallback (/Users/ilya/workspace/build/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:495:31)
    at /Users/ilya/workspace/build/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:559:14
    at flush (/Users/ilya/workspace/build/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:2402:5)
    at processTicksAndRejections (internal/process/next_tick.js:74:9)
```

**Comment by ef4** [comment]
Thanks for reporting, I *think this is going to be covered by work that I'm planning soon.

**Comment by ef4** [comment]
I think this is fixed, please file a new issue if it's not.
