### ISSUE TITLE
Error in compat build with ember-cli-imgix due to babel-plugin-inline-package-json

### ISSUE THREAD

**Issue by reidab** [embroider-build/embroider#596]
When running a build using `ember-cli-imgix`, it uses `babel-plugin-inline-package-json` to get the app's version number. There are various alternatives that I can PR to that library instead of `babel-plugin-inline-package-json`, but I wanted to check if supporting that babel plugin in compat would be more desirable.

This fails with:

```
(node:6746) UnhandledPromiseRejectionWarning: Error: common/constants.js: Cannot find module '/Users/reidab/code/thedyrt/package.json'
Require stack:
- /Users/reidab/code/thedyrt/web-ui/node_modules/babel-plugin-inline-package-json/lib/index.js
- /Users/reidab/code/thedyrt/web-ui/node_modules/babel-core/lib/transformation/file/options/option-manager.js
- /Users/reidab/code/thedyrt/web-ui/node_modules/babel-core/lib/transformation/file/index.js
- /Users/reidab/code/thedyrt/web-ui/node_modules/babel-core/lib/api/node.js
- /Users/reidab/code/thedyrt/web-ui/node_modules/babel-core/index.js
- /Users/reidab/code/thedyrt/web-ui/node_modules/ember-cli-imgix/node_modules/broccoli-babel-transpiler/lib/worker.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1030:15)
    at Function.Module._load (internal/modules/cjs/loader.js:899:27)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at PluginPass.MemberExpression (/Users/reidab/code/thedyrt/web-ui/node_modules/babel-plugin-inline-package-json/lib/index.js:16:21)
    at newFn (/Users/reidab/code/thedyrt/web-ui/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/Users/reidab/code/thedyrt/web-ui/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/reidab/code/thedyrt/web-ui/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/reidab/code/thedyrt/web-ui/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/Users/reidab/code/thedyrt/web-ui/node_modules/babel-traverse/lib/context.js:150:16)
```

**Comment by Windvis** [comment]
Closing since the mentioned addon should now be Embroider compatible 🎉
