### ISSUE TITLE
 ModuleNotFoundError: Module not found: sanitize-html

### ISSUE THREAD

**Issue by gedaiu** [embroider-build/embroider#646]
Te build is failing due usage of the `sanitize-html` is there a way to fix this issue, or should I not use this library?

```
❯ cat /tmp/error.dump.2c570afc086ac7f144e74ddd17ec5925.log
=================================================================================

ENV Summary:

  TIME: Wed Dec 02 2020 21:41:50 GMT+0100 (Central European Standard Time)
  TITLE: ember
  ARGV:
  - /usr/bin/node
  - /home/gedaiu/workspace/gis-collective/frontend/web-frontend/packages/gis-collective/node_modules/.bin/ember
  - serve
  EXEC_PATH: /usr/bin/node
  TMPDIR: /tmp
  SHELL: /bin/zsh
  PATH:
  - /tmp/yarn--1606941597034-0.7331730292879237
  - /home/gedaiu/workspace/gis-collective/frontend/web-frontend/packages/gis-collective/node_modules/.bin
  - /home/gedaiu/.config/yarn/link/node_modules/.bin
  - /home/gedaiu/workspace/gis-collective/frontend/web-frontend/node_modules/.bin
  - /usr/libexec/lib/node_modules/npm/bin/node-gyp-bin
  - /usr/lib/node_modules/npm/bin/node-gyp-bin
  - /usr/bin/node_modules/npm/bin/node-gyp-bin
  - /tmp/yarn--1606941596233-0.8050697508389568
  - /home/gedaiu/workspace/gis-collective/frontend/web-frontend/node_modules/.bin
  - /home/gedaiu/.config/yarn/link/node_modules/.bin
  - /home/gedaiu/workspace/gis-collective/frontend/web-frontend/node_modules/.bin
  - /usr/libexec/lib/node_modules/npm/bin/node-gyp-bin
  - /usr/lib/node_modules/npm/bin/node-gyp-bin
  - /usr/bin/node_modules/npm/bin/node-gyp-bin
  - /home/gedaiu/.yarn/bin
  - /home/gedaiu/.config/yarn/global/node_modules/.bin
  - /usr/local/bin
  - /usr/local/sbin
  - /usr/bin
  - /usr/sbin
  - /home/gedaiu/bin
  PLATFORM: linux x64
  FREEMEM: 5379739648
  TOTALMEM: 16667136000
  UPTIME: 7303
  LOADAVG: 2.97,2.17,1.44
  CPUS:
  - Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz - 2592
  - Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz - 2600
  - Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz - 2580
  - Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz - 2628
  - Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz - 2570
  - Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz - 2609
  - Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz - 2613
  - Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz - 2595
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.16.1
  - brotli: 1.0.9
  - cldr: 37.0
  - icu: 67.1
  - llhttp: 2.1.3
  - modules: 83
  - napi: 7
  - nghttp2: 1.41.0
  - node: 14.14.0
  - openssl: 1.1.1g
  - tz: 2019c
  - unicode: 13.0
  - uv: 1.40.0
  - v8: 8.4.371.19-node.17
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: ModuleNotFoundError: Module not found: Error: Can't resolve 'path' in '/home/gedaiu/workspace/gis-collective/frontend/web-frontend/node_modules/sanitize-html/node_modules/postcss/lib'
    at /home/gedaiu/workspace/gis-collective/frontend/web-frontend/node_modules/webpack/lib/Compilation.js:925:10
    at /home/gedaiu/workspace/gis-collective/frontend/web-frontend/node_modules/webpack/lib/NormalModuleFactory.js:401:22
    at /home/gedaiu/workspace/gis-collective/frontend/web-frontend/node_modules/webpack/lib/NormalModuleFactory.js:130:21
    at /home/gedaiu/workspace/gis-collective/frontend/web-frontend/node_modules/webpack/lib/NormalModuleFactory.js:224:22
    at /home/gedaiu/workspace/gis-collective/frontend/web-frontend/node_modules/neo-async/async.js:2830:7
    at /home/gedaiu/workspace/gis-collective/frontend/web-frontend/node_modules/neo-async/async.js:6877:13
    at /home/gedaiu/workspace/gis-collective/frontend/web-frontend/node_modules/webpack/lib/NormalModuleFactory.js:214:25
    at /home/gedaiu/workspace/gis-collective/frontend/web-frontend/node_modules/enhanced-resolve/lib/Resolver.js:213:14
    at /home/gedaiu/workspace/gis-collective/frontend/web-frontend/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/gedaiu/workspace/gis-collective/frontend/web-frontend/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /home/gedaiu/workspace/gis-collective/frontend/web-frontend/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7
    at /home/gedaiu/workspace/gis-collective/frontend/web-frontend/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/gedaiu/workspace/gis-collective/frontend/web-frontend/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /home/gedaiu/workspace/gis-collective/frontend/web-frontend/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/gedaiu/workspace/gis-collective/frontend/web-frontend/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /home/gedaiu/workspace/gis-collective/frontend/web-frontend/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
  - code: [undefined]
  - codeFrame: Module not found: Error: Can't resolve 'path' in '/home/gedaiu/workspace/gis-collective/frontend/web-frontend/node_modules/sanitize-html/node_modules/postcss/lib'
  - errorMessage: ../../../../../home/gedaiu/workspace/gis-collective/frontend/web-frontend/node_modules/sanitize-html/node_modules/postcss/lib/input.js: Module not found: Error: Can't resolve 'path' in '/home/gedaiu/workspace/gis-collective/frontend/web-frontend/node_modules/sanitize-html/node_modules/postcss/lib'
        at PackagerRunner (@embroider/webpack)
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: ../../../../../home/gedaiu/workspace/gis-collective/frontend/web-frontend/node_modules/sanitize-html/node_modules/postcss/lib/input.js
    - line: [null]
    - treeDir: [undefined]
  - message: ../../../../../home/gedaiu/workspace/gis-collective/frontend/web-frontend/node_modules/sanitize-html/node_modules/postcss/lib/input.js: Module not found: Error: Can't resolve 'path' in '/home/gedaiu/workspace/gis-collective/frontend/web-frontend/node_modules/sanitize-html/node_modules/postcss/lib'
        at PackagerRunner (@embroider/webpack)
  - name: Error
  - nodeAnnotation: @embroider/webpack
  - nodeName: PackagerRunner
  - originalErrorMessage: Module not found: Error: Can't resolve 'path' in '/home/gedaiu/workspace/gis-collective/frontend/web-frontend/node_modules/sanitize-html/node_modules/postcss/lib'
  - stack: ModuleNotFoundError: Module not found: Error: Can't resolve 'path' in '/home/gedaiu/workspace/gis-collective/frontend/web-frontend/node_modules/sanitize-html/node_modules/postcss/lib'
    at /home/gedaiu/workspace/gis-collective/frontend/web-frontend/node_modules/webpack/lib/Compilation.js:925:10
    at /home/gedaiu/workspace/gis-collective/frontend/web-frontend/node_modules/webpack/lib/NormalModuleFactory.js:401:22
    at /home/gedaiu/workspace/gis-collective/frontend/web-frontend/node_modules/webpack/lib/NormalModuleFactory.js:130:21
    at /home/gedaiu/workspace/gis-collective/frontend/web-frontend/node_modules/webpack/lib/NormalModuleFactory.js:224:22
    at /home/gedaiu/workspace/gis-collective/frontend/web-frontend/node_modules/neo-async/async.js:2830:7
    at /home/gedaiu/workspace/gis-collective/frontend/web-frontend/node_modules/neo-async/async.js:6877:13
    at /home/gedaiu/workspace/gis-collective/frontend/web-frontend/node_modules/webpack/lib/NormalModuleFactory.js:214:25
    at /home/gedaiu/workspace/gis-collective/frontend/web-frontend/node_modules/enhanced-resolve/lib/Resolver.js:213:14
    at /home/gedaiu/workspace/gis-collective/frontend/web-frontend/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/gedaiu/workspace/gis-collective/frontend/web-frontend/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /home/gedaiu/workspace/gis-collective/frontend/web-frontend/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7
    at /home/gedaiu/workspace/gis-collective/frontend/web-frontend/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/gedaiu/workspace/gis-collective/frontend/web-frontend/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /home/gedaiu/workspace/gis-collective/frontend/web-frontend/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/gedaiu/workspace/gis-collective/frontend/web-frontend/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /home/gedaiu/workspace/gis-collective/frontend/web-frontend/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43

=================================================================================
```

**Comment by sandstrom** [comment]
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue. Since it's quite old I just wanted to ask if this is still relevant? If it isn't, maybe we can close this issue?

By closing some old issues we reduce the list of open issues to a more manageable set.
