### ISSUE TITLE
Ember serve fails on windows with embroider 0.32+

### ISSUE THREAD

**Issue by mkszepp** [embroider-build/embroider#681]
The Embroider Version 0.32.0 and above is not working on windows after command `ember s`:

The problem also exists on a new ember project.

OS: Windows 10 x64
Ember Cli: 3.24.0
Embroider: 0.32.0 - 0.36.0

Steps to reproduce:
1. `npm install -g ember-cli`
2. `ember new test-app`
3. `npm i @embroider/core @embroider/compat @embroider/webpack`
4. Edit `ember-cli-build.js` like specified in Readme.md
5. `ember s`

Build Error:

```Build Error (PackagerRunner) in assets\test-app.js

Module build failed (from C:/Projects/test-app/node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 0)
[BABEL] $TMPDIR\embroider\8279ea\assets\test-app.js: module.call is not a function (While processing: "C:\\Projects\\test-app\\node_modules\\@embroider\\core\\src\\portable-babel-launcher.js")

    at babelLauncher (C:\Projects\test-app\node_modules\@embroider\core\src\portable-babel-launcher.js:18:25)
    at C:\Projects\test-app\node_modules\@babel\core\lib\config\full.js:211:14
    at Generator.next (<anonymous>)
    at Function.<anonymous> (C:\Projects\test-app\node_modules\@babel\core\lib\gensync-utils\async.js:26:3)
    at Generator.next (<anonymous>)
    at step (C:\Projects\test-app\node_modules\gensync\index.js:261:32)
    at evaluateAsync (C:\Projects\test-app\node_modules\gensync\index.js:291:5)
    at Function.errback (C:\Projects\test-app\node_modules\gensync\index.js:113:7)
    at errback (C:\Projects\test-app\node_modules\@babel\core\lib\gensync-utils\async.js:70:18)
    at async (C:\Projects\test-app\node_modules\gensync\index.js:188:31)


Stack Trace and Error Report: C:\Users\XXXXXX\AppData\Local\Temp/error.dump.dbfe1eeb8cfd0c70330d1e42d4579062.log```

**Comment by lifeart** [comment]
https://github.com/embroider-build/embroider/issues/676 may be related
