### ISSUE TITLE
Respect customized babel syntax plugins

### ISSUE THREAD

**Issue by Turbo87** [embroider-build/embroider#73]
```
Build Error (PackagerRunner) in services/filter.js:19

/private/var/folders/6y/_8qpkt114jzb442txt_9w_2c0000gn/T/embroider-cjbPbI/services/filter.js: Unexpected token (19:8)

  17 |       'filter',
  18 |       data.map(row => ({
> 19 |         ...row,
     |         ^
  20 |         ID: parseID(row.ID),
  21 |         HANDICAP: 'HANDICAP' in row ? parseFloat(row.HANDICAP) : 1.0,
  22 |       })),
```

It looks like https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax#Spread_in_object_literals is currently not supported and I could not find any documentation yet on how to add support for it in my app. With `ember-cli-babel` this seems to be supported by default though.

**Comment by Turbo87** [comment]
```
=================================================================================

ENV Summary:

  TIME: Tue Mar 19 2019 12:50:48 GMT-0700 (GMT-07:00)
  TITLE: ember
  ARGV:
  - /Users/tbieniek/.nvm/versions/node/v11.10.0/bin/node
  - /Users/tbieniek/.nvm/versions/node/v11.10.0/bin/ember
  - b
  EXEC_PATH: /Users/tbieniek/.nvm/versions/node/v11.10.0/bin/node
  TMPDIR: /var/folders/6y/_8qpkt114jzb442txt_9w_2c0000gn/T
  SHELL: /usr/local/bin/fish
  PATH:
  - /Users/tbieniek/.rvm/gems/ruby-1.9.3-p551/bin
  - /Users/tbieniek/.rvm/gems/ruby-1.9.3-p551@global/bin
  - /Users/tbieniek/.rvm/rubies/ruby-1.9.3-p551/bin
  - /Users/tbieniek/.rvm/bin
  - /bin
  - /Users/tbieniek/.cargo/bin
  - /Users/tbieniek/.nvm/versions/node/v11.10.0/bin
  - /Users/tbieniek/.yarn/bin
  - /usr/local/bin
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  - /opt/X11/bin
  - /Applications/VMware Fusion.app/Contents/Public
  - /Library/Frameworks/Mono.framework/Versions/Current/Commands
  - /Applications/Postgres.app/Contents/Versions/latest/bin
  - /Applications/Wireshark.app/Contents/MacOS
  PLATFORM: darwin x64
  FREEMEM: 197169152
  TOTALMEM: 17179869184
  UPTIME: 134949
  LOADAVG: 2.73974609375,2.173828125,2.076171875
  CPUS:
  - Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz - 3300
  - Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz - 3300
  - Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz - 3300
  - Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz - 3300
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.15.0
  - brotli: 1.0.7
  - cldr: 34.0
  - http_parser: 2.8.0
  - icu: 63.1
  - llhttp: 1.1.1
  - modules: 67
  - napi: 4
  - nghttp2: 1.34.0
  - node: 11.10.0
  - openssl: 1.1.1a
  - tz: 2018e
  - unicode: 11.0
  - uv: 1.26.0
  - v8: 7.0.276.38-node.17
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: SyntaxError: /private/var/folders/6y/_8qpkt114jzb442txt_9w_2c0000gn/T/embroider-e3xrW7/services/filter.js: Unexpected token (19:8)
  17 |       'filter',
  18 |       data.map(row => ({
> 19 |         ...row,
     |         ^
  20 |         ID: parseID(row.ID),
  21 |         HANDICAP: 'HANDICAP' in row ? parseFloat(row.HANDICAP) : 1.0,
  22 |       })),
    at Parser.pp$5.raise (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp.unexpected (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:1761:8)
    at Parser.pp$3.parseIdentifier (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:4332:10)
    at Parser.pp$3.parsePropertyName (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:4156:96)
    at Parser.pp$3.parseObj (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:4045:12)
    at Parser.pp$3.parseExprAtom (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3719:19)
    at Parser.pp$3.parseExprSubscripts (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3494:19)
    at Parser.pp$3.parseMaybeUnary (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3474:19)
    at Parser.pp$3.parseExprOps (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3404:19)
    at Parser.pp$3.parseMaybeConditional (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3381:19)
    at Parser.pp$3.parseMaybeAssign (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3344:19)
    at Parser.pp$3.parseParenAndDistinguishExpression (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3828:26)
    at Parser.pp$3.parseExprAtom (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3709:19)
    at Parser.pp$3.parseExprSubscripts (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3494:19)
    at Parser.pp$3.parseMaybeUnary (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3474:19)
    at Parser.pp$3.parseExprOps (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3404:19)
    at Parser.pp$3.parseMaybeConditional (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3381:19)
    at Parser.pp$3.parseMaybeAssign (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3344:19)
    at Parser.pp$3.parseFunctionBody (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:4226:22)
    at Parser.pp$3.parseArrowExpression (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:4190:8)
    at Parser.pp$3.parseExprAtom (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3665:21)
    at Parser.pp$3.parseExprSubscripts (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3494:19)
    at Parser.pp$3.parseMaybeUnary (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3474:19)
    at Parser.pp$3.parseExprOps (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3404:19)
    at Parser.pp$3.parseMaybeConditional (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3381:19)
    at Parser.pp$3.parseMaybeAssign (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3344:19)
    at Parser.pp$3.parseExprListItem (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:4312:16)
    at Parser.pp$3.parseCallExpressionArguments (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3573:20)
    at Parser.pp$3.parseSubscripts (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3533:31)
    at Parser.pp$3.parseExprSubscripts (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3504:15)
    at Parser.pp$3.parseMaybeUnary (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3474:19)
    at Parser.pp$3.parseExprOps (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3404:19)
    at Parser.pp$3.parseMaybeConditional (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3381:19)
    at Parser.pp$3.parseMaybeAssign (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3344:19)
    at Parser.pp$3.parseExprListItem (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:4312:16)
    at Parser.pp$3.parseCallExpressionArguments (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3573:20)
    at Parser.pp$3.parseSubscripts (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3533:31)
    at Parser.pp$3.parseExprSubscripts (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3504:15)
    at Parser.pp$3.parseMaybeUnary (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3474:19)
    at Parser.pp$3.parseExprOps (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3404:19)
    at Parser.pp$3.parseMaybeConditional (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3381:19)
    at Parser.pp$3.parseMaybeAssign (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3344:19)
    at Parser.pp$3.parseExpression (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3306:19)
    at Parser.pp$1.parseStatement (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:1906:19)
    at Parser.pp$1.parseBlockBody (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:2268:21)
    at Parser.pp$1.parseBlock (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:2247:8)
    at Parser.pp$3.parseFunctionBody (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:4235:22)
    at Parser.pp$3.parseMethod (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:4180:8)
    at Parser.pp$3.parseObjectMethod (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:4097:10)
    at Parser.pp$3.parseObjPropValue (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:4140:19)
    at Parser.pp$3.parseObj (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:4048:10)
    at Parser.pp$3.parseExprAtom (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3719:19)
    at Parser.pp$3.parseExprSubscripts (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3494:19)
    at Parser.pp$3.parseMaybeUnary (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3474:19)
    at Parser.pp$3.parseExprOps (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3404:19)
    at Parser.pp$3.parseMaybeConditional (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3381:19)
    at Parser.pp$3.parseMaybeAssign (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3344:19)
    at Parser.pp$3.parseExprListItem (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:4312:16)
    at Parser.pp$3.parseCallExpressionArguments (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3573:20)
    at Parser.pp$3.parseSubscripts (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3533:31)
    at Parser.pp$3.parseExprSubscripts (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3504:15)
    at Parser.pp$3.parseMaybeUnary (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3474:19)
    at Parser.pp$3.parseExprOps (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3404:19)
    at Parser.pp$3.parseMaybeConditional (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3381:19)
    at Parser.pp$3.parseMaybeAssign (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3344:19)
    at Parser.pp$1.parseExport (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:2645:19)
    at Parser.pp$1.parseStatement (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:1884:74)
    at Parser.pp$1.parseBlockBody (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:2268:21)
    at Parser.pp$1.parseTopLevel (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:1778:8)
    at Parser.parse (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:1673:17)
    at parse (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:7305:37)
    at File.parse (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babel-core/lib/transformation/file/index.js:485:15)
    at File.parseCode (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babel-core/lib/transformation/file/index.js:570:20)
    at /Users/tbieniek/Code/ogn-web-viewer/node_modules/babel-core/lib/transformation/pipeline.js:49:12
    at File.wrap (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babel-core/lib/transformation/file/index.js:532:16)
    at Pipeline.transform (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babel-core/lib/transformation/pipeline.js:47:17)
    at transpile (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babel-loader/lib/index.js:50:20)
    at Object.module.exports (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babel-loader/lib/index.js:173:20)
    at LOADER_EXECUTION (/Users/tbieniek/Code/ogn-web-viewer/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
    at runSyncOrAsync (/Users/tbieniek/Code/ogn-web-viewer/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
    at iterateNormalLoaders (/Users/tbieniek/Code/ogn-web-viewer/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/Users/tbieniek/Code/ogn-web-viewer/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Users/tbieniek/Code/ogn-web-viewer/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:43:16)
    at provider (/Users/tbieniek/Code/ogn-web-viewer/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:79:9)
    at /Users/tbieniek/Code/ogn-web-viewer/node_modules/graceful-fs/graceful-fs.js:90:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:54:3)

  - code: [undefined]
  - codeFrame:   17 |       'filter',
  18 |       data.map(row => ({
> 19 |         ...row,
     |         ^
  20 |         ID: parseID(row.ID),
  21 |         HANDICAP: 'HANDICAP' in row ? parseFloat(row.HANDICAP) : 1.0,
  22 |       })),
  - errorMessage: services/filter.js:19: /private/var/folders/6y/_8qpkt114jzb442txt_9w_2c0000gn/T/embroider-e3xrW7/services/filter.js: Unexpected token (19:8)
        at PackagerRunner (@embroider/webpack)
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: services/filter.js
    - line: 19
    - treeDir: [undefined]
  - message: services/filter.js:19: /private/var/folders/6y/_8qpkt114jzb442txt_9w_2c0000gn/T/embroider-e3xrW7/services/filter.js: Unexpected token (19:8)
        at PackagerRunner (@embroider/webpack)
  - name: BuildError
  - nodeAnnotation: @embroider/webpack
  - nodeName: PackagerRunner
  - originalErrorMessage: /private/var/folders/6y/_8qpkt114jzb442txt_9w_2c0000gn/T/embroider-e3xrW7/services/filter.js: Unexpected token (19:8)
  - stack: SyntaxError: /private/var/folders/6y/_8qpkt114jzb442txt_9w_2c0000gn/T/embroider-e3xrW7/services/filter.js: Unexpected token (19:8)
  17 |       'filter',
  18 |       data.map(row => ({
> 19 |         ...row,
     |         ^
  20 |         ID: parseID(row.ID),
  21 |         HANDICAP: 'HANDICAP' in row ? parseFloat(row.HANDICAP) : 1.0,
  22 |       })),
    at Parser.pp$5.raise (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp.unexpected (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:1761:8)
    at Parser.pp$3.parseIdentifier (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:4332:10)
    at Parser.pp$3.parsePropertyName (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:4156:96)
    at Parser.pp$3.parseObj (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:4045:12)
    at Parser.pp$3.parseExprAtom (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3719:19)
    at Parser.pp$3.parseExprSubscripts (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3494:19)
    at Parser.pp$3.parseMaybeUnary (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3474:19)
    at Parser.pp$3.parseExprOps (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3404:19)
    at Parser.pp$3.parseMaybeConditional (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3381:19)
    at Parser.pp$3.parseMaybeAssign (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3344:19)
    at Parser.pp$3.parseParenAndDistinguishExpression (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3828:26)
    at Parser.pp$3.parseExprAtom (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3709:19)
    at Parser.pp$3.parseExprSubscripts (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3494:19)
    at Parser.pp$3.parseMaybeUnary (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3474:19)
    at Parser.pp$3.parseExprOps (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3404:19)
    at Parser.pp$3.parseMaybeConditional (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3381:19)
    at Parser.pp$3.parseMaybeAssign (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3344:19)
    at Parser.pp$3.parseFunctionBody (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:4226:22)
    at Parser.pp$3.parseArrowExpression (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:4190:8)
    at Parser.pp$3.parseExprAtom (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3665:21)
    at Parser.pp$3.parseExprSubscripts (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3494:19)
    at Parser.pp$3.parseMaybeUnary (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3474:19)
    at Parser.pp$3.parseExprOps (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3404:19)
    at Parser.pp$3.parseMaybeConditional (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3381:19)
    at Parser.pp$3.parseMaybeAssign (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3344:19)
    at Parser.pp$3.parseExprListItem (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:4312:16)
    at Parser.pp$3.parseCallExpressionArguments (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3573:20)
    at Parser.pp$3.parseSubscripts (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3533:31)
    at Parser.pp$3.parseExprSubscripts (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3504:15)
    at Parser.pp$3.parseMaybeUnary (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3474:19)
    at Parser.pp$3.parseExprOps (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3404:19)
    at Parser.pp$3.parseMaybeConditional (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3381:19)
    at Parser.pp$3.parseMaybeAssign (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3344:19)
    at Parser.pp$3.parseExprListItem (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:4312:16)
    at Parser.pp$3.parseCallExpressionArguments (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3573:20)
    at Parser.pp$3.parseSubscripts (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3533:31)
    at Parser.pp$3.parseExprSubscripts (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3504:15)
    at Parser.pp$3.parseMaybeUnary (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3474:19)
    at Parser.pp$3.parseExprOps (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3404:19)
    at Parser.pp$3.parseMaybeConditional (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3381:19)
    at Parser.pp$3.parseMaybeAssign (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3344:19)
    at Parser.pp$3.parseExpression (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3306:19)
    at Parser.pp$1.parseStatement (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:1906:19)
    at Parser.pp$1.parseBlockBody (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:2268:21)
    at Parser.pp$1.parseBlock (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:2247:8)
    at Parser.pp$3.parseFunctionBody (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:4235:22)
    at Parser.pp$3.parseMethod (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:4180:8)
    at Parser.pp$3.parseObjectMethod (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:4097:10)
    at Parser.pp$3.parseObjPropValue (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:4140:19)
    at Parser.pp$3.parseObj (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:4048:10)
    at Parser.pp$3.parseExprAtom (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3719:19)
    at Parser.pp$3.parseExprSubscripts (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3494:19)
    at Parser.pp$3.parseMaybeUnary (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3474:19)
    at Parser.pp$3.parseExprOps (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3404:19)
    at Parser.pp$3.parseMaybeConditional (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3381:19)
    at Parser.pp$3.parseMaybeAssign (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3344:19)
    at Parser.pp$3.parseExprListItem (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:4312:16)
    at Parser.pp$3.parseCallExpressionArguments (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3573:20)
    at Parser.pp$3.parseSubscripts (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3533:31)
    at Parser.pp$3.parseExprSubscripts (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3504:15)
    at Parser.pp$3.parseMaybeUnary (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3474:19)
    at Parser.pp$3.parseExprOps (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3404:19)
    at Parser.pp$3.parseMaybeConditional (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3381:19)
    at Parser.pp$3.parseMaybeAssign (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:3344:19)
    at Parser.pp$1.parseExport (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:2645:19)
    at Parser.pp$1.parseStatement (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:1884:74)
    at Parser.pp$1.parseBlockBody (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:2268:21)
    at Parser.pp$1.parseTopLevel (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:1778:8)
    at Parser.parse (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:1673:17)
    at parse (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babylon/lib/index.js:7305:37)
    at File.parse (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babel-core/lib/transformation/file/index.js:485:15)
    at File.parseCode (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babel-core/lib/transformation/file/index.js:570:20)
    at /Users/tbieniek/Code/ogn-web-viewer/node_modules/babel-core/lib/transformation/pipeline.js:49:12
    at File.wrap (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babel-core/lib/transformation/file/index.js:532:16)
    at Pipeline.transform (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babel-core/lib/transformation/pipeline.js:47:17)
    at transpile (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babel-loader/lib/index.js:50:20)
    at Object.module.exports (/Users/tbieniek/Code/ogn-web-viewer/node_modules/babel-loader/lib/index.js:173:20)
    at LOADER_EXECUTION (/Users/tbieniek/Code/ogn-web-viewer/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
    at runSyncOrAsync (/Users/tbieniek/Code/ogn-web-viewer/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
    at iterateNormalLoaders (/Users/tbieniek/Code/ogn-web-viewer/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/Users/tbieniek/Code/ogn-web-viewer/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Users/tbieniek/Code/ogn-web-viewer/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:43:16)
    at provider (/Users/tbieniek/Code/ogn-web-viewer/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:79:9)
    at /Users/tbieniek/Code/ogn-web-viewer/node_modules/graceful-fs/graceful-fs.js:90:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:54:3)


=================================================================================
```

the app is open-source at https://github.com/Turbo87/ogn-web-viewer and I've tried embroider on top of commit 34f88f9

**Comment by ef4** [comment]
Ah yes. The problem is not specific to the spread operator, it's that our ImportParser isn't respecting your babel config. So if you have any plugins that extend syntax, that won't work.

Basically right around [here](https://github.com/embroider-build/embroider/blob/a16e308e7026fbc2355fa4edf488e2fbc6cfa875/packages/compat/src/import-parser.ts#L58) we need to use the real babel config.

Related to this is also https://github.com/embroider-build/embroider/pull/41. Because once we're using your custom babel config here, we also need to pick the right babel 6 vs 7.

Similar code is already implemented in ember-auto-import and can probably just be ported into embroider.
