### ISSUE TITLE
Windows error - node_modules\@ember-decorators contains invalid WIN32 path characters.

### ISSUE THREAD

**Issue by lifeart** [embroider-build/embroider#74]
C:\Users\lifeart\AppData\Local\Temp\embroider-cbSrw5\C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\node_modules\@ember-decorators contains invalid WIN32 path characters.

```
ERROR Summary:

  - broccoliBuilderErrorStack: Error: C:\Users\lifeart\AppData\Local\Temp\embroider-cbSrw5\C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\node_modules\@ember-decorators contains invalid WIN32 path characters.
    at mkdirsSync (C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\node_modules\@embroider\compat\node_modules\fs-extra\lib\mkdirs\mkdirs-sync.js:18:22)
    at Object.copySync (C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\node_modules\@embroider\compat\node_modules\fs-extra\lib\copy-sync\copy-sync.js:30:35)
    at forEach (C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\node_modules\@embroider\compat\src\compat-addons.js:59:24)
    at Array.forEach (<anonymous>)
    at CompatAddons.build (C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\node_modules\@embroider\compat\src\compat-addons.js:58:47)
    at WaitForTrees.build (C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\node_modules\@embroider\core\src\wait-for-trees.js:49:21)
    at resolve (C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\node_modules\broccoli\lib\wrappers\transform-node.js:29:35)
    at new Promise (<anonymous>)
    at TransformNodeWrapper.build (C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\node_modules\broccoli\lib\wrappers\transform-node.js:21:12)
    at Promise.resolve.then.then.then (C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\node_modules\broccoli\lib\builder.js:111:28)
  - code: [undefined]
  - codeFrame: C:\Users\lifeart\AppData\Local\Temp\embroider-cbSrw5\C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\node_modules\@ember-decorators contains invalid WIN32 path characters.
  - errorMessage: C:\Users\lifeart\AppData\Local\Temp\embroider-cbSrw5\C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\node_modules\@ember-decorators contains invalid WIN32 path characters.
        at WaitForTrees (@embroider/compat/addons)
-~- created here: -~-
    at new Plugin (C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\node_modules\broccoli-plugin\index.js:7:31)
    at new WaitForTrees (C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\node_modules\@embroider\core\src\wait-for-trees.js:30:9)
    at new CompatAddons (C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\node_modules\@embroider\compat\src\compat-addons.js:35:21)
    at Object.defaultPipeline [as compatBuild] (C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\node_modules\@embroider\compat\src\default-pipeline.js:11:18)
    at module.exports (C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\grdd\ember-cli-build.js:127:39)
    at Builder.readBuildFile (C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\grdd\node_modules\ember-cli\lib\models\builder.js:52:14)
    at Builder.setupBroccoliBuilder (C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\grdd\node_modules\ember-cli\lib\models\builder.js:66:22)
    at new Builder (C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\grdd\node_modules\ember-cli\lib\models\builder.js:32:10)
    at ServeTask.run (C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\grdd\node_modules\ember-cli\lib\tasks\serve.js:45:55)
    at Promise.resolve.then (C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\grdd\node_modules\ember-cli\lib\models\command.js:243:46)
-~- (end) -~-
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
    - treeDir: [undefined]
  - message: C:\Users\lifeart\AppData\Local\Temp\embroider-cbSrw5\C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\node_modules\@ember-decorators contains invalid WIN32 path characters.
        at WaitForTrees (@embroider/compat/addons)
-~- created here: -~-
    at new Plugin (C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\node_modules\broccoli-plugin\index.js:7:31)
    at new WaitForTrees (C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\node_modules\@embroider\core\src\wait-for-trees.js:30:9)
    at new CompatAddons (C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\node_modules\@embroider\compat\src\compat-addons.js:35:21)
    at Object.defaultPipeline [as compatBuild] (C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\node_modules\@embroider\compat\src\default-pipeline.js:11:18)
    at module.exports (C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\grdd\ember-cli-build.js:127:39)
    at Builder.readBuildFile (C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\grdd\node_modules\ember-cli\lib\models\builder.js:52:14)
    at Builder.setupBroccoliBuilder (C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\grdd\node_modules\ember-cli\lib\models\builder.js:66:22)
    at new Builder (C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\grdd\node_modules\ember-cli\lib\models\builder.js:32:10)
    at ServeTask.run (C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\grdd\node_modules\ember-cli\lib\tasks\serve.js:45:55)
    at Promise.resolve.then (C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\grdd\node_modules\ember-cli\lib\models\command.js:243:46)
-~- (end) -~-
  - name: BuildError
  - nodeAnnotation: @embroider/compat/addons
  - nodeName: WaitForTrees
  - originalErrorMessage: C:\Users\lifeart\AppData\Local\Temp\embroider-cbSrw5\C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\node_modules\@ember-decorators contains invalid WIN32 path characters.
  - stack: Error: C:\Users\lifeart\AppData\Local\Temp\embroider-cbSrw5\C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\node_modules\@ember-decorators contains invalid WIN32 path characters.
    at mkdirsSync (C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\node_modules\@embroider\compat\node_modules\fs-extra\lib\mkdirs\mkdirs-sync.js:18:22)
    at Object.copySync (C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\node_modules\@embroider\compat\node_modules\fs-extra\lib\copy-sync\copy-sync.js:30:35)
    at forEach (C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\node_modules\@embroider\compat\src\compat-addons.js:59:24)
    at Array.forEach (<anonymous>)
    at CompatAddons.build (C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\node_modules\@embroider\compat\src\compat-addons.js:58:47)
    at WaitForTrees.build (C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\node_modules\@embroider\core\src\wait-for-trees.js:49:21)
    at resolve (C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\node_modules\broccoli\lib\wrappers\transform-node.js:29:35)
    at new Promise (<anonymous>)
    at TransformNodeWrapper.build (C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\node_modules\broccoli\lib\wrappers\transform-node.js:21:12)
    at Promise.resolve.then.then.then (C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\node_modules\broccoli\lib\builder.js:111:28)

=================================================================================

**Comment by lifeart** [comment]
```js
 async build({ movedAddons, synthVendor, synthStyles }) {
        if (this.didBuild) {
            // TODO: we can selectively allow some addons to rebuild, equivalent to
            // the old isDevelopingAddon. This should be based off Package#mayRebuild.
            return;
        }
        fs_extra_1.emptyDirSync(this.destDir);
        [...this.packageCache.moved.values()].forEach((movedPkg, index) => {
            /// error from this line:
            fs_extra_1.copySync(movedAddons[index], movedPkg.root, { dereference: true });
            this.linkNonCopiedDeps(movedPkg, movedPkg.root);
        });
        this.linkNonCopiedDeps(this.app, this.appDestDir);
        await this.packageCache.updatePreexistingResolvableSymlinks();
        fs_extra_1.copySync(synthVendor, path_1.join(this.appDestDir, 'node_modules', '@embroider', 'synthesized-vendor'), { dereference: true });
        fs_extra_1.copySync(synthStyles, path_1.join(this.appDestDir, 'node_modules', '@embroider', 'synthesized-styles'), { dereference: true });
        this.didBuild = true;
        this.deferReady.resolve();
    }
```

**Comment by lifeart** [comment]
```
movedAddons[index] === C:\Users\lifeart\AppData\Local\Temp\broccoli-1956xZ9RREubZlk7\out-000-one_shot
movedPkg.root === C:\Users\lifeart\AppData\Local\Temp\embroider-JBwpr9\C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\node_modules\@ember-decorators\babel-transforms
```

looks like error in `movedPkg.root`

**Comment by lifeart** [comment]
after replacing to 

```
 fs_extra_1.copySync(movedAddons[index], movedPkg.root.split('\\C:\\')[0], { dereference: true });
```


```
ENOENT: no such file or directory, open 'C:\Users\lifeart\AppData\Local\Temp\embroider-ChAGu8\C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\node_modules\@ember-decorators\babel-transforms\package.json'
```

```
ERROR Summary:

  - broccoliBuilderErrorStack: Error: ENOENT: no such file or directory, open 'C:\Users\lifeart\AppData\Local\Temp\embroider-ChAGu8\C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\node_modules\@ember-decorators\babel-transforms\package.json'
    at Object.openSync (fs.js:439:3)
    at Object.readFileSync (fs.js:344:35)
    at Package.get packageJSON (C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\node_modules\@embroider\core\src\package.js:30:32)
    at Package.<anonymous> (C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\node_modules\typescript-memoize\dist\memoize-decorator.js:67:52)
    at flatMap_1.default.key (C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\node_modules\@embroider\core\src\package.js:75:84)
    at arrayMap (C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\node_modules\lodash\_arrayMap.js:16:21)
    at map (C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\node_modules\lodash\map.js:50:10)
    at Object.flatMap [as default] (C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\node_modules\lodash\flatMap.js:26:22)
    at Package.get dependencies (C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\node_modules\@embroider\core\src\package.js:75:38)
    at Package.<anonymous> (C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\node_modules\typescript-memoize\dist\memoize-decorator.js:67:52)
  - code: [undefined]
  - codeFrame: ENOENT: no such file or directory, open 'C:\Users\lifeart\AppData\Local\Temp\embroider-ChAGu8\C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\node_modules\@ember-decorators\babel-transforms\package.json'
  - errorMessage: ENOENT: no such file or directory, open 'C:\Users\lifeart\AppData\Local\Temp\embroider-ChAGu8\C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\node_modules\@ember-decorators\babel-transforms\package.json'
        at WaitForTrees (@embroider/compat/addons)
-~- created here: -~-
    at new Plugin (C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\node_modules\broccoli-plugin\index.js:7:31)
    at new WaitForTrees (C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\node_modules\@embroider\core\src\wait-for-trees.js:30:9)
    at new CompatAddons (C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\node_modules\@embroider\compat\src\compat-addons.js:35:21)
    at Object.defaultPipeline [as compatBuild] (C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\node_modules\@embroider\compat\src\default-pipeline.js:11:18)
    at module.exports (C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\grdd\ember-cli-build.js:127:39)
    at Builder.readBuildFile (C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\grdd\node_modules\ember-cli\lib\models\builder.js:52:14)
    at Builder.setupBroccoliBuilder (C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\grdd\node_modules\ember-cli\lib\models\builder.js:66:22)
    at new Builder (C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\grdd\node_modules\ember-cli\lib\models\builder.js:32:10)
    at ServeTask.run (C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\grdd\node_modules\ember-cli\lib\tasks\serve.js:45:55)
    at Promise.resolve.then (C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\grdd\node_modules\ember-cli\lib\models\command.js:243:46)
-~- (end) -~-
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
    - treeDir: [undefined]
  - message: ENOENT: no such file or directory, open 'C:\Users\lifeart\AppData\Local\Temp\embroider-ChAGu8\C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\node_modules\@ember-decorators\babel-transforms\package.json'
        at WaitForTrees (@embroider/compat/addons)
-~- created here: -~-
    at new Plugin (C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\node_modules\broccoli-plugin\index.js:7:31)
    at new WaitForTrees (C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\node_modules\@embroider\core\src\wait-for-trees.js:30:9)
    at new CompatAddons (C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\node_modules\@embroider\compat\src\compat-addons.js:35:21)
    at Object.defaultPipeline [as compatBuild] (C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\node_modules\@embroider\compat\src\default-pipeline.js:11:18)
    at module.exports (C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\grdd\ember-cli-build.js:127:39)
    at Builder.readBuildFile (C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\grdd\node_modules\ember-cli\lib\models\builder.js:52:14)
    at Builder.setupBroccoliBuilder (C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\grdd\node_modules\ember-cli\lib\models\builder.js:66:22)
    at new Builder (C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\grdd\node_modules\ember-cli\lib\models\builder.js:32:10)
    at ServeTask.run (C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\grdd\node_modules\ember-cli\lib\tasks\serve.js:45:55)
    at Promise.resolve.then (C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\grdd\node_modules\ember-cli\lib\models\command.js:243:46)
-~- (end) -~-
  - name: BuildError
  - nodeAnnotation: @embroider/compat/addons
  - nodeName: WaitForTrees
  - originalErrorMessage: ENOENT: no such file or directory, open 'C:\Users\lifeart\AppData\Local\Temp\embroider-ChAGu8\C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\node_modules\@ember-decorators\babel-transforms\package.json'
  - stack: Error: ENOENT: no such file or directory, open 'C:\Users\lifeart\AppData\Local\Temp\embroider-ChAGu8\C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\node_modules\@ember-decorators\babel-transforms\package.json'
    at Object.openSync (fs.js:439:3)
    at Object.readFileSync (fs.js:344:35)
    at Package.get packageJSON (C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\node_modules\@embroider\core\src\package.js:30:32)
    at Package.<anonymous> (C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\node_modules\typescript-memoize\dist\memoize-decorator.js:67:52)
    at flatMap_1.default.key (C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\node_modules\@embroider\core\src\package.js:75:84)
    at arrayMap (C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\node_modules\lodash\_arrayMap.js:16:21)
    at map (C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\node_modules\lodash\map.js:50:10)
    at Object.flatMap [as default] (C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\node_modules\lodash\flatMap.js:26:22)
    at Package.get dependencies (C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\node_modules\@embroider\core\src\package.js:75:38)
    at Package.<anonymous> (C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\node_modules\typescript-memoize\dist\memoize-decorator.js:67:52)

=================================================================================
```

**Comment by ef4** [comment]
Thanks for reporting.

We should audit all the places that contain the string literal `"/"`. There are several in `moved-package-cache.ts` that are probably responsible for this bug.

**Comment by lifeart** [comment]
replacing `/` to `path.sep` dosen't solve issue,

C:\Users\lifeart\AppData\Local\Temp\embroider-ChAGu8\C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\node_modules\@ember-decorators\babel-transforms\package.json

and

C:\Users\lifeart\AppData\Local\Temp\embroider-JBwpr9\C:\Users\lifeart\Documents\repos\dreamcatcher-web-app\node_modules\@ember-decorators\babel-transforms

has doubled paths (`C:\...\Temp\embroider-ChAGu8\C:\...\package.json`

path has two `C:\`, one in the beginning and one in the middle.

**Comment by ef4** [comment]
Yes, I think the problem is more likely that we are doing something similar to `if (path.startsWith('/'))` to test for absolute paths.

**Comment by lifeart** [comment]
fixed
