### ISSUE TITLE
Issues with @pollyjs

### ISSUE THREAD

**Issue by Mciocca** [embroider-build/embroider#767]
I'm not well versed in embroider and not sure if this is an issue with embroider or some updating. Trying to run tests with pollyjs installed fails because it can not find `@pollyjs/core`

```
            Error: Could not find module `@pollyjs/core` imported from `(require)`
                at missingModule (http://localhost:7357/assets/vendor.js:256:11)
                at findModule (http://localhost:7357/assets/vendor.js:267:7)
                at requireModule (http://localhost:7357/assets/vendor.js:33:15)
                at eval (webpack:///../externals/@pollyjs/core.js?:1:18)
                at Object.../externals/@pollyjs/core.js (http://localhost:7357/assets/chunk.1b5c9874276dfbdc23d0.js:165:1)
                at __webpack_require__ (http://localhost:7357/assets/chunk.1b5c9874276dfbdc23d0.js:80:30)
                at eval (webpack:///./tests/acceptance/index-test.js?:5:139)
                at Module../tests/acceptance/index-test.js (http://localhost:7357/assets/chunk.1b5c9874276dfbdc23d0.js:188:1)
                at __webpack_require__ (http://localhost:7357/assets/chunk.1b5c9874276dfbdc23d0.js:80:30)
                at Module.eval [as callback] (webpack:///./assets/test.js?:193:10)

```

I have reporduced this issue here: https://github.com/Mciocca/polly-embroider-example

**Comment by ef4** [comment]
> It looks like the problem here is the relative require

I don't think that's correct, the file in question is not part of the runtime code of the addon, it's the addon's build-time configuration, which always includes `require('./package')`. You can see it in the [default addon blueprint](https://github.com/ember-cli/ember-addon-output/blob/2837653a0dc7656ce29034dbfecfdfc09d73fc21/index.js#L4).

**Comment by ef4** [comment]
@Mciocca, thanks for sharing the reproduction. That app fails because it's trying to do something illegal: it's trying to import `@pollyjs/core` from within the app's own test suite, but the app doesn't depend directly on `@pollyjs/core`. 

You cannot access your dependency's dependencies. In a classic build, all dependencies are flattened into one namespace, which causes a lot of correctness problems. Embroider doesn't do that, and each package gets its own dependencies.

If `@pollyjs/ember` intends to make `@pollyjs/core` available to apps, it should list `@pollyjs/core` as a peerDependency instead of a dependency and make apps depend directly on it.

Alternatively, `@pollyjs/ember` could reexport the things from `@pollyjs/core` that people will need, and apps should import them from `@pollyjs/ember`.

**Comment by ef4** [comment]
In your own app, you can workaround by adding a dependency on `@pollyjs/core` and being careful to make sure you're getting the same copy that `@pollyjs/ember` is getting.

**Comment by offirgolan** [comment]
@ef4 could the culprit here be the [contentFor](https://github.com/Netflix/pollyjs/blob/cbca602a5a446da46a4a2834f893670b8c577880/packages/%40pollyjs/ember/index.js#L65-L70) hook?

**Comment by ef4** [comment]
That `contentFor` is likely to work. I would definitely expect it to work with embroider in its most compatible mode (which is the default). It may not work in the most optimized mode, if `@pollyjs/ember/-private/preconfigure` gets shaken out of the build, in which case people should be told to import it themselves into their `app.js` file where it would be visible to embroider.

I explained the real problem above:

> that app fails because it's trying to do something illegal: it's trying to import @pollyjs/core from within the app's own test suite, but the app doesn't depend directly on @pollyjs/core.

You cannot skip dependency levels. Apps that want to import from `@pollyjs/core` need to actually have a direct dependency on it. The classic build let you cheat on this and import from your dependencies dependencies. Embroider does not, because it's not safe to rely on (it depends on the vagaries of NPM hoisting optimizations that may or may not happen and certainly won't happen in alternative systems like Yarn PnP).

The solution here is for apps to add `@pollyjs/core` to their devDependencies (or dependencies, doesn't really matter when it comes to apps). In order to guarantee that `@pollyjs/ember` and the app both share the exact same copy of `@pollyjs/core`, my suggestion is to move `@pollyjs/core` from `@pollyjs/ember`'s dependencies to its peerDependencies and document that apps must provide it.

Alternatively, `@pollyjs/ember` can reexport whatever people were going to use from `@pollyjs/core`, so they can import directly from `@pollyjs/ember` and not manage a separate dependency.

**Comment by offirgolan** [comment]
That makes sense to me. We can move the other @pollyjs dependencies as peer deps under the @pollyjs/ember package and update the documentation accordingly.

**Comment by ArnaudWeyts** [comment]
The `contentFor` hook didn't seem to work anymore for me using `@embroider/core@2.1.1`, so I've manually imported the `preconfigure` file inside of `test-helper.js`, which does the trick
