### ISSUE TITLE
0.41.0 broke using font awesome? Cannot read property default of undefined

### ISSUE THREAD

**Issue by NullVoxPopuli** [embroider-build/embroider#821]
Stack/build/example: https://github.com/NullVoxPopuli/limber/pull/114/checks?check_run_id=2638506237#step:7:21

Occured during renovate upgrade from embroider 0.40.0

Top portion of stack:
```
            TypeError: Cannot read property 'default' of undefined
                at Module.default (webpack://limber/./components/fa-icon.js?:3:154)
                at Module.eval [as callback] (webpack://limber/./components/limber/navigation/index.hbs?:14:51)
                at Module.exports (http://localhost:7357/assets/vendor.js:115:32)
                at requireModule (http://localhost:7357/assets/vendor.js:36:18)
                at Class._extractDefaultExport (webpack://limber/../node_modules/ember-resolver/resolvers/classic/index.js?:460:25)

```
(Output of running ember test with assets that build successfully any a prior ci job)

I have webpack@v5 already, here: https://github.com/NullVoxPopuli/limber/blob/main/frontend/package.json#L115

I read the release notes and didn't see anything that'd be relevant. Did I miss something?

**Comment by ef4** [comment]
Do you have ember-cli-babel 7.26.6?

**Comment by NullVoxPopuli** [comment]
I do, ["ember-cli-babel": "^7.26.6",](https://github.com/NullVoxPopuli/limber/blob/main/frontend/package.json#L80)

**Comment by NullVoxPopuli** [comment]
ah, I didn't notice that I _also_ have this error:
```
     Error: Could not find module `ember-get-config` imported from `(require)`
                at missingModule (http://localhost:7357/assets/vendor.js:256:11)
                at findModule (http://localhost:7357/assets/vendor.js:267:7)
                at requireModule (http://localhost:7357/assets/vendor.js:33:15)
                at eval (webpack://limber/../../externals/ember-get-config.js?:1:18)
                at Object.../../externals/ember-get-config.js (http://localhost:7357/assets/chunk.703f3fd5c7e745bab3d8.js:222:1)
                at __webpack_require__ (http://localhost:7357/assets/chunk.c41fb7dda7723b7b6f82.js:174:42)
                at eval (webpack://limber/../node_modules/@fortawesome/ember-fontawesome/components/fa-icon.js?:8:85)
                at Module.../node_modules/@fortawesome/ember-fontawesome/components/fa-icon.js (http://localhost:7357/assets/chunk.54ed88766d2c3b892a0d.js:4630:1)
                at __webpack_require__ (http://localhost:7357/assets/chunk.c41fb7dda7723b7b6f82.js:174:42)
                at eval (webpack://limber/./components/fa-icon.js?:5:120)
```

I think I've seen this one reported. gonna look around

**Comment by NullVoxPopuli** [comment]
ah: https://github.com/embroider-build/embroider/issues/823
I'm going to poke around font-awesome and see if it still needs the compat adapter

**Comment by NullVoxPopuli** [comment]
good news - reproduced with just ember-fontawesome over here: https://github.com/FortAwesome/ember-fontawesome/pull/174

**Comment by bendemboski** [comment]
Any workaround for this? It's preventing me from upgrading embroider...

**Comment by NullVoxPopuli** [comment]
I don't think so, we need font awesome to use embroider macros, but there were issues it seems

**Comment by NullVoxPopuli** [comment]
In the latest release of font-awesome, This is no longer an issue :tada: 

I'm using:
```
    "@fortawesome/ember-fontawesome": "^0.3.0",
```
