### ISSUE TITLE
unable to resolve babel plugin @babel/plugin-proposal-nullish-coalescing-operator

### ISSUE THREAD

**Issue by nlfurniss** [embroider-build/embroider#835]
[Repo link](https://github.com/nlfurniss/ember-simple-wormhole)

Running the latest `@embroider/test-setup`, v0.41.0, fails in `embroider-safe` and `embroider-optimized` scenarios.

Full stacktrace:
```
ERROR Summary:

  - broccoliBuilderErrorStack: Error: unable to resolve babel plugin @babel/plugin-proposal-nullish-coalescing-operator from /tmp/embroider/833b79/tests/dummy
    at PortableBabelConfig.resolveBabelPlugin (/home/runner/work/ember-simple-wormhole/ember-simple-wormhole/node_modules/@embroider/core/src/portable-babel-config.js:124:27)
    at Portable.dehydrate (/home/runner/work/ember-simple-wormhole/ember-simple-wormhole/node_modules/@embroider/core/src/portable-babel-config.js:43:35)
    at Portable.dehydrate (/home/runner/work/ember-simple-wormhole/ember-simple-wormhole/node_modules/@embroider/core/src/portable.js:24:46)
    at /home/runner/work/ember-simple-wormhole/ember-simple-wormhole/node_modules/@embroider/core/src/portable.js:41:62
    at Array.map (<anonymous>)
    at Portable.dehydrate (/home/runner/work/ember-simple-wormhole/ember-simple-wormhole/node_modules/@embroider/core/src/portable.js:41:33)
    at /home/runner/work/ember-simple-wormhole/ember-simple-wormhole/node_modules/@embroider/core/src/portable.js:59:43
    at /home/runner/work/ember-simple-wormhole/ember-simple-wormhole/node_modules/lodash/mapValues.js:38:34
    at /home/runner/work/ember-simple-wormhole/ember-simple-wormhole/node_modules/lodash/_createBaseFor.js:17:11
    at baseForOwn (/home/runner/work/ember-simple-wormhole/ember-simple-wormhole/node_modules/lodash/_baseForOwn.js:13:20)
  - code: [undefined]
  - codeFrame: unable to resolve babel plugin @babel/plugin-proposal-nullish-coalescing-operator from /tmp/embroider/833b79/tests/dummy
  - errorMessage: unable to resolve babel plugin @babel/plugin-proposal-nullish-coalescing-operator from /tmp/embroider/833b79/tests/dummy
        at WaitForTrees (@embroider/compat/app)
-~- created here: -~-
    at new Plugin (/home/runner/work/ember-simple-wormhole/ember-simple-wormhole/node_modules/@embroider/core/node_modules/broccoli-plugin/dist/index.js:47:36)
    at new WaitForTrees (/home/runner/work/ember-simple-wormhole/ember-simple-wormhole/node_modules/@embroider/core/src/wait-for-trees.js:30:9)
    at CompatApp.get tree (/home/runner/work/ember-simple-wormhole/ember-simple-wormhole/node_modules/@embroider/core/src/build-stage.js:26:16)
    at CompatApp.<anonymous> (/home/runner/work/ember-simple-wormhole/ember-simple-wormhole/node_modules/typescript-memoize/dist/memoize-decorator.js:100:52)
    at new PackagerRunner (/home/runner/work/ember-simple-wormhole/ember-simple-wormhole/node_modules/@embroider/core/src/to-broccoli-plugin.js:10:26)
    at Object.defaultPipeline (/home/runner/work/ember-simple-wormhole/ember-simple-wormhole/node_modules/@embroider/compat/src/default-pipeline.js:43:12)
    at maybeEmbroider (/home/runner/work/ember-simple-wormhole/ember-simple-wormhole/node_modules/@embroider/test-setup/src/index.js:39:19)
    at module.exports (/home/runner/work/ember-simple-wormhole/ember-simple-wormhole/ember-cli-build.js:21:10)
    at Builder.readBuildFile (/home/runner/work/ember-simple-wormhole/ember-simple-wormhole/node_modules/ember-cli/lib/models/builder.js:49:14)
    at Builder.setupBroccoliBuilder (/home/runner/work/ember-simple-wormhole/ember-simple-wormhole/node_modules/ember-cli/lib/models/builder.js:63:22)
-~- (end) -~-
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
    - treeDir: [undefined]
  - message: unable to resolve babel plugin @babel/plugin-proposal-nullish-coalescing-operator from /tmp/embroider/833b79/tests/dummy
        at WaitForTrees (@embroider/compat/app)
-~- created here: -~-
    at new Plugin (/home/runner/work/ember-simple-wormhole/ember-simple-wormhole/node_modules/@embroider/core/node_modules/broccoli-plugin/dist/index.js:47:36)
    at new WaitForTrees (/home/runner/work/ember-simple-wormhole/ember-simple-wormhole/node_modules/@embroider/core/src/wait-for-trees.js:30:9)
    at CompatApp.get tree (/home/runner/work/ember-simple-wormhole/ember-simple-wormhole/node_modules/@embroider/core/src/build-stage.js:26:16)
    at CompatApp.<anonymous> (/home/runner/work/ember-simple-wormhole/ember-simple-wormhole/node_modules/typescript-memoize/dist/memoize-decorator.js:100:52)
    at new PackagerRunner (/home/runner/work/ember-simple-wormhole/ember-simple-wormhole/node_modules/@embroider/core/src/to-broccoli-plugin.js:10:26)
    at Object.defaultPipeline (/home/runner/work/ember-simple-wormhole/ember-simple-wormhole/node_modules/@embroider/compat/src/default-pipeline.js:43:12)
    at maybeEmbroider (/home/runner/work/ember-simple-wormhole/ember-simple-wormhole/node_modules/@embroider/test-setup/src/index.js:39:19)
    at module.exports (/home/runner/work/ember-simple-wormhole/ember-simple-wormhole/ember-cli-build.js:21:10)
    at Builder.readBuildFile (/home/runner/work/ember-simple-wormhole/ember-simple-wormhole/node_modules/ember-cli/lib/models/builder.js:49:14)
    at Builder.setupBroccoliBuilder (/home/runner/work/ember-simple-wormhole/ember-simple-wormhole/node_modules/ember-cli/lib/models/builder.js:63:22)
-~- (end) -~-
  - name: Error
  - nodeAnnotation: @embroider/compat/app
  - nodeName: WaitForTrees
  - originalErrorMessage: unable to resolve babel plugin @babel/plugin-proposal-nullish-coalescing-operator from /tmp/embroider/833b79/tests/dummy
  - stack: Error: unable to resolve babel plugin @babel/plugin-proposal-nullish-coalescing-operator from /tmp/embroider/833b79/tests/dummy
    at PortableBabelConfig.resolveBabelPlugin (/home/runner/work/ember-simple-wormhole/ember-simple-wormhole/node_modules/@embroider/core/src/portable-babel-config.js:124:27)
    at Portable.dehydrate (/home/runner/work/ember-simple-wormhole/ember-simple-wormhole/node_modules/@embroider/core/src/portable-babel-config.js:43:35)
    at Portable.dehydrate (/home/runner/work/ember-simple-wormhole/ember-simple-wormhole/node_modules/@embroider/core/src/portable.js:24:46)
    at /home/runner/work/ember-simple-wormhole/ember-simple-wormhole/node_modules/@embroider/core/src/portable.js:41:62
    at Array.map (<anonymous>)
    at Portable.dehydrate (/home/runner/work/ember-simple-wormhole/ember-simple-wormhole/node_modules/@embroider/core/src/portable.js:41:33)
    at /home/runner/work/ember-simple-wormhole/ember-simple-wormhole/node_modules/@embroider/core/src/portable.js:59:43
    at /home/runner/work/ember-simple-wormhole/ember-simple-wormhole/node_modules/lodash/mapValues.js:38:34
    at /home/runner/work/ember-simple-wormhole/ember-simple-wormhole/node_modules/lodash/_createBaseFor.js:17:11
    at baseForOwn (/home/runner/work/ember-simple-wormhole/ember-simple-wormhole/node_modules/lodash/_baseForOwn.js:13:20)
```

**Comment by ef4** [comment]
This could be NPM/Yarn inconsistency. Please run `npx are-my-node-modules-messed-up` to rule that out first.

**Comment by nlfurniss** [comment]
> npx are-my-node-modules-messed-up

```
nfurniss: ember-simple-wormhole (master) $ npx are-my-node-modules-messed-up
npx: installed 23 in 2.343s
Your node_modules look good.
```
☹️

**Comment by ef4** [comment]
Ok, I took a look at the repo. The dummy app is relying on that babel plugin:

https://github.com/nlfurniss/ember-simple-wormhole/blob/a88941fb0ec5684a952068a95e5083cfcecc3ee0/ember-cli-build.js#L9

without declaring it as a dependency:

https://github.com/nlfurniss/ember-simple-wormhole/blob/a88941fb0ec5684a952068a95e5083cfcecc3ee0/package.json#L33-L68

It usually works by accident in the classic build, because of yarn hoisting optimization. It doesn't work under embroider because we are stricter.

**Comment by nlfurniss** [comment]
Thanks Ed!
