### ISSUE TITLE
Incorrect resolve attached to `ember-source`. ModuleNotFoundError.

### ISSUE THREAD

**Issue by esbanarango** [embroider-build/embroider#849]
Similar issue to https://github.com/embroider-build/embroider/issues/817. I have an app where I'm trying out embroider. This app uses mirage, and it depends on `pretender "^3.4.3"`. I'm getting this build error:

```
Build Error (PackagerRunner) in ../../../../../../../../Users/esbanarango/Developer/embroiderTestApp/node_modules/pretender/dist/pretender.es.js

Module not found: Error: Can't resolve 'ember-source/route-recognizer/index.js' in '/Users/esbanarango/Developer/embroiderTestApp/node_modules/pretender/dist/pretender.es.js'
```

<img width="595" alt="pretender_es_js_—_workspace__Workspace_" src="https://user-images.githubusercontent.com/1156865/121951002-fbf8d100-cd1f-11eb-813b-0dff72ed1ac8.png">

Somehow it's trying to resolve `route-recognizer` from `ember-source/route-recognizer/index.js` ? 🤔 

<details>
<summary>Logs</summary>
<pre>
ERROR Summary:

  - broccoliBuilderErrorStack: ModuleNotFoundError: Module not found: Error: Can't resolve 'ember-source/route-recognizer/index.js' in '/Users/esbanarango/Developer/embroiderTestApp/node_modules/pretender/dist/pretender.es.js'
    at /Users/esbanarango/Developer/embroiderTestApp/node_modules/webpack/lib/Compilation.js:1762:28
    at /Users/esbanarango/Developer/embroiderTestApp/node_modules/webpack/lib/NormalModuleFactory.js:732:13
    at eval (eval at create (/Users/esbanarango/Developer/embroiderTestApp/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:8:1)
    at /Users/esbanarango/Developer/embroiderTestApp/node_modules/webpack/lib/NormalModuleFactory.js:274:22
    at eval (eval at create (/Users/esbanarango/Developer/embroiderTestApp/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:7:1)
    at /Users/esbanarango/Developer/embroiderTestApp/node_modules/webpack/lib/NormalModuleFactory.js:403:22
    at /Users/esbanarango/Developer/embroiderTestApp/node_modules/webpack/lib/NormalModuleFactory.js:117:11
    at /Users/esbanarango/Developer/embroiderTestApp/node_modules/webpack/lib/NormalModuleFactory.js:648:24
    at /Users/esbanarango/Developer/embroiderTestApp/node_modules/webpack/lib/NormalModuleFactory.js:802:8
    at /Users/esbanarango/Developer/embroiderTestApp/node_modules/webpack/lib/NormalModuleFactory.js:922:5
  - code: [undefined]
  - codeFrame: Module not found: Error: Can't resolve 'ember-source/route-recognizer/index.js' in '/Users/esbanarango/Developer/embroiderTestApp/node_modules/pretender/dist/pretender.es.js'
  - errorMessage: ../../../../../../../../Users/esbanarango/Developer/embroiderTestApp/node_modules/pretender/dist/pretender.es.js: Module not found: Error: Can't resolve 'ember-source/route-recognizer/index.js' in '/Users/esbanarango/Developer/embroiderTestApp/node_modules/pretender/dist/pretender.es.js'
        at PackagerRunner (@embroider/webpack)
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: ../../../../../../../../Users/esbanarango/Developer/embroiderTestApp/node_modules/pretender/dist/pretender.es.js
    - line: [null]
    - treeDir: [undefined]
  - message: ../../../../../../../../Users/esbanarango/Developer/embroiderTestApp/node_modules/pretender/dist/pretender.es.js: Module not found: Error: Can't resolve 'ember-source/route-recognizer/index.js' in '/Users/esbanarango/Developer/embroiderTestApp/node_modules/pretender/dist/pretender.es.js'
        at PackagerRunner (@embroider/webpack)
  - name: Error
  - nodeAnnotation: @embroider/webpack
  - nodeName: PackagerRunner
  - originalErrorMessage: Module not found: Error: Can't resolve 'ember-source/route-recognizer/index.js' in '/Users/esbanarango/Developer/embroiderTestApp/node_modules/pretender/dist/pretender.es.js'
  - stack: ModuleNotFoundError: Module not found: Error: Can't resolve 'ember-source/route-recognizer/index.js' in '/Users/esbanarango/Developer/embroiderTestApp/node_modules/pretender/dist/pretender.es.js'
    at /Users/esbanarango/Developer/embroiderTestApp/node_modules/webpack/lib/Compilation.js:1762:28
    at /Users/esbanarango/Developer/embroiderTestApp/node_modules/webpack/lib/NormalModuleFactory.js:732:13
    at eval (eval at create (/Users/esbanarango/Developer/embroiderTestApp/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:8:1)
    at /Users/esbanarango/Developer/embroiderTestApp/node_modules/webpack/lib/NormalModuleFactory.js:274:22
    at eval (eval at create (/Users/esbanarango/Developer/embroiderTestApp/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:7:1)
    at /Users/esbanarango/Developer/embroiderTestApp/node_modules/webpack/lib/NormalModuleFactory.js:403:22
    at /Users/esbanarango/Developer/embroiderTestApp/node_modules/webpack/lib/NormalModuleFactory.js:117:11
    at /Users/esbanarango/Developer/embroiderTestApp/node_modules/webpack/lib/NormalModuleFactory.js:648:24
    at /Users/esbanarango/Developer/embroiderTestApp/node_modules/webpack/lib/NormalModuleFactory.js:802:8
    at /Users/esbanarango/Developer/embroiderTestApp/node_modules/webpack/lib/NormalModuleFactory.js:922:5
</pre>
</details>

```
"@embroider/compat": "^0.41.0",
"@embroider/core": "^0.41.0",
"@embroider/webpack": "^0.41.0",
...
"ember-source": "3.28.0-beta.5"
"ember-cli-babel": "^7.26.6",
"ember-cli-mirage": "2.2.0",
```

**Comment by mydea** [comment]
I encountered the same issue. I created an issue with a minimal reproduction over in ember-source, not sure where this belongs to:
https://github.com/emberjs/ember.js/issues/19601

**Comment by ef4** [comment]
Thanks for reporting. This is indeed the same issue as #817.

We can probably do a fancier CompatAdapter for ember-source that would fix its own references to these packages without leaking rules that change everybody else's references to them.

But ultimately ember-source needs to ship something that makes more sense: either stop bundling in these dependencies, or keep bundling them but import them via relative paths instead of expecting them to be resolvable by their original package names.

**Comment by esbanarango** [comment]
@ef4 Thank you 🙏 

> We can probably do a fancier CompatAdapter for ember-source that would fix its own references to these packages without leaking rules that change everybody else's references to them.

Is this ^ being considerated at all?

**Comment by alexlafroscia** [comment]
@ef4 is it the `customAddonTree` that is updating the module paths? I'd love to try to fix this, but reading through the `ember-source` compat adapter I can't quite find anything that looks like it's updating module paths

https://github.com/alexlafroscia/embroider/blob/f29d767fb87390c32abf50de417781420a559596/packages/compat/src/compat-adapters/ember-source.ts#L38-L47

**Comment by esbanarango** [comment]
@alexlafroscia let me know if you have any in-progress branch I can test with 🙏

**Comment by alexlafroscia** [comment]
I wish I could say I did, but without having any idea where to start digging into this, I don't have anything in progress 😦

**Comment by ef4** [comment]
There is now some in progress work for this issue here: https://github.com/embroider-build/embroider/pull/919

**Comment by esbanarango** [comment]
That's great! Thank you @ef4

**Comment by lolmaus** [comment]
This issue should no longer happen with latest Embroider. If you encounter the issue in the latest Embroider version, don't hesitate to ping to reopen.
