### ISSUE TITLE
Issue with ember-engines v0.8.5+ and ember-source < 3.24

### ISSUE THREAD

**Issue by thoov** [embroider-build/embroider#857]
Error:

```
Error: Could not find module `../components/link-to-component` imported from `(require)`
   at missingModule (http://localhost:7357/assets/vendor.js:256:11)
   at findModule (http://localhost:7357/assets/vendor.js:267:7)
   at requireModule (http://localhost:7357/assets/vendor.js:33:15)
   at Class.buildRegistry (webpack://app-template/../../home/runner/work/embroider/embroider/tests/scenarios/node_modules/ember-engines/-private/engine-ext.js?:13:98)
```

Relevant: 

https://github.com/ember-engines/ember-engines/blob/9cf5d88d79d8ea025a291ac2b6feb6da7a16b908/packages/ember-engines/addon/-private/engine-ext.js#L14

Temp workaround:

Pin ember-engines to 0.8.5

**Comment by thoov** [comment]
Found this issue during #854 when trying to unpin ember-engines version

**Comment by ef4** [comment]
Yeah, I saw this too but didn't debug it yet: https://github.com/embroider-build/embroider/issues/745

**Comment by thoov** [comment]
@ef4 this fixes it: https://github.com/ember-engines/ember-engines/pull/777. We might want to talk about how we can handle this case better or output a warning / error.
