### ISSUE TITLE
Local helpers not resolved in tests

### ISSUE THREAD

**Issue by NullVoxPopuli** [embroider-build/embroider#894]
```
Build Error (PackagerRunner) in tests/rendering/compile-hbs-test.ts

Module build failed (from ../../../../../home/me/Development/NullVoxPopuli/ember-play/node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 0)
$TMPDIR/embroider/5e47be/tests/dummy/tests/rendering/compile-hbs-test.ts/compile-hbs-test.ts: Missing helper: this.compile in tests/rendering/compile-hbs-test.ts

    at CompatResolver.dependenciesOf (/home/me/Development/NullVoxPopuli/ember-play/node_modules/@embroider/compat/src/resolver.js:251:33)
    at NodeTemplateCompiler.precompile (/home/me/Development/NullVoxPopuli/ember-play/node_modules/@embroider/core/src/template-compiler-common.js:78:42)
    at handleTagged (/home/me/Development/NullVoxPopuli/ember-play/node_modules/@embroider/core/src/babel-plugin-inline-hbs.js:68:62)
    at PluginPass.TaggedTemplateExpression (/home/me/Development/NullVoxPopuli/ember-play/node_modules/@embroider/core/src/babel-plugin-inline-hbs.js:38:29)
    at PluginPass.<anonymous> (/home/me/Development/NullVoxPopuli/ember-play/node_modules/@embroider/core/src/portable-babel-launcher.js:37:29)
    at newFn (/home/me/Development/NullVoxPopuli/ember-play/node_modules/@babel/traverse/lib/visitors.js:171:21)
    at NodePath._call (/home/me/Development/NullVoxPopuli/ember-play/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/home/me/Development/NullVoxPopuli/ember-play/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/home/me/Development/NullVoxPopuli/ember-play/node_modules/@babel/traverse/lib/path/context.js:90:31)
    at TraversalContext.visitQueue (/home/me/Development/NullVoxPopuli/ember-play/node_modules/@babel/traverse/lib/context.js:99:16)
```

```ts
  test('it works', async function (assert) {
    assert.expect(5);

    this.setProperties({
      compile: () => {
        let template = `
          {{#each (array 1 2) as |num|}}
            <output>{{num}}</output>
          {{/each}}
        `;

        let {component, name, error} = compileHBS(template);

        assert.notOk(error);
        assert.ok(name);

        return component;
      },
    });

    await render(
      hbs`
        {{#let (this.compile) as |CustomComponent|}}
          <CustomComponent />
        {{/let}}
      `
    );

    assert.dom('output').exists({count: 2});
    assert.dom().containsText('1');
    assert.dom().containsText('2');
  });
```

this occurs during the embroider-optimized build of my addon with the additional following config in the ember-cli-build:
```js
  const { maybeEmbroider } = require('@embroider/test-setup');

  return maybeEmbroider(app, {
    packageRules: [
      {
        package: 'dummy',
        helpers: {
          '{{this.compile}}': { safeToIgnore: true },
        },
      },
    ],
    packagerOptions: {
      webpackConfig: {
        node: {
          global: false,
          __filename: true,
          __dirname: true,
        },
        resolve: {
          fallback: {
            path: 'path-browserify',
          },
        },
      },
    },
  });
```

**Comment by NullVoxPopuli** [comment]
I can _kinda_ get past this with a non-ideal way via `staticHelpers: false`, but I don't think that's a great solution, as I do technically have a statically-analyzeable helper.

**Comment by lifeart** [comment]
looks like `this` in tests is a pain

**Comment by ef4** [comment]
The extra parentheses here mean you're trying to invoke `this.compile` as a helper:

```hbs
{{#let (this.compile) as |CustomComponent|}}
```

I think it will work fine if you do this:

```hbs
{{#let this.compile as |CustomComponent|}}
```

**Comment by NullVoxPopuli** [comment]
I have a plain-function helper-manager, so `(this.compile)` is correct
