### ISSUE TITLE
ember-canary packages/utils appears to be failing

### ISSUE THREAD

**Issue by stefanpenner** [embroider-build/embroider#932]
ember-canary in packages/utils appears to be failing:
See https://github.com/embroider-build/embroider/runs/3397677418
```js
not ok 1 Chrome 92.0 - [143 ms] - Integration | Helper | ensure-safe-component: string value
    ---
        actual: >
            null
        stack: >
            TypeError: templateFactory$$1 is not a function
                at Function.create (webpack://dummy/../../node_modules/ember-source/@ember/-internals/glimmer/index.js?:8716:22)
                at FactoryManager.create (webpack://dummy/../../node_modules/ember-source/@ember/-internals/container/index.js?:483:25)
                at Proxy.create (webpack://dummy/../../node_modules/ember-source/@ember/-internals/container/index.js?:262:16)
                at eval (webpack://dummy/../../../../node_modules/@ember/test-helpers/setup-rendering-context.js?:252:35)
        message: >
            Promise rejected before "string value": templateFactory$$1 is not a function
        negative: >
            false

```

I am starting to investigate now, and I am able to reproduce locally

**Comment by stefanpenner** [comment]
I believe `@ember/test-helpers` is currently incompatible with `ember-canary` due to https://github.com/emberjs/ember.js/pull/19680 landing. I suspect https://github.com/emberjs/ember.js/pull/19680#discussion_r694190928 will need to be added to `@ember/test-helpers`

**Comment by stefanpenner** [comment]
possible FIX to `@ember/test-helpers` -> https://github.com/emberjs/ember-test-helpers/pull/1110

**Comment by stefanpenner** [comment]
Ok, that fix landed. Unfortunately, there appears to be a new issue, this time one with the template-compiler.

**Comment by stefanpenner** [comment]
```
Module build failed (from ../../../../../../../../../../../../Users/spenner/src/embroider-build/embroider/packages/babel-loader-8/index.js):
NonErrorEmittedError: (Emitted value instead of an instance of Error) TypeError: $TMPDIR/embroider/cb03bb/node_modules/@ember/test-helpers/setup-rendering-context.js/setup-rendering-context.js: Cannot read property 'visitor' of undefined
    at processResult (/Users/spenner/src/embroider-build/embroider/node_modules/webpack/lib/NormalModule.js:718:12)
    at /Users/spenner/src/embroider-build/embroider/node_modules/webpack/lib/NormalModule.js:827:5
    at /Users/spenner/src/embroider-build/embroider/node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at /Users/spenner/src/embroider-build/embroider/node_modules/loader-runner/lib/LoaderRunner.js:251:18
    at context.callback (/Users/spenner/src/embroider-build/embroider/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at /Users/spenner/src/embroider-build/embroider/node_modules/babel-loader/lib/index.js:59:103
```

**Comment by stefanpenner** [comment]
I believe I have fixed the next issue as well. Pending CI confirmation.
