### ISSUE TITLE
embroider don't works with relative path on import

### ISSUE THREAD

**Issue by villander** [embroider-build/embroider#97]
Embroider: 0.1.0
ember-cli: 3.8.1

```
web_app git:(feature/embroider) ✗ ember s
DEPRECATION: ember-i18n has been deprecated in favor of ember-intl
The `no-bare-strings` rule must be configured when using a localization framework (`ember-i18n`). To prevent this warning, add the following to your `.template-lintrc.js`:

  rules: {
    'no-bare-strings': true
  }
Building into /private/var/folders/0v/jpdg1flj3qscvbvt728pgt8c0000gn/T/embroider-DotAHl
WARNING: Your build is slower because some babel plugins are non-serializable []
Build Error (PackagerRunner)

Module not found: Error: Can't resolve './gateway-api' in '/private/var/folders/0v/jpdg1flj3qscvbvt728pgt8c0000gn/T/embroider-DotAHl/adapters'


Stack Trace and Error Report: /var/folders/0v/jpdg1flj3qscvbvt728pgt8c0000gn/T/error.dump.88b151df316fe42658b4399af3e6ae65.log
```

# log error

```
=================================================================================

ENV Summary:

  TIME: Fri Mar 22 2019 16:57:24 GMT-0300 (GMT-03:00)
  TITLE: ember
  ARGV:
  - /Users/villander/.nvm/versions/node/v10.15.3/bin/node
  - /Users/villander/.nvm/versions/node/v10.15.3/bin/ember
  - s
  EXEC_PATH: /Users/villander/.nvm/versions/node/v10.15.3/bin/node
  TMPDIR: /var/folders/0v/jpdg1flj3qscvbvt728pgt8c0000gn/T
  SHELL: /bin/zsh
  PATH:
  - /Users/villander/.nvm/versions/node/v10.15.3/bin
  - /usr/local/bin
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  PLATFORM: darwin x64
  FREEMEM: 159432704
  TOTALMEM: 17179869184
  UPTIME: 27279
  LOADAVG: 2.224609375,1.81103515625,1.767578125
  CPUS:
  - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz - 2600
  - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz - 2600
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.15.0
  - cldr: 33.1
  - http_parser: 2.8.0
  - icu: 62.1
  - modules: 64
  - napi: 3
  - nghttp2: 1.34.0
  - node: 10.15.3
  - openssl: 1.1.0j
  - tz: 2018e
  - unicode: 11.0
  - uv: 1.23.2
  - v8: 6.8.275.32-node.51
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: ModuleNotFoundError: Module not found: Error: Can't resolve './gateway-api' in '/private/var/folders/0v/jpdg1flj3qscvbvt728pgt8c0000gn/T/embroider-DotAHl/adapters'
    at factory.create (/Users/villander/Projects/web_app/node_modules/webpack/lib/Compilation.js:821:10)
    at factory (/Users/villander/Projects/web_app/node_modules/webpack/lib/NormalModuleFactory.js:397:22)
    at resolver (/Users/villander/Projects/web_app/node_modules/webpack/lib/NormalModuleFactory.js:130:21)
    at asyncLib.parallel (/Users/villander/Projects/web_app/node_modules/webpack/lib/NormalModuleFactory.js:224:22)
    at /Users/villander/Projects/web_app/node_modules/neo-async/async.js:2825:7
    at /Users/villander/Projects/web_app/node_modules/neo-async/async.js:6886:13
    at normalResolver.resolve (/Users/villander/Projects/web_app/node_modules/webpack/lib/NormalModuleFactory.js:214:25)
    at doResolve (/Users/villander/Projects/web_app/node_modules/enhanced-resolve/lib/Resolver.js:184:12)
    at hook.callAsync (/Users/villander/Projects/web_app/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/villander/Projects/web_app/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at resolver.doResolve (/Users/villander/Projects/web_app/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5)
    at hook.callAsync (/Users/villander/Projects/web_app/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/villander/Projects/web_app/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at hook.callAsync (/Users/villander/Projects/web_app/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/villander/Projects/web_app/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:12:1)
    at resolver.doResolve (/Users/villander/Projects/web_app/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
    at hook.callAsync (/Users/villander/Projects/web_app/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn42 (eval at create (/Users/villander/Projects/web_app/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:393:1)
    at hook.callAsync (/Users/villander/Projects/web_app/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/villander/Projects/web_app/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:12:1)
    at resolver.doResolve (/Users/villander/Projects/web_app/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
    at hook.callAsync (/Users/villander/Projects/web_app/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
  - code: [undefined]
  - codeFrame: Module not found: Error: Can't resolve './gateway-api' in '/private/var/folders/0v/jpdg1flj3qscvbvt728pgt8c0000gn/T/embroider-DotAHl/adapters'
  - errorMessage: Module not found: Error: Can't resolve './gateway-api' in '/private/var/folders/0v/jpdg1flj3qscvbvt728pgt8c0000gn/T/embroider-DotAHl/adapters'
        at PackagerRunner (@embroider/webpack)
-~- created here: -~-
    at new Plugin (/Users/villander/Projects/web_app/node_modules/broccoli-plugin/index.js:7:31)
    at new PackagerRunner (/Users/villander/Projects/web_app/node_modules/@embroider/core/src/to-broccoli-plugin.js:11:13)
    at Object.defaultPipeline [as compatBuild] (/Users/villander/Projects/web_app/node_modules/@embroider/compat/src/default-pipeline.js:24:12)
    at module.exports (/Users/villander/Projects/web_app/ember-cli-build.js:72:39)
    at Builder.readBuildFile (/Users/villander/Projects/web_app/node_modules/ember-cli/lib/models/builder.js:52:14)
    at Builder.setupBroccoliBuilder (/Users/villander/Projects/web_app/node_modules/ember-cli/lib/models/builder.js:66:22)
    at new Builder (/Users/villander/Projects/web_app/node_modules/ember-cli/lib/models/builder.js:32:10)
    at ServeTask.run (/Users/villander/Projects/web_app/node_modules/ember-cli/lib/tasks/serve.js:45:55)
    at Promise.resolve.then (/Users/villander/Projects/web_app/node_modules/ember-cli/lib/models/command.js:243:46)
    at tryCatcher (/Users/villander/Projects/web_app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:323:19)
    at invokeCallback (/Users/villander/Projects/web_app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:495:31)
    at /Users/villander/Projects/web_app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:559:14
    at flush (/Users/villander/Projects/web_app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:2402:5)
    at process._tickCallback (internal/process/next_tick.js:61:11)
    at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
-~- (end) -~-
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
    - treeDir: [undefined]
  - message: Module not found: Error: Can't resolve './gateway-api' in '/private/var/folders/0v/jpdg1flj3qscvbvt728pgt8c0000gn/T/embroider-DotAHl/adapters'
        at PackagerRunner (@embroider/webpack)
-~- created here: -~-
    at new Plugin (/Users/villander/Projects/web_app/node_modules/broccoli-plugin/index.js:7:31)
    at new PackagerRunner (/Users/villander/Projects/web_app/node_modules/@embroider/core/src/to-broccoli-plugin.js:11:13)
    at Object.defaultPipeline [as compatBuild] (/Users/villander/Projects/web_app/node_modules/@embroider/compat/src/default-pipeline.js:24:12)
    at module.exports (/Users/villander/Projects/web_app/ember-cli-build.js:72:39)
    at Builder.readBuildFile (/Users/villander/Projects/web_app/node_modules/ember-cli/lib/models/builder.js:52:14)
    at Builder.setupBroccoliBuilder (/Users/villander/Projects/web_app/node_modules/ember-cli/lib/models/builder.js:66:22)
    at new Builder (/Users/villander/Projects/web_app/node_modules/ember-cli/lib/models/builder.js:32:10)
    at ServeTask.run (/Users/villander/Projects/web_app/node_modules/ember-cli/lib/tasks/serve.js:45:55)
    at Promise.resolve.then (/Users/villander/Projects/web_app/node_modules/ember-cli/lib/models/command.js:243:46)
    at tryCatcher (/Users/villander/Projects/web_app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:323:19)
    at invokeCallback (/Users/villander/Projects/web_app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:495:31)
    at /Users/villander/Projects/web_app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:559:14
    at flush (/Users/villander/Projects/web_app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:2402:5)
    at process._tickCallback (internal/process/next_tick.js:61:11)
    at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
-~- (end) -~-
  - name: BuildError
  - nodeAnnotation: @embroider/webpack
  - nodeName: PackagerRunner
  - originalErrorMessage: Module not found: Error: Can't resolve './gateway-api' in '/private/var/folders/0v/jpdg1flj3qscvbvt728pgt8c0000gn/T/embroider-DotAHl/adapters'
  - stack: ModuleNotFoundError: Module not found: Error: Can't resolve './gateway-api' in '/private/var/folders/0v/jpdg1flj3qscvbvt728pgt8c0000gn/T/embroider-DotAHl/adapters'
    at factory.create (/Users/villander/Projects/web_app/node_modules/webpack/lib/Compilation.js:821:10)
    at factory (/Users/villander/Projects/web_app/node_modules/webpack/lib/NormalModuleFactory.js:397:22)
    at resolver (/Users/villander/Projects/web_app/node_modules/webpack/lib/NormalModuleFactory.js:130:21)
    at asyncLib.parallel (/Users/villander/Projects/web_app/node_modules/webpack/lib/NormalModuleFactory.js:224:22)
    at /Users/villander/Projects/web_app/node_modules/neo-async/async.js:2825:7
    at /Users/villander/Projects/web_app/node_modules/neo-async/async.js:6886:13
    at normalResolver.resolve (/Users/villander/Projects/web_app/node_modules/webpack/lib/NormalModuleFactory.js:214:25)
    at doResolve (/Users/villander/Projects/web_app/node_modules/enhanced-resolve/lib/Resolver.js:184:12)
    at hook.callAsync (/Users/villander/Projects/web_app/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/villander/Projects/web_app/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at resolver.doResolve (/Users/villander/Projects/web_app/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5)
    at hook.callAsync (/Users/villander/Projects/web_app/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/villander/Projects/web_app/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at hook.callAsync (/Users/villander/Projects/web_app/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/villander/Projects/web_app/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:12:1)
    at resolver.doResolve (/Users/villander/Projects/web_app/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
    at hook.callAsync (/Users/villander/Projects/web_app/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn42 (eval at create (/Users/villander/Projects/web_app/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:393:1)
    at hook.callAsync (/Users/villander/Projects/web_app/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/villander/Projects/web_app/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:12:1)
    at resolver.doResolve (/Users/villander/Projects/web_app/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
    at hook.callAsync (/Users/villander/Projects/web_app/node_modules/enhanced-resolve/lib/Resolver.js:238:5)

=================================================================================
```

**Comment by Turbo87** [comment]
@villander can you provide instructions on how to reproduce this issue?

**Comment by villander** [comment]
@Turbo87 I just install `embroider` on my app, then run `ember s`

**Comment by Turbo87** [comment]
can you reproduce this with a fresh `ember new` app? (we don't have access to "your app" 😉)

**Comment by villander** [comment]
@Turbo87 look the error - `Module not found: Error: Can't resolve './gateway-api' in '/private/var/folders/0v/jpdg1flj3qscvbvt728pgt8c0000gn/T/embroider-TwHjWl/adapters'` 


My adapter are importing with relative path. with absolute path this works. But ok, I'll reproduce this with a new ember app

**Comment by villander** [comment]
I fixed that using `web-app/adapters/gateway-api`. Embroider continue don't working with relative paths.

**Comment by ef4** [comment]
Given that error message, _is_ there are file named `gateway-api.js` in `/private/var/folders/0v/jpdg1flj3qscvbvt728pgt8c0000gn/T/embroider-TwHjWl/adapters`? What is in that folder? Where does gateway-api.js normally come from?

**Comment by villander** [comment]
come from `web-app/adapters/`

**Comment by ef4** [comment]
In a normal ember app, wouldn't that be `web-app/app/adapters/gateway-api.js`, not `web-app/adapters/gateway-api.js`?

**Comment by NullVoxPopuli** [comment]
Given that this is for embroider < v1, I'm going to close.

If the same issue exists on current embroider (v3.2+), let's open a new issue. thanks all!
