### ISSUE TITLE
dynamic import does not allow data:text URLs

### ISSUE THREAD

**Issue by NullVoxPopuli** [embroider-build/embroider#983]
I'm loading a module via 
```js
let code = `export const two = 2;`;
let encodedJs = encodeURIComponent(code);
let result = await import(`data:text/javascript;charset=utf-8,${encodedJs}`);
```
which, works in the browser: https://jsfiddle.net/NullVoxPopuli/1b0nvrmg/1/

![image](https://user-images.githubusercontent.com/199018/134835286-cfd611ba-b061-4ff4-a5fb-09a4834cee99.png)

<details><summary>error report</summary>

```

=================================================================================

ENV Summary:

  TIME: Sun Sep 26 2021 21:20:10 GMT-0400 (Eastern Daylight Time)
  TITLE: ember
  ARGV:
  - 🏠/.volta/tools/image/node/14.17.6/bin/node
  - /✂️/ember-repl/node_modules/ember-cli/bin/ember
  - s
  - -p
  - 4201
  EXEC_PATH: 🏠/.volta/tools/image/node/14.17.6/bin/node
  TMPDIR: /tmp
  SHELL: /bin/bash
  PATH:
  - /✂️/ember-repl/node_modules/.bin
  - /✂️/node_modules/.bin
  - /✂️/node_modules/.bin
  - 🏠/node_modules/.bin
  - /home/node_modules/.bin
  - /node_modules/.bin
  - 🏠/.volta/tools/image/node/14.17.6/bin
  - 🏠/.volta/tools/image/npm/7.7.5/bin
  - 🏠/.volta/tools/image/yarn/1.22.11/bin
  - 🏠/.volta/tools/image/node/14.17.6/bin
  - 🏠/.volta/bin
  - 🏠/.pythons/Python-3.6.3/bin
  - 🏠/.cargo/bin
  - 🏠/Applications
  - 🏠/apps/phantomjs/bin
  - 🏠/scripts/system-utils
  - 🏠/scripts/git
  - 🏠/scripts/rails
  - 🏠/scripts
  - 🏠/.volta/bin
  - /usr/local/sbin
  - /usr/local/bin
  - /usr/sbin
  - /usr/bin
  - /sbin
  - /bin
  - /usr/games
  - /usr/local/games
  - /snap/bin
  - 🏠/.dotnet/tools
  - 🏠/.dotnet/tools
  - 🏠/.fzf/bin
  PLATFORM: linux x64
  FREEMEM: 140959744
  TOTALMEM: 17388204032
  UPTIME: 4703050.69
  LOADAVG: 2.48,0.75,0.38
  CPUS:
  - Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz - 3192
  - Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz - 3192
  - Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz - 3192
  - Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz - 3192
  - Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz - 3192
  - Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz - 3192
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.17.2
  - brotli: 1.0.9
  - cldr: 39.0
  - icu: 69.1
  - llhttp: 2.1.3
  - modules: 83
  - napi: 8
  - nghttp2: 1.42.0
  - node: 14.17.6
  - openssl: 1.1.1l
  - tz: 2021a
  - unicode: 13.0
  - uv: 1.41.0
  - v8: 8.4.371.23-node.76
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: ModuleNotFoundError: Module not found: Error: Can't resolve 'data:text' in '$TMPDIR/embroider/1fdc02/esm/index.js'
    at /✂️/ember-repl/node_modules/webpack/lib/Compilation.js:1779:28
    at /✂️/ember-repl/node_modules/webpack/lib/ContextModuleFactory.js:210:15
    at /✂️/ember-repl/node_modules/neo-async/async.js:2830:7
    at /✂️/ember-repl/node_modules/neo-async/async.js:6877:13
    at /✂️/ember-repl/node_modules/webpack/lib/ContextModuleFactory.js:180:26
    at finishWithoutResolve (/✂️/ember-repl/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:296:11)
    at /✂️/ember-repl/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:362:15
    at /✂️/ember-repl/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:410:5
    at eval (eval at create (/✂️/ember-repl/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /✂️/ember-repl/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:410:5
  - code: [undefined]
  - codeFrame: Module not found: Error: Can't resolve 'data:text' in '$TMPDIR/embroider/1fdc02/esm/index.js'
  - errorMessage: ../../esm/index.js: Module not found: Error: Can't resolve 'data:text' in '$TMPDIR/embroider/1fdc02/esm/index.js'
        at PackagerRunner (@embroider/webpack)
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: ../../esm/index.js
    - line: [null]
    - treeDir: [undefined]
  - message: ../../esm/index.js: Module not found: Error: Can't resolve 'data:text' in '$TMPDIR/embroider/1fdc02/esm/index.js'
        at PackagerRunner (@embroider/webpack)
  - name: Error
  - nodeAnnotation: @embroider/webpack
  - nodeName: PackagerRunner
  - originalErrorMessage: Module not found: Error: Can't resolve 'data:text' in '$TMPDIR/embroider/1fdc02/esm/index.js'
  - stack: ModuleNotFoundError: Module not found: Error: Can't resolve 'data:text' in '$TMPDIR/embroider/1fdc02/esm/index.js'
    at /✂️/ember-repl/node_modules/webpack/lib/Compilation.js:1779:28
    at /✂️/ember-repl/node_modules/webpack/lib/ContextModuleFactory.js:210:15
    at /✂️/ember-repl/node_modules/neo-async/async.js:2830:7
    at /✂️/ember-repl/node_modules/neo-async/async.js:6877:13
    at /✂️/ember-repl/node_modules/webpack/lib/ContextModuleFactory.js:180:26
    at finishWithoutResolve (/✂️/ember-repl/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:296:11)
    at /✂️/ember-repl/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:362:15
    at /✂️/ember-repl/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:410:5
    at eval (eval at create (/✂️/ember-repl/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /✂️/ember-repl/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:410:5

=================================================================================
```

</details>

**Comment by NullVoxPopuli** [comment]
or maybe this a webpack issue, given the top of the stack 🤔

**Comment by NullVoxPopuli** [comment]
ah, the solution -- silly webpack:

```jv
let code = `export const two = 2;`;
let encodedJs = encodeURIComponent(code);
let result = await import(
  /* webpackIgnore: true */  `data:text/javascript;charset=utf-8,${encodedJs}`
);
```
